### ISSUE TITLE
Cookies: Invalid cookie. Value not a token or quoted value

### ISSUE THREAD

**Issue by faisal6621** [js-cookie/js-cookie#100]
I am creating a cookie as
`Cookies.set('key',[25,23,65],{expires:10});`
But this is causing an issue with the server. I am getting the message logged in `server.log` as mentioned in title (`Cookies: Invalid cookie. Value not a token or quoted value`).

I tried using `JSON.stringify()` for setting value as:
`Cookies.set('key',JSON.stringify([25,23,65]),{expires:10});`
but the issue remains.

I am using `JBoss AS 7.1.1`

**Comment by FagnerMartinsBrack** [comment]
There are some servers that are not compliant to the official cookie spec ([RFC 6265](http://tools.ietf.org/html/rfc6265)), we are planing to document it [here](https://github.com/js-cookie/js-cookie/blob/7e628d2b8a6f8349b88a429a0a691b1f5980ceda/SERVERS.md).

See the discussion at https://github.com/js-cookie/js-cookie/issues/70.

**Comment by FagnerMartinsBrack** [comment]
@faisal6621 It seems that the servlet implementation of JBoss does not accept `[` or `]` in the cookie value, although it is valid as per RFC 6265, [see here](http://anonsvn.jboss.org/repos/jbossas/projects/specs/tags/jboss-servlet-api_3.0_spec-1.0.0.Final/src/main/java/javax/servlet/http/Cookie.java).

It would be worth opening an issue in JBoss side, in the mean time I will document this incompatibility issue in #70 and track it there.

**Comment by FagnerMartinsBrack** [comment]
@faisal6621, take a look [here](https://github.com/js-cookie/js-cookie/blob/cb6db3967fbc7ab835e9cf3625a556819a937847/SERVER_SIDE.md#jboss-711). We will release a ["write" converter](https://github.com/js-cookie/js-cookie/pull/71) (probably in version 2.1.0) to be able to workaround those kind of issues.

**Comment by faisal6621** [comment]
Hi @FagnerMartinsBrack, thanks for the time. Looking forward for ver. 2.1.0.
