### ISSUE TITLE
how do I access cookies for other domain?

### ISSUE THREAD

**Issue by siddo420** [js-cookie/js-cookie#104]
I am using cross domain AJAX requests.

The site is hosted on 192.168.1.x and it is making AJAX requests (with/without session) on 192.168.1.y.

Can I access cookies for 192.168.1.y? 

My AJAX requests are valid and authenticated using the above.

**Comment by FagnerMartinsBrack** [comment]
Hi, I am not sure how browsers will handle IP addresses in the [domain attribute](https://github.com/js-cookie/js-cookie/tree/5afa5d967d8f6b5d2a498926ae3e98e9a1c4857d#domain), but that attribute would be the first thing I would look into. Usually when you define a `domain: "example.com"` the cookie is visible for all subdomains of `*.example.com`, not sure how you would do it with IP addresses.

Anyway, this question is a better fit for [StackOverflow](http://stackoverflow.com/questions/tagged/js-cookie) site. An answer to this question might be helpful for someone else in the future, so StackOverflow is a better choice for relevance in Google Search results.

If you open a question there please link it here for cross-reference, maybe we can enhance the docs, thanks.

**Comment by FagnerMartinsBrack** [comment]
Closing this for now since this seems to be an usage issue and we have no controle over how browsers handle the cookie attribute.
