### ISSUE TITLE
About write spaces???

### ISSUE THREAD

**Issue by rogerangers** [js-cookie/js-cookie#105]
Hi!

About js-cookie, about write spaces:

var space = ' '; //one space

Cookies.set('test',space+space+space+'1'+space+space+space+space+'2'+space+space+space);

Cookies.get('test') = > return ' 1 2 '

?

**Comment by FagnerMartinsBrack** [comment]
@rogerangers 

The behavior seems correct:

```javascript
var space = ' '; //one space
Cookies.set('test',space+space+space+'1'+space+space+space+space+'2'+space+space+space);
var result = Cookies.get('test');
console.log( result ); // =>   1    2   
```

```javascript
Cookies.remove( 'test' );
var valueBefore = '  1  2  ';
Cookies.set( 'test', valueBefore );
var valueAfter = Cookies.get( 'test' );
console.log( valueBefore === valueAfter ); // => true
```

What exactly is the problem?

**Comment by rogerangers** [comment]
Sorry, I had made a mistake just returned Cookies.get ('test') and looking at the output value in console, where I should have done console.log(Cookies.get ('test')). Is working as it should! Thank you for your support!

**Comment by FagnerMartinsBrack** [comment]
Ok :+1:
