### ISSUE TITLE
Cookie Path not working

### ISSUE THREAD

**Issue by MikeHarrison** [js-cookie/js-cookie#106]
Hi,

I am trying to set the path for the cookie to be the current page, but it is just showing as the root path in dev tools. My code is:
```
Cookies.set('timeElapsed', data.seconds, { path: '' });
```
Is there something else I need to do?

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for reporting an issue.

When you use `path: ""` you tell the browser to ignore the `Path` attribute completely. In this case it falls into the default behavior, that is to create a Session Cookie.

> I am trying to set the path for the cookie to be the current page

It is impossible to set the path for the cookie to be the current page. What you can do is set the path of the cookie to be **the path** of the current page.

Assuming cookie creation at **/index.html**

```javascript
Cookies.set( "timeElapsed", 50, { path: "" });
```

The cookie path will be default to `Path: /`

Assuming cookie creation at **/dir/index.html**

```javascript
Cookies.set( "timeElapsed", 50, { path: "" });
```

The cookie path will be default to `Path: /dir`

Note: I tested this only in Chrome. I have **no idea** if this default behavior is consistent across all browsers, the only thing that js-cookie does is to tell the browser to create a Session Cookie. How browsers do it, standard or not, it is out of our control.

**If you find a different behavior for another browser or if you want to enhance the docs to make this things clear, please feel free to open a Pull Request.**

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
