### ISSUE TITLE
How to Set and Read Cookies with Keys

### ISSUE THREAD

**Issue by born2ice** [js-cookie/js-cookie#107]
I need to do something like this

Customer is the main cookie and name/dob is the key.

cookie.writeKey('customer', 'name', 'Jeff Smith');
cookie.writeKey('customer', 'dob', '07/15/1991');

**Comment by FagnerMartinsBrack** [comment]
Hi, this question is a better fit for [StackOverflow](http://stackoverflow.com). The docs [have very good examples on how to do that](https://github.com/js-cookie/js-cookie/tree/v2.0.4#basic-usage).
