### ISSUE TITLE
Is there js.cookie.min.js  

### ISSUE THREAD

**Issue by playgithub** [js-cookie/js-cookie#108]
Is building js.cookie.min.js supported?
Thanks.

**Comment by FagnerMartinsBrack** [comment]
Sure, the [Contributing Guidelines](https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md#getting-started) contains the steps to generate the minified file. Although it is not called `js.cookie.min.js` but rather `js.cookie-x.x.x.min.js`.

Basically it is:

```
$ npm install
...
$ grunt 
```

**Comment by playgithub** [comment]
OK, thanks.
