### ISSUE TITLE
Add support for typed cookie

### ISSUE THREAD

**Issue by JSteunou** [js-cookie/js-cookie#111]
I dont know if this is in some kind of RFC or just an expressjs thing, but they add "s:" before string cookie value, and "j:" before json cookie value which make JSON.parse fail.

I have to substring and JSON.parse manually because of this. Could you consider adding this to your internal JSON.parse if this is a thing a lot of server do?

**Comment by JSteunou** [comment]
Typically I had to

```
var value = cookie.getJSON('key');
// ...
if (typeof value === 'string' && value.substr(0, 2) === 'j:') value = JSON.parse(value.slice(2));
```

**Comment by FagnerMartinsBrack** [comment]
Which tool is adding `s:` and `j:` before the value?

> I dont if this is in some kind of RFC or just an expressjs thing

As far as I am concerned express should not do that, unfortunately we need a reason for why that is being added, otherwise there is nothing we can do.

I would suggest monkey patching JavaScript Cookie, **but be aware that this technique can break in newer version because it rely in internal behavior**, use at your own risk.

```javascript
var CrazyCookies = (function( OldCookies ) {
  var forString = function( string ) {
    return {
      startsWith: function( substring ) {
        return string.substring( 0, substring.length ) === substring;
      },
      restAfter: function( substring ) {
        return string.substring( substring.length, string.length );
      }
  };
  Cookies.getJSON = function( key ) {
    var cookieValue = Cookies.get( key );
    if ( !cookieValue ) {
      return OldCookies.getJSON.apply( this, arguments );
    }
    if ( !forString( cookieValue ).startsWith( "j:" ) ) {
      return OldCookies.getJSON.apply( this, arguments );
    }
    return JSON.parse( forString( cookieValue ).restAfter( "j:" ) );
  };
} ( Cookies ));
```
The usage would be like this:

```javascript
// as_json=j:{"key", "value"}
CrazyCookies.getJSON( "as_json" ); // => {"key", "value"}
```

**Note: This is NOT tested, I just wrote on the fly to explain the concept behind it.**

**Comment by JSteunou** [comment]
Yep, was afraid there is no RFC linked to that. I find a better way though, I just `JSON.stringify` before setting the cookie, so it does not transform my object and add `j:` then front-end js-cookie `getJSON` can still work.

Anyway thanks for your feedback.

**Comment by ericnewton76** [comment]
@FagnerMartinsBrack this could be accomplished with a Converter, yes?

**Comment by FagnerMartinsBrack** [comment]
@ericnewton76 Probably yes.

Unfortunately you would have to duplicate the whole encoding/decoding mechanism, because a converter delegates to the developer the whole responsibility of deciding how to encode/decode each cookie, which in some cases might not be desired.
