### ISSUE TITLE
How can I complete a JS action based on the presence of a cookie?

### ISSUE THREAD

**Issue by MrzAOK** [js-cookie/js-cookie#113]
I am working on a form and when you focus on an input field, I have a pop up that reminds them to save when they are complete. I only want the user to see this pop up once every 60 days. On focus I set a cookie that tells me they have seen the alert. Then however, since I only want this to appear every 60 days, I want to make sure it doesn't happen again next time they click. How do I execute something like, "if this cookie exists, then do this?" Below is a sample of the code I'm using:

$("input").focus(function(){
	//My alert goes here (i'm good on this part")
	Cookies.set('saveChanges', 'wasAlerted', { expires: 60, path: '/' });
        //if SOMETHING, do SOMETHING ("need help here")
});

FYI, My cookie name is 'saveChanges' and the value is 'wasAlerted'.

**Comment by FagnerMartinsBrack** [comment]
You can post questions regarding general usage in StackOverflow, under the tag `js-cookie`: http://stackoverflow.com/questions/tagged/js-cookie

You will have a better change to get a satisfactory response there. Also, your answer will rank better for someone that might be looking for this answer in the future through Google.
