### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by robertpeter07** [js-cookie/js-cookie#116]
Hi,

When will you create a nuget package for this?

**Comment by FagnerMartinsBrack** [comment]
Related to: https://github.com/carhartl/jquery-cookie/pull/244#issuecomment-93534520, https://github.com/carhartl/jquery-cookie/pull/260#issuecomment-93535347

See also https://github.com/carhartl/jquery-cookie/issues/152#issuecomment-12953584

**Comment by FagnerMartinsBrack** [comment]
As from some of the links above, we will stick with npm and Bower for now. There is a trend in the front-end community to drop Bower in the future and stick with npm, if that happens we will probably drop bower too, but only time will tell.

In the meantime feel free to register and support other package managers for other languages. We can perhaps add a link in the Wiki pointing to it.

**Comment by igitur** [comment]
Packaged at https://www.nuget.org/packages/js-cookie/

**Comment by FagnerMartinsBrack** [comment]
Thanks @igitur
