### ISSUE TITLE
Release converters

### ISSUE THREAD

**Issue by evandipietro** [js-cookie/js-cookie#121]
I noticed that the documentation (and latest code) have the converters feature, however this has not yet been released via NPM. @FagnerMartinsBrack, could you bump the version to release converters?

**Comment by FagnerMartinsBrack** [comment]
Yes, sure. I was waiting for more stuff to piggyback the minor bump 2.1.0, but it seems that is taking too long so I will put them in a new milestone:

![image](https://cloud.githubusercontent.com/assets/835857/12052030/f5c476a6-aef1-11e5-9cc8-963c1bf0aca6.png)

Thanks for the reminder. I can't do it right now but I will do it as soon as I can and then I ping you here ok?

**Comment by evandipietro** [comment]
Thanks, I appreciate that.

**Comment by FagnerMartinsBrack** [comment]
@evandipietro I have just released and is already available on npm: https://github.com/js-cookie/js-cookie/releases/tag/v2.1.0

Happy cookying.
