### ISSUE TITLE
Browser Chrome 2016 not working

### ISSUE THREAD

**Issue by KingRider** [js-cookie/js-cookie#129]
Browser Chrome a newest version 2016 not working... i think is bug

![cookies-bug](https://cloud.githubusercontent.com/assets/4491180/12581320/004d2a92-c41d-11e5-811c-608cf2f66c03.png)

http://prntscr.com/9v195o

**Comment by willemtoledano** [comment]
I confirm that with version  48.0:
``
$(document).ready(function(){
``
``
    if(!Cookies.get('modalShown')) {
``
``
        $("#myModal").modal('show');
``
``
        Cookies.set('modalShown', true, { expires: 2 });
``
``
    } else {
``
``
        alert('Your modal wont show again as its shown before.');
``
``
    }
``
``
});
``


> Cookies.get()
<- Object {}
> Cookies.set('test', 1234)
<- "test=1234; path=/"
> Cookies.get('test')
<- undefined

**Comment by KingRider** [comment]
willemtoledano,

i know a code, try offline? its not work... why just web online?

Test online:
https://jsfiddle.net/KingRider/g377bzt9/2/

**Comment by FagnerMartinsBrack** [comment]
@KingRider The code you posted is working for me. What is the issue?

**Comment by KingRider** [comment]
Fagnes, save code ur html to try offline. Not try online.

**Comment by FagnerMartinsBrack** [comment]
For security purposes some browsers like Chrome does not allow cookies to be set in the `file://` protocol, if you are using like that then the behavior is expected.

**Comment by DeadcatDev** [comment]
The same problem here... Working with it for couple of hours and silimiar problems...

**Comment by FagnerMartinsBrack** [comment]
@DeadcatDev see my comment, cookies does not work running locally, you need to setup a server.

**Comment by FagnerMartinsBrack** [comment]
Unfortunately this PR does not have enough information to provide any action from js-cookie side. All evidence points out that you are using Chrome in offline mode, which doesn't support cookies by default. See [this StackOverflow answer](http://stackoverflow.com/a/347997) for more information.

Feel free to provide more information so we can reopen it.
