### ISSUE TITLE
Make testing in Sauce Labs work for all PRs

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#13]
Moved from carhartl/jquery-cookie#268

**Comment by carhartl** [comment]
Isn't that working by now? Fwiw, there has been some movement lately on making this work without workarounds: https://github.com/travis-ci/travis-core/pull/418 - though it still hasn't made it to Travis...

**Comment by FagnerMartinsBrack** [comment]
It doesn't work yet, what it does is to ignore Sauce Labs testing for [other ppl PRs](https://travis-ci.org/js-cookie/js-cookie/builds/63886003#L209-L211), the only PRs that run  Sauce Labs are the ones created by us: https://travis-ci.org/js-cookie/js-cookie/builds/61077154#L425

**Comment by carhartl** [comment]
Ah, yes, I misunderstood the issue in that regard.

**Comment by cvrebert** [comment]
I'm still quite willing to offer y'all assistance in setting up a Savage instance.

**Comment by FagnerMartinsBrack** [comment]
It's been a long time since the last comment on this and we haven't received a lot of PR activity that justify the efforts to implement Savage in this repo.

Thanks @cvrebert for your interest in helping us (and your great work on twbs too xD), but it seems this is not something that we need right now.

I will be closing this, but we can reopen when the need arises or if @carhartl have any plans in supporting Savage.
