### ISSUE TITLE
Not Encoding {}

### ISSUE THREAD

**Issue by ThiagoDosSantos** [js-cookie/js-cookie#130]
When you do Cookies.set("key", {"property":"value"}) everything is encoded except {}. Why?

**Comment by FagnerMartinsBrack** [comment]
`{` and `}` are allowed characters in a cookie value as from RFC 6265. Why should they be encoded?

**Comment by ThiagoDosSantos** [comment]
Ok, I'm saying that because jquery cookie works that way. I wasn't able to upgrade to js-cookie because my server argue that this cookie is invalid

**Comment by ThiagoDosSantos** [comment]
Just solved. I'm using tomcat 8 and it could be solved by changing the Cookie Processor. Just add this line to conf/context.xml and it works:

`<Context>
<CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"/>
</context>`

**Comment by FagnerMartinsBrack** [comment]
@ThiagoDosSantos Indeed js-cookie contains breaking changes, but even though the encoding mechanism was never documented, we mentioned that in the changelog at [RFC 6265 compliance](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0) section (not encoding specifically, but that there were changes in behavior).

And by the way, thank you very much for that information on Tomcat! I wonder if that could be added in [SERVER_SIDE.md](https://github.com/js-cookie/js-cookie/blob/3f2b5e6884407c54b391483f39ddcd4c70f9243c/SERVER_SIDE.md), what do you think?

**Comment by ThiagoDosSantos** [comment]
@FagnerMartinsBrack I think it's a good idea. Probably there are others servers that are still using the old cookie RFC and people migrating from jquery cookie to js-cookie will appreciate that specific information. I'm glad to help you. Thank you!!

**Comment by FagnerMartinsBrack** [comment]
Do you want to send a pull request since you are the one who pointed out the CookieProcessor?

**Comment by ThiagoDosSantos** [comment]
Done. #131
