### ISSUE TITLE
Usage with crosswalk for Android

### ISSUE THREAD

**Issue by bernatcanal** [js-cookie/js-cookie#133]
I'm writing an app for Android that loads local HTML files into the Crosswalk Webview. 
Is this library compatible?

Thanks!

**Comment by FagnerMartinsBrack** [comment]
I don't know what is crosswalk, but the lib should be compatible with any browser that implements the DOM cookie API correctly.

**Comment by FagnerMartinsBrack** [comment]
I will close this because there is no action we can take now unless you point us to some requirements to make crosswalk working in case the lib is not working for any reason :+1:.

**Comment by bernatcanal** [comment]
Sorry, it ended up being crosswalk's issue. Thanks
