### ISSUE TITLE
Default value on get

### ISSUE THREAD

**Issue by Soullivaneuh** [js-cookie/js-cookie#135]
To avoid conditional code and get it proper, I suggest you to implement default value on `Cookies.get` and `Cookies.getJson`.

Examples (we assume the cookie does not exists):

```javascript
Cookies.get('foo') // undefined
Cookies.get('bar', 42) // 42
```

**Comment by FagnerMartinsBrack** [comment]
What is the practical difference between these two?

```javascript
Cookies.get('bar', 42); // => 42
```

and

```javascript
Cookies.get('bar') || 42; // => 42
```

If we build something as simple as this in the `get` API we would prevent the second argument to be extended for something more useful in the future. There is no sense in changing an API to do something that can be easily achieved with one line.

**Comment by Soullivaneuh** [comment]
Indeed, I didn't know about this trick.

**Comment by FagnerMartinsBrack** [comment]
Ok, closing then. Thanks for the issue :+1:
