### ISSUE TITLE
Cookies.getJSON is not a function

### ISSUE THREAD

**Issue by Soullivaneuh** [js-cookie/js-cookie#136]
I just got your library from Bower (`2.1.*`) and included the JS file.

With the following code:

```coffee
closedAlerts = Cookies.getJSON 'closed_alerts'
```

I get `Cookies.getJSON is not a function` error.

This code works:

```coffee
closedAlerts = JSON.parse Cookies.get 'closed_alerts'
```

I check the vendor JS file and the `getJSON` is right here. Already had this issue?

**Comment by FagnerMartinsBrack** [comment]
We had similar issues but it was always custom code that was changing the API behavior at runtime. Can you post some snippet that reproduces the error on jsfiddle.net or similar?

**Comment by Soullivaneuh** [comment]
@FagnerMartinsBrack Unfortynatly, I can't reproduce on jsfiddle: https://jsfiddle.net/xnsk9a7a/

Maybe something wrong with the bower package?

**Comment by FagnerMartinsBrack** [comment]
Did you used the same version from the bower_components directory? If you
did then the problem is not with js-cookie. I suggest in this case that you
read sscce.org and post a question in stackoverflow with a reduced example
that reproduces the problem, then certainly somebody will help you much
faster. Also when a question is in stackoverflow it has a better visibility
on Google for those looking the answer for the same problem in the future.

On Feb 11, 2016 12:55 AM, "Sullivan SENECHAL" <notifications@github.com>
wrote:
>
> @FagnerMartinsBrack Unfortynatly, I can't reproduce on jsfiddle:
https://jsfiddle.net/xnsk9a7a/

**Comment by FagnerMartinsBrack** [comment]
@Soullivaneuh Did you find the problem?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.

**Comment by Soullivaneuh** [comment]
@FagnerMartinsBrack Sorry for the time.

No it's not the exact same version, I have 2.1.4 but this one is not available on jsdeliver.

**Comment by FagnerMartinsBrack** [comment]
@Soullivaneuh Not sure if there's anything we can do from here. Looks like a problem in your environment.

**Comment by Soullivaneuh** [comment]
Well, it's a simple jQuery env... Could you please elaborate?

**Comment by FagnerMartinsBrack** [comment]
@Soullivaneuh The [code you posted](https://jsfiddle.net/xnsk9a7a/) doesn't throw any `Cookie.getJSON` is not a function. Can you please take a look in http://sscce.org and provide a simple example with one or two lines of code and attach it here in a form that can be reproducible in my environment? Preferably without using coffeescript?

Alternatively, I suggest posting a question in StackOverflow with that same information.

**Comment by evictor** [comment]
I am also getting this error on 3.0.0-rc.0. All other cookie-js functionality works fine.

The `getJSON` function doesn't ever appear to be defined in master here. @FagnerMartinsBrack did it inadvertently get removed at some point possibly?

**Comment by evictor** [comment]
Also `.set()` given a native JS object or array does not work to spec (auto JSON encode). I think this functionality was accidentally removed from library but is still documented in the README.

Of note I am using a js-cookie object created by `.withAttributes`—not sure if that will make a difference

**Comment by carhartl** [comment]
@evictor

In v3 all built-in functionality related to handling json has been removed (it‘s mentioned in the release notes for the first beta).

> I think this functionality was accidentally removed from library but is still documented in the README

Could you point me to where this is still documented, I can‘t seem to find it?

**Comment by evictor** [comment]
My bad @carhartl I was referring to old docs for v2—https://www.npmjs.com/package/js-cookie

Curious why it was removed? Security concerns?
