### ISSUE TITLE
Sometimes path is set even if it should not

### ISSUE THREAD

**Issue by max-favilli** [js-cookie/js-cookie#139]
I set the cookie this way:
![screen shot 2016-02-17 at 18 12 54](https://cloud.githubusercontent.com/assets/1472899/13156564/62cc1070-d683-11e5-9ccf-3978861a5994.png)
But sometimes the path is the root, sometimes is set to the current page, why? 
![screen shot 2016-02-17 at 18 12 19](https://cloud.githubusercontent.com/assets/1472899/13156601/882d8d30-d683-11e5-95e4-06fb1ba9bc14.png)

Leaving it empty it should set it to the default value, the root, shoudn't it?

**Comment by FagnerMartinsBrack** [comment]
Can you please provide a simplified example that we can run locally and that shows the problem?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
