### ISSUE TITLE
Firefox 44.0.2 incompatibility

### ISSUE THREAD

**Issue by Antman261** [js-cookie/js-cookie#144]
Cookies.get() has stopped working since Firefox 44.0.2. Same code is still working in Safari and Chrome. If I run Cookies.get("cookiename") in Firebug it returns undefined.

EDIT: User error. Misread the expiry and hadn't noticed that it was in the past. Feel free to close.

**Comment by FagnerMartinsBrack** [comment]
> User error. Misread the expiry and hadn't noticed that it was in the past. Feel free to close.

:+1:
