### ISSUE TITLE
Provide minified version of the library

### ISSUE THREAD

**Issue by ste93cry** [js-cookie/js-cookie#146]
It would be cool if you could provide a minified version in the bower distribution. It's common for libraries to have a `dist` folder with all the production assets ready for use (minified and optimized).

**Comment by FagnerMartinsBrack** [comment]
It's on the way, see https://github.com/js-cookie/js-cookie/issues/57#issue-92249881. Any help is appreciated.

**Comment by l2aelba** [comment]
Im using this so long : http://jscompress.com/

**Comment by FagnerMartinsBrack** [comment]
@l2aelba 

You could use the project's built in minification system. This project's code is optimized for GZip, not only for minification. If you [follow the steps to run the build](https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md#getting-started) then you will see the generated file in the `build` folder.

Also, you can use the minified file that is always uploaded for each release in the releases page: https://github.com/js-cookie/js-cookie/releases

**Comment by l2aelba** [comment]
@FagnerMartinsBrack  Wow thanks

**Comment by FagnerMartinsBrack** [comment]
Closing in favor of #57.
