### ISSUE TITLE
How to set cookies for both http and https ?

### ISSUE THREAD

**Issue by ocvninfo** [js-cookie/js-cookie#148]
site: http://dev-mad-style-com.3dcartstores.com

When i on homepage, Newsletter cookie popup appear -> i close popup -> then F5 homepage -> popup disappear => **This is correctly.**

But then i go to login page or any page has https, popup appear again, then i close it, then F5 -> popup still appear. And then i back to homepage, popup still appear again.
Why??

**Anyone please give me some advice?**
Thanks!

**Comment by FagnerMartinsBrack** [comment]
Please, post support questions on [StackOverflow](http://stackoverflow.com) under the tag [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie). The benefit in posting in StackOverflow is that the question will have a better SEO and can be easily viewable by Googlers that look for the same problem, this way you are helping yourself and others in the future :)

Also, take a look in the [Secure](https://github.com/js-cookie/js-cookie/tree/v2.1.0#secure) attribute, it might help you in this case.
