### ISSUE TITLE
temporary and persistant cookie

### ISSUE THREAD

**Issue by alieslamifard** [js-cookie/js-cookie#151]
Hi.
i have a login form that work with **ajax** and there is a "**Remember Me**" check-box.
i want to set a **temporary cookie** when user do not check this.
can u help me please.
**thanks.**

**Comment by FagnerMartinsBrack** [comment]
Please post this question on [StackOverflow](http://stackoverflow.com/) under the tag [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie). This repository is for issues related to the library only, in StackOverflow you are more likely to receive a response if you have a concrete question about a specific problem you face.

**Comment by FagnerMartinsBrack** [comment]
Closing because there is nothing we can do here, thanks.
