### ISSUE TITLE
discrepancy by domain

### ISSUE THREAD

**Issue by benikov** [js-cookie/js-cookie#152]
when exists a pair of cookies with same key for different domains:
one for wild domain: ".domain" and second for specified subdomain, for ex. 

1. uuid  | 30f4b7ff-c368-4178-bd9b-c5b60e0482da | test.domain.com
2. uuid | f10d90d9-dffe-417c-a4c9-a73dc62f7815 | .domain.com

from test.domain.com Cookies.get() returns  {uuid:"30f4b7ff-c368-4178-bd9b-c5b60e0482da"},
but Cookies.get("uuid") returns f10d90d9-dffe-417c-a4c9-a73dc62f7815

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964814

**Comment by FagnerMartinsBrack** [comment]
We still need to document how the behavior is when there are 2 cookies with the same name. This is internal browser behavior and the only thing we can do is to document it. Until this is properly documented, I recommend to assume that creating 2 cookies with the same name, despite the properties passed, is an undefined behavior.

PRs are welcome.

**Comment by benikov** [comment]
You're right
Thank you!

**Comment by FagnerMartinsBrack** [comment]
Closing in favor of https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964814 then. I have added a bullet point there pointing to this issue.
