### ISSUE TITLE
The behavior should be no-op in environments without a "document"

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#164]
Originally reported on https://github.com/js-cookie/js-cookie/pull/159

**Comment by krzysiek1507** [comment]
@FagnerMartinsBrack new release with this change? ;)

**Comment by FagnerMartinsBrack** [comment]
@krzysiek1507 Sure, I plan releasing a patch version 2.1.1 (because we only have changes that do not add a new feature to the public API). I will do that once [the issues for the milestone v2.1.1 are closed](https://github.com/js-cookie/js-cookie/milestones/v2.1.1). If you really need this fix, you can help to move those issues forward by reading them and see if there is anything left to do, #171 is an example of an issue that needs some tests.

**Comment by FagnerMartinsBrack** [comment]
@krzysiek1507 New [patch release is there](https://github.com/js-cookie/js-cookie/releases/tag/v2.1.1)!
