### ISSUE TITLE
Feature request: Add params support for converters

### ISSUE THREAD

**Issue by fexblanco** [js-cookie/js-cookie#166]
I want to convert also the params in my Cookies instances, something like this:

```
Cookies.withConverter({
    read: function (value, name, params) {
        // Read converter
    },
    write: function (value, name, params) {
        // Write converter
    }
});
```

**Comment by FagnerMartinsBrack** [comment]
In this case what would be the content of the `params` argument? Where does it come from?

**Comment by fexblanco** [comment]
Maybe something like that

```
Cookies.withConverter({
    write: function (value, name, params) {
        return {
          value: transformValue(value),
          params = transformParams(params)
        }
    }
});
```

**Comment by FagnerMartinsBrack** [comment]
@fexblanco I am still not able to get where does the `params` come from, are you referring to the [Cookie Attributes](https://github.com/js-cookie/js-cookie/tree/d82dc72dab240ac64756afa7182b0d71e112dba1#cookie-attributes)?

**Comment by fexblanco** [comment]
@FagnerMartinsBrack  sorry if I have not explained well, yes, I'm referring the Cookies Attributes

**Comment by FagnerMartinsBrack** [comment]
@fexblanco Thanks for the response.

Can you please explain what is the use case for this feature? Is this something you are stuck on?

What is the difference between using a wrapper function to access the cookie attribute whenever it is necessary? Example below:

```javascript
var setCookie = function(name, value, attributes) {
  doSomethingWithTheAttributes(attributes);
  Cookies.set(name, value, attributes);
};
```

Do you need the Cookie Attributes to be able to convert then into a given format? If so, which format and why you need the attributes?

Looking forward on your response, thanks.

**Comment by fexblanco** [comment]
Hello, thank you for the fast support

I'm looking for my cookies to be available for parent domain and subdomains, so I have to write them with the domain param '.domain' every time that I write them.
````
Cookies.set(name, value, { domain: .domain});
````
So I thought to create a write converter which setup the right domain everytime that I write a cookie

**Comment by FagnerMartinsBrack** [comment]
@fexblanco 

> ...  so I have to write them with the domain param '.domain' every time that I write them.

To fix that you can just create a factory function that constructs the desired cookie attributes:

```javascript
var withMyDomainAttributes = function() {
  return {
    domain: "my-domain.com"
  };
};
Cookies.set('name', 'value', withMyDomainAttributes());
```

or better yet, you can use the `defaults` to set a specific domain for the given Cookie instance as stated [in the docs](https://github.com/js-cookie/js-cookie/tree/v2.1.0#cookie-attributes):

> Cookie attributes defaults can be set globally by setting properties of the Cookies.defaults object

```javascript
Cookies.defaults.domain = 'my-domain.com'
```

The converters API was designed to workaround the common problem of server-side incompatibility with cookie values. Adding another layer of indirection on top of it might add unnecessary complexity to the consumers of the library and violate the single responsibility of that API.

Looking forward on your response.

**Comment by fexblanco** [comment]
I haven't thought using the `Cookies.defaults` as you say, it's the best solution for my problem.

Thank you very much for the support @FagnerMartinsBrack

**Comment by FagnerMartinsBrack** [comment]
@fexblanco Were you aware of this feature in the first place? Do you have any suggestion in how we can improve the docs so that the feature becomes clearer for those reading it for the first time?

Looking forward on your response.

**Comment by FagnerMartinsBrack** [comment]
Ping @fexblanco

**Comment by FagnerMartinsBrack** [comment]
@fexblanco As a consideration for my free support, could you please help improving the docs so that the `Cookies.defaults` becomes clearer for those reading it for the first time?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
