### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by commax89** [js-cookie/js-cookie#173]
Hey guys,

i have a little problem, the console fires "Uncaught ReferenceError: Cookies is not defined" on the following website: http://www.musicapalazzo.com/

I use your script for a wordpress plugin to manage cookies for european policy law. This is the only website that is giving a problem.

I verified that the script is included in the page and it is, and there is no angular JS in this site (it is site based on WP). I think it is some kind of conflict problem.
Can you help me solve this problem?

Please keep in mind that since it is a wp plugin i have installed it on 100+ sites, so any change on 1 site will change on all sites.

Thank you very much.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/blob/4a4122eb06bc6c4fa8034f00dd9170bd07d4ce7c/CONTRIBUTING.md#issues:

> If reporting a bug, please add a simplified example.

**Comment by denniss** [comment]
+1 for some reason even after the script is loaded, calling `Cookies` will return a reference error

**Comment by FagnerMartinsBrack** [comment]
@denniss As stated above, we need an example that we can test, without that there is nothing we can do.

Closing for now, when there is a small example that shows the problem we can reopen again.

**Comment by commax89** [comment]
Sorry for the late reply, very busy in these days.
Anyways the only example that i can provide is my code i wrote in the plugin and i can give you some other sites in wich it doesn't work (since an other came up in these days).

What type of example do you need to help me figure the problem?

**Comment by FagnerMartinsBrack** [comment]
@commax89 as stated above, if reporting a bug, please add a [simplified example](http://sscce.org/). Check the link for more details.

You are free to post any code you have, but without a simplified example that reproduces the problem it is impossible for us to take any action about it.

**Comment by patroqueeet** [comment]
any update here? I'm having the same problem
