### ISSUE TITLE
Cannot set html dom into cookies

### ISSUE THREAD

**Issue by MagicJohnJang** [js-cookie/js-cookie#174]
It wont accept the string like "<span>hi</span>" in cookies, the encoding method not cover it,

but angular $cookies could work.

error message:

Server Error in '/' Application.

A potentially dangerous Request.Cookies value was detected from the client (yourParameter="...ho%20is%20<span%20contentedita...").

**Comment by FagnerMartinsBrack** [comment]
This works correctly:

```javascript
Cookies.set('hi', 'hi'); // => hi=hi
```

Can you please explain better what is not working with a [simplified example](http://sscce.org/)?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
