### ISSUE TITLE
Using js-cookie without commonjs or amd

### ISSUE THREAD

**Issue by MartinMuzatko** [js-cookie/js-cookie#177]
Hello there! Is there currently a way to retrieve js-cookie on the clientside without any commonjs or amd?
If so, please document.
If not, please document how to install js-cookie.

**Comment by MartinMuzatko** [comment]
Figured it out! Clearer info would be very much appreciated never the less

**Comment by FagnerMartinsBrack** [comment]
> Clearer info would be very much appreciated never the less

@MartinMuzatko We are aways looking for feedback in the docs. What is the problem with how it is documented in the README?

<img width="1047" alt="screenshot 2016-04-13 22 25 58" src="https://cloud.githubusercontent.com/assets/835857/14493080/d6b11918-01c6-11e6-8d87-aa579b815f2e.png">

Looking forward on your feedback.

**Comment by MartinMuzatko** [comment]
Oh I think I overlooked that. Maybe I'm not used to getting a working answer so fast. Haha. So by no means is it your fault.

I think only these big words confused me a bit.

> js-cookie supports npm and Bower under the name js-cookie
>It can also be loaded as an AMD or CommonJS module.

I thought you would require me to use AMD or CommonJS together with npm/bower.

Alternatively, you could destroy their implied context by saying:

"js-cookie can be found as `js-cookie` on npm and Bower."

And maybe move it up over the rawgit attention note.
Additionaly, you could improve the way to get this software with:

"js-cookie can be found as `js-cookie` on npm and Bower or downloaded here alternatively"

**Comment by FagnerMartinsBrack** [comment]
What about:

> js-cookie can also be found on npm and Bower under the name `js-cookie`, or downloaded here alternatively.

Or better, we could separate in sub-sections inside "Installation":

Installation
  - Browser
  - Package Managers
  - Module Loaders

Which one you think would be better?

**Comment by MartinMuzatko** [comment]
I like both ideas. However the last one, separating the ways to install it into their use cases is a great way to offer information. 
I'm not sure about the section "Browser". Isn't it only used with the browser in the end? I know with Browser you probably mean "download it manually and use a script tag". I think there could be a better title.

Examples:
https://jquery.com/download/
http://riotjs.com/download/

"Direct Download" is a good way to describe it.

**Comment by FagnerMartinsBrack** [comment]
Unfortunately we don't have a way to easily document a CDN for "direct downloads" like what the others do, see https://github.com/js-cookie/js-cookie/pull/46. Document the master is not encouraged because `master` is always unstable, we don't want to document an unstable version.

I guess the solution could be:

Installation
  * Direct download
  * Package Managers
  * Module Loaders

And in the "Direct Download" just put the Snippet that shows how to use it in the browser. What do you think @MartinMuzatko?

**Comment by MartinMuzatko** [comment]
Yep agree! Thank you for providing better documentation :)

**Comment by FagnerMartinsBrack** [comment]
No, thank you for helping to enhance it :)

**Comment by FagnerMartinsBrack** [comment]
@MartinMuzatko Could you please review #182?
