### ISSUE TITLE
Content synchronisation when too quick read write generates error, need validation

### ISSUE THREAD

**Issue by Trebly** [js-cookie/js-cookie#181]
Hi,

I met the following problem.
To test the good result I wrote a write-read (set-get). **I get often an error because I get back, after being red, the previous state of the cookie while it have been written for an update.
**
Currently we are not sure when we write (cookie.set) that it will be successful, the reasons for set or get error are several.

I am currently launching a test using a checking of the set by writing the update system date-time and update index into the cookie.
When I get it back I compare the datetime and index with the writing date and index stored separately.

As I was sure of getting an error, I began developments which are not ended which avoid set-read concurrent and to quickly to be issued. So I cannot for now give more elements because it is not ended.

Secondarily, your opinion about these technical points can change my solutions.

I will implement the solution of a temporise between read and writes (can be concurrent and launched by several process).

So, for reliability, I summit the idea of two enhancements :
1- a return value which gives the issue of the requests set and get (case cookies are not accepted, case unable to write to disk into a limited time, file locked ?)
2- an option for set to ask to check the good writing of the cookie : will force a synchronous execution (don't return while cookie is not written completely).

Best regards

Trebly

**Comment by FagnerMartinsBrack** [comment]
Hi, this channel is for bug reports or feature requests regarding the library. This is not for usage questions or architecture consulting.

Can you please be more objective on what this request is about and, if this is a bug report, provide a [SSCCE](http://sscce.org)?

**Comment by FagnerMartinsBrack** [comment]
I will close for triage, but will reopen once there is a concrete request related specifically to the library that we can look into.
