### ISSUE TITLE
dist version not available

### ISSUE THREAD

**Issue by huglester** [js-cookie/js-cookie#193]
Hello,

it would be nice if minified version would also be provided.
You have tests already, so these tests could be also applied to minified version. Since sometimes minifiers happen to break stuff :(

Thank you!

**Comment by FagnerMartinsBrack** [comment]
That is a known issue. Duplicated of https://github.com/js-cookie/js-cookie/issues/57

**Comment by huglester** [comment]
Thank you for the info. Will be watching
