### ISSUE TITLE
Cookies.set doesn't work for stringified object

### ISSUE THREAD

**Issue by rogercorrea** [js-cookie/js-cookie#194]
Please.

I don't know upgrading one existing cookie.
I tryed with the code in below but don't worked.
He isn't upgrading array length but $.listImages.length return correct number.

My Jquery version is 1.11.

`var listJSON = JSON.stringify($.listImages);
Cookies.set('imagensSelecionadas', listJSON)`

**Comment by FagnerMartinsBrack** [comment]
If you have support questions, please use [StackOverflow](http://stackoverflow.com/questions/tagged/js-cookie) under the tag [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie). It is much easier to get answers there.

Also StackOverflow has better Search Engine Optimization, therefore questions and answers there have a better chance to help more people.

**Comment by rogercorrea** [comment]
I asked here because I didn't see what I did wrong and seem to be a bug.

**Comment by rogercorrea** [comment]
For those who look here, open question in Stack:
http://stackoverflow.com/questions/37083793/jquery-and-cookie-update-of-the-first-start-but-not-after

**Comment by FagnerMartinsBrack** [comment]
The project doesn't use jquery anymore and we have tests proving that it works. Your code is working, see https://jsfiddle.net/r0odz1jv/

If you find a snippet that shows a problem with the library we will be glad to take a look.

> For those who look here, open question in Stack:
http://stackoverflow.com/questions/37083793/jquery-and-cookie-update-of-the-first-start-but-not-after

Thanks for linking it here. It is very important for those who come here later. I will update the issue title for better localization.

**Comment by FagnerMartinsBrack** [comment]
I will close this for now but feel free to reopen later if it is identified any problem with js-cookie itself. Maybe if you provide the content of `$.listImages` to the StackOverflow question you just opened they might find the problem easily.

**Comment by FagnerMartinsBrack** [comment]
Closing in favor of the StackOverflow answer. As form [this](http://stackoverflow.com/a/37084211/1400037), it seems the problem was the high count of bytes in the cookie. One more reason to document that in the FAQ: #37.
