### ISSUE TITLE
when i use wechat app which is installed on ios9.3 to open my site

### ISSUE THREAD

**Issue by Craft24** [js-cookie/js-cookie#195]
I find that Cookies is a Object then i must use it like this "Cookies.get().mycookie" to get the cookie.I don't know what happened. but use it like this "Cookies.get('mycookie')",it always get the value 1.Android have no problem like this.

**Comment by FagnerMartinsBrack** [comment]
Make sure you are not setting `Cookies.json = true` anywhere.

Related to https://github.com/js-cookie/js-cookie/issues/89#issuecomment-140897719, https://github.com/js-cookie/js-cookie/issues/117,

**Comment by Craft24** [comment]
sorry，i don't use the jsonconfig,I just only use it like this  
    <script src="<?php echo base_url();?>static/js/jquery-2.1.4.js"></script>
    <script src="<?php echo base_url();?>static/js/js.cookie.js"></script>  
var sendaddress=Cookies.get().sendaddress;//降序  
I did nothing

**Comment by FagnerMartinsBrack** [comment]
`Cookies.get().sendaddress` will throw an error because what is returned is always a String. Your usage is wrong.

**Comment by Craft24** [comment]
But I didn't set `Cookies.json = true` up.   
console>Cookies.get()
Object
fee: "0"
operation: "2"
operation1: "2"
sendaddress: "1"
sendendtime: "0"
__proto__: —  
Must I use `Cookies.getJSON()` instead it?

**Comment by Craft24** [comment]
I mean why it works well when i use it like this,but i use `Cookies.get('mycookie')`,it doesn't work.

**Comment by FagnerMartinsBrack** [comment]
See here: https://jsfiddle.net/zngpoa70/

It works. Can you please provide a simple example that doesn't work?

**Comment by FagnerMartinsBrack** [comment]
Sorry, the problem is with `window.json = true`, not `Cookies.json = true`, see https://jsfiddle.net/zngpoa70/1/

**Comment by Craft24** [comment]
1.I use it in wechat(微信) app which is installed on IOS9.3,It has a build-in webview or something webbrowser .  
2.I don't quite understand `window.json`, Is it default value in js or js-cookie?

**Comment by FagnerMartinsBrack** [comment]
Sorry I don't know what weechat is. I need a simple example in order to take any action on it.

**Comment by Craft24** [comment]
Sorry,I will give the example,but you need to install the app for test it.I just want to figure out whether it's the app environment.

**Comment by Craft24** [comment]
I'm Sorry, I'm sure it's my environment.
