### ISSUE TITLE
the expires must be  integer?

### ISSUE THREAD

**Issue by ggunmo** [js-cookie/js-cookie#197]
the expires must be  integer?I want to save cookie about several hours.3q.

**Comment by FagnerMartinsBrack** [comment]
[Take a look here](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#expire-cookies-in-less-than-a-day), does that solves the problem?

**Comment by FagnerMartinsBrack** [comment]
I will assume the problem was solved and the question answered.
