### ISSUE TITLE
Cookies size limitations when storing JSON objects

### ISSUE THREAD

**Issue by vitroz** [js-cookie/js-cookie#199]
Hello All,

Im trying to use the library to store a cookie with an array of objects. My arrays are quite big actually(it is one array with multiple objects, with each object having 16 fields).  I noticed when testing, that it would only store up to 6 objects on my cookie.

Is there anyway to increase the size limit for a cookie?
or what I am trying to do is not possible?

**Comment by FagnerMartinsBrack** [comment]
Please, take a look here: https://github.com/js-cookie/js-cookie/issues/37#issuecomment-217620753. I have added a new bullet point with this issue there.

**Comment by vitroz** [comment]
I see.. thanks!
