### ISSUE TITLE
Support default value for get method

### ISSUE THREAD

**Issue by hurelhuyag** [js-cookie/js-cookie#202]
Idea is if cookie is not available then return 'defaultvalue'

Cookies.get('cookiename', 'defaultvalue');

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/135 for a whole discussion on this.

What is the difference between `Cookies.get('cookiename', 'defaultvalue')` and `Cookies.get('cookiename') || 'defaultvalue'`?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.
