### ISSUE TITLE
Documentation clarification (.remove and secure flag)

### ISSUE THREAD

**Issue by bendiksolheim** [js-cookie/js-cookie#203]
In the specification, regarding removal of cookies (`.remove`), the following is specified:

```
IMPORTANT! when deleting a cookie, you must pass the exact same path, domain and secure attributes that were used to set the cookie, unless you're relying on the default attributes.
```

During my testing, it seems this is true for domain and path, but it does not seem to be true for secure. We set the cookie to secure on the server (Chrome Developer Tools confirms this), but it seems to be possible to remove the cookie without setting the secure flag. Explicitly removing with `secure: false` seems to work as well. Should this not work (indicating I am doing something wrong, which might entirely be the case), or am I misunderstanding the documentation?

**Comment by FagnerMartinsBrack** [comment]
@bendiksolheim Thanks for opening the issue!

Hmm, that documentation line dates from 2012, it was added by this commit: https://github.com/js-cookie/js-cookie/commit/a5349aaf8c2ccc69d45b8abc48873ea8f27f0689.

I checked the [RFC 6265](https://tools.ietf.org/html/rfc6265#section-5.3):

> If the cookie store contains a cookie with the same name, **domain, and path** as the newly created cookie:

>  1.  Let old-cookie be the existing cookie with the same name,
       domain, and path as the newly created cookie.  (Notice that
       this algorithm maintains the invariant that there is at most
       one such cookie.)

>  2.  If the newly created cookie was received from a "non-HTTP"
      API and the old-cookie's http-only-flag is set, abort these
      steps and ignore the newly created cookie entirely.

> 3.  Update the creation-time of the newly created cookie to
         match the creation-time of the old-cookie.

> 4.  Remove the old-cookie from the cookie store.

The key points are highlighted and it seems that you need only the domain and path! If this is correct in all browsers I guess we need to change the docs, @bendiksolheim can you test for us if this is a consistent behavior among all current browsers? xD.

It is insane how this documentation could have been wrong for so many years! Maybe this was true at the time? @carhartl do you remember this?

**Comment by carhartl** [comment]
Looks like a careless mistake to me, even more so because the comment states it correctly: https://github.com/carhartl/jquery-cookie/blame/master/README.md#L71

**Comment by FagnerMartinsBrack** [comment]
Good catch.

@bendiksolheim It's confirmed that we don't need the `secure` attribute, want to create a PR on that?

**Comment by bendiksolheim** [comment]
I'll say, you guys are quick at responding! I created a PR with `secure` removed from the text (and fixing a were -> was, sorry :p). It's right here: https://github.com/js-cookie/js-cookie/pull/204

Please let me know if I did anything wrong in the PR, I am not a very seasoned contributor to open source projects.

Thanks for the clarification!

**Comment by FagnerMartinsBrack** [comment]
Thanks man!

**Comment by jazoom** [comment]
I thought this was required because the documentation still reads:

```
Cookies.remove('name', { secure: true });
```

**Comment by FagnerMartinsBrack** [comment]
@jazoom good catch!

![image](https://cloud.githubusercontent.com/assets/835857/26631317/cedcc3e6-464d-11e7-9091-55bcc9ad00bf.png)

Do you want to raise a PR fixing that? Maybe we can use the `domain` instead of `secure` there?

[Here](https://github.com/js-cookie/js-cookie/blob/8b70250875f7e07445b6a457f9c2474ead4cba44/README.md)'s the current revision with the bug, for posterity.

**Comment by FagnerMartinsBrack** [comment]
@jazoom Do you still wanna create a PR fixing this?

**Comment by jazoom** [comment]
@FagnerMartinsBrack Please correct me if I'm wrong (I'm not super up with all the GitHub culture) but wouldn't this be like a 10 second fix? It doesn't seem to make sense to me to clone the library, locate what needs to be changed, change it, submit the PR and anything else that goes along with it. Wouldn't it be easy for someone who already works on the project to just make the change?

It's entirely possible I'm misunderstanding things here.

**Comment by FagnerMartinsBrack** [comment]
@jazoom Of course I could just do it. However, since you brought this problem up, you have the right to make the change and [be registered as a contributor](https://github.com/js-cookie/js-cookie/graphs/contributors).

Unless you don't want to, then I can do it.

**Comment by jazoom** [comment]
@FagnerMartinsBrack Oh, I never thought about it like that. Since I'm not really in the "tech scene" or have ever been looking to be hired or gain community recognition I've never considered that aspect. Thanks for explaining it.

I'm happy for you to go ahead and make the change.

**Comment by FagnerMartinsBrack** [comment]
@jazoom Cool, thanks.

**Comment by FagnerMartinsBrack** [comment]
Created a PR. See https://github.com/js-cookie/js-cookie/pull/369.
