### ISSUE TITLE
Add expired cookie detail to docs

### ISSUE THREAD

**Issue by robyedlin** [js-cookie/js-cookie#205]
It should be noted in the readme that the expires attribute can accept a float, and will be converted into hours/minutes. I needed a cookie to expire in 12 hours and the following worked:

~~~
Cookies.set('name', 'value', { expires: 0.5 });
~~~

**Comment by FagnerMartinsBrack** [comment]
The Wiki has something about it: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#expire-cookies-in-less-than-a-day

**Comment by FagnerMartinsBrack** [comment]
@robyedlin Did that comment solved your issue? Is there anything we can do in the docs to make that clear? Do you have any suggestions? Want to create a Pull Request to update the docs?

**Comment by robyedlin** [comment]
Sorry, I think the wiki inclusion is fine!
