### ISSUE TITLE
Setting parent domain from subdomain doesn't work

### ISSUE THREAD

**Issue by cultron** [js-cookie/js-cookie#213]
I've tried setting `.domain.com` from `sub.domain.com` and it just sets `sub.domain.com` instead of `.domain.com`.

Cookie.set('name', 'value', { domain: '.domain.com' } == "name=value; domain=sub.domain.com"

**Comment by FagnerMartinsBrack** [comment]
According to the [domain attribute docs](https://github.com/js-cookie/js-cookie/tree/d430a7351127fc3ea0e231103a2badbeedda0e55#domain):

> ... The cookie will also be visible to all subdomains.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by stephenhandley** [comment]
? Dude.

**Comment by FagnerMartinsBrack** [comment]
> ? Dude.

Can you elaborate?

**Comment by stephenhandley** [comment]
I actually had more of a general question about cookies, do you understand them well?

**Comment by FagnerMartinsBrack** [comment]
@stephenhandley js-cookie issue tracker is just for issues related to js-cookie library. For general questions, please refer to stackoverflow.com.

**Comment by stephenhandley** [comment]
but you understand cookies pretty well, right?

**Comment by stephenhandley** [comment]
seems like you understand cookis pretty well or why make a cookie library on bower?

**Comment by stephenhandley** [comment]
? Dude.

**Comment by Ravenna** [comment]
I have this same issue @FagnerMartinsBrack , any help is appreciated.  
I am setting a cookie on a subdomain(foo.example.com) and I want it available to example.com.  

My create code: Cookies.set('loggedin', '1', { expires: 7 }, { path: '/' }, { domain: '.example.com' });

I have been playing with this for a good while no matter what I change the cookie is always set for foo.example.com.  Any ideas?

**Comment by Ravenna** [comment]
@FagnerMartinsBrack nevermind my issue was the same as #90.  To many parameters.  Works like a charm when you set it right.

**Comment by stephenhandley** [comment]
Dude.
