### ISSUE TITLE
is it possible to get cookie expiration time?

### ISSUE THREAD

**Issue by iTayGNR** [js-cookie/js-cookie#218]
hey,
i want to make a cookie which is alive for 5 minutes and prevents users to upload posts if they haven't waited 5 minutes since the last time they uploaded a post. I need to get the expiration time of that cookie - it is possible?

**Comment by FagnerMartinsBrack** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#expire-cookies-in-less-than-a-day

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by jacek213** [comment]
Well, I need to get cookie expiration time too. FAQ doesn't cover that.

**Comment by FagnerMartinsBrack** [comment]
@jacek213 You mean get the value it was set? You can't get the expiration of the cookie. There's no browser API for that.
