### ISSUE TITLE
How to make a Cookie expires in 1 minutes?

### ISSUE THREAD

**Issue by RafaelPlantard** [js-cookie/js-cookie#222]
Is it possible make a Cookie expires in 1 minute?

**Comment by renatonascalves** [comment]
@RafaelPlantard Check here: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions

**Comment by FagnerMartinsBrack** [comment]
Closing as answered above, thanks @renatonascalves.

**Comment by renatonascalves** [comment]
Anytime! ;)

**Comment by RafaelPlantard** [comment]
Thanks @renatonascalves
