### ISSUE TITLE
FAQ: Why when my cookies are too big they are being deleted?

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#227]
Issues opened about confusions created due to the cookie size:
- js-cookie/js-cookie#194
- js-cookie/js-cookie#76 
- js-cookie/js-cookie#88
- js-cookie/js-cookie#35 
- https://github.com/js-cookie/js-cookie/issues/76#issuecomment-139660396
- carhartl/jquery-cookie#221
- js-cookie/js-cookie#199

Cookies are not meant to store big chunks of data, just small identifiers. The JSON support is just to allow it to have a structure, but one should never abuse it and store a lot of stuff in there because you will reach the maximum limit of 4096 bytes.

(use `js.cookie.debug.js` if already built, see #57)

**Comment by fiendish** [comment]
Could you switch over to localstorage internally if the size is too large instead of silently failing on the premise that failing is bad and silently failing is even worse?

**Comment by FagnerMartinsBrack** [comment]
> Could you switch over to localstorage internally if the size is too large instead of silently failing, on the premise that failing is bad and silently failing is even worse?

@fiendish Using `localStorage` is out of the scope of this project. Unfortunately, js-cookie's abstraction leaks a lot of things from the browser `document.cookie` implementation so we try to document everything as much as we can. Using `localStorage` would require us to mimic the cookie limitations in order to preserve the API, which is a complexity that [we'd rather avoid](ttps://medium.freecodecamp.com/code-that-dont-exist-is-the-code-you-don-t-need-to-debug-88985ed9604) at this stage.

**Comment by FagnerMartinsBrack** [comment]
> Could you switch over to localstorage internally if the size is too large instead of silently failing, on the premise that failing is bad and silently failing is even worse?

@fiendish Using `localStorage` is out of the scope of this project. Unfortunately, js-cookie's abstraction leaks a lot of things from the browser `document.cookie` implementation so we try to document everything as much as we can. Using `localStorage` would require us to mimic the cookie limitations in order to preserve the API, which is a complexity that [we'd rather avoid](https://medium.freecodecamp.com/code-that-dont-exist-is-the-code-you-don-t-need-to-debug-88985ed9604) at this stage.

**Comment by FagnerMartinsBrack** [comment]
Added to the Wiki: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions/d279bdbee6148b19c0f714d407a4c3e68a226f59
