### ISSUE TITLE
Setting multiple cookies

### ISSUE THREAD

**Issue by frozenfrank** [js-cookie/js-cookie#228]
The current library returns the string that was used in creating the cookie. It would be nice if the `Cookies.set()` function instead returned the `Cookie` object to allow chaining. Then I would be allowed to do `Cookies.set('name1','value1').set('name2','value2');`

**Comment by FagnerMartinsBrack** [comment]
> The current library returns the string that was used in creating the cookie.

The return is not documented in the API.

> The current library returns the string that was used in creating the cookie.

What would be the benefit of chaining besides theoretical legibility that can be achieved wrapping in your custom domain model?

**Comment by frozenfrank** [comment]
Im just saying that returning the string used provides no benefit while returning the object does...

**Comment by FagnerMartinsBrack** [comment]
> I'm just saying that returning the string used provides no benefit while returning the object does...

What is the benefit of chaining? Is there any benefit that is not theoretical?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.
