### ISSUE TITLE
Can't read cookies when using rollup

### ISSUE THREAD

**Issue by MartinMuzatko** [js-cookie/js-cookie#229]
![image](https://cloud.githubusercontent.com/assets/2950505/16494583/235e3bc8-3eea-11e6-84c5-3ab4b18420ed.png)

As you can see, with the latest version, I can't read cookies anymore.
Even though they are written to document.cookie.

![image](https://cloud.githubusercontent.com/assets/2950505/16495252/e661234a-3eec-11e6-813a-73dbe4ac27ca.png)

This is my rollup configuration:

```js
rollup({
        sourceMap: true,
        globals: {
            'jquery': '$',
        },
        plugins: [
            nodeResolve({
                jsnext: true,  // Default: false
                main: true,  // Default: true
                browser: true,  // Default: false
                extensions: [ '.js', '.json' ],  // Default: ['.js']
                preferBuiltins: false  // Default: true
            }),
            commonjs({
                include: 'node_modules/**'
            }),
            inject({
                exclude: 'node_modules/**',
                $: 'jquery',
                jQuery: 'jquery',
                Cookies: 'js-cookie',
                Spinner: 'spin.js',
            })
        ]
    })
```

**Comment by FagnerMartinsBrack** [comment]
Try incognito, you might have other cookie with the same name shadowing the one you are trying to create.

**Comment by MartinMuzatko** [comment]
I hoped this would be the answer. But nope. Cleared all cookies (even tried in different browsers)

![image](https://cloud.githubusercontent.com/assets/2950505/16514358/9edbf836-3f6b-11e6-8ff2-50b5fb3c7b17.png)


If you want to try it yourself, please visit https://www-dev.k15t.com/

**Comment by FagnerMartinsBrack** [comment]
Sorry, but I need a small example that doesn't require debugging an entire site that I am not familiarized with.

From the [CONTRIBUTING.md guidelines](https://github.com/js-cookie/js-cookie/blob/960a75ed4f5876327c2a7628cc6e41be282effcc/CONTRIBUTING.md#issues):

> If reporting a bug, please add a simplified example.

Can you please come up with a [Simplified Example](http://sscce.org) or post the question on [StackOverflow](http://stackoverflow.com) under the tag `js-cookie`? Thanks.

**Comment by MartinMuzatko** [comment]
Sure. I'll organize a reduced test case.

**Comment by MartinMuzatko** [comment]
Alright, changed the build process to webpack - works perfectly now!
