### ISSUE TITLE
JQuery Set cookie for different path

### ISSUE THREAD

**Issue by cgtv** [js-cookie/js-cookie#232]
Please check Stackoverfow :
http://stackoverflow.com/questions/38327826/jquery-set-cookie-for-different-path

**Comment by FagnerMartinsBrack** [comment]
Hi, please post a [simplified example](http://sscce.org) as required from the contributing guidelines.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.
