### ISSUE TITLE
Can't import npm package?

### ISSUE THREAD

**Issue by hakunin** [js-cookie/js-cookie#233]
Hi,
sorry for a stupid question, but I just can't seem to import the `Cookies` object in my project no matter what I try.

Here is what I tried:
```
import 'js-cookie'
````
and
```
import Cookie from 'js-cookie'
window.Cookie = Cookie
```

None produce any Cookie names object in the window, or local context.
I can import any other packages just fine, but somehow not this one.

Any ideas why that might be?

**Comment by FagnerMartinsBrack** [comment]
We haven't tested the library with any ES6 feature yet. Feel free to create a Pull Request adding compatibility with ES6 while maintaining backwards compatibility with ES5, if that's possible.

Unfortunately, we can't use transpilers in the code on master to use ES6 because many people use the code straight from Github and it might break if their browser does not support ES6 features.

Maybe if you come up with a PR we can talk about it and maybe find the best solution for addressing this.

**Comment by hakunin** [comment]
Oh, in that case it would be nice to have a big warning somewhere so that people don't waste time banging their haid on the desk like I did :)

**Comment by hakunin** [comment]
So what I end up doing was adding a file in my projects where it says
```
window.Cookies = require('js-cookie');
```
And importing it from the main file where I import stuff.

**Comment by FagnerMartinsBrack** [comment]
@hakunin 

> Oh, in that case it would be nice to have a big warning somewhere so that people don't waste time banging their haid on the desk like I did :)

Or maybe it would be nice if someone could help out investigating and implementing the feature, after all this is an open-source project.

The minimum one could do is contributing to make it better as a reward for many hours of confusion and pain that the project saved from, those hours would otherwise be wasted. If someone is wasting time struggling for a feature that doesn't exist, then it might aswell help implementing that :)

**Comment by ThaNarie** [comment]
The es6 module spec doesn't have anything similar to the `module.exports = obj`, there's only default and named exports.

Fortunately, you can still fake it by doing:
```
import * as Cookies from "js-cookie";
```
In this case, all the variable and functions from the exported object will be 'transferred' over the the `Cookies` object.

Note: If you are using TypeScript, use the `--allowSyntheticDefaultImports` flag.

So no code changes needed, adding this usage to the docs however would be nice :)

**Comment by FagnerMartinsBrack** [comment]
@ThaNarie Thanks for the example

**Comment by jrgleason** [comment]
I added 

`import * as Cookies from "js-cookie";`

and I get `(4,26): error TS2307: Cannot find module 'js-cookie'.`

package.json says.. `"js-cookie": "^2.1.3",`

**Comment by ThaNarie** [comment]
You might also need definitions for this :)

e.g.; put `declare module "js-cookie";` somewhere.
https://www.typescriptlang.org/docs/handbook/modules.html

**Comment by FagnerMartinsBrack** [comment]
@jrgleason We need a [simplified example](http://sscce.org) that proves there's a problem in js-cookie. If you can't do it, post the question in [StackOverflow](http://stackoverflow.com) under the tag `js-cookie`.

**Comment by aymericbouzy** [comment]
I just installed version `2.1.4` and the following works for me with webpack : 
```js
import Cookie from 'js-cookie'

Cookie.get("foo")
```

**Comment by FagnerMartinsBrack** [comment]
@aymericbouzy Can you track down which commit fixed this? I don't remember to have done any change to a module definition between 2.1.3 and 2.1.4.

**Comment by ThaNarie** [comment]
It might be babel 6, it does the same thing as TS with the `allowSyntheticDefaultImports` flag; converts commonjs `module.exports =` to a default export when importing it as a es6 module default import.

**Comment by aymericbouzy** [comment]
I have babel 6 indeed, but I can't tell if that's the reason it's working for me.

**Comment by FagnerMartinsBrack** [comment]
@ThaNarie @aymericbouzy It would be great if you guys could track down the solution. This issue receives a good amount of exposure since I linked @ThaNarie's [comment in the README](https://github.com/js-cookie/js-cookie/commit/583c52457fa1bb6ac823fa687ef52749a9cd2fa2).

**Comment by ThaNarie** [comment]
When using the babel REPL, and you import this library:
```
import Cookie from 'js-cookie'

Cookie.get('foo');
```
It will transpile to:
```
'use strict';

var _jsCookie = require('js-cookie');

var _jsCookie2 = _interopRequireDefault(_jsCookie);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_jsCookie2.default.get('foo');
```

As you can see, the export module is wrapped in an object with the default key, so it will also work in es2015 module systems.

More info:
https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/

All this is totally unrelated to this project, and applies to everything being exported with `module.exports = ` on the internet.

If you like I can edit my linked comment to add this info.

**Comment by FagnerMartinsBrack** [comment]
@ThaNarie 

> If you like I can edit my linked comment to add this info.

That can be useful for those coming from a search engine.
