### ISSUE TITLE
Cookies.get might get real boolean type value

### ISSUE THREAD

**Issue by jackycute** [js-cookie/js-cookie#235]
I'm not sure about this issue is caused by browser or this package.
Tested under Chrome v51 and test both in Mac OS X and Windows (and also iOS Safari).

When it get some value with key like `Cookies.get('loginstate')`.
It might get real boolean type value like `true` but it should be in string type `"true"`.

But I can't reproduce it anywhere, just been so confused.
Could you please tell me do this package specifically cast the value to string no matter what it was? Or just extract and leave it alone?

Thanks a lot!

**Comment by FagnerMartinsBrack** [comment]
Can you please provide a [simplified example](http://sscce.org)?

**Comment by jackycute** [comment]
You get the point about `window.json`!
Somehow the browser will auto mapping the dom with id `json` if you call `window.json` (so and others).
And that cause the issue.

https://jsfiddle.net/oLynz3yt/1/

**Comment by FagnerMartinsBrack** [comment]
I have created an issue to investigate that: https://github.com/js-cookie/js-cookie/issues/238.
