### ISSUE TITLE
Investigate issues with js-cookie and window.json

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#238]
There are some issues being reported about it, we need to investigate why this is leaking and how w can fix it without a huge impact in byte size:

* https://github.com/js-cookie/js-cookie/issues/235
* https://github.com/js-cookie/js-cookie/pull/237#issuecomment-232858028
* https://github.com/js-cookie/js-cookie/issues/117

This can also happen when we have an element with and id `json` instead of just `window.json`.

**Comment by jshuaf** [comment]
Changing `this.json` to `window.json` fixed it for me. Prior to the fix, `Cookies.get()` always returned empty.
