### ISSUE TITLE
encoding compatibility?

### ISSUE THREAD

**Issue by ash-f** [js-cookie/js-cookie#240]
Cookie value js-cookie set is encoded differently from encodeURIComponent() or PHP.
How is it possible to set same value with encodeURIComponent() or PHP?

**Comment by FagnerMartinsBrack** [comment]
Did you read the docs?

https://github.com/js-cookie/js-cookie/tree/960a75ed4f5876327c2a7628cc6e41be282effcc#encoding

https://github.com/js-cookie/js-cookie/tree/960a75ed4f5876327c2a7628cc6e41be282effcc#converters

https://github.com/js-cookie/js-cookie/blob/960a75ed4f5876327c2a7628cc6e41be282effcc/SERVER_SIDE.md

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
