### ISSUE TITLE
WARNING's from UglifyJs

### ISSUE THREAD

**Issue by AliveDD** [js-cookie/js-cookie#243]
when i use js-cookie (v2.1.2) in my project, my webpack with uglify get me warnings:

`Condition always true [./app/js.cookie.js:9,0]`
`Dropping unreachable code [./app/js.cookie.js:11,2]`
`Declarations in unreachable code! [./app/js.cookie.js:14,0]`
`Dropping unused variable OldCookies [./app/js.cookie.js:14,0]`
`Dropping unused variable api [./app/js.cookie.js:15,0]`

**Comment by FagnerMartinsBrack** [comment]
Can you provide [a small example](http://sscce.org) and track down what those warnings mean? This could be a bug with webpack with uglifyjs, but even if it is not, I need to know what is exactly the problem and how it is related to js-cookie.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again

**Comment by AliveDD** [comment]
for example — 1st string of log — 9th string in code:
uglify says: Condition always true
for: `if (typeof define === 'function' && define.amd) {`

**Comment by FagnerMartinsBrack** [comment]
@AliveDD I have tried to minify online on https://skalman.github.io/UglifyJS-online/ and it works. As mentioned later, can you provide a [SSCCE](http://sscce.org) that reproduces uglify throwing that error?
