### ISSUE TITLE
Feature Request: Remove all cookies with prefix

### ISSUE THREAD

**Issue by shivanraptor** [js-cookie/js-cookie#246]
This library works great, but if the library can support removing cookies, which has the same prefix, in batch, it will be perfect.

Is that possible?

**Comment by FagnerMartinsBrack** [comment]
Hi, this is out of the scope of the project. We just provide a simple API for encoding/decoding cookies. We encourage to use js-cookie as a dependency for a custom module that does what you want to, we have plenty of support for AMD, CommonJS, etc.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
