### ISSUE TITLE
Default value for "path" attribute

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#25]
Now we have the opportunity to rethink the browser defaults.

I understand there is a lot of requests to change the default path to the whole site instead of relying in the browser defaults:

* https://github.com/carhartl/jquery-cookie/issues/284
* https://github.com/carhartl/jquery-cookie/issues/2
* https://github.com/carhartl/jquery-cookie/issues/332
* https://github.com/carhartl/jquery-cookie/pull/108
* https://github.com/carhartl/jquery-cookie/issues/266
* https://github.com/carhartl/jquery-cookie/issues/193
* https://github.com/carhartl/jquery-cookie/issues/178
* https://github.com/carhartl/jquery-cookie/issues/225

What I notice is that a lot of developers do not bother to understand the specifics of how `document.cookie` work. They rely entirely in abstractions provided by scripts like js-cookie and expect the defaults to account for the most common use cases.
I wonder if it makes sense to change the default value of the "path" attribute for the version 2.0.

@carhartl Thoughts?

**Comment by jerek** [comment]
This would be great! It's rare to want a cookie to not be site-wide, and the browser defaults are rather awkward.

**Comment by FagnerMartinsBrack** [comment]
Cookies are sent on each request. I believe the reason for restricting cookies visibility in a given path is also to prevent unnecessary byte transmission. Each cookie can have a size up to 4k, and they are **not** gzipped.

**Comment by carhartl** [comment]
@FagnerMartinsBrack Is this an argument against choosing "/" as a default value?

Given the amount of requests I am convinced that making cookies side-wide out of the box is the best choice (personally I still think different). 

I don't think developers are going to create many cookies containing lots of data client-side?

**Comment by FagnerMartinsBrack** [comment]
This is not in favor or against, just pointing out the trade-offs. Considering the ease to create a cookie using the library and the size JSON storage with 3 bytes encoded characters uses, I believe it is safe to assume people will be creating a lot of cookies.

But that´s just speculation, if performance is an issue one could delete the defaults using:

```javascript
delete Cookies.defaults.path
```

If you think this should be default then let´s do it. I am really not in favor nor against since anyone can change defaults at any time anyway.

**Comment by FagnerMartinsBrack** [comment]
I have started this implementation and here is how it works with the default path attribute to `/`.

Consider I am reading the cookie from the server:

```javascript
document.cookie = 'c=v';
```

Now I want to remove it using `js-cookie`. The first thing I would try and expect to work is this:

```javascript
Cookies.remove('c');
```

But it doesn't work. `js-cookie` is trying to remove the cookie using the `js-cookie` custom default attributes, in this case `path: '/'`. To be able to remove it successfully, one should pass the custom attribute to the `remove` function or change the defaults:

```javascript
Cookies.remove('c', {
  path: ''
});
```

```javascript
Cookies.defaults.path = '';
Cookies.remove('c');
```

If after altering the defaults one wants to roll back to `js-cookie` defaults (not browsers defaults), then it's just to delete the custom property from the `defaults` like this:

```javascript
delete Cookies.defaults.path;
```

Then it will consider the default path attribute to `/` for `set/get/remove` operations:

It is a little confusing when dealing with cookies from the server, but if you deal with cookies only through `js-cookie` or one of it's [available language ports](https://github.com/js-cookie), then it is just a matter of declaring what you want to do without worring about any configuration:

```javascript
Cookies.set('c', 'v'); // default: "path: /"
Cookies.remove(); // removed successfully using default: "path: /"
```

**Comment by FagnerMartinsBrack** [comment]
Closed from https://github.com/js-cookie/js-cookie/commit/1a0d1ed13c106382d2cfe1186a73e8091e4ac349
