### ISSUE TITLE
Display splash page on first load

### ISSUE THREAD

**Issue by e11even** [js-cookie/js-cookie#267]
My JS skills are pretty much zero but I found your solution via css-tricks (https://css-tricks.com/redirecting-to-a-splash-page-but-only-once-with-cookies/). All I'd like to do is set a cookie to check if it is a user's first visit to the current page and if so redirect them to an on-boarding screen. Next time they visit the page this must not happen, they must stay on the current page. How do I do this?

**Comment by anuja-joshi** [comment]
@e11even  what I feel is, this is not an issue with library as you have doubts regarding implementation, you should have asked this on [Stackoverflow](http://stackoverflow.com/questions/tagged/js-cookie).
This might help you:
```
$(function() {
	var COOKIE_NAME = 'isOnBoardingCompleted';
	var OnBoarded = Cookies.get(COOKIE_NAME);
	if (!OnBoarded) {
		Cookies.set(COOKIE_NAME, true, { expires: 365, path: '' });
		// send to on-boarding screen
	}
});
```
here, you have to chose cookie expiry time wisely as it will get expired after those many days and user will again get redirected to on-boarding, same in case if user explicitly clears cookies. If you do not want this to happen then maintain this user info in database, whether he is on-boarded or not and then redirect accordingly(this decision totally depends on your requirements).

**Comment by FagnerMartinsBrack** [comment]
As @anuja-joshi said, this is for issues related to te library, not usage issues. For support, the best place is StackOverflow.

**Comment by e11even** [comment]
Thanks guys, rookie mistake. I got it working eventually, it was a simple problem with loading order of JS files.
