### ISSUE TITLE
Browserify w/ NPM : Uncaught ReferenceError: getCookie is not defined

### ISSUE THREAD

**Issue by dimic00** [js-cookie/js-cookie#268]
Hi, 

I try to use js-cookie with Browserify and NPM.
I check my compiled JS files, js-cookie is inside, everything look fine.

But when I want to use function of js-cookie, I got this error : 

`Uncaught ReferenceError: getCookie is not defined`

Am I doing something wrong ?

**Comment by gchudnov** [comment]
Hi dimic00,

are you sure your issue is related to `js-cookie`?
There is no `getCookie` in the source code of this library.

**Comment by dimic00** [comment]
My bad, I forget to delete this line...
But the problem is still here, different but still here.

`Uncaught ReferenceError: Cookies is not defined(anonymous function)`

refer to

`var _myvar_ = Cookies.get('_mycookiename_');`

**Comment by gchudnov** [comment]
Guess, you should import the library, like this:
```
var Cookies = require('js-cookie');
```
or if you use ES6 with babel + browserify,  you can use import:
```
import Cookies from 'js-cookie'
```
and later:
```
var value = Cookies.get('KEY');
OR
const value = Cookies.get('KEY'); // ES6
```

**Comment by dimic00** [comment]
Ok works now, I didn't use the correct var for the require, like this
`var Cookies = require('js-cookie');`

Thanks for your help! I feel so stupid to look for the solution during too much times :3

**Comment by gchudnov** [comment]
You're welcome!
