### ISSUE TITLE
Default value for cookies

### ISSUE THREAD

**Issue by james4388** [js-cookie/js-cookie#270]
When I need to provide default value to cookie key I have to do:
```
var value = Cookies.get('key');
if (typeof(value) === 'undefined') {
    value = default_value;
}
```

Can we modify api to accept default value? Is there any reason not to do so? May I provide a pull request?

**Comment by FagnerMartinsBrack** [comment]
We had similar discussions in the past, see https://github.com/js-cookie/js-cookie/issues/202 and https://github.com/js-cookie/js-cookie/issues/135.

**Comment by james4388** [comment]
Well you can do Cookies.get('key') || 42 and it return 42 but thing come complected when cookie value is true / false
Cookies.set('key', false)
Cookies.get('key') || true => true
But since all cookie value become string then this problem is not an issue. You can close this then.

PS to preserve get parameter for something useful in the future. we can use arguments.

**Comment by FagnerMartinsBrack** [comment]
The only issue could be when the value is an empty String, but in that case, it is easy to create a wrapper that does something like:

```javascript
getCookieWithDefaultValue('key', '42');
```

And uses js-cookie underneath.
