### ISSUE TITLE
Cookies arent set

### ISSUE THREAD

**Issue by DevCubeHD** [js-cookie/js-cookie#272]
I can set cookies as on the example, but when I do document.cookies or Cookies.get(); there is nothing in it or it just returns an empty object...

Cookies.set("credentials", "DevCu");
Answer: "credentials=DevCu; path=/"
Cookies.get();
Answer: Object {}
document.cookie
Answer: ""

**Comment by angularDEV** [comment]
I am facing the same issue, with no cookies returned in **document.cookie**, even after setting up **js-cookie** for angular version 1.2.x  

Any solutions/suggestions.

**Comment by FagnerMartinsBrack** [comment]
We need a [SSCCE](http://sscce.org) to be able to take any action on this. Please provide a failing example, thanks.

**Comment by DevCubeHD** [comment]
As I told you I copied the example 1:1

**Comment by FagnerMartinsBrack** [comment]
I just checked and the code is working correctly wth version 2.1.3. Please provide a failing simplified example as stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md) with steps on how to reproduce it.
