### ISSUE TITLE
Check the cookies

### ISSUE THREAD

**Issue by sundar2016** [js-cookie/js-cookie#274]
How to check the Cookie variable?  is this set or not?

**Comment by FagnerMartinsBrack** [comment]
The documentation [has very good explanations](https://github.com/js-cookie/js-cookie/tree/7fd36e66b60a4e0ac9d09207fb3a348a2969152c#javascript-cookie--) of how to use it.

The issue tracker is for issues regarding the library, not supporting questions. For supporting questions, please ask it on [StackOverflow](stackoverflow.com) under the tag [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie).
