### ISSUE TITLE
Support for SameSite cookie (Strict vs Lax)

### ISSUE THREAD

**Issue by pjdicke** [js-cookie/js-cookie#276]
A security audit has required us to add the SameSite param to cookies. I was wondering if there was any plans to include this newer spec in this plugin?

**Comment by FagnerMartinsBrack** [comment]
Same as https://github.com/js-cookie/js-cookie/pull/275, #78 and #264.

> I was wondering if there was any plans to include this newer spec in this plugin?

We do have plans to include it once the RFC enters the category of `Standards Track`.

@TBoonX, @kukulich: why did you all decide to request support for it just now? The spec [has been there since 2014](https://tools.ietf.org/html/draft-west-first-party-cookies-00) but just now we are getting requests to support it in js-cookie. Did anything change or this is just coincidence?

**Comment by FagnerMartinsBrack** [comment]
@kukulich What about IE, Safari, Edge, and Firefox?

**Comment by kukulich** [comment]
@FagnerMartinsBrack No support currently in other browser. However Chrome has big share, especially on mobiles.

**Comment by pjdicke** [comment]
@FagnerMartinsBrack, just to add to why it may be a good time to add this, the audit came from HBO. Big players are looking for this attribute.

**Comment by FagnerMartinsBrack** [comment]
FYI, there's [a PR to fix this](https://github.com/js-cookie/js-cookie/pull/284) by allowing arbitrary cookie attributes to be used at the own risk of the developer.

**Comment by FagnerMartinsBrack** [comment]
Changing to milestone 2.2.0 to document explicit support for `SameSite` attribute once we feel comfortable to do so (at least when most browsers support it and the spec is finalized).

**Comment by FagnerMartinsBrack** [comment]
Might be worth linking the feature on README to this blog post: https://scotthelme.co.uk/csrf-is-dead/. Or maybe in the Wiki.

**Comment by suprMax** [comment]
We're also interested in this feature

**Comment by FagnerMartinsBrack** [comment]
One more useful link: https://blogs.dropbox.com/tech/2017/03/preventing-cross-site-attacks-using-same-site-cookies

**Comment by FagnerMartinsBrack** [comment]
@suprMax Feel free to use `master` until the next release.
@mikewest IS it safe for libraries to support this feature at this stage?

**Comment by FagnerMartinsBrack** [comment]
https://github.com/js-cookie/js-cookie/releases/tag/v2.2.0
This is officially released! Thanks for everyone involved.

**Comment by sunknudsen** [comment]
Trying to set `sameSite` in a TypeScript project but the `CookieAttributes` interface doesn’t include the `sameSite` property. Also coudn’t find docs for `sameSite` on https://github.com/js-cookie/js-cookie/tree/latest#readme, but https://github.com/js-cookie/js-cookie/releases/tag/v2.2.0 announces its implementation. Am I missing something?

**Comment by carhartl** [comment]
We accept attributes that work as is without a qualified api:

```javascript
Cookies.set('foo', 'bar', { 'samesite': 'strict'})
```


```

**Comment by carhartl** [comment]
Not sure about the TypeScript definitions, we decided to provide them as part of this package for the upcoming v3 release.

**Comment by ez4gis** [comment]
> We accept attributes that work as is without a qualified api:
> 
> ```js
> Cookies.set('foo', 'bar', { 'samesite': 'strict' })
> ```

@carhartl   

I'm new to js-cookie, recently seeing warning in Chrome console about 'SameSite;.  Sorry for asking maybe the obvious to some.

1) was it `samesite` or `sameSite`?
2) if I want to set `SameSite` to "None" and `Secure` to true,  what syntax shoudl I use in js-cookie library. Is it camelCase, or all-lowercase for property name and/or value?  Thanks.

```js
Cookies.set('foo', 'bar', {samesite: 'none',  secure: true};
```
or
```js
Cookies.set('foo', 'bar', {sameSite: 'None', secure: true};

**Comment by carhartl** [comment]
We should probably document `samesite`, and also consider it in these type definitions. At the moment this is not consistent with say `domain` or `path`, which are also just strings and would just work when passed.

Would it be expected to have an api such as: `sameSite: 'strict'?

**Comment by carhartl** [comment]
@ez4gis

The MDN docs say regarding SameSite:

> Possible values for the flag are lax or strict

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

Not sure about “none”. I guess you’d omit it?

Regarding your other question, with

```javascript 
Cookies.set('foo', 'bar', {samesite: 'none',  secure: true};
```

you’d currently be on the safe side.

**Comment by ez4gis** [comment]
Thank you, @carthartl

regarding the 'None' value, I noticed that on MDN page regarding [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie),  it listed `Strict`, `Lax` and `None` as SameSite value.

> @ez4gis
> 
> The MDN docs say regarding SameSite:
> 
> > Possible values for the flag are lax or strict
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
> 
> Not sure about “none”. I guess you’d omit it?

**Comment by FagnerMartinsBrack** [comment]
Here's what the RFC says: https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1
>If the "attribute-name" case-insensitively matches the string
>   "SameSite", the user agent MUST process the "cookie-av" as follows:

"SameSite" that is. If it doesn't work, create a bug ticket for the offending browser.

---

@carhartl said:

> Not sure about the TypeScript definitions, we decided to provide them as part of this package for the upcoming v3 release.

Here are the TypeScript definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/js-cookie/index.d.ts

You can try to specify "SameSite" property as a valid TypeScript attribute, but then that means we need to create tests for it and a README for those who don't use TypeScript in case we want to support "officially".

----

@sunknudsen @ez4gis 

Right now the burden is on the developer to make due research, find the spec and get the correct name for the "SameSite" property.

Here's the link again: https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1

**Comment by carhartl** [comment]
Let’s not confuse the cookie header specification (`SameSite`) and the `document.cookie` API. The latter is expecting a value of `samesite`, at least according to https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

The referenced type definitions are wrong in terms of `sameSite`, another reason to finally provide our own, correct ones. 

In terms of the API I believe it’s the right thing to provide a `sameSite` option — tested and documented. By now it’s a common cookie attribute even when it’s not supported by IE. As a developer that’s what I would expect, and apparently other’s as well.

**Comment by carhartl** [comment]
Regarding IE support MDN has somewhat contradicting information: 

Says no: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

Says yes (kind of, isn’t granular enough):
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by carhartl** [comment]
>In terms of the API I believe it’s the right thing to provide a sameSite option — tested and documented.

Or at least *document* that it’s possible to provide arbitrary options, which already enables samesite support.

**Comment by FagnerMartinsBrack** [comment]
Damn, that was stupid! Does that mean the RFC is only for the Set-Cookie header? Oh my... 🤦‍♂ 

Redacted.

**Comment by carhartl** [comment]
Here's the twist.. at least in Chrome all of the attributes passed to `document.cookie` work in a case insensitive manner. All of the following do set the SameSite as expected:

```javascript
document.cookie = "foo=bar; samesite=lax"
document.cookie = "foo=bar; SameSite=lax"
document.cookie = "foo=bar; SAMESITE=lax"
document.cookie = "foo=bar; sAmEsItE=lax"
```

**Comment by carhartl** [comment]
So it might be the case that 

```javascript
Cookies.set('foo', 'bar', { sameSite: 'lax' })
```

works just fine already. We'd just add documentation.

**Comment by FagnerMartinsBrack** [comment]
Write a test for `SameSite`. If Browser Stack passes the test for all supported browsers then there we have the answer :D

**Comment by carhartl** [comment]
> Write a test for SameSite. If Browser Stack passes the test for all supported browsers then there we go with the answer :D

Not quite. Since you can throw any garbage at `document.cookie` without knowing whether it works or not, this method wouldn’t help. We‘d have to create a rather convoluted, Selenium based end-to-end test for verification. Yeah right, not going to happen.

After all this worked already, even the type definitions were not wrong in a way, someone seemed to have missed documentation.

**Comment by FagnerMartinsBrack** [comment]
> We‘d have to create a rather convoluted, Selenium based end-to-end test for verification. Yeah right, not going to happen.

Yeah, I was thinking of setting up two servers in different ports and then checking if the cookie is accessible or not (maybe using iFrames?).

Indeed a lot of work.

**Comment by nolimitdev** [comment]
Im wondered with this topic. SameSite attribute is only for server headers. It is not possible to set this cookie `document.cookie = "foo=bar; SameSite=lax"` even though Secure attribute is added `document.cookie = "foo=bar; SameSite=lax; Secure"` which is required since future Chrome v80.  Now in Chrome v78 it is not working - cookie is rejected at all. Firefox sets cookie but without SameSite attribute. In chrome is possible to set via JavaScript only SemeSite=None but in Firefox it is ignored.

I think that feature added thanks this issue should be removed because it is misleading and not working. Strict and Lax attributes are never set via JavaScript.

**Comment by devlinjunker** [comment]
so what's up with this? we need to use a newer version of js-cookie than 2.2.0?

Is there a specific syntax needed? I have been trying with 2.2.1 and ```cookies.set(SESSION_TOKEN_COOKIE_KEY, sessionToken, { secure: true, samesite: 'None' });```

**Comment by FagnerMartinsBrack** [comment]
As of https://github.com/js-cookie/js-cookie/pull/293, we've opened up the possibility to specify Custom Attributes that are unsupported by js-cookie documentation.

Quote from the linked PR:

> This is not a green light to support all custom attributes. js-cookie only supports and documents attributes described in the public API documentation because they are usually known to work in most browsers. Anything different than that should be considered unsafe.

If things have changed and now `SameSite` is mainstream, then we'll have to create a Pull Request to update the documentation. I'm not sure why Snyk is requiring an upgrade from 2.2.0 to 2.2.1. AFAIK Snyk is a security-related tool and there are no security issues with js-cookie in 2.2.0.

The code for Custom Attributes is working fine, [click here to see the test](https://github.com/js-cookie/js-cookie/blob/7d41e167ab6e4c1f65716d7a1ad2533fb952e80b/test/tests.js#L329-L340). If this is a potential bug we need a new issue and [an SSCCE](http://sscce.org/) that you can attach and can download and run.

**Comment by devlinjunker** [comment]
Hmm interesting... well it looks like the code is working. I am able to use the Chrome inspector and see that the `SameSite` and `Secure` attributes are included in the `stringifiedAttributes` variable when we are setting the cookie using `document.cookie` in js-cookie. 

So I'm not really sure if this is an issue with the way I am passing these parameters, something wrong with my chrome version, or something incorrect in how js-cookie is passing these attributes.

I've created this stackoverflow ticket to see if anyone else can help: https://stackoverflow.com/questions/60961752/document-cookie-and-chromes-samesite-secure-restrictions

**Comment by Terrox** [comment]
Will js-cookie use a default value which doesn't throw a warning to the console? so I don't need to go in and add samesite to all my code and work out which to use.

**Comment by carhartl** [comment]
@Terrox 
> so I don't need to go in and add samesite to all my code

You can use defaults, please see https://github.com/js-cookie/js-cookie/blob/latest/README.md

**Comment by Terrox** [comment]
> 
> 
> @Terrox
> 
> > so I don't need to go in and add samesite to all my code
> 
> You can use defaults, please see https://github.com/js-cookie/js-cookie/blob/latest/README.md#cookie-attributes

Yes I did using below code after including js-cookie
`// add Cookies defaults
Cookies.defaults = {
	sameSite: 'None',
	Secure: true
};`
