### ISSUE TITLE
I'm setting the cookie with domain but still able to access the cookie in the localhost

### ISSUE THREAD

**Issue by chopraaseem** [js-cookie/js-cookie#283]
Cookies.set('key',' value', {
		        expires: 30,
		        domain:'.xyz.com'
		    });
when I fetch in the console from localhost it show the cookie value
Cookies.get('key');

**Comment by chopraaseem** [comment]
Issue sorted bro my mistake figured it out :)

**Comment by FagnerMartinsBrack** [comment]
@chopraaseem What was the issue?

**Comment by abelschooleman** [comment]
What solved the problem? I'm having the same issue.

**Comment by chopraaseem** [comment]
Hi,

Just check whether any localstorage of that cookie is not being done and
even though we are setting the cookie along with domain but there might be
a possibility that the same cookie is set in the browser without domain
sometimes in the past. So we have delete that also when r changing the
cookie storing structure with new domain.

In case still having issue let me know.

Regards,
Aseem

**Comment by chopraaseem** [comment]
@FagnerMartinsBrack  you can close this bro
