### ISSUE TITLE
Remove all cookies of all domains

### ISSUE THREAD

**Issue by excme** [js-cookie/js-cookie#296]
Good day!
I started use js-cookie and have qusetion.
How to remove all cookies of all domains in browser?
Thanks

**Comment by FagnerMartinsBrack** [comment]
For security reasons, the browser doesn't provide an API to remove a cookie from a different domain. You need to remove each cookie from the page it's available, since the browser also doesn't provide an API to retrieve cookies from a different `path`.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by afeld** [comment]
What if it were able to clear all cookies that the page has access to, by iterating through cookie keys and then the domain/subdomain for each, as necessary?

**Comment by FagnerMartinsBrack** [comment]
@afeld That works for cookies the page has access to as [per the comment above](https://github.com/js-cookie/js-cookie/issues/296#issuecomment-274376922).

js-cookie doesn't support removing all of them, you can iterate over `Cookies.get()` or use something like http://npmjs.com/package/js-cookie-remove-all.

I recommend the first option cause then you have control of it and not coupled to versioning.
