### ISSUE TITLE
Bug using Cookie.remove with Edge / is Edge "supported"?

### ISSUE THREAD

**Issue by TheThirdRace** [js-cookie/js-cookie#300]
Hi,

I've been using js-cookies 2.1.3 for a while, but just discovered I'm having a problem with Cookies.remove() in Microsoft Edge.

I know Edge not listed as "supported" officially, but it's been working no problem to set cookies. Also, you still support IE6 so I wonder why you wouldn't support Edge... So I'm asking if Edge is supported or there are any plans to support it fully?

If it is supported, then as said earlier I have a bug with Cookies.remove().

When I log in, I set the guid in a cookie
`Cookies.set("user.guid", response.data[0].guid, {
							expires: ap.global.var.cookieExpire
						});`

Then later if I find out the guid is expired I remove the cookie
`Cookies.remove("user.guid");`

The remove doesn't work, Cookies.get() keep finding the cookie.

***
I did 1 more test and found out that if I use a dot "." in the name of the cookie, there's a problem. If I remove the dot, the cookies is removed without any problem. Chrome doesn't have any problem with the dot, is this a bug or a limitation of the browser?

Regards,

TheThirdRace

**Comment by FagnerMartinsBrack** [comment]
@TheThirdRace 

> I know Edge not listed as "supported" officially, but it's been working no problem to set cookies. Also, you still support IE6 so I wonder why you wouldn't support Edge... So I'm asking if Edge is supported or there are any plans to support it fully?

Edge is supposed to be supported as long as it follows the cookie spec (RFC 6265) correctly.

> I did 1 more test and found out that if I use a dot "." in the name of the cookie, there's a problem. If I remove the dot, the cookies are removed without any problem. Chrome doesn't have any problem with the dot, is this a bug or a limitation of the browser?

As far as I know there should be no issue with dots in the cookie name, since it's allowed according to the RFC 6265 (see [this StackOverflow answer](http://stackoverflow.com/a/1969339/1400037) for a less formal explanation).

Have you tested in other browsers such as Safari and Firefox?

**Comment by TheThirdRace** [comment]
@FagnerMartinsBrack 
Did some tests and only Edge is having the problem.

I opened the console in Edge, IE11, Firefox and Chrome. I created a cookie, deleted it and tried to retrieve it. Only Edge had a problem with a dot "." in the cookie name, every other browser worked.

As soon as you remove the dot ".", Edge works flawlessly.

**Comment by FagnerMartinsBrack** [comment]
@TheThirdRace Did you managed to reproduce the issue using `document.cookie`? If the problem happens there then maybe we need to report the issue on Microsoft Edge issue tracker.

Do you want to create a PR updating the list of supported browsers in Sauce Labs to add the version you're seeing issues and create a integration test for the "dot" in the cookie name?

This way we can prove the problem exists and ensure it doesn't happen again in other browsers.

**Comment by TheThirdRace** [comment]
Sorry, I don't know what "create a PR" means...

I did the test with document.cookie in Edge and it's working fine. I re-did the test with Cookies.remove() and it works too...

Now, these tests are performed on a different computer than the one exhibiting the problem so it might have something to do with the other computer. I'll have to do more tests, I'll keep you updated.

**Comment by FagnerMartinsBrack** [comment]
@TheThirdRace Take a look here, this might help: http://sscce.org/

**Comment by TheThirdRace** [comment]
That won't be necessary... 

Rebuilt/Recompile my website and now I can't reproduce it. I'm very sorry to have wasted your time. I did test it many times before reporting the problem, but it seems it wasn't thorough enough. 

Again, sorry...

**Comment by FagnerMartinsBrack** [comment]
@TheThirdRace my suggestion next time is to try to reduce the problem in a way it can be reproduced in an environment outside the application code. This way you can reduce the scope of the problem to the library 👍
