### ISSUE TITLE
No unpkg link

### ISSUE THREAD

**Issue by insign** [js-cookie/js-cookie#306]
https://unpkg.com/js-cookie exists but not found in the read me. It is a tip. :)

**Comment by FagnerMartinsBrack** [comment]
We could add that to the Wiki. The README is just or supported package managers.

**Comment by FagnerMartinsBrack** [comment]
I have added to the Wiki. See https://github.com/js-cookie/js-cookie/wiki/Community-Supported-CDNs/40333bf7b9daf20073f0f4fadeb7fe467367f81a.

**Comment by FagnerMartinsBrack** [comment]
[Added jsDelivr CDN to the README](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-340131636) because now they support on-demand minification.
