### ISSUE TITLE
Can't import to webpack project

### ISSUE THREAD

**Issue by tutv95** [js-cookie/js-cookie#310]
I used **Webpack** and **Typescript** to develop app and I import js-cookie by code:

`import 'js-cookie';` or `require('js-cookie')`

But I can't use variable `Cookies` as a global variable. 
Typescript report:
```
ERROR in ./src/app/index.ts
Module not found: Error: Can't resolve 'Cookies' in 'my_path/src/app'
 @ ./src/app/index.ts 1:0-18
 @ multi babel-polyfill ./src/app/index.ts
```

How can this be resolved?

Thanks 👍

**Comment by tutv95** [comment]
I have found the way to resolve this issue #233

**Comment by FagnerMartinsBrack** [comment]
Yeah, it's on the list to document better: https://github.com/js-cookie/js-cookie/issues/239
