### ISSUE TITLE
The RegExp for decode should ignore case

### ISSUE THREAD

**Issue by CFDylan** [js-cookie/js-cookie#313]
at Line105 of `src/js.cookie.js`, add ignoring case for `var rdecode = /(%[0-9A-Z]{2})+/g;` .

The cookie could be write at server side, which write it with lower case. Then a error would happen when decode string like `%e7%8e%a9`.

**Comment by FagnerMartinsBrack** [comment]
To deal with server-side you need to provide a custom decoder. Which server writes the cookie using uppercase percent-encoded characters? It might be worth adding an example in the [SERVERS.md](https://github.com/js-cookie/js-cookie/blob/2a367621645cefc27078e191f512224f9da9737a/SERVER_SIDE.md) file.

As stated explicitly in [the converters docs](https://github.com/js-cookie/js-cookie/tree/2a367621645cefc27078e191f512224f9da9737a#converters):

> Please note that the default encoding/decoding strategy is meant to be interoperable only between cookies that are read/written by js-cookie. To override the default encoding/decoding strategy you need to use a converter.

**Comment by CFDylan** [comment]
Thank you for your reply. The server-side is from many teams which use language with Node.js, Jave or PHP. So I provide a custom decoder for it : )

**Comment by FagnerMartinsBrack** [comment]
@CFDylan is it working then without having to change the library default decoding mechanism?

**Comment by CFDylan** [comment]
Yes, it is working by ignoring case.
