### ISSUE TITLE
Can get cookie but can not set and remove cookie

### ISSUE THREAD

**Issue by clarkk** [js-cookie/js-cookie#314]
I can get cookies without problems..

But if I try to remove a cookie `get_cookie` still print the value of the cookie

And I can not set the cookie.. After setting the cookie `get_cookie` still print the old value

The functions are called from the `success` callback from a jquery request

```
function get_cookie(name){
	var cookie = Cookies.getJSON(name);
	console.log(cookie)
	
	return cookie;
}

function set_cookie(name, data){
	Cookies.set(name, JSON.stringify(data), {
		expires: 30
	});
	get_cookie(name);
}

function remove_cookie(name){
	Cookies.remove(name);
	get_cookie(name);
}
```

**Comment by clarkk** [comment]
hmm.. dont know what happened, but after clearing all cookies in the browser it works..

I just want to mention that before I used the predecessor `carhartl` and have just switched to this because the old one has ended maintenance

**Comment by FagnerMartinsBrack** [comment]
Don't forget to read the [changelog](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0) and we need more detailed info. Please provide a [http://sscce.org/](Short, Self Contained, Correct (Compilable), Example)

**Comment by FagnerMartinsBrack** [comment]
Closing as it seems the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) seems to have found a solution and it looks like an environment issue.
