### ISSUE TITLE
How to load js-cookies in typescript for external use?

### ISSUE THREAD

**Issue by balexandre** [js-cookie/js-cookie#326]
Deleted the old question as I'm past that wall, but stumble upon another one that whatever I tried, I go nowhere :(

I've made a simple [question in StackOverflow](http://stackoverflow.com/q/43424758/28004) together with  a [test GitHub project](https://github.com/balexandre/ts-stackoverflow-question) if you prefer to follow up there.

Bottom line is that I'm having trouble loading **js-cookies** from inside my code and compiled typescript to use from my `index.html` file.

When compiling the typescript files, the `js-cookies` is not added into the `amd` modules, and my `client.js` file upon use, does not load it, throwing then the error:

![](https://s6.postimg.org/opad482ld/screenshot_335.png)

**Comment by balexandre** [comment]
I think it's as easy as using the [npm version](https://www.npmjs.com/package/js-cookie) ... darn me, always trying to complicate the simple things :)

**Comment by balexandre** [comment]
all working as intended now ... github project updated so it can serve as example for others like me (can't be many though).

please close this issue :)

**Comment by FagnerMartinsBrack** [comment]
Closing as from the request of [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af).

If you came here from Google having a similar issue, take a look in the [StackOverflow question above](http://stackoverflow.com/q/43424758/28004) and the [provided Github test repo](https://github.com/balexandre/ts-stackoverflow-question).

Thanks @balexandre for the detailed explanation of the issue and getting back to us with the solution and the links.
