### ISSUE TITLE
Not working on Mobile devices

### ISSUE THREAD

**Issue by vikcheema** [js-cookie/js-cookie#331]
I am using this to set the cookie on slide in popup close. Works well on desktop browsers but not working on mobile devices. 
Any suggestions?

**Comment by FagnerMartinsBrack** [comment]
There are many things that could be happening. We can't help if there's no [SSCCE](http://sscce.org/) to follow. Please, read this link and see if it helps: http://sscce.org/

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
