### ISSUE TITLE
Expire Duration

### ISSUE THREAD

**Issue by navin11** [js-cookie/js-cookie#334]
How to set expire duration in mins, like if suppose I want to have the cookie only for 15 mins. then what  I should do??? thanks.

**Comment by jeremyhodges** [comment]
Details are on the Wiki: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions

**Comment by FagnerMartinsBrack** [comment]
Closing as from the comment above.

**Comment by navin11** [comment]
@jeremyhodges thank you!!!

**Comment by SeanDKendle** [comment]
500 Error on the wiki, I need to know how to do this ASAP, please.

**Comment by carhartl** [comment]
https://www.githubstatus.com/
