### ISSUE TITLE
Handle or warn when cookie limit is excited

### ISSUE THREAD

**Issue by uaoleg** [js-cookie/js-cookie#339]
Currently if I try to save value that is more than 4096 bytes it just not saved. No handling or even warning.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-are-my-cookies-being-deleted

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
