### ISSUE TITLE
Cookie not being set when is marked as 'secure'

### ISSUE THREAD

**Issue by jazoom** [js-cookie/js-cookie#340]
This sets a cookie:
```
Cookies.set('text', text, { expires: new Date("2017-11-29T19:48:23.819Z") });
```

This does not set a cookie:
```
Cookies.set('text', text, { secure: true, expires: new Date("2017-11-29T19:48:23.819Z") });
```

I've just read through the documentation several times and I can't see a reason why this would be the case.

**Comment by FagnerMartinsBrack** [comment]
Are you running the server on `https://`? You can't set a secure cookie through `http://`, or at least it's not gonna be visible when you try to retrieve it using any API.

**Comment by jazoom** [comment]
Sigh. Yes, localhost. I realised that while lying in bed (I knew I should have slept a bit earlier). I came back to close this issue but of course GitHub was down for me so you beat me to it. Sorry to waste your time.

**Comment by jazoom** [comment]
Though, I keep seeing documented that secure cookies aren't sent to insecure destinations, but I've not come across anything saying they won't even be set. That doesn't really make sense to me.
