### ISSUE TITLE
How do I simply check if cookies are enabled?

### ISSUE THREAD

**Issue by stamminator** [js-cookie/js-cookie#341]
Is there a function to simply check if the browser has cookies enabled? I would think such a thing would be listed on the documentation page, but everything I've seen has to do with modifying actual instances of cookies.

**Comment by FagnerMartinsBrack** [comment]
Duplicated of https://github.com/js-cookie/js-cookie/issues/115
See https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-extend-or-add-a-new-plugin-or-functionality-to-the-library
See also https://github.com/js-cookie/js-cookie/issues/115#issuecomment-166490085

**Comment by stamminator** [comment]
Thanks for the update. I'm not sure why I didn't think to use modernizr for this :)
