### ISSUE TITLE
How to set HttpOnly?

### ISSUE THREAD

**Issue by iamdubx** [js-cookie/js-cookie#344]
Hi. Is it possible to set HttpOnly cookie? If I set it just by adding like this, it doesn't work:

```
        Cookies.set('refresh_token', response.data.refresh_token, HttpOnly)
```

**Comment by xiongsyao** [comment]
HttpOnly means that JS can not  operate the cookies...

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/carhartl/jquery-cookie/issues/122#issuecomment-10148763 and https://github.com/js-cookie/js-cookie/pull/84
