### ISSUE TITLE
Cookies.set('this_speed','<i>test</i>') is not url encoding

### ISSUE THREAD

**Issue by bandapatideepak** [js-cookie/js-cookie#346]
when given special characters in value while creating a cookie, it is not performing URL encoding. below is the example.
![image](https://user-images.githubusercontent.com/3783779/28939693-caf586d4-78af-11e7-8703-710bc05cafce.png)

**Comment by FagnerMartinsBrack** [comment]
js-cookie does not do URL Encoding. As per [the encoding docs](https://github.com/js-cookie/js-cookie/tree/8b70250875f7e07445b6a457f9c2474ead4cba44#encoding):

> All special characters that are not allowed in the cookie-name or cookie-value are encoded with each one's UTF-8 Hex equivalent using percent-encoding.
> The only character in cookie-name or cookie-value that is allowed and still encoded is the percent % character, it is escaped in order to interpret percent input as literal.
> Please note that the default encoding/decoding strategy is meant to be interoperable only between cookies that are read/written by js-cookie. To override the default encoding/decoding strategy you need to use a converter.

**Comment by bandapatideepak** [comment]
thanks for your time @FagnerMartinsBrack. what ever the cookie i am creating should by default encode without writing any converter. i went through the logic in library which is calling api method to create or get cookie. in the logic when creating a cookie. it encoding and then immediately decoding the input which i did not understand. can please look into it and clarify if possible
![image](https://user-images.githubusercontent.com/3783779/28957620-3e29fe5e-7910-11e7-9611-f53c17205762.png)

**Comment by FagnerMartinsBrack** [comment]
That line is encoding only the characters that are not allowed in a `cookie-value` as per RFC 6265 if there's no write converter. The `decodeURIComponent` is used to revert back the characters that are allowed.

If you have questions regarding the internals of the library, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we avoid answering too many questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

**Comment by bandapatideepak** [comment]
Gotcha. thank you @FagnerMartinsBrack
