### ISSUE TITLE
Request For Feedback: Document ES6 module usage

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#353]
Are you interested in having ES6 module usage documented [like this](https://github.com/js-cookie/js-cookie/tree/d999bcfc7d49e5ebd44911f18708a33bcd1395ae#es6)?

If yes, react to this issue with a thumbs up:

![thumbsup reaction](https://user-images.githubusercontent.com/835857/29481256-a2e7d90c-84c2-11e7-8eec-9243e9baf08d.png)

**Comment by mcabreranovelo** [comment]
rgdg

**Comment by FagnerMartinsBrack** [comment]
(Locking to keep the upvotes at the time this decision was made)
