### ISSUE TITLE
[Feature request] Cookies.has function

### ISSUE THREAD

**Issue by alfonsobries** [js-cookie/js-cookie#358]
What do you think about add the has Method to the Cookies  object, i think this might be useful is some cases an cleaner than check if the current value is null , example

```
if (Cookies.has('prefered-color')) {
 // Do something
} 
```

**Comment by FagnerMartinsBrack** [comment]
@alfonsobries A discussion like this have been brought up before, see https://github.com/js-cookie/js-cookie/pull/298#issuecomment-277874456

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
