### ISSUE TITLE
Expiration time in hours

### ISSUE THREAD

**Issue by ChainKiller** [js-cookie/js-cookie#36]
How to set expiration time in hours?

**Comment by carhartl** [comment]
You have two options:

A. The expires option accepts an instance of `Date`, so you could create one, say 6 hours in the future.

B. expires also allows fractions of a day, for six hours you'd use: 6/24.

**Comment by carhartl** [comment]
@FagnerMartinsBrack Remind me to create a FAQ :)

**Comment by FagnerMartinsBrack** [comment]
:+1:

It's really useful do document the most common use cases.

**Comment by FagnerMartinsBrack** [comment]
I created an issue to track it: https://github.com/js-cookie/js-cookie/issues/37

**Comment by carhartl** [comment]
Thanks!

**Comment by XanderCam** [comment]
So how would you go about setting the instance of Date at say Midninght ?`
a.k.a 0:00

**Comment by FagnerMartinsBrack** [comment]
@XanderCam Something like `new Date(2016, 4, 3, 0, 0, 0, 0)` see [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date), or use a lib such as [moment.js](http://momentjs.com/).
