### ISSUE TITLE
getJSON does not work on cookie with escaped quotes

### ISSUE THREAD

**Issue by farazs** [js-cookie/js-cookie#363]
Example: The value is `"{\"key1\":\"val1\",\"key2\":\"val2\"}"` including the outermost quotes. Calling `JSON.parse` on this normally would work but these lines remove the quotes at the ends which causes a parse error to occur because the value becomes `{\"key1\":\"val1\",\"key2\":\"val2\"}`.
https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L112-L114

What is the purpose of those lines? Should they be only for the non-JSON get?

You can test this out with `JSON.parse('"{\\"key1\\":\\"val1\\",\\"key2\\":\\"val2\\"}"')` which works. And `JSON.parse('{\\"key1\\":\\"val1\\",\\"key2\\":\\"val2\\"}')` does not. The double backslash is so that the backslash stays in the resulting string otherwise the `\"` gets evaluated to just `"`.

**Comment by FagnerMartinsBrack** [comment]
@farazs Can you please provide a running example ([SSCCE](http://sscce.org/))? You can attach a zip file with an `index.html`file in this thread.

**Comment by FagnerMartinsBrack** [comment]
Oh sorry, just saw your PR, nvm.
