### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by rafaelkapela** [js-cookie/js-cookie#367]
This is a very very good and useful class...

How can I make a donation?

**Comment by rafaelkapela** [comment]
Please PayPal, bitches =)

**Comment by FagnerMartinsBrack** [comment]
Where would the donation go? I don't need it.
In any case, there's a Bitcoin address I use for OSS donations: https://blockchain.info/address/19EJPi72uVNtmyPpMesZa4jpbPR6AVbfX5
Ping @carhartl

**Comment by FagnerMartinsBrack** [comment]
@rafaelkapela I believe the best donation would be improving the docs, answering questions on StackOverflow under the tag `js-cookie` and helping with initiatives such as https://github.com/js-cookie/js-cookie-release (If you want to, I can provide more information in regards the planned strategy for that project, which is not very well documented)

Closing for now, if there's anything else you believe might be worth discussing let us know, thanks.
