### ISSUE TITLE
Create FAQ (Frequently Asked Questions)

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#37]
- Expiration time in hours
- Creating cookie with same name but different attributes
- Being careful about the cookie size limit (use `js.cookie.debug.js` if already built, see #57)

**Comment by FagnerMartinsBrack** [comment]
Previous issues and requests regarding on how to set a cookie to expire in less than a day:

* https://github.com/carhartl/jquery-cookie/issues/280
* https://github.com/carhartl/jquery-cookie/issues/162
* https://github.com/carhartl/jquery-cookie/pull/65
* https://github.com/carhartl/jquery-cookie/issues/246
* https://github.com/carhartl/jquery-cookie/issues/113
* https://github.com/carhartl/jquery-cookie/issues/34
* https://github.com/carhartl/jquery-cookie/pull/327
* https://github.com/carhartl/jquery-cookie/issues/240
* https://github.com/carhartl/jquery-cookie/issues/188

**Comment by FagnerMartinsBrack** [comment]
Previous links I could find with issues related in creating 2 cookies with the same name:

* carhartl/jquery-cookie#21
* carhartl/jquery-cookie#172
* carhartl/jquery-cookie#343
* carhartl/jquery-cookie#249
* carhartl/jquery-cookie#178
* carhartl/jquery-cookie#130
* js-cookie/js-cookie#52

**Comment by carhartl** [comment]
+1 for same name cookies shadowing other one

**Comment by FagnerMartinsBrack** [comment]
Maybe add a note regarding browser limitations?

See https://github.com/js-cookie/js-cookie/issues/76. Not everyone have the time to read through all the spec. Now with JSON support, people might abuse the cookie usage and persist a lot of information instead of small tokens.

**Comment by FagnerMartinsBrack** [comment]
FAQ [is created](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions) :D

I created in the wiki because I believe the best place to put this is there.

For now I have just documented on how to expire in less than a day.

**Comment by FagnerMartinsBrack** [comment]
Issues opened about confusions created due to the cookie size:

- #194

**Comment by renatonascalves** [comment]
Add the FAQ in the main README.md It will allow people to see that first. 

Great work by the way!

**Comment by FagnerMartinsBrack** [comment]
@renatonascalves We have a link to the Wiki, isn't that enough?

**Comment by FagnerMartinsBrack** [comment]
Oh ok, just saw https://github.com/js-cookie/js-cookie/issues/222, one more evidence that we need a FAQ in the front page.

**Comment by renatonascalves** [comment]
Got it! I think this would help. Some people don't check everything in the repo, even the Wiki...

**Comment by FagnerMartinsBrack** [comment]
I created https://github.com/js-cookie/js-cookie/issues/223, let's do something like that and see if the amount of report changes.

**Comment by FagnerMartinsBrack** [comment]
The FAQ for "Expiration time in hours" was moved to https://github.com/js-cookie/js-cookie/issues/224.

**Comment by FagnerMartinsBrack** [comment]
The FAQ for "2 cookies shadowing another one" was moved to https://github.com/js-cookie/js-cookie/issues/226.

**Comment by FagnerMartinsBrack** [comment]
The FAQ for "cookie size" was moved to https://github.com/js-cookie/js-cookie/issues/227.

**Comment by FagnerMartinsBrack** [comment]
I moved all FAQs to their respective issues, this way it is easier to track and register the history of questions that were created in this repository because of that so that we can take actions in fixing it.

New FAQ proposals should have a single focused issue. Closing this in favor of those.
