### ISSUE TITLE
How do we set cookies as httpOnly?

### ISSUE THREAD

**Issue by Saeven** [js-cookie/js-cookie#375]
Thanks!

**Comment by sonnysavage** [comment]
https://github.com/js-cookie/js-cookie/issues/344

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
