### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by tonoslav** [js-cookie/js-cookie#378]
Could not find a declaration file for module 'js-cookie'. '.../node_modules/js-cookie/src/js.cookie.js' implicitly has an 'any' type.
  Try `npm install @types/js-cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-cookie';`

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/50

**Comment by tonoslav** [comment]
Oh ok sorry I did't saw it and also I forgot to restart my VSCode after installing that types :)

**Comment by arn-ob** [comment]
> Oh ok sorry I did't saw it and also I forgot to restart my VSCode after installing that types :)

Its worked.

**Comment by Michael-Liendo** [comment]
Wow, thanks so much

**Comment by Vangelis-191** [comment]
THank you very much it works
