### ISSUE TITLE
Add .min for unpkg.com

### ISSUE THREAD

**Issue by ravilution** [js-cookie/js-cookie#379]
Please add .min.js into src so that it can be accessed as https://unpkg.com/js-cookie@2.2.0/src/js.cookie.js

**Comment by FagnerMartinsBrack** [comment]
Can you use [jsDelivr CDN](https://www.jsdelivr.com/package/npm/js-cookie)?

**Comment by ravilution** [comment]
The good thing with unpkg is that people can access any file in the github using unpkg CDN. Irrelevant of that, can we have a min version of js in the repo? Any issue having a min version of the file in repo?

**Comment by MartinKolarik** [comment]
@ravilution same goes for jsDelivr -  it can serve any file from npm/GitHub, and if you want to download the file for offline usage, you can just download it from there, it's linked in the README.

**Comment by ravilution** [comment]
@MartinKolarik oh! I never knew that. Cool. Thanks. But how is jsDelivr having a min file in src which I do not see in github?

**Comment by MartinKolarik** [comment]
@ravilution it is able to minify files on-demand. You can find all info here: https://www.jsdelivr.com/features#minify

**Comment by ravilution** [comment]
@MartinKolarik thanks.
