### ISSUE TITLE
Setting a cookie with a path doesn't work on safari IE and edge

### ISSUE THREAD

**Issue by lauterry** [js-cookie/js-cookie#390]
Hello

On Safari, IE and Edge, when I try to set a cookie with a path using 

```
Cookies.set('name', 'value', { path: 'fr-FR' });
```

The following code returns undefined

```
Cookies.get('name');
```

This works and Firefox and Chrome

Any Idea why ? 

Best regards

**Comment by FagnerMartinsBrack** [comment]
@lauterry You need to be in the path `/fr-FR` to be able to read it.

**Comment by lauterry** [comment]
Yes thank you for the solution
