### ISSUE TITLE
attributes.expires.toUTCString is not a function

### ISSUE THREAD

**Issue by cjboco** [js-cookie/js-cookie#393]
I was getting an error when I was trying to pass a date string in the expires attribute. (Safari 11.0.2).

The value I passed:
`{path: "/", expires: "Fri, 22 Dec 2017 18:46:44 GMT"}`

The Console Log Error:
`TypeError: attributes.expires.toUTCString is not a function. (In 'attributes.expires.toUTCString()', 'attributes.expires.toUTCString' is undefined)`

My Solution (Line 60), change the following line: 
`attributes.expires = attributes.expires ? attributes.expires.toUTCString() : '';`

...to...

`if (attributes.expires && !isNaN(attributes.expires)) {
	attributes.expires = attributes.expires.toUTCString();
} else if (attributes.expires && isNaN(attributes.expires)) {
	attributes.expires = new Date(attributes.expires);
	attributes.expires = attributes.expires.toUTCString();
} else {
	attributes.expires = '';
}`

Looks like I was already passing a UTCString and needed to convert it back to a date... I'm sure you can come up with a more elegant solution.

[Edit: Wrong line number.]

**Comment by FagnerMartinsBrack** [comment]
The [docs says](https://github.com/js-cookie/js-cookie/tree/a0012f21ba0519fa3c7571cc6f16e15902ec051b#expires) it only accepts a `Number` or a `Date` instance, not a `String`.
