### ISSUE TITLE
Can't access values of object stored in cookie

### ISSUE THREAD

**Issue by Njunge11** [js-cookie/js-cookie#410]
1.I set the cookie by passing an object:

   ` Cookies.set('name', {foo:'bar'})`

2.Then proceed to access the object:

   ` Cookies.getJSON('name'); `

3.When i try to access foo's value, i get an error:

 `   Cookies.getJSON('name').foo // Cannot read property 'foo' of undefined`

Kindly advice on what I’m doing wrong?

**Comment by sid2201** [comment]
`Cookies.set('name', { foo: 'bar' })`
`console.log(Cookies.getJSON('name').foo);`

Tried out the above code and I get this in my console

`bar`

It seems to work. Am I missing anything?

**Comment by Njunge11** [comment]
Hi @sid2201 , I appreciate the quick response. It seems like the issue is how I was implementing the above code in REACT. Once placed in the correct life cycle method, it runs perfectly...
