### ISSUE TITLE
Synchronous 

### ISSUE THREAD

**Issue by GoGross** [js-cookie/js-cookie#411]
Please do mention that js-cookie is Synchronous , i ran into debugging problem because I hadn't check that. Thanks

**Comment by foxaal** [comment]
Can you say what happened and what your use case was?

**Comment by FagnerMartinsBrack** [comment]
That's right @foxaal. @GoGross can you share your example and explain why it was confusing? JavaScript is synchronous by default unless you use callbacks, Promises or `async`/`await`. How could it being synchronous cause confusion? It's just an API that does `get`/`set`/`remove`.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to work in the PR again, feel free to comment here to open up the discussion again

**Comment by hanoii** [comment]
I stumbled upon this. On my case I was adding it on the footer and rightly so it didn't work until I move it to the header. I could use dom.ready equivalent with/without jquery but I think it's ok for it to be on the header. I wonder though if an async option should be present on the library itself with some event trigger when it's loaded or the like. You can then use async and be on with it.

**Comment by FagnerMartinsBrack** [comment]
You can make it async by wrapping into an async function:

```
const AsyncCookies = () => {
  return {
    get: async () => {
      return Cookies.get.apply(null, arguments);
    }
  };
};

const value = await AsyncCookies().get('name');
```

(note: untested code, this is just to show the idea)

**Comment by tylerlong** [comment]
Today I encountered an issue. My app was stuck  for 3 seconds after I click a button. It turns out that it is caused by saving a large cookie. My app won't be stuck if this library is async. 

This is not a complaint. Just to provide some evidence for the importance of mentioning that js-cookie is a sync library.

**Comment by FagnerMartinsBrack** [comment]
@tylerlong The problem in your case is not that js-cookie is sync, the problem is that you are creating large cookies. Cookies were never designed to be large, they shouldn't exceed 4k.

Can you provide an example of a usage of js-cookie where it causes the browser to hang?
