### ISSUE TITLE
How is this typically used -- what is it for?

### ISSUE THREAD

**Issue by foxaal** [js-cookie/js-cookie#412]
This looks like it is used on the client side only, is that correct?  Is it nutty to use js-cookie to manage sessions using, e.g., socket.io (because browser does not seem to send the cookie over the socket, or is it?) Is there a scenario for using this to manage sessions?  For example, client authenticates, server uses socket to send a "hard to guess number" to client.  Client sets cookie using that number.  Later on, client re-connects to server, client retrieves its cookie, client sends cookie to server over socket, server looks up "hard to guess number" in a database, and restores the session info keyed on that number.  Or is this library for something else entirely.

**Comment by ADTC** [comment]
For cookies from server, they are sent by server to client by way of response header (like the PHP session ID cookie). The browser then sends it back with request header on subsequent requests. Javascript is completely unnecessary for that, and it's fully automatically managed by the client.

This library is merely for client-side management of cookies. If you wish to set, remove or get cookies in Javascript purely for client-side purposes, this library will be useful.

**Comment by foxaal** [comment]
Many thanks.  Perhaps of interest, I am finding it useful for session mgmt as well in a socket.io context over TLS.  It seems easier to just send a hard-to-guess key to the client upon authentication (with username and password), generate a non-expiring cookie on client which stores the number (using js-session).   Then, with every browser request, I can retrieve the cookie in socket.io, get the key, and restore the session from a DB.  I know this isn't a comment board, so I appreciate your patience, but I wonder if this isn't another use case.

**Comment by ADTC** [comment]
I don't see why you'd need JavaScript for that. If your server generates a hard to guess key and sends it to client as a cookie, the client will keep sending it back for the server to read and verify (until the cookie expires). JavaScript is not necessary, in fact you can turn JavaScript completely off and cookies will still work.

You must NOT generate the key client-side using JavaScript. That's a security risk. If you're using JavaScript to touch the key in any way, I would think you're approaching session management wrong.

Read about cookies: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

**Comment by ADTC** [comment]
Please do give the "Secure and HttpOnly cookies" section at that link a read. It's specifically mentioned that cookies to identify sessions on server-side (like your hard to guess key) should be set as HttpOnly, making it unavailable to JavaScript.

**Comment by foxaal** [comment]
Aha.  Muchas gracias. To prevent XSS.  Owasp has good info on this as well.  So I will generate cookie on server and send with httponly response header.  That feels better anyway.  Goodbye js-cookie :(    
https://www.owasp.org/index.php/HttpOnly

**Comment by FagnerMartinsBrack** [comment]
Exactly @foxaal. If you want to manage keys securely, read and write cookies from the server using the `Set-Cookie` header.

You can also avoid server-side cookies if you want your application to be stateless, just send the authentication data on every server communication using a hidden field such as `<input type="hidden">` or using JS by reading from your internal view model (in case of modern apps).

**Comment by foxaal** [comment]
@FagnerMartinsBrack Wait, are you saying there is another way to store a "secret" securely on the client than httpOnly cookie that is accessible by client side JS?  Can you point me to a link or something, I'd be quite curious in light of ADTC comments...  This may be getting off topic for js-cookie, but I would like to know...

**Comment by FagnerMartinsBrack** [comment]
> ... are you saying there is another way to store a "secret" securely on the client than httpOnly cookie that is accessible by client side JS?

I never said that. I said you can transfer the secret like this:

```html
<form>
  <input type="hidden" value="MY_SECRET">
</form>
```

Every submission can return the same form with the same secret that is always sent to the server without the need for cookies.

POST response
```html
<form>
  <input type="hidden" value="MY_SECRET">
</form>
```

GET response
```html
<form>
  <input type="hidden" value="MY_SECRET">
</form>
```

etc.

... or use Cookies in JS which means you can't have HttpOnly Cookies.

This is definitely starting to become off topic. Feel free to create a StackOverflow question and link it here so we can continue the discussion there.

**Comment by FagnerMartinsBrack** [comment]
Closing due to this not being an issue, but a question.
