### ISSUE TITLE
Why is the api function responsible for read and write?

### ISSUE THREAD

**Issue by nanndemoiikara** [js-cookie/js-cookie#415]
Why is the api function responsible for read and write?
api function any intention to change responsibility depending on the number of arguments?

**Comment by FagnerMartinsBrack** [comment]
In the eyes of the Public API, it makes no difference, you still have read and write methods. Internally, it uses the same function for the purpose of reducing the byte size and allow the code to be GZipped around the 900 bytes target, [as stated in the README as a feature](https://github.com/js-cookie/js-cookie/tree/e56c99086300e0f3bc81d4e85e355a6f0284be77#javascript-cookie---).

This is a compromise between clean code vs 100% code coverage + downloadable bytes.

**Comment by carhartl** [comment]
It is also due to heritage of once being _jquery-cookie_. In jQuery back then it was a common pattern to have this kind of overload for read + write operations.

**Comment by FagnerMartinsBrack** [comment]
An interesting side-effect of this is https://github.com/js-cookie/js-cookie/issues/417.

**Comment by FagnerMartinsBrack** [comment]
I don't think there's anything we can act on here. Closing then...
