### ISSUE TITLE
getJSON with domain ?

### ISSUE THREAD

**Issue by cyrilchapon** [js-cookie/js-cookie#416]
Hey, what's the API for getJSON with domain ?

I tried

```
cookies.getJSON(k, {domain: 'a'})
```

```
cookies.get(k, {domain: 'a', json: true})
```

Neither worked

**Comment by carhartl** [comment]
It’s not possible to read cookies using those cookie attributes. That’s a limitation of the underlying api, not imposed by us.

**Comment by cyrilchapon** [comment]
You mean, `get()` doesn't accept a second argument, even for "reading in domain" ?

I'm writing on '.mydomain.com' from 'a.mydomain.com', and I'm using 

```
cookies.get(k, {domain: '.mydomain.com'})
```

which seems to work properly

**Comment by cyrilchapon** [comment]
Is `.get` just ignoring any options, and my `.get` working *only* because I set cookie subdomain-free with .mydomain.com ?

**Comment by carhartl** [comment]
>Is .get just ignoring any options, and my .get working only because I set cookie subdomain-free with .mydomain.com ?

Exactly.

**Comment by carhartl** [comment]
E.g. a cookie with that key is visible from the current subdomain, and therefore `get()` retrieves it.

**Comment by cyrilchapon** [comment]
Ok.

So, to getJSON works exactly the same, right ?

**Comment by carhartl** [comment]
It should. But taking a second look I noticed that for `getJSON()`, in contrast to `get()`, we‘re passing on all given arguments. So what‘s actually happening when you called it with two arguments is each time a cookie is written (due to the api’s underlying implementation). You won’t notice the difference if the values remain the same, but that seems to be a bug. cc @FagnerMartinsBrack

**Comment by carhartl** [comment]
We have:
```javascript
api.getJSON = function () {
    return api.apply({
        json: true
	}, arguments);
};
```
and I believe we should have:
```javascript
function (key) {
    return api.call({ json: true}, key);
};
```

**Comment by carhartl** [comment]
I believe it’s worse..

```javascript
cookies.getJSON(k, {domain: 'a'})
```

would result in a cookie `k` written with a value of json stringified `{domain: 'a'}`. Cannot test this right now.

**Comment by cyrilchapon** [comment]
Yeap. I noticed that, i was wondering why :')

Closing this, opening a bug

**Comment by carhartl** [comment]
It‘s not a bug per se imo. But we can and should make using the api in a wrong way side-effect free.

**Comment by carhartl** [comment]
I‘d rather throw an exception if one of the cookie getters were called with more than one argument. I no longer find it developer friendly to just silently swallow everything. But that’s something for v3 maybe.

**Comment by cyrilchapon** [comment]
Well, the API is not strongly documented about params.

Nothing disallow me to think that `get` can take a second argument, especially with the words 

```
Cookies.set('name', 'value', { domain: 'subdomain.site.com' });
Cookies.get('name'); // => undefined (need to read at 'subdomain.site.com')
```

and thus, thinking that `getJSON` would behave the same way seems pretty logical.

Not everyone knows underlying cookie API limitations (which is, btw, accurately why one would search and trust a library like this one), and the lib API is, again, not strongly documented, leaving the "expected behavior" not that objective.

In common sense, a method "expected behavior", in javascript, when called with too many arguments can lead to 2 things :

- Throw
- Ignore rest parameters

The actual behavior is : a getter acts as a setter. This seems pretty much like a bug.

**Comment by cyrilchapon** [comment]
> I‘d rather throw an exception if one of the cookie getters were called with more than one argument. I no longer find it developer friendly to just silently swallow everything. But that’s something for v3 maybe.

If you want my personal opinion, I think the right way is :

- Document strongly each method
- Make methods accept `.length` by passing real arguments (it allows currying, for example)
- Make them just ignore additional parameters

"developer friendly" dimension should be covered by documentation, not with throws, IMHO

**Comment by carhartl** [comment]
I don't disagree much anyway, yet..

> The actual behavior is : a getter acts as a setter. This seems pretty much like a bug.

In terms of _documented api_, there is no such setter in the first place. That's all I'm saying.. you were using the api in a way that isn't documented (thus could be considered no expected behavior attached), based on your own assumptions. That's why I'm saying it is not a bug _per se_. I'm happy to make the library more error-proof of course.

**Comment by carhartl** [comment]
Furthermore, if you find the documenation somewhat vague or misleading, I encourage you to send a PR ❤️
