### ISSUE TITLE
Cookies defaults : json and secure option.

### ISSUE THREAD

**Issue by divad91** [js-cookie/js-cookie#42]
Hi, 
Is there a reason why I can't set the the json and secure property in the same way ?
Version 1.5.1
                Cookies.json = true; // Don't know why we can't set it in Cookies.defaults.
		// Cookies.secure = true;  // Doesn't work.
		$.extend(Cookies.defaults, { 
			// For all cookies, override secure property.			
			secure: true	//	// Don't know why we can't set it vis Cookies.secure=true.
			// json : true // Doesn't work.
		});
Also, In beta version (2.0.0), the secure flag is not working. The cookie itself wont be created when adding option secure to it.

Thanks
David

**Comment by FagnerMartinsBrack** [comment]
Hi, very good question.

Although in the docs the behavior is well documented (https://github.com/js-cookie/js-cookie/tree/v1.5.1#configuration), let me try to address the "why"...

> Is there a reason why I can't set the the json and secure property in the same way ?

There is a difference between attributes (AKA options in < 1.5.1) and configurations (AKA configs).

In 1.5.1 you can interpret `defaults` as `defaultOptions`. In 2.0.0+ you can interpret `defaults` as `defaultAttributes`. We use some sort of [Duck typing](http://pt.wikipedia.org/wiki/Duck_typing) to separate the responsibilities of each flag while removing a few unnecessary bytes.

Attributes/options refers to the cookie attributes, like `secure`, `path` and `domain`. They are set in the `defaults` property, which represents the default **attributes** of a cookie.

Configurations are globals and totally unrelated to the browser cookie attributes, like `json` and `raw`. Those are not **attributes**, they are custom configs, hence they are not set in the `defaults` API.

We are aware of the confusion that configs can cause (specifically the `json` config), for that reason it will be removed in 2.0.0. After that, the only thing that remains is `defaults` to be interpreted as `defaultAttributes`. There will be no more confusion ;)

**Comment by divad91** [comment]
Thank you for the precision !
I didn't notice the difference between configuration and options. Now it's working great with version 1.5.1.

Concerning the secure flag, should I dynamically change the value of this option to "true" or "false" base on the current protocol (http or https) or the lib will manage it. Ex: When im testing locally (localhost), if the secure flag is true, will it impact something ?
It seems to work perfectly fine but just in case.
Thanks 
David

**Comment by FagnerMartinsBrack** [comment]
> Concerning the secure flag, should I dynamically change the value of this option to "true" or "false" base on the current protocol (http or https) or the lib will manage it

You are responsible to define how you want the cookies to behave, so you need to be responsible to set the "secure" attribute and any other attribute for the cookie you want. js-cookie will not manipulate the attributes, they will be directly passed to the browser default cookie mechanism.

The only exception in js-cookie v2.0.0 is the handling of the "path" default attribute, that is default to the whole site ("/") instead of default to the path of the current page (""). As a rule of thumb, any attribute you pass will be considered over anything else in the following order:

1. Specifying a default attributes will override js-cookie defaults
2. Specifying an attribute for a cookie will override the specified defaults

**Comment by divad91** [comment]
Perfect ! Thanks a lot

**Comment by FagnerMartinsBrack** [comment]
More info regarding of how the default path attribute works: https://github.com/js-cookie/js-cookie/pull/32
