### ISSUE TITLE
LICENSE - Fagner Brack not listed in LICENSE file but is in js-cookie.js under "src"

### ISSUE THREAD

**Issue by PrestonL** [js-cookie/js-cookie#424]
Fagner Brack not listed in LICENSE file but is in js-cookie.js under "src", copyright dates don't match.

**Comment by FagnerMartinsBrack** [comment]
I'm not a lawyer so I don't know why that matters. @PrestonL, do you want to create a PR updating those files?

**Comment by PrestonL** [comment]
Done with PR 425.  I'll do a little digging into CLA / CAA so that persons doing PRs will have transferred Copyright for MIT if you're interested in shoring that up; right now there may be some issues with that if there are other contributions pushed into the project.

**Comment by FagnerMartinsBrack** [comment]
> right now there may be some issues with that if there are other contributions pushed into the project.
Which issues could that be?

**Comment by PrestonL** [comment]
I am not a lawyer, but the way I understand it is that if someone contributes code to a project, they still retain copyright rights to the derivative work; changes to MIT code aren't necessarily licensed under the MIT License. A contributor license agreement generally assigns copyright to the project maintainer or an open source foundation so that said maintainer can then release the derivative work under the MIT License.  Right now in open source there is a mess of CLAs and CAAs out there.  I'm going to write one for myself and my own F/OSS projects, and can post it if you'd like to implement it yourself; I looked at the FSF and other places, and a good CLA/CAA guide doesn't really seem to exist.

**Comment by FagnerMartinsBrack** [comment]
Do those rules change per country? I guess Github is in US so we're bound to their laws?

> I'm going to write one for myself and my own F/OSS projects, and can post it if you'd like to implement it yourself

If you want to create good guidelines or tools for this we would definitely implement here.

Honestly, I'm not too worried about this. Anybody contributing to Open Source should be aware their work is going to be of the same license as the project. If anybody tries to sue or anything, it's just a matter of reverting the commit. Twbs had a similar problem in the past and they looked at the commits for people who didn't want to change the license and just reverted it.

Unless I'm missing something.

**Comment by PrestonL** [comment]
It gets complicated, copyright is generally similar between counties because of treaties, and because of what you said about the intent of people contributing code, it's mostly a non-issue.

There could in theory be liability and damages where reverting a commit wouldn't absolve one of liability.  Say for instance, if someone is doing work for their employer, their work is owned by the employer.  They push a commit on GitHub, and it's rolled into the code.  Employer is a facist, and decides to go after an open source project manager for damages as the person submitting the code never had a right to convey it.  A CLA can work to protect all parties, and can be made simple a-la MIT License Style.

After some research, it seems that this is probably the best place and easiest way to generate a CLA, they don't go far into the benefits and reasoning for having one, but it's a good start:  You could just generate one of those and add it under CONTRIBUTING.md and have everyone send you one.

http://selector.harmonyagreements.org

**Comment by FagnerMartinsBrack** [comment]
Looks like it increases the barrier for contributions. Something automated would be the way to go, one that the contributor would just read and tick "I agree" or something like that.

**Comment by PrestonL** [comment]
Yeah, there is the CLA Assistant that helps with that part of it:

https://cla-assistant.io

**Comment by FagnerMartinsBrack** [comment]
Hmm, https://cla-assistant.io seems really easy to set up.

Ping @carhartl

**Comment by FagnerMartinsBrack** [comment]
I've asked other maintainers about this and got the following resources to look at:

https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/

https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license

https://docs.google.com/document/d/1JyxzyH79xgkZINVwbo0BQygLCzxsTRLIC9MTZh0ghqg/edit

https://opensource.guide/legal/#does-my-project-need-an-additional-contributor-agreement

**Comment by FagnerMartinsBrack** [comment]
I didn't know about the "inbound=outbound" concept

**Comment by PrestonL** [comment]
I just saw that and wasn't aware of the inbound=outbound concept either.  I suppose under the MIT License in that case, the contributor still owns copyright to it, but also gives license under that license (in this case MIT).  I know that OpenStreetMap says "(c) OpenStreetMap Contributors" as each contributor holds copyright to the contributions, but the work is licensed back to the project.  So the question is, would "Copyright (c) Klaus Hartl, GitHub Contributors" suffice in the case of a GitHub hosted MIT-Licensed repository? 🤔  My best guess, is yes.

> 
> https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license
> 
> 6. Contributions Under Repository License
> 
> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supersede.
> 
> Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.
