### ISSUE TITLE
Uncaught SyntaxError: The requested module ( path to js.cookie.js ) does not provide an export named 'default'

### ISSUE THREAD

**Issue by gogoIsComing** [js-cookie/js-cookie#426]
hey geys : 
when i am trying to import the js.cookie.js file in order to use set( ) & get( ) functions , i get this error message said : 
![1](https://user-images.githubusercontent.com/33967218/38382792-8b38ca68-3913-11e8-95d7-cc381764fd36.png)

my HTML code : 

![2](https://user-images.githubusercontent.com/33967218/38382919-d1430fdc-3913-11e8-970d-fe6b892053cf.png)

my JS code : 

![3](https://user-images.githubusercontent.com/33967218/38382925-d44f37d2-3913-11e8-82e2-fdce5e15b2e8.png)

Any Help :)

**Comment by FagnerMartinsBrack** [comment]
Probably related to https://github.com/js-cookie/js-cookie/issues/423 and https://github.com/js-cookie/js-cookie/issues/407

**Comment by gogoIsComing** [comment]
@FagnerMartinsBrack  thank you
`import * as Cookies from './js-cookie-master/src/js.cookie.js';`
works for me

**Comment by SaluiMP** [comment]
SyntaxError: The requested module './pokemon.js' does not provide an export named 'example'
    at /
