### ISSUE TITLE
can not import my npm 'js-cookie' module

### ISSUE THREAD

**Issue by gogoIsComing** [js-cookie/js-cookie#428]
hey guys : 
when i import my js-cookie module i get this message error : 

![4](https://user-images.githubusercontent.com/33967218/38427304-8af96586-39c1-11e8-9077-b1eb71b16866.png)

JS code : 
![5](https://user-images.githubusercontent.com/33967218/38427356-b0e41d5e-39c1-11e8-8504-a1d320bc5149.png)

Any Help :)

**Comment by Harystolho** [comment]
Try 'js-cookie.js'

**Comment by FagnerMartinsBrack** [comment]
Closing in favor of https://github.com/js-cookie/js-cookie/issues/423.

**Comment by yvzkr** [comment]
> Try 'js-cookie.js'

bad answer

**Comment by VigneshQikink** [comment]
same problem facing here. how to solve pls say?

**Comment by ahmadalzoubi13579** [comment]
@VigneshQikink i was beginner and I was using imports in pure html/css/js code, you need webpack for this I guess.

**Comment by Banaishik** [comment]
you need to download the parcel builder, it worked for me. 
npm install -g parcel-bundler
to start the project, you just need to type in : 
parcel index.html
If nothing runs then just add npx.
npx parcel index.html

**Comment by VigneshQikink** [comment]
ok thanks.
