### ISSUE TITLE
API to write the encoded Cookie value to a returned string?

### ISSUE THREAD

**Issue by ibc** [js-cookie/js-cookie#435]
Basically I'd like to generate the same Cookie value that `js-cookie` generates (when calling `set()` with a JS object) and have the generated value in a string.

AFAIS there is no API for that. Is there a way to generate the same value?

**Comment by FagnerMartinsBrack** [comment]
You can read [RFC 6265](https://tools.ietf.org/html/rfc6265) and code against those rules. Why do you need an API to expose the internal standard algorithm? What's the exact use case?

**Comment by ibc** [comment]
Use case:

Communication between `react-native` main thread and a 100% web app running within a `WebView` in the `react-native` app.

The web app uses `js-cookie`. And, in certain circumstances, the `react-native` code must manually create a Cookie with the `js-cookie` syntax, so later, when the `WebView` is open, the web app finds such a Cookie. And of course, the `react-native` code cannot use `js-cookie` since there is no `document`.

**Comment by carhartl** [comment]
There is no such thing as a "js-cookie" syntax though, in the end this is just RFC 6265. The web app could retrieve any cookie by name. 

I haven’t understood yet where would the cookie be created by the react-native app, e.g. where would such a cookie live? Or do you mean to store a string later to be consumed by the web app? If so, could you instead store a bit of JavaScript code, namely the writing of the cookie, that would be injected into the web view?

**Comment by ibc** [comment]
Let's assume that the web app cannot be "too much" modified. It's in fact a real web app that works in browsers. But it's also rendered into a `WebView` within the react-native app.

So, the scenario is:

* The react-native app is opened for first time, the user does login stuff (somehow) and the app generates a cookie that stores in the react-native local storage (which is not `window.document.cookie`).
* Later the react-native app opens the `WebView` (with a flag to share its cookies) and loads an external URL (the web app).
* The web app runs and reads the Cookie (with `js-cookie`) from `window.document.cookie` as usual.

**Comment by carhartl** [comment]
You could also use something like `serialize()` from https://www.npmjs.com/package/cookie — should be interoperable with js-cookie.

**Comment by carhartl** [comment]
Regarding hacking some stand-in document object, wouldn‘t the following be sufficient:

```javascript
(function() {
    var document = {};
    Cookies.set("foo", "bar");
    console.log(document.cookie); // => "foo=bar“
})();
```

**Comment by FagnerMartinsBrack** [comment]
☝️ That's a good point, maybe that will.

However, I would advise from doing this. I'm pretty sure we don't expect to change the global `document` access internally, but we may change to something like `window.document` without further notice at some point in the future, and that will break the code.

The safest way is to avoid hacks and use the tools for the purpose they've been intended to, be aware that [library internals do not exist](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0) so you shouldn't be relying on this internal behavior. If we try to support every single hacky use case we would have to add so much clutter to the API that it would become a mess to everyone else who don't care about those hacky use cases.

**Comment by carhartl** [comment]
I was just trying to be a little pragmatic.

**Comment by FagnerMartinsBrack** [comment]
> I just ask whether such an API could be provided by js-cookie itself.

I guess the feeling is that we're not willing to expose that as an API, given that there are not enough legit use cases to justify that.

**Comment by ibc** [comment]
Fair. Thanks a lot.
