### ISSUE TITLE
Set default settings?

### ISSUE THREAD

**Issue by Daijobou** [js-cookie/js-cookie#440]
Its possible to set a domain string as default setting? 

Actual for each set/get

```
Cookies.set('name', 'value', { expires: 1, domain: '.example.com' }));
```

Maybe better and shorter
```
// Set default values
Cookies.settings({ expires: 1, domain:  '.example.com' });
Cookies.set('name', 'value')); // => expires is 1 day; domain is '.example.com'
Cookies.set('name', 'value', { expires: 3 })); // => domain is '.example.com'
```

In most cases I think the domain is always same.

**Comment by Daijobou** [comment]
Oh, thanks! It would help much to include a simple code example. :)

**Comment by mherodev** [comment]
Agreed, this could use an example.

**Comment by Fabio-Zeus-Soft** [comment]
My code is:
`Cookies.defaults({
          secure: true,
          sameSite: 'lax'
  });`
but it gives:
`TypeError: Cookies.defaults is not a function`

How can I solve?

**Comment by carhartl** [comment]
@Fabio-Zeus-Soft 

With v2: `Cookies.defaults = { ... }`

**Comment by ryanjbonnell** [comment]
Configure Default Cookie Attributes

```js
Cookies.defaults = {
  path: "/",
  domain: ".example.com",
  secure: false,
  expires: 365,
};
```

Create a New Cookie with Default Values
```js
Cookies.set('name', 'value');
```

Set Cookie and Override Default(s)
```js
Cookies.set('name', 'value', { expires: 7, path: '' });
```
