### ISSUE TITLE
Documentation text is wrong for domain settting

### ISSUE THREAD

**Issue by Daijobou** [js-cookie/js-cookie#441]
https://github.com/js-cookie/js-cookie#domain

> A String indicating a valid domain where the cookie should be visible. The cookie will **also be visible to all subdomains**.
> 
> Default: Cookie is visible only to the domain or subdomain of the page where the cookie was created, except for Internet Explorer (see below).

I understand the explain text and default text as two things.
I tested it with Cookies.set('ABC', '123', { expires: 1 });
I'm on www.example.com and the domain in cookie is not ".example.com" its "www.example.com", so the default text is right and the bold text is wrong. Cookie is not accessable from a subdomain. Or I missunderstand the text. :)

**Comment by FagnerMartinsBrack** [comment]
Everything is bound to the part that says "except for Internet Explorer (see below)". Do you want to improve the docs and create a PR? You can add the "except for Internet Explorer (see below)" in the text above, not just the "default" one :)

**Comment by FagnerMartinsBrack** [comment]
> Do you want to improve the docs and create a PR?
Ping @Daijobou ☝️

**Comment by Daijobou** [comment]
Sorry, my english is terrible. Its not my native language ;-)

**Comment by FagnerMartinsBrack** [comment]
@Daijobou That's fine. I'll close this then since it's hard to understand what's exactly the problem 😃.

**Comment by carhartl** [comment]
I think what was meant here to improve, being more explicit:

...also be visible to all subdomains _of this (given) domain_

**Comment by Daijobou** [comment]
@carhartl Maybe that my bad english, but I think that not what I mean in start post. The Text is

> **domain**
> A String indicating a valid domain where the cookie should be visible. **The cookie will also be visible to all subdomains.**
> 
> Default: Cookie is visible only to the domain or subdomain of the page where the cookie was created, except for Internet Explorer (see below).

Like FagnerMartinsBrack said, the bold part refers to Internet Explorer alone as exceptio (I never hear before that ^^). The default setting is only a domain OR a single subdomain NOT domain and his all subdomains of this given domain. Default is not `.domain.tld` (see dot before domain name) its only current domain without subdomains.

So when you want domain and subdomains for your cookies, you must set it like 

`Cookies.defaults = { domain: '.yourdomain.tld' };`

**Comment by carhartl** [comment]
But the bold part is not (or is not supposed to be) related to Internet Explorer at all. The mention of a particular Internet Explorer quirk is referring to when relying on the default value of the `domain` value, and therefore this part is written in _a separate paragraph_. The separate paragraph is supposed to help conveying that distinction, and should not be read as one sentence.
