### ISSUE TITLE
SyntaxError: return not in function

### ISSUE THREAD

**Issue by mkoula** [js-cookie/js-cookie#442]
I installed the js-cookies trough yarn and after some fight I loaded it in my webpack js file:
`import * as Cookies from "js-cookie";`

but I am getting and error on load: `SyntaxError: return not in function` pointing me to js.cookies.js file to the line 146:

```
		api.getJSON = function () {
			return api.apply({
				json: true
```

Any idea?

**Comment by FagnerMartinsBrack** [comment]
Sorry I don't use webpack, we need a [SSCCE](http://sscce.org/) to continue any further.

**Comment by FagnerMartinsBrack** [comment]
Probably related to #443.

Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
