### ISSUE TITLE
Saucelabs failing on Travis CI

### ISSUE THREAD

**Issue by DanielRuf** [js-cookie/js-cookie#448]
https://travis-ci.org/js-cookie/js-cookie/builds/388143611

**Comment by FagnerMartinsBrack** [comment]
Probably a problem with Sauce Labs again. I tried to run [a previously passing build](https://travis-ci.org/js-cookie/js-cookie/builds/385142810) and it also failed =/

Let's wait and try again later, I guess...

**Comment by FagnerMartinsBrack** [comment]
Closing in favor of https://github.com/js-cookie/js-cookie/issues/478
