### ISSUE TITLE
'expires: 0' deletes cookie

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#45]
@sp00n
Moved from https://github.com/carhartl/jquery-cookie/issues/364

**Comment by carhartl** [comment]
The moment it's written, imo expected behavior. There is a difference between passing an explicit expires or none.

**Comment by FagnerMartinsBrack** [comment]
I totally agree.

The docs says:
> ... Value can be a Number which will be interpreted as days from time of creation ...

* If you want the cookie to expire in `0` days, then you want it to expire immediately, because 0 days will end now.
* If you want it to expire in half a day, then you set expires as `0.5`.
* If you want to create a session cookie, just omit expires, because a session cookie is the default behavior.

@sp00n
In the given context you provided, there's no evidence that changing the behavior will have any benefit. Maybe it would help if you provide a code sample explaining the use case?

**Comment by Tardis1234** [comment]
@FagnerMartinsBrack As the docs no longer state the bullets you mentioned in 2015, it would be great if they were updated with this info.

**Comment by FagnerMartinsBrack** [comment]
@Tardis1234 The wiki has something: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-make-the-cookie-expire-in-less-than-a-day
