### ISSUE TITLE
Issue with iOS 11

### ISSUE THREAD

**Issue by Fax3D** [js-cookie/js-cookie#453]
It seems there's an issue with the last iOS 11.x: cookies are not stored, and closing and reopening the browser (Safari and Chrome checked) result in loosing all cookies.

My web app works fine on Android and Windows.

EDIT: It seems to be ok even on iOS 11 but only when setting an expiration in Cookie.set method.

**Comment by FagnerMartinsBrack** [comment]
See the [expires section](https://github.com/js-cookie/js-cookie/tree/cab66782392b7fa17cf65a1153c167a00025e038#expires) in the README:

> Default: Cookie is removed when the user closes the browser.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
