### ISSUE TITLE
Not working in even a simple page.

### ISSUE THREAD

**Issue by sudhir600** [js-cookie/js-cookie#458]
Here is my code in html .
```
<head>
    <title>Youtube Time Tracker</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,400,700" rel="stylesheet">
	<link rel="stylesheet" href="css/popup.css">
	<script src="js/jquery.js"></script>
	<script src="js/cookie.min.js"></script>
	<script src="js/code.js"></script>
</head>

```
and in code.js where i want to save cookies -
```
$(window).load(function(){
     $.cookie('name', 'value', { expires: 7 });
    var a = $.cookie('name');
    alert(a);
})
```
I eve n  tried with `document.ready`

Here what i get in error -
![image](https://user-images.githubusercontent.com/4952560/42416594-1bb7e094-8291-11e8-9ff2-d6c7a7d84f28.png)

**Comment by BitpopCoin** [comment]
Who told you it was a jquery plugin? The examples are clear and simple. No where mentioned $.cookie

Use Cookies.set('name', 'value');

**Comment by FagnerMartinsBrack** [comment]
As @BitpopCoin said, this is not a jquery plugin anymore for years. See https://github.com/carhartl/jquery-cookie/issues/349#issuecomment-116822133.

**Comment by Erutan409** [comment]
You should probably remove it from the [keywords](https://github.com/js-cookie/js-cookie/blob/69f802be223209e0ea283b23cba05b1cd0fbc551/package.json#L10), then, yeah?

**Comment by BitpopCoin** [comment]
No it helps find the updated version

**Comment by FagnerMartinsBrack** [comment]
@Erutan409 I see. So were you looking for the tag jQuery-plugin  in npm and that's why you got confused? What else did you get confused to believe it still had jQuery as a dependency. Would just remove the tag fix the problem?

Thanks

**Comment by Erutan409** [comment]
I was only confused for like 90 seconds when I was looking for a solution to my [cookie] problem.  Took me that long to realize it wasn't a jQuery plugin, anymore.

My point is that your repo still has remnants of when it used to be a jQuery plugin.  So:

> Who told you it was a jquery plugin? The examples are clear and simple. No where mentioned $.cookie
> 
> Use Cookies.set('name', 'value'); it works beautifully.
> 
> This project is not this one! https://github.com/carhartl/jquery-cookie

In a *way* you're alluding to it being a jQuery plugin, if not for it just serving as meta data for historical purposes.  Referring to @BitpopCoin 's remark.

I'm not going to engage in a debate about it.  If you don't want to remove it, that's fine.  Doesn't affect me at all and I'm still going to continue to use it.  I just wanted to make sure you were aware of the aforementioned in case anyone else seems to stumble on this assumption in the future.

**Comment by sudhir600** [comment]
@BitpopCoin  @FagnerMartinsBrack 
Yes, I was assuming that it is jquery cookie plugin.  it make confusion for developers.  till writing this comment, there is still "jquery-plugin" mentions in keywords. hope you will remove so it will be excluded from google search. that day i found your package using google search by "jquery cookie plugin npm".

Thanks for understanding.

**Comment by BitpopCoin** [comment]
Ok I apologize
