### ISSUE TITLE
Unable to set attributes other than "expires" and "path"

### ISSUE THREAD

**Issue by kooolbreez1** [js-cookie/js-cookie#460]
I am using a cookie to save user input for use in repopulating the input form after a failed form submit. I have found that I can change the "expires" and the "path" attributes when creating the cookie but when I try to go the same thing for "secure" and "httpOnly" it is unable to generate the cookie. Here is my code for creating the cookie: 
```Javascript
  const attributes = { expires: 1 };
  // const attributes = { secure: true };
  const values = JSON.stringify({
    email: formChange.key === 'email' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).email : '',
    firstName: formChange.key === 'firstName' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).firstName : '',
    lastName: formChange.key === 'lastName' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).lastName : '',
    address1: formChange.key === 'address1' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).address1 : '',
    address2: formChange.key === 'address2' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).address2 : '',
    city: formChange.key === 'city' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).city : '',
    state: formChange.key === 'state' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).state : '',
    zip: formChange.key === 'zip' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).zip : '',
    phone: formChange.key === 'phone' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).phone : '',
    wigs: formChange.key === 'wigs' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).wigs : false,
    hair: formChange.key === 'hair' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).hair : false,
    cosmetics: formChange.key === 'cosmetics' ? formChange.value : Cookies.get('coupon') ? JSON.parse(Cookies.get('coupon')).cosmetics : false
  });
  Cookies.set('coupon', values, attributes);
```
When I comment out the first `attributes` and replace it with the one directly below it fails to create the cookie. Hope this is enough info for you guys, I'm new to using cookies so if I am missing something helpful feel free to let me know. I know I should be able to set the default attributes by setting Cookies.default but I havent been able to get that working either (the docs didnt really make it clear how to set that object). I am using firefox to test this.

**Comment by kooolbreez1** [comment]
That makes a ton of sense, so basically I need to pass it to my API and deal with it there. Thanks for the help!

**Comment by FagnerMartinsBrack** [comment]
@kooolbreez1 
Be advised it's also not recommended to send that amount of data in a cookie given it has a limit of 4096 bytes. Prefer to store a key instead or pass the information inside the body of the request and use POST, PUT, etc.
