### ISSUE TITLE
Minifed file for webjars

### ISSUE THREAD

**Issue by cdalexndr** [js-cookie/js-cookie#468]
All deployed flavors on [webjars](https://www.webjars.org/) (classic, npm, bower) don't have a minified file.

**Comment by FagnerMartinsBrack** [comment]
See also https://github.com/js-cookie/js-cookie/issues/120 and https://github.com/js-cookie/js-cookie/issues/73. In particular this comment: https://github.com/js-cookie/js-cookie/issues/73#issuecomment-131093762.

I don't have time to implement a proper release process that doesn't add more technical debt to the project and don't require me to manually commit the minified file.

Feel free to download from https://github.com/js-cookie/js-cookie/releases the minified version.

If Github doesn't expose another API to download the minified file, you can run a script that uses Chrome Headless and fetches the releases page like:

```javascript
const urlsToDownload = querySelector('.release-main-section a').filter(minifiedFileHref).href;
downloadAll(urlsToDownload)
```

See [this](https://medium.com/@fagnerbrack/html-is-an-api-8508362107a3) for more context.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
