### ISSUE TITLE
Reading cookies from a request header

### ISSUE THREAD

**Issue by megapctr** [js-cookie/js-cookie#469]
I noticed the logic for parsing cookies is coupled with `document.cookie` object. I'd like to read a cookie from request cookie header.

One way to do this would be to add a `Cookies.getFrom(value, json, source)` method, and have the current `Cookie.get` method call `getFrom(value, json, document.cookie)` internally after checking if `document` exists.

**Comment by megapctr** [comment]
We could just add a third parameter to `Cookies.get`, but I feel passing an options object would be a better way to go. However, that would require a major release, since it would be a breaking change.

**Comment by megapctr** [comment]
We could add a third Converter method (e.g. `getSource`) for obtaining the raw cookie string. The default would return `document.cookie`, my custom converter would return the request header.

We could add another method for persisting the cookie string (instead of assigning to `document.cookie`) should anyone need that.

**Comment by carhartl** [comment]
Thanks for the suggestion , but I believe what you’re looking for might be something like https://www.npmjs.com/package/cookie .. this library was created with the intention to provide an easier way to work with cookies _in the browser_.

**Comment by megapctr** [comment]
Fair enough, thanks for the tip. I just wrote a basic cookie parser by hand, which is enough for my use case
