### ISSUE TITLE
Cookies.set silently fails if max content size is exceeded

### ISSUE THREAD

**Issue by TomSmartBishop** [js-cookie/js-cookie#470]
In Firefox I saw that the following call silently fails:
Cookies.set("test", aStringWithMoreThan4094bytes, { expires: 365 });

Or maybe I just don't know how to check for that?

Would there be a way to create a second cookie and store more?

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-are-my-cookies-being-deleted. Why are you storing 4092 bytes in a cookie? Be aware they are sent in the headers of every request without GZip optimization.

**Comment by TomSmartBishop** [comment]
I was just prototyping, now using localStorage instead. But that was not the point, I think it just shouldn't fail silently. Cheers, Thomas

**Comment by FagnerMartinsBrack** [comment]
@TomSmartBishop In the spirit of feedback, what do you suggest to do in this specific case? Would having a `js-cookie.debug.js` file with warning and logs help to make things clear?

See also https://github.com/js-cookie/js-cookie/issues/88#issuecomment-140106983 and https://github.com/js-cookie/js-cookie/issues/86#issuecomment-140058592.

**Comment by TomSmartBishop** [comment]
Maybe yes

**Comment by mauriciabad** [comment]
I'm having the same problem as @TomSmartBishop.
I think that the `README.md` file should say that there's a max cookie size in the encoding section.

**Comment by FagnerMartinsBrack** [comment]
Alright, so it seems the wiki page is not enough https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-are-my-cookies-being-deleted. Can one if you create a PR to improve the README? Perhaps link to the Wiki?

Thanks.

**Comment by TomSmartBishop** [comment]
Just as a comment: I had a single value suddenly exceeding the size, so nothing was 'deleted' just the new value wasn't stored and the old one kept showing up.

**Comment by FagnerMartinsBrack** [comment]
@TomSmartBishop Can you provide an [SSCCE](http://sscce.org/)? You can attach a nodeJS project in a zip file to Github issues.
