### ISSUE TITLE
implement a support more simple for expires in hours, minutes and seconds

### ISSUE THREAD

**Issue by pedropolisenso** [js-cookie/js-cookie#476]
Hi Guys,

I use js-cookie a long time, however would be interesting if the module have a feature or flag name for be more simple the expires implementation in hours, minutes and seconds. 

I know that today we can use an approach like this: `new Date(new Date().getTime() + 1 * 60 * 1000);` for expires in one minute, but could be very nice improve this module using the specific times.

**Comment by carhartl** [comment]
This has been discussed a couple of times before, and our take has so far been that we refrain from adding more options to provide the expired option (apart from the two existing ones). These would need to be implemented, tested, documented, maintained. And it would add more code which we try to keep at a minimal size as well.

Fwiw, if you’d needed 1 hour, you can already do this:
```
expires: 1/24
```
You could implement that as tiny functions to make it more readable:
```
expires: 1/24
```
expires: oneHourFromNow()
```

**Comment by carhartl** [comment]
Or:
```
hoursFromNow(1)
```
```
minutesFromNow(35)
```
and so on :)

**Comment by FagnerMartinsBrack** [comment]
[The Wiki](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-make-the-cookie-expire-in-less-than-a-day) shows what to do in this case. As Klaus said, we don't want to add more logic to this code so that we can keep it simple, stable and with one responsibility.

**Comment by FagnerMartinsBrack** [comment]
X-Ref to all discussions about this subject: https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964773
