### ISSUE TITLE
Is version 2.0 working?

### ISSUE THREAD

**Issue by zealmurapa** [js-cookie/js-cookie#48]
Is this version working for anyone?

**Comment by FagnerMartinsBrack** [comment]
Why you say it's not working? There's a whole test suite that proves it is working: https://github.com/js-cookie/js-cookie/tree/7c3a8bd7a05d89b7cee79a0d465556facf05ae59/test

Did you tried including in the page directly from CDN?

```html
<head>
    <script src="//cdnjs.cloudflare.com/ajax/libs/js-cookie/2.0.0-beta.1/js.cookie.min.js"></script>
</head>
```

Please, provide more information specifically about what is not working for you.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP, we reopen if more information is provided.
