### ISSUE TITLE
Cookies.getJSON - Cannot parse object containing some escaped characters.

### ISSUE THREAD

**Issue by qchouleur** [js-cookie/js-cookie#480]
Some characters contained in a given cookie appear to be decoded prior to the JSON parsing call. It prevents the cookie content to be successfully parsed for valid JSON.

Given a cookie set with the following parameters: 
![image](https://user-images.githubusercontent.com/6623565/49022216-99a54880-f194-11e8-9a19-b34aac7e735c.png)

Parsing the raw content works:
![image](https://user-images.githubusercontent.com/6623565/49022245-ad50af00-f194-11e8-83dd-24bfba82eea8.png)

Calling the get and getJSON return the following values:
![image](https://user-images.githubusercontent.com/6623565/49022372-fd2f7600-f194-11e8-9b5d-3e4345e4ec94.png)

**Comment by FagnerMartinsBrack** [comment]
@qchouleur The following code works using version 2.2.0:

```
Cookies.set('test', '["message": "%22example%22"]');
alert(Cookies.getJSON('test'));
```

Can you please provide a running example that fails? See this website: http://sscce.org/

**Comment by qchouleur** [comment]
Indeed the cookie was set somewhere else, It was set using ASP.NET MVC. I used a custom converter to make it work. Thanks for you answer.

**Comment by FagnerMartinsBrack** [comment]
Cool @qchouleur if you find the root cause feel free to create a PR for the [SERVER_SIDE.md](https://github.com/js-cookie/js-cookie/blob/d62645185a4ede39ae10216fa695e5f70e701482/SERVER_SIDE.md) file documenting the peculiarities of ASP.NET MVC :)
