### ISSUE TITLE
IE11 not saving cookie when domain set 'localhost'

### ISSUE THREAD

**Issue by stephenliu1944** [js-cookie/js-cookie#486]
Cookie.set('test', {name: 'stephen'}, { 
    path: '/',
    domain: 'location'
    // or 
    domain: 'location:8080'
}); 
Cookie.get('test');      // undefined
both not work on IE11

**Comment by carhartl** [comment]
In that snippet you‘re using `location` instead of `localhost`..

**Comment by stephenliu1944** [comment]
Cookie.set('test', {name: 'stephen'}, { 
    path: '/',
    domain: 'location'
    // or 
    domain: '127.0.0.1'
});   
Thansk, do you mean this? but both not work too.

**Comment by carhartl** [comment]
Just wanted to make sure that you don’t attempt using a wrong value.

**Comment by carhartl** [comment]
Does IE11 store cookies like that on other domains/sites? Does it work when you add an entry to your hosts file, and then using that domain?
