### ISSUE TITLE
Plus sign encoding

### ISSUE THREAD

**Issue by mrkamel** [js-cookie/js-cookie#487]
Certain frameworks still use + for encoding spaces in cookies. As js-cookie doesn't handle this, it's hard to fix, because simply replacing it afterwards is too late as it would replace regular plus signs encoded via %2B as well.

Are you open for a PR to replace + with space js-cookie's decode function? Or do you have any other suggestions?

**Comment by FagnerMartinsBrack** [comment]
What about [converters](https://github.com/js-cookie/js-cookie/tree/d62645185a4ede39ae10216fa695e5f70e701482#converters)?

**Comment by mrkamel** [comment]
That should be working! Didn't see those. Would still be great to have '+' decoding intergrated as first class citiziens, but i'm closing this issue. Thx for your help!
