### ISSUE TITLE
Set secure: true as default

### ISSUE THREAD

**Issue by piu130** [js-cookie/js-cookie#489]
Since HTTPS becomes more and more standard we should change the default value of `secure` to `true`.

This may prevent attacks where a session cookie is set and then transmitted over a non-HTTPS channel because the developer does not know about or did forget to set the `secure` flag.

**Comment by FagnerMartinsBrack** [comment]
@piu130 Do you have a real-life example that justifies the change to HTTPS by default? This is a big breaking change even or a major version, but nothing prevents us from implementing on a v3. The only concern I have is that this is the only report in 9 years...

**Comment by piu130** [comment]
@FagnerMartinsBrack There are different ways to get an insecure cookie.

The simplest way is, when the user requests `http://example.com/login` and is redirected to `https://example.com/login`.
A man-in-the-middle can then read the cookies (eg. session cookie), because the initial request was http.

[Here](https://www.pivotpointsecurity.com/blog/securing-web-cookies-secure-flag/) is a blog post describing other scenarios.

I think we should consider this for a v3 release but its not important enough to create it.

**Comment by gregakaoz** [comment]
Why can't you test "location.protocol" and upgrade to https: if needed? Requiring additional information from the user to step down to http seems like a common bug for people that do debugging on localhost or on a private network.

**Comment by FagnerMartinsBrack** [comment]
@gregakaoz I'm not sure if you're suggesting for us to change the js-cookie code, but if it is if we couple the API to look at the `location.protocol` we still need to write code to account for environment which don't have global `location` property. The only global the js-cookie is coupled is to the `document.cookie` which is essential to be able to achieve the API abstraction.

The developer can easily write the code to check for the `location.prototol` if they want to outside js-cookie and call `Cookies.set('name', { secure: location.protocol === ? })` if necessary.

I would advise not to have this logic client-side if possible.

**Comment by FagnerMartinsBrack** [comment]
@piu130 I believe changing the `secure` property at this point will break too many websites. @carhartl Shall we close this as `wontfix` and recommend users to use `https` and `secure: true` in the readme?

**Comment by piu130** [comment]
I would not recommend to use `location.protocol`, because there are frameworks/libraries refreshing the cookie on route change.

@FagnerMartinsBrack Major release means there are breaking changes, so developers should read the changelog. The bigger problem is it would break the development process, because most developer do not use `https` in development.

So the developer might use hacks like `location.protocol`. Maybe it's better to advise them to set `secure: true` as you said?

**Comment by gregakaoz** [comment]
@FagnerMartinsBrack due to xss the change would be in the readme and not the "base code". 

Only code suggestion would be a "Global Flag" with the possibility to set flags such as secure or httppnly that alter all "set" calls.

**Comment by FagnerMartinsBrack** [comment]
Thanks @gregakaoz. You can also create a Pull Request updating the README if you want to.

**Comment by carhartl** [comment]
We would probably recommend the following in the readme?

```javascript
Cookies.defaults.secure = location.protocol === 'https:'
```

**Comment by piu130** [comment]
Is there a use case, where you need http and https for the same site?

Otherwise , we should not recommend this, because it could be dangerous.I can not think of a case where it would, but there were a lot of failures in security because of dynamic properties.

What do you think about something like this:

```js
Cookies.defaults.secure = process.env.NODE_ENV === 'production'
```

`NODE_ENV` should not change on run-time unlike `location.protocol`.
This works only for `webpack`, `browserify` and other build-tools.

Another solution would be to just make the developer aware of this setting and only recommend to set it to `true` for websites with https.

**Comment by FagnerMartinsBrack** [comment]
@piu130 

> Is there a use case, where you need http and https for the same site?

Anyone can have that in prod, although it's not used very often now that HTTPS is the recommended standard. This would be mostly for http when running `http://localhost`; the friction to have http in `localhost` is too high.

 > Cookies.defaults.secure = process.env.NODE_ENV === 'production'

This lib is not meant for NodeJS. Although you pointed out this is used by webpack/browserify we want to build js-cookie build/environment agnostic. The only dependency is the `document` DOM API and JavaScript.

> Another solution would be to just make the developer aware of this setting and only recommend to set it to true for websites with https.

How's that different from what @carhartl suggested? Is it the same recommendation but without checking against `location.protocol`?

**Comment by FagnerMartinsBrack** [comment]
I'm ok with changing `secure` to default to `true`, I'm just concerned with the potential issues saying "Why is my cookie not working in localhost" like the ones we have saying "why is my cookie nor working when I open an HTML file in the browser from my file system"?

**Comment by carhartl** [comment]
To sum this up: I believe we're not going to add anything to the actual implementation. Developers are held responsible to apply the setting on their own. We can add a note to the documentation, nudging developers towards doing the right thing and/or make them aware. We will happily accept pull requests for such a documenation tweak :)
