### ISSUE TITLE
Cookies.get() always returns undefined

### ISSUE THREAD

**Issue by dzarezenko** [js-cookie/js-cookie#491]
When I am trying to get cookies values in my NUXT.js project I always receive `undefined`
```
import Cookies from 'js-cookie'

// ...

let token = Cookies.get('token')
console.log(token) // undefined

let cookies = Cookies.get()
console.log(cookies) // undefined
```

So I use this approach now:
```
const tokenCookie = request.headers.cookie
  .split(";")
  .find(c => c.trim().startsWith("token="));
if (!tokenCookie) {
  return
}
token = tokenCookie.split('=')[1]
```
but it's not so elegant as I want.

**Comment by itopizarro** [comment]
I *just* installed js-cookies on my WebPack/Vue project and noticed that the method names are different from what is listed in the readme. `Cookies.get( 'foo' )` generates an error, where `Cookies.getItem('foo')` seems to be the new nomenclature.

**Comment by dzarezenko** [comment]
I just tried `Cookies.getItem('token')` and received this `TypeError`
```
js_cookie__WEBPACK_IMPORTED_MODULE_0___default.a.getItem is not a function
```

**Comment by itopizarro** [comment]
That's the same error I got when I tried `Cookies.get('foo')` — I'm thinking maybe I have a version issue(?)

**Comment by carhartl** [comment]
Fyi, at no point did we change the api from `get` to `getItem()`...

**Comment by itopizarro** [comment]
Yep. I had the ENTIRELY wrong library. I edited my reply.

**Comment by dzarezenko** [comment]
@carhartl , could you help me with this issue? Why I am receiveing `undefined` with `.get()`?

**Comment by carhartl** [comment]
@dzarezenko I‘m lacking too much information/context. There are many reasons why cookies are not written, one of which might just be a browser settings. Also, I don‘t know Nuxt.js at all..

**Comment by carhartl** [comment]
Can you show me the code that is writing the cookie with the name `token`?

**Comment by carhartl** [comment]
It looks like you‘re running into this: 
https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js

**Comment by dzarezenko** [comment]
@carhartl sure
```
import Cookies from 'js-cookie'

//....

// store auth token to the cookies
Cookies.set("token", response.data.user_key)

// ...
```

**Comment by carhartl** [comment]
What does `Cookies.set(...)` return?

**Comment by dzarezenko** [comment]
Something like this:
```
Cookies set: token=5f4f03f6c4c7792165520c219611973d; path=/; expires=Wed, 13 Feb 2019 20:43:16 GMT
```

**Comment by carhartl** [comment]
That looks good. Is the cookie maybe expired shortly after it was written?

**Comment by dzarezenko** [comment]
Looks like I have no `document` object on that stage. I want to get cookies value on the server side before rendering on client with NUXT.js

**Comment by carhartl** [comment]
No wait, it says expires tomorrow..

**Comment by dzarezenko** [comment]
But I can receive cookies value from `request.headers.cookie` as I mentioned before in the issue description.

**Comment by carhartl** [comment]
> Looks like I have no document object on that stage

That‘s what I suspected..

**Comment by zinwalin** [comment]
I reckon Cookies.get has been called in async way.  can you check if it's running in any async func?

**Comment by MULUALEM-TEKLE** [comment]
in some cases if the cookie is defined with httpOnly=true it might be the issue if you keep getting undefined, try setting it to false
