### ISSUE TITLE
Unable to set cookie for a physical file in chromium/chrome

### ISSUE THREAD

**Issue by focusedMonk** [js-cookie/js-cookie#492]
I am using the electron JS desktop application where I am trying to set a cookie and it seems like cookies are not being set. I tried with document.cookie = "name=value" still doesn't make any difference. Later after seeking for help online, I found that, application has to be hosted on the server to set a cookie and for physical file it's not possible to set a cookie since electron applications are launched locally without any server. Is there any possibility from this package to set a cookie for physical file?

**Comment by carhartl** [comment]
I think you‘d better be using localStorage for your purpose.

**Comment by focusedMonk** [comment]
Hey carhartl, Thanks for your suggestion. Server is reading the data from cookie and that's common for multiple projects. So I need a way to set the cookie.

**Comment by carhartl** [comment]
Since you mentioned Chrome, maybe you can manage to apply the `enable-file-cookies` flag?

https://wehavefaces.net/enabling-cookies-on-file-google-chrome-c84eeb2c7cc2

**Comment by carhartl** [comment]
I found something about cookies in the electron documentation as well, not sure if that‘s a helpful: https://electronjs.org/docs/api/cookies

**Comment by carhartl** [comment]
Since this is not a problem with this library I‘m closing the issue.
