### ISSUE TITLE
Code not working in Firefox

### ISSUE THREAD

**Issue by Anupya** [js-cookie/js-cookie#493]
Hey there! I recently made a Chrome extension using JS-Cookie. It works perfectly on Chrome but I loaded the extension as is on Firefox as a local add-on.

I go to Chrome console and type the following:
Cookie.set("color", 5)
// "color=5; path=/"
Cookie.get("color")
// 5

However for Firefox, 
Cookie.set("color", 5)
// "color=5; path=/"
Cookie.get("color")
// undefined

I do not know why Cookies.get is not working. Any help?

**Comment by carhartl** [comment]
Hi he documentation suggests that you to take additional steps in order to enable cookies in an extension:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies

**Comment by Anupya** [comment]
Oh I found a way to store data without using JSCookies, so I cannot remember if I tried this method already or not. I hope it helps somebody else with the same problem though!
