### ISSUE TITLE
Cookies are lost after closing browser

### ISSUE THREAD

**Issue by gijo-varghese** [js-cookie/js-cookie#494]
I tried to put cookie using the below code
```
Cookies.set(key, value, { expires: 60 });
```

However, after closing and opening browser, the cookies will be lost. Also the 'expires' are not set even though I've specified it

**Comment by carhartl** [comment]
Would you able to provide more context (browser, os and so on). I don’t think we’ll be able to help, since the described problem is not the general case...

**Comment by carhartl** [comment]
It could for instance be a browser setting, an ad blocker/privacy extension an so forth..

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by matinwd** [comment]
Same problem here. with firefox developer 77.0b6

**Comment by carhartl** [comment]
> Also the 'expires' are not set even though I've specified it

This explains why the cookie is gone after closing the browser (without expiration cookies become session cookies).

@matinwd Browsers increasingly start to implement mechanisms that restrict particular cookie features, mostly for privacy reasons. Safari for instance caps expiration of cookies at seven days as part of its Intelligent Tracking Prevention. Maybe Firefox just doesn’t accept any other (client-side written) cookies apart from session cookies any longer. Would need to investigate a little, bit it’s definitely something to look out for.

**Comment by carhartl** [comment]
This might provide a bit of useful information:
>Create a cookie 'allow' exception to keep such cookies, especially in case of secure websites and when cookies expire when you close Firefox.

https://support.mozilla.org/en-US/questions/1068003
