### ISSUE TITLE
In chrome of android, setting expire_date is null, Cookie still saved after close browser

### ISSUE THREAD

**Issue by Hung-TM** [js-cookie/js-cookie#495]
My purpose is to remove cookies after close the browser. i setted expire_date is null, but cookie don't lost data after close browser in chrome of android . All other environment  work normally. please help, thanks!
Cookies.set('name', 'value');

**Comment by Hung-TM** [comment]
```
return rememberMe ? Cookies.set(TokenKey, token, { expires: process.env.EXPIRE_AT }) : sessionStorage.setItem(TokenKey, token)
```
Currently, i'm using it in conjuntion with sessionStorage. And solved the problem. But i just want to solve it by js-cookie :((

**Comment by carhartl** [comment]
Possibly this: https://github.com/js-cookie/js-cookie/issues/481#issuecomment-443994779

**Comment by Hung-TM** [comment]
@carhartl in dont think so. Because, in the windows chrome, i set On Starter *Continue where you left off* on chrome, sessionStorage also doesn't lost data. Here, it just happened in android chrome

**Comment by carhartl** [comment]
Could you tell me the Chrome and Android version you’re seeing this in? I would want to try to reproduce this in Browserstack..

**Comment by Hung-TM** [comment]
please Android 7.0 with chrome 72.0.3626.121
thank you @carhartl

**Comment by carhartl** [comment]
Could you also check this: https://stackoverflow.com/a/19560566

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
