### ISSUE TITLE
Cookie encryption

### ISSUE THREAD

**Issue by dbaronov** [js-cookie/js-cookie#496]
Could we optionally prevent users from tampering with cookies by encoding / encrypting values in a reversible manner?

**Comment by dbaronov** [comment]
Meanwhile, since I only needed to make it unreadable and not encrypted, here is what I came up with:

```
            let encodedCookieString = btoa('some-value');
            jsCookie.set('cookie-name', encodedCookieString, { expires: 365 });
```

IE 10+ support

**Comment by carhartl** [comment]
Converters could be useful here: https://github.com/js-cookie/js-cookie/blob/master/README.md#converters

**Comment by FagnerMartinsBrack** [comment]
@dbaronov 
Cookies are client-side, therefore it's impossible to prevent users from changing the values. You can use one-way hashing but the client can still change the values for another hash.

**Comment by courtneyaschwartz** [comment]
@FagnerMartinsBrack  True it is not literally _"preventing"_ tampering... but it does have a use.

1. Decrypt failures _detect_ tampering attempts. 
2. Fuzzing is impractical in real time (unless by chance they miraculously edit a hash to a sane value, for example). 

@dbaranov Careful... **Encoding is not encryption.** It's easily circumvented. When even a novice looks at the string, it's easy to guess "Base64" then go to https://www.base64decode.org/. Now I just input my new value, Base64 encode, and feed the valid encoding back to your app...  Doesn't achieve the 2 goals above. Most people actually want a **SHA-256 hash**. (Still fast, but tamper-proof.) 

Try a good, community-tested crypto package like:

`sjcl.encrypt("password", "data");`

https://bitwiseshiftleft.github.io/sjcl/

**Comment by carhartl** [comment]
I refrain from implementing that as part of this supposedly light-weight library, especially given we have converters to support such an “obfuscation” use case easily...
