### ISSUE TITLE
[Question] For loop vs Array.forEach

### ISSUE THREAD

**Issue by willstocks-tech** [js-cookie/js-cookie#497]
Hey guys! 

Let me start by saying - thank you! 😄 

On to the question: is there a reason you've stuck with `for` loops rather than using the native `Array.forEach` (which is supported from IE9 onwards)? I know there's always some effort to micro-optimize, or minify code as much as possible (such as in #401)

Do you see a performance benefit in sticking with `for` loops, or is it readability, or supportability?

**Comment by carhartl** [comment]
We planned to do a new mayor release dropping support for IE < 9. With that we can have nicer, and maybe less code along the way.  

We just never did the release :)

**Comment by willstocks-tech** [comment]
Hahaha! Nice - always the way ;)

Do you think that release will ever happen? Probably a lot you can do
natively now if you were to drop _extremely_ old browsers support (I killed
off IE11 and older personally - was just far too much overhead with too
little traffic) as well as with a smaller/more efficient codebase (not that
it is inefficient!!!!!)?? :smile:

**Comment by FagnerMartinsBrack** [comment]
One of the benefits of this lib is that it supports IE6 since forever. I don't think it hurts to keep like that if the code doesn't change. Of course, if we need to upgrade it would be not because of IE6 global usage, it will be only because of tools like QUnit or Sauce Labs which dropped IE6 support a long time ago.

To answer your question, the `for` loops are due to supportability (IE6). Also, we have other parts of the code and byte size optimizations we didn't do in order to support oldIE, which will probably go away with https://github.com/js-cookie/js-cookie/issues/370.

**Comment by willstocks-tech** [comment]
Thanks @FagnerMartinsBrack - if [this chart](https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browserVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222018-03%22%2C%22dateEnd%22%3A%222019-02%22%2C%22segments%22%3A%22-1000%22%2C%22pageLength%22%3A50%7D) is to be believed, IE10 and older (because _in theory_, IE11 still has "support" due to being part of W10) caters for less than 2.05% of worldwide browser usage 🙂 (which is actually very slightly higher than I expected - I was expecting less than 1.5%)

Do you think the next release/version (that I imagine will drop <IE10 support) will happen any time soon? It'd be great to see js-cookie not rely on legacy code for the sake of super old and (vendor) unsupported browsers. At any rate, if there were a list of vanilla features used that may not be fully supported on older browsers, a user could polyfill those if they absolutely wanted to support old browser versions (I do this personally - I built a little script to only polyfill a feature when I absolutely have to)

**Comment by FagnerMartinsBrack** [comment]
> Do you think the next release/version (that I imagine will drop <IE10 support) will happen any time soon?

I don't think so unless @carhartl wants to do it or you create a PR to leave it ready for when we do it.

> It'd be great to see js-cookie not rely on legacy code for the sake of super old and (vendor) unsupported browsers.

JavaScript doesn't have legacy code that can go away in a future version if that's what you mean. Therefore, what's the significant cost of leaving as it is?

>  At any rate, if there were a list of vanilla features used that may not be fully supported on older browsers, a user could polyfill those if they absolutely wanted to support old browser versions (I do this personally - I built a little script to only polyfill a feature when I absolutely have to)

We all agree that we can drop support at this stage, only that leaving as it is has no cost whatsoever as long as we don't make any more changes to the lib. The lib is very stable and feature complete. I don't foresee any significant changes in the future other than dropping browser support for golfing the minified byte size.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

Discussion for dropping IE support can continue on https://github.com/js-cookie/js-cookie/issues/370

**Comment by carhartl** [comment]
If you look more closely though you will notice that we‘re making use of `break` as well as `continue` within these “classic” loops. For breaking we’d need to throw an exception which I, personally, find ugly. While `forEach()` is mostly useless in our cases, I’m sure we might be able to — ignoring breaking for a moment — utilize the `filter()`, `reduce()` and `map()`Array methods to achieve what we need.

**Comment by carhartl** [comment]
.. in fact I had played with that a little bit (now that we’re no longer supporting IE < 10), but it made the library larger, minified and gripped, so I stopped pursuing this.

**Comment by carhartl** [comment]
PS: Also, I don’t see how these oldschool loops are a bad thing.. readability maybe?

**Comment by FagnerMartinsBrack** [comment]
On top of that, most of the spaghetti/imperative code of js-cookie is constrained to its small context. Legibility is something we clearly sacrificed in favor of byte size reduction and other tradeoffs (like browser compatibility). All this is done at the cost of a high degree of test coverage.

When I write production code, I write it in an entirely different way than how I do for js-cookie, and that's ok, not all the code needs to be written the same.

I also don't think there's an issue with old school loops in this project.
