### ISSUE TITLE
please how do I update a cookie value?

### ISSUE THREAD

**Issue by folamy** [js-cookie/js-cookie#500]
I'm using js-cookie with vuex store mutation, and each time i commit the state i want store the state in cookie

**Comment by carhartl** [comment]
There is no difference in updating or writing a cookie, so you will do a `Cookies.set('my_vuex_state', ...)` each time.

**Comment by yutod** [comment]
@folamy 
Is your question asking when/how cookie should be set?
When I faced the situation working with vuex, used to set cookie with the state after updating it as @carhartl described.

ex)
```
mutations: {
    setTargetValue(state, payload) {
        state.targetValue = payload.targetValue;
        try {
            Cookie.set('cookieKey', state.targetValue, { expires: 0.5, path: '/', ... });
        } catch (error) {
            state.errorMessage = `cannot set ${state.targetValue} on cookie`;
        }
    }
}
```

**Comment by folamy** [comment]
Thanks all
