### ISSUE TITLE
How to use httponly

### ISSUE THREAD

**Issue by FreddyCrugger** [js-cookie/js-cookie#502]
Hello,

httponly is a very important feature to have.
I understand that js cannot use httponly and this is exactly why it is important.
When you build an app with vue(example), you need to save the token(for security reason) as a cookie with http only. The token (from the cookie) is then passed as a header to the API solving many security issues. Without httponly, you have to save the cookie as is which can be stolen.

I could not find httponly in your doc.

Thank you.

**Comment by FagnerMartinsBrack** [comment]
As of 2.2.0 you can use any undocumented attribute when setting the cookie: https://github.com/js-cookie/js-cookie/tree/v2.2.0

See also https://github.com/js-cookie/js-cookie/releases
