### ISSUE TITLE
Cookies are not setting for less than 2 days

### ISSUE THREAD

**Issue by msufiannasir** [js-cookie/js-cookie#503]
It does not allow me to set the cookie for one day. When I make it 2 days it works.
Not working:
Cookies2.set('mycookie', 'test', { expires: 1 });
Working:
Cookies2.set('mycookie', 'test', { expires: 2 });

**Comment by FagnerMartinsBrack** [comment]
If you use the `document.cookie` browser API, does it work?

**Comment by carhartl** [comment]
Where’s the `Cookies2` reference coming from?

**Comment by msufiannasir** [comment]
@FagnerMartinsBrack - I didn't try it with document.cookie.

@carhartl Here is the full code snippet:
var Cookies2 = Cookies.noConflict();
jQuery(document).ready(function ($) {
        $(document).on("click", ".cta-button", function () {
        Cookies2.set('ddctapopupcookie', 'yes', { expires: 2 });
    });
 });

**Comment by FagnerMartinsBrack** [comment]
@msufiannasir If you try with `document.cookie` and it still doesn't work then the problem might be on the development environment.
Can you try with `document.cookie` and let us know how it goes?

**Comment by msufiannasir** [comment]
Sure. I will let you know

**Comment by JerryGreen** [comment]
Just noticing - you can pass a `new Date(<your needed date>)` as an `expires` argument. So you can set it for even less than a day. Works for me

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by msufiannasir** [comment]
@JerryGreen  - new Date(<your needed date>) works like a charm.

@FagnerMartinsBrack - my issue is resolved using data object as an expiry. 

Thanks for your time guys :)
