### ISSUE TITLE
Can't read a cookie set with "expires"

### ISSUE THREAD

**Issue by BogdanEM** [js-cookie/js-cookie#505]
I can't read back a cookie set with "expires".

I set a non session cookie like this: `Cookies.set('acceptance', 'yes', { expires: 365 });`. The cookie is saved in the browser and remains there after I close the browser.

When I open the browser again and read the cookie, although the cookie is there, `Cookies.get('acceptance')` returns undefined.

I'm currently testing on some local static HTML files, so the protocol is `file:///`. Not sure if this matters but just thought of mentioning it.

Am I doing something wrong?

**Comment by carhartl** [comment]
Are you using Chrome here? In Chrome, setting a cookie for the `file` protocol is not supported.

**Comment by BogdanEM** [comment]
I'm using Firefox Quantum 66.0.3 (64-bit).

I can read the cookie while the browser is still open. `document.cookie` also shows the cookie. But after I close the browser and reopen, I can no longer read it and `document.cookie` shows an empty string as well, although the cookie is there and I see it in the developer tools.

**Comment by carhartl** [comment]
This seems to give a hint: https://stackoverflow.com/questions/47349152/getting-cookies-from-local-drive-in-javascript-using-firefox-quantum

**Comment by BogdanEM** [comment]
Interesting workaround :D, but I need to use a cookie for my particular case.

It is indeed a `file` protocol issue. I just stuck all my pages in a web server and it works as expected over `http`. 

All my site is static html so I just opened it from disk for convenience. But I don't mind opening it from `http://localhost` either, especially if it avoids issues like this.

Thanks for the help. 

This issue can be closed now.
