### ISSUE TITLE
Failed tests for Safari?

### ISSUE THREAD

**Issue by migsyboy** [js-cookie/js-cookie#507]

**Comment by taewo** [comment]
<img width="625" alt="스크린샷 2019-05-25 오후 5 32 36" src="https://user-images.githubusercontent.com/14291977/58366848-25fdb180-7f13-11e9-9be0-8a3bf3ba2103.png">

May be we can't use js-cookie for Safari

**Comment by Brian611** [comment]
So this does not support Safari? well, that's disappointing.

**Comment by carhartl** [comment]
Definitely not on purpose... not sure what‘s happening.

**Comment by carhartl** [comment]
The last build on master is green, including Safari: 
https://travis-ci.org/js-cookie/js-cookie/builds/494492528

Later there was a failing build for an (automated) pull request, but the Saucelabs build matrix image always shows the status of the latest build, and is therefore misleading.

**Comment by Brian611** [comment]
I see thanks for clarifying that, I would suggest you try another status build as developers may be turned off when they see no support for Safari.

**Comment by carhartl** [comment]
Please also compare the Travis build badge, which is authorative when it comes to build status (and it includes Selenium/Saucelabs test status).

I’m inclined to remove the build matrix widget for its misleadingness.. thoughts @FagnerMartinsBrack ?

**Comment by FagnerMartinsBrack** [comment]
@carhartl Agree, it's not the first time this comes up
