### ISSUE TITLE
In the  "Build Status Matrix"

### ISSUE THREAD

**Issue by mor26** [js-cookie/js-cookie#51]
Hi,
In the "Build Status Matrix" there is Android version 5.1 so it means that "js-cookis" version works on Android 5.1 and less? so basically on any android version?

Thanks

**Comment by FagnerMartinsBrack** [comment]
Hi @mor26.

All browser versions with considerable market share are supported. The "Build Status Matrix" only proves that `js-cookie` is being automatically tested on Android 5.1. We are not aware of any bugs on cookie handling among different Android versions, so we assume Android 5.1 and earlier **are** working.

If you find any bugs or edge cases in Android versions with a considerable market share (>1%), please let us know or send a pull request that we will look into it.
