### ISSUE TITLE
Incorrect html coding in set()

### ISSUE THREAD

**Issue by bm13kk** [js-cookie/js-cookie#511]
I have value, that I got from 3rd party `AU|21-12-1999`
It HTML encoded and stored in the cookie as `AU%7C21-12-1999`.
And now I cannot store the same value in cookie.
`Cookies.set('AU|21-12-1999')` will store `AU|21-12-1999` as is. Which is incorrect.

Escaping it `escape('AU|21-12-1999') === 'AU%7C21-12-1999'` will get
`Cookies.set(escape('AU|21-12-1999'))` => `AU%257C21-12-1999`. Which is also incorrect.

And with this, I should remove your lib and do vanilla JS.

**Comment by carhartl** [comment]
In this case you could be using a converter (documented in the readme) with `escape` being the write converter, and `unescape` the one for read.

**Comment by bm13kk** [comment]
I can not escape before put. As I wrote, I already get setted cookie from 3rd party.
