### ISSUE TITLE
New Release > 2.2.0

### ISSUE THREAD

**Issue by tombrain** [js-cookie/js-cookie#512]
official release is still 2.2.0. by using npn or npm-asset/js-cookie, you get always this old version (Oct 28, 2017, 6:04:48 AM)

**Comment by carhartl** [comment]
What is it that you‘re looking for in a new release? Since the last released version 2.2.0 there have been — from the point of a user — almost no changes..

**Comment by tombrain** [comment]
There are some changes that were made after the release. Also in codefile:  Split api() into separate functions to get and set cookies (#454)

**Comment by FagnerMartinsBrack** [comment]
@tombrain As @carhartl said, the PR #454 is only [refactoring](https://medium.com/@fagnerbrack/how-to-refactor-a-public-interface-317ed18d38a3). It doesn't change the public behavior of the lib. You can see that because there are no test changes.

**Comment by carhartl** [comment]
Besides, using npm, you can always specify the dependency like so:

```
"js-cookie": "git@github.com:js-cookie/js-cookie.git#d2724a8"
```

^ This will give the currently latest commit on master.

**Comment by carhartl** [comment]
https://www.npmjs.com/package/js-cookie/v/2.2.1
