### ISSUE TITLE
how to secure the cookie?

### ISSUE THREAD

**Issue by LogeswariV** [js-cookie/js-cookie#514]

**Comment by carhartl** [comment]
What do mean by securing the cookie?

**Comment by LogeswariV** [comment]
Cookies.set('name', 'value', { secure: true }); is not working.If I give secure attribute it is not creating that particular cookies.but with Cookies.set('name', 'value', { expiry: 30 }); it is working.How can i use both secure and expiry attribute?I am using this one in my next.js project.

**Comment by carhartl** [comment]
This should work:
```
Cookies.set('name', 'value', { secure: true, expires: 30 });
```

(Just in case, note the attribute is named `expires`, not `expiry`.)

**Comment by carhartl** [comment]
PS: another reason for the cookie not being created might be that you’re trying `secure: true` while on an insecure `http://` domain?

**Comment by LogeswariV** [comment]
That is not working.If i pass secure,Iam not bale to see that value in the cookies.It is not seeting that value.
 jsCookie.set('userid',id,{ secure: true, expires: 30 }) with this code Iam not able to userid in the cookies.

**Comment by LogeswariV** [comment]
Yay!!!In localhost iam having htttp.Is ther any way to give https in localhost?

**Comment by LogeswariV** [comment]
> PS: another reason for the cookie not being created might be that you’re trying `secure: true` while on an insecure `http://` domain?

Yay!!!In localhost iam having htttp.Is ther any way to give https in localhost?

**Comment by carhartl** [comment]
You could use a tool like mkcert to create certificates for localhost: https://dev.to/rhymes/really-easy-way-to-use-https-on-localhost-341m

Closing this issue.

**Comment by encryptblockr** [comment]
> This should work:
> 
> ```
> Cookies.set('name', 'value', { secure: true, expires: 30 });
> ```
> 
> (Just in case, note the attribute is named `expires`, not `expiry`.)

and how do we get the expires value from Cookies.get('name')?

**Comment by carhartl** [comment]
> and how do we get the expires value from Cookies.get('name')?

It‘s not possible.
