### ISSUE TITLE
This library does not work with ReactJs

### ISSUE THREAD

**Issue by allnash** [js-cookie/js-cookie#517]
Tried using the instructions -
`import Cookies from 'js-cookie'`

Please advice.

**Comment by carhartl** [comment]
Did you see: https://github.com/js-cookie/js-cookie/issues/407#issuecomment-365562240

**Comment by sevdog** [comment]
I have been using this for two years (Feb 2018) without any problem in my project imported as
```
import cookie from 'js-cookie';
```


Maybe the problem could be related to some other settings (`webpack.config.js`, `.babelrc`, or other bundler/transpiler).

**Comment by allnash** [comment]
Ok let me take a look.

On Jul 18, 2019, at 10:32 AM, sevdog <notifications@github.com<mailto:notifications@github.com>> wrote:


I have been using this for two years (Feb 2018) without any problem in my project imported as

import cookie from 'js-cookie';


Maybe the problem could be related to some other settings (webpack.config.js, .babelrc, or other bundler/transpiler).

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by redaxmedia** [comment]
This should be documented in the README.md ...

```
import * as Cookies from 'js-cookie';
...
