### ISSUE TITLE
Check if cookie has expired

### ISSUE THREAD

**Issue by gmum4d** [js-cookie/js-cookie#518]
what is the best way to check if a cookie has expired, and then call a function if it has expired?

For example, will this work? I works for me if the cookie is deleted, but if it just expires (set for 1 day) the autologout function does not get called.

```
setInterval(function() {
		
	if (!Cookies.get('ID')) {

		autologout();

		} 
	
	}, 5000);
```

**Comment by carhartl** [comment]
Technically, if a cookie is expired, `Cookies.get('ID')` shouldn’t return anything, and that‘s the only way to know if a cookie expired. It could just as well never have been set or deleted, but it‘s impossible to distinguish these scenarios.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
