### ISSUE TITLE
Can't remove cookie if parent path has the same cookie name

### ISSUE THREAD

**Issue by quangld** [js-cookie/js-cookie#52]
$.cookie('CookieTest','local')
"CookieTest=local"
$.cookie('CookieTest','root',{path:'/'})
"CookieTest=root; path=/"
$.removeCookie('CookieTest')
false

If you accidentally have 2 cookies with the same name, you can't remove the local cookie without removing the same cookie name saved in the parent path.
So in this above example, you have to:
$.removeCookie('CookieTest',{path:'/'})
true

then
$.removeCookie('CookieTest',{path:'/'})
true

**Comment by FagnerMartinsBrack** [comment]
This is the desired behavior, check [this discussion](https://github.com/carhartl/jquery-cookie/issues/249#issuecomment-30091922):

> If you accidentally have 2 cookies with the same name, you can't remove the local cookie without removing the same cookie name saved in the parent path.

It's correct. That's a browser behavior that cannot be changed. Each developer is responsible for consistently create the cookie and manipulate it using the same path, secure and domain options. We **do not recommend** creating 2 cookies with the same name and different options to prevent this kind of confusion.

To help making it clear, the "options" were renamed to "attributes" in [version 2 of jquery-cookie](https://github.com/js-cookie/js-cookie/tree/v2.0.0-beta.1).

@carhartl 
I believe this is also worth pointing out in a FAQ. I have added in https://github.com/js-cookie/js-cookie/issues/37. What you think?

**Comment by FagnerMartinsBrack** [comment]
I will document here all links I could find with issues related in creating 2 cookies with the same name:

* https://github.com/carhartl/jquery-cookie/issues/21
* https://github.com/carhartl/jquery-cookie/issues/172
* https://github.com/carhartl/jquery-cookie/issues/343
* https://github.com/carhartl/jquery-cookie/issues/249
* https://github.com/carhartl/jquery-cookie/issues/178
* https://github.com/carhartl/jquery-cookie/issues/130
