### ISSUE TITLE
Running tests in Sauce Labs no longer working

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#524]
All we get to see is a tunnel being started and immediately after it is closed:

```
$ grunt saucelabs
Running "uglify:build" (uglify) task
>> 2 files created 7.77 kB → 3.28 kB

Running "connect:build-sauce" (connect) task
Started connect web server on http://localhost:9999

Running "saucelabs-qunit:all" (saucelabs-qunit) task
=> Starting Tunnel to Sauce Labs
>> 
=> Stopping Tunnel to Sauce Labs
>> Error closing tunnel
```

This happens both in Travis as well as when running `grunt saucelabs` locally while providing the saucelabs credentials via environment. Tried with a newly created access key.

**Comment by FagnerMartinsBrack** [comment]
That's the cost of relying on NPM packages. After a few years they run the risk of stop working and now we have 10 times the effort to fix them.

I might not have the time to help but here's my recommendation:

Step1:
* dump all the tests for oldIE
* remove the cross-browser matrix from README (https://github.com/js-cookie/js-cookie/issues/286)
* Create a release removing oldIE support (https://github.com/js-cookie/js-cookie/issues/370)

Step 2:
* Figure out why sauce labs are failing
* If too costly to figure out: choose another provider and test only in **latest** Safari, Edge, Chrome, FF, (Brave?), and IE11?

**Comment by carhartl** [comment]
Maybe I‘m using the wrong Sauce access key all the time? I can‘t remember how to sign-in for the js-cookie account on Sauce Labs.

**Comment by FagnerMartinsBrack** [comment]
@carhartl I don't remember how to set up the keys. It's been a while since the last time I run the Sauce Labs tests locally.

**Comment by carhartl** [comment]
We seem to have an account with a user `js-cookie`, but I can’t seem to find credentials. I could try a password reset but then I do not know which email it’s going to..

**Comment by FagnerMartinsBrack** [comment]
I created that with my personal e-mail. I can't add another subaccount it says the limit of "> 2 subaccounts" has been reached =/

Then I removed that account and got locked out of Sauce Labs. I tried to login with the Github integration and that seems to be the parent account...

I have created another subaccount and now it worked. Check your email and let me know if it works fine :).

**Comment by FagnerMartinsBrack** [comment]
It could be I created another account using the Github integration. If that's the case I believe that account is ready for Open Source so I guess you can try to setup js-cookie again?

**Comment by carhartl** [comment]
Thanks @FagnerMartinsBrack -- tested with the newly created acccount, as well as with another private one where I still had trial minutes left. None of them work, so at least I'm sure that it wasn't a problem with some stale access key.

**Comment by carhartl** [comment]
Maybe it's time to revive https://github.com/js-cookie/js-cookie/pull/409 and figure out why we can't run tests on iOS devices in Browserstack... oh my, stuck between two hard rocks it seems.

**Comment by carhartl** [comment]
Using the same credentials I am able to set up a tunnel using just Saucelabs' `sc` downloadable binary.

**Comment by carhartl** [comment]
Maybe it has to do with grunt-saucelabs using version 1.5.0 of https://www.npmjs.com/package/saucelabs

=> https://github.com/axemclion/grunt-saucelabs/blob/127cac287947399be79b5d6c96493dff5fb45184/package.json#L32

There's a much newer version out. We could try to define our own task for running the tests via tunnel...

**Comment by carhartl** [comment]
>Maybe it has to do with grunt-saucelabs using version 1.5.0 of

Doesn't even seem to be used...

**Comment by carhartl** [comment]
...maybe the `sauce-tunnel` package needs the latest binary, it's using `4.3.16` (https://github.com/jmreidy/sauce-tunnel#v250), current one is `4.5.4`.

**Comment by carhartl** [comment]
>.maybe the sauce-tunnel package needs the latest binary

That also doesn't seem to be the case.

**Comment by carhartl** [comment]
>maybe the sauce-tunnel package needs the latest binary

Yes, that seems to be the case. Started to run tests successfully with a patched, local sauce-tunnel package.

**Comment by carhartl** [comment]
And that worked only once...: https://app.saucelabs.com/tests/0c0bfb443e9147af92b6cb922c95e710

**Comment by carhartl** [comment]
Not sure what I did to make them run... updating the binaries didn't seem to do it and it worked by coincidence. 🤷

**Comment by carhartl** [comment]
Ok, we're running tests again in Saucelabs in the first place, but on macOS 10.14 they seem to be unstable (getting a "500 Internal Server Error") when accessing the qunit test suite: https://app.saucelabs.com/tests/801c906a9a0c4561a6676c60e3f71128#51

In macOS 10.13 it would just hang.

**Comment by carhartl** [comment]
This seems to be the same problem:
https://github.com/webdriverio/webdriverio/issues/3754

>So the workaround is to or use 10.13 or use the local ip of the machine that hosts the site.

**Comment by carhartl** [comment]
One test left times out (Firefox 68 on macOS 10.13), though the tests seem to run successfully:  https://app.saucelabs.com/tests/55f0d0ad57c8459ca2a3bad0a57c2ef6#2

(Same for Firefox 65 earlier..)

**Comment by carhartl** [comment]
The remaining failing tests in Saucelabs seem to be browser compatibility issues? I could successfully run tests in Firefox 24 on macOS 10.13: https://app.saucelabs.com/tests/37ef923d2dda4c73aed53ee056888a9c

With Firefox 68 (latest) the tests suite is green but it hangs nevertheless and the test in the end reports as failed.

**Comment by carhartl** [comment]
I'm starting too believe that in the end the saucelab grunt task and libraries and dependencies may have been rotting for too long. I might take another look whether that looks a bit better with Browserstack. Otherwise we may be able to come up with our own implementation of executing Selenium based tests on Saucelabs, and ditch the grunt task etc.

**Comment by carhartl** [comment]
What's missing in those stalled tests is that the test result is not being posted back like in here:

<img width="559" alt="Screenshot 2019-09-03 at 20 55 24" src="https://user-images.githubusercontent.com/21918/64200701-5697a480-ce8d-11e9-91fd-58ac7f4f2f7b.png">

**Comment by carhartl** [comment]
> What's missing in those stalled tests is that the test result is not being posted back like in here

Not quite. In more recent ones we get a 408 back when trying to retrieve test results, for example: https://app.saucelabs.com/tests/1e094517081440f28be1acd59895b30b#2

**Comment by carhartl** [comment]
Along the way I noticed that we also seem to run into QUnit's done being fired twice: https://github.com/qunitjs/qunit/issues/1102

**Comment by carhartl** [comment]
Giving up on Saucelabs. With Browerstack we are at least able run tests in relevant OS desktop browsers, including macOS 10.14. Will address running tests in iOS devices later.
