### ISSUE TITLE
cookies.set show a error in v2.2.1

### ISSUE THREAD

**Issue by feinimoshu753** [js-cookie/js-cookie#526]
i find a bug in v2.2.1. when i use maxAge, get a error "attributes[attributeName] is not a function". 
can you fix it?

**Comment by carhartl** [comment]
Could you provide an example of the code that exposes the error?

**Comment by feinimoshu753** [comment]
demo: Cookies.set(key, value, {path: '/', maxAge: 3600})
i have found the error code. becouse i pass a argument of maxAge
![image](https://user-images.githubusercontent.com/11944235/63022160-dd7fdf80-bed4-11e9-8304-6fe7741b269b.png)

**Comment by carhartl** [comment]
Yeah, you need to use `expires`.

**Comment by feinimoshu753** [comment]
do you think transform the params  is a better choice？
like this.
"String(attributes[attributeName]).split(';')[0]"

**Comment by carhartl** [comment]
Not sure. I don’t see a real case for this when you follow the public, documented api. Even when you really really want to use an arbitrary cookie attribute you could do so by sticking to a string: `maxAge: "3600"`. Might not be 100% intuitive but you are hacking the api in the first place.

**Comment by Mati365** [comment]
@feinimoshu753 same here, regenerate of yarn.lock during deploy 2h ago broke my production code.

**Comment by carhartl** [comment]
In a future version 3 release, in which we were dropping support for old IEs, we would possibly switch from using expires to the max-age attribute. (Important to note: it’s `max-age`, I don’t think `maxAge` would have any effect.)

**Comment by carhartl** [comment]
@Mati365 You seem to be using an `exp` attribute, but you want `expires`. With the former there’s no effect, neither in version 2.2.0 nor 2.2.1.

You’re basically creating session cookies.

So the fix is not to downgrade but use the api as documented.

**Comment by Mati365** [comment]
@carhartl lol, I see - sorry. Can we serialize `Date` object in that field?

**Comment by carhartl** [comment]
>Can we serialize Date object in that field?

Yes, that’s already supported. See readme, it contains hopefully enough documentation regarding usage of expires.

**Comment by feinimoshu753** [comment]
> Not sure. I don’t see a real case for this when you follow the public, documented api. Even when you really really want to use an arbitrary cookie attribute you could do so by sticking to a string: `maxAge: "3600"`. Might not be 100% intuitive but you are hacking the api in the first place.

do you think a extra params shouldn't cause an js error?
when i use v2.2.0, it's ok. a accidently update cause my code broken. maybe some people have same question.
i hope you can consider the condition, thank you.
