### ISSUE TITLE
why did not provide clear or removeAll method?

### ISSUE THREAD

**Issue by jiangdefu** [js-cookie/js-cookie#527]
I want remove all cookies ,have any methods provide?

**Comment by carhartl** [comment]
Something like:
```
for (var c in Cookies.get()) {
    Cookies.delete(c);
}
```
If you’re able to utilize newer JavaScript features:
```
Object.keys(Cookies.get()).forEach(Cookies.delete);
```

**Comment by carhartl** [comment]
Wait, the latter example won't work, the `forEach()` callback takes more than 1 argument. 

This should work:

```
Object.keys(Cookies.get()).forEach(key => Cookies.delete(key));
```

**Comment by daiyang123456** [comment]
path of cookie  will be uneffcetive
