### ISSUE TITLE
Will some cookies be invisible?

### ISSUE THREAD

**Issue by taurenshaman** [js-cookie/js-cookie#529]
Server: ASP.net MVC5
Testing Browser: Opera 62, Firefox 68

Here is the complete cookies using developer tools:  
![request cookie](https://user-images.githubusercontent.com/1308706/63650714-66720300-c780-11e9-975d-f1c7638cd4c9.png)

**But**, There will be some invisible item if I give a test using document.cookie or Cookies.get:  
![console test](https://user-images.githubusercontent.com/1308706/63650734-96b9a180-c780-11e9-810d-f0be379c8da3.png)

**The property _HttpOnly_  of Cookie makes the effect?**  
**Server Code**
```
      HttpCookie accountCookie = new HttpCookie( UserManagement.StorageKey_AccountID, account );
      HttpCookie pwd512Cookie = new HttpCookie( UserManagement.StorageKey_AccountPassword, pwd );

      if ( !System.Diagnostics.Debugger.IsAttached ) { // not debug
        // share between sub domains
        // ref: http://www.codeguru.com/csharp/csharp/cs_internet/article.php/c19417/Sharing-Cookies-Across-Domains.htm
        accountCookie.Domain = Common.Business.Domain;
        pwd512Cookie.Domain = Common.Business.Domain;

        // 
        accountCookie.HttpOnly = true;
        pwd512Cookie.HttpOnly = true;
      }

      if ( saveCookieForAMonth.HasValue && saveCookieForAMonth.Value ) {
        accountCookie.Expires = DateTime.Now.AddDays( 30 );
        pwd512Cookie.Expires = DateTime.Now.AddDays( 30 );
      }
      Response.Cookies.Add( accountCookie );
      Response.Cookies.Add( pwd512Cookie );
```

In client side, the following code always give me _undefined_:
```
Cookies.get('account.id')
```

Can anyone give me some adivice?   
Thank you very much!

**Comment by carhartl** [comment]
Yes, `HttpOnly` makes the cookie inaccessible for client-side scripting.
