### ISSUE TITLE
Uncaught TypeError: jQuery(...)

### ISSUE THREAD

**Issue by Sebazz** [js-cookie/js-cookie#53]
Hi guys i have problem with yours  jquery script. I am using jquery 1.11.1:

src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">
type="text/javascript" src="media/js/jquery.cookie.js">
type="text/javascript" src="media/js/sandblind-cookie.js">

Sandlind-cookie.js : 

```javascript
$(document).ready(function(){
// Sprawdzamy czy użytkownik wcześniej nie wybrał wersji dla niedowidzących
var cookiesSandBlind = $.cookie("SandBlindPIS");
if(cookiesSandBlind == "true") {
	$("body").addClass("sand-blind");
};
$(".mobutton").click(function(){
	$(".mobutton").addClass("clicked");
	$("body").addClass("sand-blind");
	$.cookie()("SandBlindPIS", "true");
  });


$(".mobutton.clicked").click(function(){

	$(".mobutton.clicked").removeClass("clicked");
	$("body").removeClass("sand-blind");
	$.removeCookie('SandBlindPIS');
});


});
```

And while i run my page i have got error:

Uncaught TypeError: jQuery(...).tokenInput is not a function
Uncaught TypeError: $.cookie is not a function

how can i solved it ?

**Comment by FagnerMartinsBrack** [comment]
> $.cookie()("SandBlindPIS", "true");
> $.removeCookie('SandBlindPIS');

1. [jQuery `$` was removed in version 2](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0), there's no `$.cookie` or `$.removeCookie` anymore.
2. There's no such API that calls `$.cookie()("SandBlindPIS", "true");` as a function.

I suggest asking questions about usage [on stackoverflow](http://stackoverflow.com/questions/ask) under the tags [jquery-cookie](http://stackoverflow.com/questions/tagged/jquery-cookie) and [js-cookie](http://stackoverflow.com/questions/tagged/js-cookie). There's a lot of people that know how to help better there.

**Comment by Sebazz** [comment]
Thank you for reply i understand it :) but why i have still problem with:

Uncaught TypeError: jQuery(...).tokenInput is not a function

?

**Comment by carhartl** [comment]
`tokenInput()` seems to be a different jQuery plugin that is unrelated to cookie. Make sure you include that plugin in order to make that function available.

**Comment by carhartl** [comment]
Quickly googling turned up http://loopj.com/jquery-tokeninput/

**Comment by Sebazz** [comment]
Thanks a lot :+1: You are my master :+1:
