### ISSUE TITLE
s.replace(/(%[0-9A-Z]{2})+/g, decodeURIComponent) error

### ISSUE THREAD

**Issue by chenlong07253** [js-cookie/js-cookie#530]
![image](https://user-images.githubusercontent.com/16698038/63917343-0673a900-ca6d-11e9-925f-ea893ae58424.png)
你好，我们在用js-cookie的时候发现一个兼容问题，我们的后端是.net，编码后的字符串是小写， js取不到相应的cookie。

Hello, we found a compatibility problem when using js-cookie. Our backend is. net, the encoding string is lowercase, JS can not get the corresponding cookie.

"%e5%9c%a8%e5%b8%8c%e6%9c%9b%e7%9a%84%e7%94%b0%e9%87%8e%e4%b8%8a".replace(/(%[0-9A-Z]{2})+/g, decodeURIComponent)

**Comment by carhartl** [comment]
In case you want to read a cookie that has been provided by some server-side web framework you may need to use a custom (read) converter: 

https://github.com/js-cookie/js-cookie/blob/master/README.md#read

It is impossible for us to ensure compatibility with the many different web frameworks out there, instead we chose to be RFC 6265 compliant:

https://github.com/js-cookie/js-cookie/blob/master/README.md#encoding

Converters allow to divert from that encoding strategy and provide a custom decoder, and encoder, being compatible with your backend.

**Comment by chenlong07253** [comment]
Thank you for your explanation.

**Comment by carhartl** [comment]
@chenlong07253

This is now fixed in v3 and we support such lowercase url encoded cookie values!

**Comment by carhartl** [comment]
(I only realized now that this is the same as #466...)
