### ISSUE TITLE
Catching "Failed to read the 'cookie' property from 'Document'"

### ISSUE THREAD

**Issue by mcmimik** [js-cookie/js-cookie#531]
If the script is executed inside an iframe with a `sandbox` attribute, it can throw an error:

> Stack: Error: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

**test.html**
```
<iframe src="iframe.html" sandbox="allow-scripts"></iframe>
```

Script inside **iframe.html** sufficient to reproduce the error:
```
document.cookie;
```

Possible solution: replace this check in `get` and `set` functions:

```
if (typeof document === 'undefined') {
  return;
}
```

by this:

```
try { document.cookie; } catch (e) { return; }
```

**Comment by AndreyYevtukhov** [comment]
I've caught similar errors:
`Failed to read the 'cookie' property from 'Document': Access is denied for this document.`

**Comment by FagnerMartinsBrack** [comment]
I would appreciate having a PR with a failing test that reproduces this exact error in a sandboxed iframe. Wanna do it @AndreyYevtukhov @mcmimik?

**Comment by mcmimik** [comment]
I'm on vacation and did not write tests before, so probably no. But I can try in a month.

**Comment by carhartl** [comment]
Why would you execute/load the script when having explicitly sandboxed the iframe and thus expecting it to not work?

Asked differently: if we were to catch the error and swallow it silently, how would a developer know that she had *accidentally* sandboxed the iframe?

**Comment by carhartl** [comment]
That being said, I believe it's up to the developer adding `allow-same-origin` to the `sandbox` attribute of an iframe if she wants to use this lib (cookies).

**Comment by bigb06** [comment]
I'm having quite the same error but no iframe here:
Failed to read the 'cookie' property from 'Document' : Access is denied for this document

It happens only on chrome and I can't reproduce the problem : disable cookies, privacy sandbox, ...
 I just log error since few days and it happens on chrome 91.x with android 8 to 11.

**Comment by vinaynair39** [comment]
@bigb06 Were you able to find the solution to this?

**Comment by bigb06** [comment]
No I can't find a way to catch this properly

**Comment by MAfzalKhan1997** [comment]
any update on this ? I'm facing same.
