### ISSUE TITLE
2.2.1 function set has TypeError problem

### ISSUE THREAD

**Issue by hotNoder** [js-cookie/js-cookie#532]
line 95:
`stringifiedAttributes += '=' + attributes[attributeName].split(';')[0];`

code:
`cookie.set('a', 1, { 'max-age': 100 });`

error:
TypeError: attributes[attributeName].split is not a function

**Comment by carhartl** [comment]
Please see https://github.com/js-cookie/js-cookie/issues/526#issuecomment-521235119, you need to stick to the public, documented api and use `expires`.
