### ISSUE TITLE
Support max-age attribute instead of expires

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#534]
Now that we dropped support for old IEs we can start to support `max-age`. Should we replace expires or support both?

**Comment by FagnerMartinsBrack** [comment]
What's the difference to js-cookie library and developers using it? What's the value of one or the other?

**Comment by carhartl** [comment]
@FagnerMartinsBrack 

As far as I remember `expires` was somewhat deprecated, `max-age` the preferred attribute. We had to hold on to `expires` because old IEs didn't support `max-age`. I wanted to double check that.

I believe, since we will be releasing a new mayor version, we wouldn't need to support both, and instead drop `expires` in favor of `max-age`. So no additional code eventually.

**Comment by FagnerMartinsBrack** [comment]
Why `max-age` vs `expires` would reduce the amount of code? Wouldn't the lib still have to support passing a `Date` instance?

**Comment by carhartl** [comment]
The value for `max-age` is a number (timestamp), so writing the value becomes slightly simpler (no `toUTCString()`).

**Comment by carhartl** [comment]
And, the expected value is this:

>Number of seconds until the cookie expires

If we make the api accept seconds right away we would also not need the code to compute the days.

**Comment by carhartl** [comment]
Anyway, I couldn’t find anything in the RFC regarding `expires` being deprecated or discouraged. It seems that `max-age` is just newer and slightly easier to use. 

Shall we close this? We support arbitrary cookie attributes already of the form `"key": "value"`, so a developer wishing to use `max-age` could do so: `"max-age": "12345678"`.

I certainly wouldn’t want to support both attributes.

**Comment by FagnerMartinsBrack** [comment]
I agree to keep the existing API as it is for the same reasons. One of the features of js-cookie is its stability. It doesn't seem to make much sense to do this. However, if we want to change the handling of `max-age` it has to be done now, otherwise it will become a backwards compatible issue after v3

**Comment by carhartl** [comment]
Hmmm, `max-age` is seductively simpler, both in implementation as well as usage. Since the value is the amount of seconds until the cookie expires, we wouldn't even need to support both a number and a date. Just give us the cookie's expected age in seconds as a number, that's it. We wouldn't even have to have any extra code handling this attribute any longer. We should replace `expires` with this, for all its simplicity, _in v3_.

**Comment by FagnerMartinsBrack** [comment]
If the time is relative to the user timezone then I agree. Problem is if the browser assumes it's relative to UTC, then things get messy.

**Comment by carhartl** [comment]
The disadvantage of `Expires` is exactly that: it isn’t relative and the time on a server vs client may not be synchronized. Max age however is relative and timezones and all that do not even matter.


Another advantage of max age is that it will result in less bytes to be sent over the wire.

**Comment by carhartl** [comment]
>will result in less bytes to be sent over the wire

...in terms of the cookie string. It seems that the library itself will also be slightly smaller, but I need to see.

**Comment by FagnerMartinsBrack** [comment]
@dingcaiying can you explain the thumbs down reaction?
<img width="774" alt="Screen Shot 2019-10-02 at 12 55 42 PM" src="https://user-images.githubusercontent.com/835857/66014937-fdff0a00-e513-11e9-8b7c-e4f8c7b39a40.png">

**Comment by dingcaiying** [comment]
@FagnerMartinsBrack nope. let me remove it.

**Comment by carhartl** [comment]
I guess that means “you should be supporting max-age”.

**Comment by jduhls** [comment]
"max-age" integrates with OAuth's "expires_in" nicely too.

RE: https://tools.ietf.org/html/rfc6749#section-5.1

**Comment by carhartl** [comment]
I was about to send a PR for this, but it turns out that even recent versions of Internet Explorer do not support `max-age` _as part of the `document.cookie` api_. I probably misunderstood/misinterpreted the MDN compatibility table [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), which is all about the `Set-Cookie` header. So IE starting with version 9 does understand a cookie header with `Max-Age`, but that's it.

Here's another extensive cookie compatibility reference table with proof: https://inikulin.github.io/cookie-compat/

A developer in need of `max-age` can always do: `Cookies.set('foo', 'bar', { 'max-age': '3600'})`

Closing 🤕

**Comment by carhartl** [comment]
I'll keep the `max-age` branch around for a while...

**Comment by bi-kai** [comment]
Both for adults.
Make it easy to use.
