### ISSUE TITLE
Broken direct download link in the README.md

### ISSUE THREAD

**Issue by ckhatton** [js-cookie/js-cookie#542]
I just thought I'd point out that the direct download link in the [README.md](https://github.com/js-cookie/js-cookie/blob/master/README.md) is broken.

![bitmoji](https://render.bitstrips.com/v2/cpanel/a3197293-3ed6-4bfc-93dd-3835ec8146b1-922300ab-c8f4-42cd-91cd-4ba456e3400d-v1.png?transparent=1&palette=1&width=246)

**Comment by carhartl** [comment]
I think we should no longer encourage people to include the source like this.

**Comment by ckhatton** [comment]
😶 ... 😪

**Comment by carhartl** [comment]
Ah, now I understand. The link is broken at the moment because it is pointing to the (new) `mjs` file at the latest tag, and this will be fixed when we do the first release of v3.

**Comment by carhartl** [comment]
c498f784d3cb19b134003a040778bd958bd8574c
