### ISSUE TITLE
`+` in value of JSON cookie is removed from request.cookies in rails

### ISSUE THREAD

**Issue by lifeiscontent** [js-cookie/js-cookie#543]
when using a cookie in JSON format, if there is a value that uses a `+` in the string, it gets removed when the cookie is parsed in rails using `request.cookies`

**Comment by carhartl** [comment]
This sounds like a problem in Rails, not this library. I‘m not entirely sure, but often in web frameworks a `+` is interpreted and thus decoded as whitespace (thus “removed”). You could try using a converter.

**Comment by carhartl** [comment]
There‘s this: https://github.com/carhartl/jquery-cookie/issues/13#issuecomment-4207083

What I don’t understand is: we should be encoding `+` as `%2B`, so how do you end up with a `+` in your cookie? Could you please provide a test case?

**Comment by carhartl** [comment]
Ah, I found it: https://github.com/js-cookie/js-cookie/blob/da65bd32bdad336071fdd787045337ccfd715a59/test/encoding.js#L215

Because `+` is allowed according to RFC 6265 we‘re not encoding it.

**Comment by carhartl** [comment]
Nothing we can do, but you have two options if you have to have a plus in your cookie value (JSON or not):

1. Bypass the decoding in Rails, and retrieve the raw value:
https://stackoverflow.com/questions/33479176/how-to-get-raw-url-encoded-cookie-value-in-rails

2. Implement an encoder (information in the readme) that encodes pluses in a particular way, in conjunction with a decoder that knows how to turn back the encoded plus on the Rails side.

**Comment by carhartl** [comment]
Third option: if you’re absolutely sure that your cookie values will never contain whitespace, you could revert that into `+` again when reading a cookie and before doing anything with it.

**Comment by lifeiscontent** [comment]
@carhartl thanks for your suggestions! 👍
