### ISSUE TITLE
Please update import example

### ISSUE THREAD

**Issue by redaxmedia** [js-cookie/js-cookie#544]
This should be used in the `README` instead of the outdated dist approach:

```
import Cookies from 'js-cookie';
```

**Comment by carhartl** [comment]
Could you point me to exactly what you’re referring to? I can’t follow. A pull request would also be highly appreciated.. thanks!

**Comment by redaxmedia** [comment]
I am using this library inside a single page application and the current import example is just missleading from my point of view. There is no dist folder published in NPM also.

https://github.com/js-cookie/js-cookie#es-module
```
import Cookies from './node_modules/js-cookie/dist/js.cookie.mjs'
```

**Comment by carhartl** [comment]
We're only providing a single default export.. not sure what I'm missing, but how would `*` work?

https://github.com/js-cookie/js-cookie/blob/0d16266152377b421a6951ea630c1b1e2b7732af/src/js.cookie.mjs#L144

There's currently work in progress for v3, supporting ES modules right away, and what you're looking at might be the documentation at master (which doesn't work with v2).

**Comment by carhartl** [comment]
As the readme tries to advise, you should take a look at the documentation for the latest release, which is here: https://github.com/js-cookie/js-cookie/tree/latest#readme

**Comment by redaxmedia** [comment]
Sorry, I did read that hint. If possible, create an `index.js` to export the internal dist file:

```js
export { Cookie } from './dist/js.cookie.mjs';
```

So we can use

```
import Cookies from 'js-cookie';
```

**Comment by carhartl** [comment]
Ah, thanks, that never seemed right to me, going to look into this..

**Comment by carhartl** [comment]
Not sure how this is going to work! The idea was that in the package definition we have a `browser` property (instead of `main`) pointing to the UMD variant of this library, for maintaining full compatibility. And then there’s a `module` property, pointing to the ES module distribution — this is what both webpack and rollup advise going forward with ES modules until there’s going to be a standardized approach — so we’re supporting ES module in this way. 

The index.js that you’re proposing would only work when used with `main`/`browser`?

**Comment by carhartl** [comment]
Ah, no.. the index.js is supposed to sit in the root.

**Comment by redaxmedia** [comment]
I never worked with `release-it` but you might use their hooks or whatever to create or copy the `index.js` to the root.

A tooling like this comes with the trade off that you might lose the control of the internals and things that cannot be configured.

```
"hooks": {
    "after:bump": "npm run dist-that-also-copies-index""
  }
```

In addition: does your build step create a file that contains `module.exports` ?

**Comment by carhartl** [comment]
This could become useful: https://www.npmjs.com/package/create-index

**Comment by carhartl** [comment]
Nice... I've set up a little webpack example, and using `module` in the package definition seems to be all we need.

```
import Cookies from 'js-cookie'
```

works without adding another `index.js` file at all. I'm going to adapt the documentation and might also add the example to the repo.

**Comment by carhartl** [comment]
..but because we‘re using both the `browser` and `module` properties in the package.json, webpack uses the former for bundling:

https://github.com/webpack/webpack/blob/86a2829147c0ae78797b48c121bf5e11a8151562/lib/WebpackOptionsDefaulter.js#L348

**Comment by carhartl** [comment]
Tested with the following `webpack.config.js` and it works the same, this time picking up the ES module dist file:

```javascript
module.exports = {
  resolve: {
    mainFields: ['module', 'main']
  }
}
```

**Comment by carhartl** [comment]
@redaxmedia I've just released v3 as a beta, would be helpful if you find the time to try it out:

```
$ npm install --save js-cookie@beta
```

**Comment by symn** [comment]
@carhartl thanks for your work. However, when using the lib outside a bundle, in my case in a jest test, i get the following error when importing it with:

```javascript
import Cookies from 'js-cookie';
```

`Cannot find module 'js-cookie' from 'Results-test.js`

**Comment by carhartl** [comment]
@symn Could you provide a repo or code that allows for reproducing the problem?

**Comment by carhartl** [comment]
We might have to do this: https://github.com/js-cookie/js-cookie/issues/544#issuecomment-535440792

**Comment by carhartl** [comment]
In any case I guess I will soon find out anyway: #573

**Comment by carhartl** [comment]
@symn Could you try again with the latest beta? I've just bumped it and it might provide a fix for your problem.

**Comment by symn** [comment]
> @symn Could you try again with the latest beta? I've just bumped it and it might provide a fix for your problem.

Sorry for the late response (christmas holidays). 

I tried version `3.0.0-beta.3` and it works now! Great, thx for your work!
