### ISSUE TITLE
How I can set expire time in minutes and hours?

### ISSUE THREAD

**Issue by royallife88** [js-cookie/js-cookie#545]
I want to set cookie for specific time but there is option for expiry in days. I want to set just for just few minutes? please help

**Comment by carhartl** [comment]
As documented `expires` can be an instance of `Date`.

https://github.com/js-cookie/js-cookie/blob/latest/README.md#expires

**Comment by carhartl** [comment]
You can also pass a fraction that would equal the amount of minutes: `1 / 24` would make the cookie expire after 1 hour.

**Comment by carhartl** [comment]
PS: An answer to this is also in the FAQs.

https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-make-the-cookie-expire-in-less-than-a-day
