### ISSUE TITLE
Missing documentation about JSON 

### ISSUE THREAD

**Issue by tom-korec** [js-cookie/js-cookie#547]
**Describe the bug**
Documentation about JSON, which is here https://www.npmjs.com/package/js-cookie is missing in readme at Github.

**Comment by carhartl** [comment]
We’ve removed built-in json support in v3, so that’s expected. Please see the change log of the v3 beta release for alternatives: https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-beta.0

**Comment by carhartl** [comment]
The `latest` Tag should point to the last v2 release instead of the v3 beta though.

**Comment by carhartl** [comment]
Fixed... looking at master, you're going to see the latest documentation, which might be work in progress, and this point reflects the ongoing work for the upcoming v3 release. Looking at "latest" however, you're getting the documentation referring to the latest release (2.2.1), which contains what you expect:

https://github.com/js-cookie/js-cookie/tree/latest
