### ISSUE TITLE
malformed URI sequence

### ISSUE THREAD

**Issue by flanderboy** [js-cookie/js-cookie#55]
Hello,
I used the script but I get this error

malformed URI sequence...
cookie = converter && converter(cookie, name) || cookie.replace(rdecode, decodeURIComponent);

I'm writing a cookie in this way
Cookies.set('screech', 'hide', {expires: 1});

Stefano

**Comment by FagnerMartinsBrack** [comment]
That error occurs while decoding the cookies.

Which version are you using?
Can you please post the contents of your `document.cookie`?

**Comment by flanderboy** [comment]
Hello,
I do not decoded the cookie. I checked only if there is.

if (!Cookies.get('screech')) {

}

**Comment by FagnerMartinsBrack** [comment]
> I do not decoded the cookie.

The decode is done automatically when you call `Cookies.get()`. The error probably represents another cookie with an invalid format.

I need the following information to understand which cookie it is:

1. Open the developer console
2. Type `document.cookie`
3. Post the returning data.

Example below:

![example](https://cloud.githubusercontent.com/assets/835857/8411129/a7b81cbc-1e58-11e5-96bb-efa337383c2d.gif)

**Comment by flanderboy** [comment]
"PHPSESSID=4h2skf7q3bh5ucvguni41918k0; screech=hide"

**Comment by FagnerMartinsBrack** [comment]
Are you sure what you posted is the content of `document.cookie` when the error happens?

**Comment by flanderboy** [comment]
yes

**Comment by FagnerMartinsBrack** [comment]
I tested the following code with [the master version pf js.cookie.js](https://github.com/js-cookie/js-cookie/blob/76932e33d9b4a50789c2edb0a1aa9657fde9b829/src/js.cookie.js) and everything is fine, there's no error:

```html
<!DOCTYPE html>
<html>
	<head>
		<script src="js.cookie.js"></script>
	<head>
	<body>
		<script>
			window.onload = function() {
				document.cookie = "PHPSESSID=4h2skf7q3bh5ucvguni41918k0; screech=hide";
				Cookies.set( "screech", "hide", {
					expires: 1
				});
				if ( !Cookies.get( "screech" ) ) {
					alert( "no cookie!" );
				}
			};
		</script>
	</body>
<html>
```

**Comment by FagnerMartinsBrack** [comment]
My assumption is that there is an invalid cookie that is being set somewhere and breaking js-cookie. I need to understand how all your cookies are setup in order to find the root cause of the problem and provide a [converter](https://github.com/js-cookie/js-cookie/tree/76932e33d9b4a50789c2edb0a1aa9657fde9b829#converter) code to workaround it. For that I need the `document.cookie` result at the time the error happens.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.

We can open this again if you provide a simplified example reproducing the error, as documented in the [CONTRIBUTING.md](https://github.com/js-cookie/js-cookie/blob/76932e33d9b4a50789c2edb0a1aa9657fde9b829/CONTRIBUTING.md#issues) file.
