### ISSUE TITLE
Internet Explorer 11 - localhost as domain

### ISSUE THREAD

**Issue by mrarnolds** [js-cookie/js-cookie#552]
**Describe the bug**
If you provide *localhost* as the domain in Cookies.set, it will fail for Internet Explorer 11.

**To Reproduce**
`Cookies.set('my-cookie', 'my-cookie-value', { domain: 'localhost' });`
`var value = Cookies.get('my-cookie');`
`if (!value) { alert('Could not read the cookie value'); }`

**Comment by carhartl** [comment]
Please see https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762
