### ISSUE TITLE
SameSite=Lax/Strict not working in Chrome

### ISSUE THREAD

**Issue by nolimitdev** [js-cookie/js-cookie#554]
**Describe the bug**
It is not possible to set this cookie `document.cookie = "foo=bar; SameSite=Lax"` even though Secure attribute is added `document.cookie = "foo=bar; SameSite=Lax; Secure"` which is required since future Chrome v80.  Now in Chrome v78 it is not working - cookie is rejected at all. Firefox sets cookie OK. In chrome is possible to set via JavaScript only SameSite=None. I think it is not possible to fix but it should be mention in doc that is not reliable in all browsers including top used Chrome.

**Comment by EddieOne** [comment]
What is the solution?
