### ISSUE TITLE
`Cookies(key,value,option)` does not work in which version ?

### ISSUE THREAD

**Issue by occultskyrong** [js-cookie/js-cookie#557]
**Describe the bug**

`Cookies(key,value,option)` does not work .
But , `Cookies.set(key,value,option)` it's worked

In `2.2.0` i use `Cookies(key,value,option)` it's work
I want to know which version of the update .

**To Reproduce**
none

**Expected behavior**
none

**Screenshots**
none

**Desktop (please complete the following information):**
none

**Smartphone (please complete the following information):**
none

**Additional context**
none

**Comment by carhartl** [comment]
You‘re using an "accidental feature" that was never part of the public api and was later fixed. 

I strongly recommend to stick to using public, documented APIs.

For getting a cookie, use `get()`.

See here as well: https://github.com/js-cookie/js-cookie/issues/523#issuecomment-519838019

**Comment by occultskyrong** [comment]
thx
