### ISSUE TITLE
Allow an encoder to be provided for cookie name

### ISSUE THREAD

**Issue by Aaronius** [js-cookie/js-cookie#560]
**Is your feature request related to a problem? Please describe.**
I would like to set a cookie with custom encoding for the cookie name. In our particular case, I don't want the name to be encoded at all (it was previously encoded elsewhere in our system).

**Describe the solution you'd like**
Allow an encoder to be provided for the cookie name, similar to how an encoder can be provided for the cookie value.

**Describe alternatives you've considered**
In our particular case, it would involve decoding our (already encoded) cookie name before using js-cookie to set the cookie. If we don't decode it before using js-cookie to set the cookie, the cookie name will be double-encoded.

**Additional context**
None.

**Comment by Aaronius** [comment]
I plan on writing a pull request for this change. It would be helpful to know if you're open to the idea and, if so, if you have any opinion on the API. To keep it most in line with what you already have, I was going to split `withConverter` into two different methods: `withNameConverter` and `withValueConverter`. Thanks for the great library and any attention you give here.

**Comment by Aaronius** [comment]
After thinking about this some more, I think the cleaner API is this:

```
Cookies.withConverter({
  name: {
    read(name) { },
    write(name) { }
  },
  value: {
    read(name, value) { },
    write(name, value) { }
  }
})
```

If any of those properties are left off, the defaults would be used.

**Comment by FagnerMartinsBrack** [comment]
@carhartl This is hunting us now. At the time we decided to only return `value : fn(value, name)` for the converters so that devs could override the `value` converter with a new decoding/encoding, but it didn't allow the `key` to be overridden.

The assumption was that the name wouldn't need messing around.

@Aaronius can you give us an example in which circumstance you would not like to have the key encoded? Be aware that if you don't, the cookie name will contain invalid characters which may break in certain browsers.

**Comment by Aaronius** [comment]
Sure. We have a library hitting a third-party server and the third-party server responds with a response body that contains, among other things, keys and values that our library needs to write as first-party cookies (since the third-party server can't write first-party cookies itself). Both the keys and values have been pre-encoded by the server. It would take a lot more to explain why keys and values have been pre-encoded by the server, but that's what's going on. We're re-thinking some of our strategy, which may cause us to not require the functionality requested in this issue. In the meantime, we've [stripped out the encoding/decoding of js-cookie for our purposes](https://github.com/adobe/alloy/blob/3da1c3bc8789905aae0c9f83dc39957269251417/src/utils/cookieJar.js).

**Comment by FagnerMartinsBrack** [comment]
@Aaronius If that's server application-specific misbehavior then I wouldn't take that as evidence to change the library. However, if it's server-implementation misbehavior, then we might consider it to make sure js-cookie can integrate with all servers.

**Comment by Aaronius** [comment]
I'm not sure what you mean by "misbehavior". Both our JavaScript and our server are behaving as designed. Our design is that the server encodes keys and values before sending them to our library and our library then writes the cookies without any additional encoding. The only way we can do that while using js-cookie is to remove/modify js-cookie's encoding/decoding behavior for both the cookie key and value.

**Comment by FagnerMartinsBrack** [comment]
> I'm not sure what you mean by "misbehavior".

What I'm asking is if this is behavior specific to Adobe's library or is this a problem with how a given server implementation deal with cookie name encoding.

We got some community feedback about servers like Apache, Tomcat, Rack, etc. misbehaving on how they encode the cookie values, for example, `+` for spaces in PHP instead of percent-encoding. That's why I created the [SERVER_SIDE.md](https://github.com/js-cookie/js-cookie/blob/master/SERVER_SIDE.md) file.

However, I didn't see evidence so far (either my testing or community reports) that servers misbehave in regards to the cookie name encoding. Is that what's happening with you?

The cookie name encoding as it is is necessary because RFC 6265 does not allow the following characters in the cookie name: `( ) < > @ , ; : \\`... etc. ([See the tests](https://github.com/js-cookie/js-cookie/blob/ac337a9432182c02cc291b13798c0a1fbfa0e3a4/test/encoding.js#L545-L1081)). Therefore, js-cookie encodes and decodes them using percent-encoding.

**Comment by Aaronius** [comment]
The behavior I'm describing is specific to the contract we've set up between Adobe's library and Adobe's server. It is entirely in the application code space and not in the HTTP server implementation.

**Comment by FagnerMartinsBrack** [comment]
I see @Aaronius, thanks for the response. In that case, do you reckon the fix could be on your side instead? I'm worried about kicking off js-cookie API changes like this if it's possible to try an application-specific change first, as you said: 

> We're re-thinking some of our strategy, which may cause us to not require the functionality requested in this issue. In the meantime, we've stripped out the encoding/decoding of js-cookie for our purposes.

**Comment by Aaronius** [comment]
> The cookie name encoding as it is is necessary because RFC 6265 does not allow the following characters in the cookie name: ( ) < > @ , ; : \\... etc. (See the tests). Therefore, js-cookie encodes and decodes them using percent-encoding.

Understood. In our case, Adobe's server runs keys and values through this same encoding process, then sends the encoded keys and values to Adobe's library through the response **body**, then the library writes the cookie for the key-value pair (which has already been encoded by the server and therefore should not be re-encoded on the client).

**Comment by FagnerMartinsBrack** [comment]
Now I get the problem.

You return the cookie name in a response body and then when js-cookie receives it, it gets reencoded twice. In that case, would passing the unencoded values in the body work? It's not necessary to do any additional encoding for HTTP response bodies to be transferred over the wire correctly...

**Comment by Aaronius** [comment]
> In that case, would passing the unencoded values in the body work? It's not necessary to do any additional encoding for HTTP response bodies to be transferred over the wire correctly...

We're still in discussions on that. We understand the encoding is not necessary for response bodies. In our case, there are benefits to the server doing the encoding, but it's a much deeper discussion that's specific to our objectives. There are also downsides. I believe tomorrow I'll know our final decision on how we'll move forward.

I understand your hesitancy to introduce these changes since the general need for modifying encoding of cookie names is probably rare. If we continue with having the server encode the key-value pairs and you decide not to implement this in js-cookie, we'll likely continue to use our stripped down version of js-cookie that doesn't do any encoding. We'd prefer to use an official version of js-cookie in this case, but it's understandable if we can't.

**Comment by carhartl** [comment]
This sounds like a very application specific case, as mentioned, and as long as we do not get a whole lot of +1s for the time being I would like to refrain from adding this extra complexity.

**Comment by Aaronius** [comment]
That's understandable. I probably would make the same decision to be honest. In the end, we've decided to take a different approach for our project so we no longer need this functionality. I'll close this issue and if someone else needs the functionality maybe it can be reconsidered.
