### ISSUE TITLE
2.2.1 Cannot set cookie with attributes

### ISSUE THREAD

**Issue by mtjn** [js-cookie/js-cookie#561]
**Describe the bug**
`Cookies.set(key, value)` works. `Cookies.set(key, value, attributesObj)` doesn't work (no cookie is set, and no error is logged/thrown).

The problem also happens when setting default values via `Cookies.defaults = {attributesObj}`

**Expected behavior**
E.g. `Cookies.set('cookieId', 'cookieValue', {secure: true, httpOnly: true})` should work.

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: Chromium
- Version: 78.0.3904.108 snap 64-bit

**Comment by carhartl** [comment]
Using `httpOnly` you will not see the cookie after you‘ve written it in the client.

**Comment by carhartl** [comment]
It will only be transmitted in requests to the server.

**Comment by carhartl** [comment]
> The HTTPOnly cookie attribute can help to mitigate this attack by preventing access to cookie value through Javascript.

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by mtjn** [comment]
Thank you! Sorry I didn't know that. Setting `secure: true` also seems to cause the cookie to be hidden. Is this intentional, or am I not understanding something?

**Comment by carhartl** [comment]
I think with `secure` it might be the same when testing on `http://localhost`

**Comment by carhartl** [comment]
PS: inquiries about missing cookies when using `httpOnly` come up frequently here, so you’re not alone. I think it’s time for adding it to the FAQs :)
