### ISSUE TITLE
Consider droping string casting

### ISSUE THREAD

**Issue by nreynis** [js-cookie/js-cookie#568]
There's two explicits `String` conversion:
https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.mjs#L33
https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.mjs#L38

You should consider removing them:
* the same argument you made for dropping JSON support can be made here: users can just cast their objects to string themselves before feeding it to the library
* internally `decodeURIComponent` already do string conversion, so this have effectively no effect and is entirely backward compatible: [language spec](https://www.ecma-international.org/ecma-262/6.0/#sec-decodeuricomponent-encodeduricomponent), [passing tests on all environments](https://github.com/nreynis/js-cookie/pull/1)
* remove a few bytes from the library weight

**Comment by carhartl** [comment]
They might be from a time when we didn‘t care what is being passed as value, `null` might have produced an error. Good catch.

**Comment by carhartl** [comment]
If I do this change now, you'll have to update #566 I guess...
