### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by schroef** [js-cookie/js-cookie#569]
The examples in this repo are not working. It has wrong paths and looks messy

**Comment by carhartl** [comment]
What exactly isn't working?

When I cd in the `examples/webpack` and run `npm install && npm start` a server starts up, and I can see in a browser that a cookie is being written. All this example is supposed to do is showcasing how to use the ES module with webpack. 

Also, what exactly do you feel is messy? The code in the only example we have, for webpack, is run through prettier, thus at least we're ensuring a consistent formatting with the rest of the codebase.

How would you improve it?

**Comment by carhartl** [comment]
If you're looking for other examples for how to use the library, there's the readme.
