### ISSUE TITLE
Implement an automatic release process

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#57]
Currently, everything is done manually, I just [document the steps](https://github.com/js-cookie/js-cookie/tree/76932e33d9b4a50789c2edb0a1aa9657fde9b829#manual-release-steps).

Here are a few things that should be fixed after a proper release process:
- <strike>[Minification for jsDelivr](https://github.com/jsdelivr/jsdelivr/pull/5507#issuecomment-116729066)</strike> (jsDelivr has [on-demand minification now](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-339047451))
- <strike>[Document the CDN file](https://github.com/js-cookie/js-cookie/pull/46#issuecomment-113061185)</strike> (We're documenting [jsDelivr](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-340131636) for now)
- [Cleanup the README by removing the manual steps](https://github.com/js-cookie/js-cookie/tree/76932e33d9b4a50789c2edb0a1aa9657fde9b829#manual-release-steps)
- [Play nice with Django by releasing the minified file on NPM](https://github.com/js-cookie/js-cookie/issues/66)
- [Request to add the minified version in bower](https://github.com/js-cookie/js-cookie/issues/73)
- [Create a `js.cookie.debug.js` file for sanity checks regarding wrong domain](https://github.com/js-cookie/js-cookie/issues/86) (Maybe use `drop_console` option from UglifyJS?)
- [Create a `js.cookie.debug.js` file for sanity checks regarding maximum cookie size](https://github.com/js-cookie/js-cookie/issues/88)

Pull request: #82

**Comment by carhartl** [comment]
Just saw this, maybe worth it to take a closer look: https://medium.com/@webprolific/using-release-it-60b96515c073

**Comment by FagnerMartinsBrack** [comment]
[Added jsDelivr CDN to the README](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-340131636) because now they support on-demand minification.
The bullet points related to the CDN from the PR description have been removed because of that.

**Comment by FagnerMartinsBrack** [comment]
Update: Haven't had time to continue on [js-cookie-release](https://github.com/js-cookie/js-cookie-release), be advised this may take a long time to be implemented. Automate a release with proper tests to make sure all the Git commits always work fine seem to be harder than what I thought.

**Comment by FagnerMartinsBrack** [comment]
It's been too long since this issue was opened and the last commit on https://github.com/js-cookie/js-cookie-release was one year ago. If somebody wants to take https://github.com/js-cookie/js-cookie-release to help to build a release process or know a cheaper way of doing this (without adding 9999999 dependencies) feel free to get in touch.

Closing this until further notice.
