### ISSUE TITLE
Simplify read conversion behavior

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#571]
See https://github.com/js-cookie/js-cookie/pull/566/files#r354517248

Having made the default converter accessible opens up room for writing more wholesome converters without relying on internals. So far there was a mechanism in place that allowed to write a converter that only acts on particular keys and otherwise forwards the value to the standard converter (signaled by a falsy return value). This can now be implemented within a custom converter altogether:

```js
var customReadConverter = (value, key) => {
  if (value === 'special') {
    return value.toUpperCase()
  }
  return Cookies.rfc6265Converter.read(value)
}
```

The following line 
https://github.com/js-cookie/js-cookie/blob/8454f234ae026a2ec1e4f3ed780efc7b61015bd2/src/js.cookie.mjs#L97

is going to simplified to:
```js
jar[name] = converter.read(cookie, name)
```

**Comment by FagnerMartinsBrack** [comment]
Early return, less bytes and no implicit return FTW 👍 
This v3 is getting better and better xD
