### ISSUE TITLE
Replace nodeunit + qunit with jest

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#573]
Maybe.

nodeunit is no longer maintained, and generally I would like not to have two different test frameworks in such a small project.

**Comment by carhartl** [comment]
Or Jasmine (if it allows to test in node), since I’d prefer even more to not put anything from Facebook in here.

**Comment by carhartl** [comment]
Might provide an interesting avenue for testing cookie read/write: https://github.com/jsdom/jsdom/blob/master/README.md#cookie-jars

**Comment by carhartl** [comment]
Plus there's https://www.npmjs.com/package/jest-environment-browserstack

**Comment by carhartl** [comment]
Check https://github.com/js-cookie/js-cookie/issues/544#issuecomment-564925761

**Comment by FagnerMartinsBrack** [comment]
The reason the lib is using QUnit is to allow the test to run in a browser environment using an HTML file which gives access to the global `document`. I've tried to use Jest a long time ago but it failed to run in a browser environment which is much easier with QUnit.

Maybe things have changed since then...

**Comment by FagnerMartinsBrack** [comment]
Also, QUnit allows us to specify the number of expected assertions, while Jest doesn't have such functionality (if you miss an "expect", Jest assume the test is passing)

**Comment by carhartl** [comment]
¯\_(ツ)_/¯

**Comment by FagnerMartinsBrack** [comment]
Closing because Jest still can't run in a browser environment? :D

**Comment by carhartl** [comment]
I‘m happy to not spent time on this, but I’m leaving a little more context here.

Besides having two test frameworks side-by-side, there are other flaws I see with our current testing approach. For instance, for any test we need go through the full build pipeline,  e.g. producing the dist for use with the qunit test html page. As such, feedback time is terribly slow. Compare that to jest’s watch mode.

There is a place for such kind of tests, but it‘s not unit, rather than something along the lines of end to end/smoke tests.

Furthermore, I don’t want to be bothered with including css for the sake of unit testing.

Generally speaking, in terms of usability, jest leaves qunit pretty much in the dust, but that’s of course more of a subjective view.

Regarding specifying the number of expectations: more often than not it’s getting in my way, when writing or adapting tests. I don’t think it’s particularly useful and it doesn’t really matter how many assertions there are, as long as code is being executed sequentially anyway. The only place where I can see it’s useful is when you’re dealing with asynchronous code and you need to ensure that a certain number of assertions have run after the asynchronous code has finished running.

Last not least, introducing jest would be the last piece of the codebase modernization puzzle, allowing us to finally remove grunt (to be replaced by rollup + jest), and thus further making working with the codebase more straightforward: at the moment, for certain development tasks there’s a mix of `npm run` tasks plus some other grunt tasks. I would like to have a single entry point (`npm run ...`) for executing development tasks.

**Comment by carhartl** [comment]
Regarding jest and browser environments: afaik by default jest runs in a `jsdom` environment; this should allow us to test with a `document` in place.

There is a solution to run jest tests in Browserstack (see earlier comment), thus browser based. There’s also an environment that allows to run tests in puppeteer. 

But I haven’t tried or spiked any of that yet, so I can’t tell whether it would suit our needs. This is why the ticket said:

>Maybe.

**Comment by FagnerMartinsBrack** [comment]
Looks like Jest could work then.

> The only place where I can see it’s useful is when you’re dealing with asynchronous code and you need to ensure that a certain number of assertions have run after the asynchronous code has finished running.

On top of that, if you use async/await that becomes unnecessary anyway. It's only useful if you use callbacks like [this test](https://github.com/js-cookie/js-cookie/blob/17b370152c5c0e7d2ac1d04cf594a248fba46bc3/test/tests.js#L152-L165).

The thing that gets in the way of not specifying the number of expectations is that the test runner assumes no expectation is a success. A test without an expectation (even if that means to assert that it throws no exception) is not a useful test at all.

**Comment by carhartl** [comment]
Btw... I tried to spike it at https://github.com/js-cookie/js-cookie/tree/spike/jest, and it turns out that at least with the jest-environment-browserstack package it wouldn't work the way we would need it: you can only specify a single browser for the environment but we'd need to run tests in serveral ones. Sticking to good old QUnit I guess :)
