### ISSUE TITLE
expires parameter set to -1

### ISSUE THREAD

**Issue by pensierinmusica** [js-cookie/js-cookie#574]
Hi,

What happens when the `expires` parameter is set to `-1` like by default?

https://github.com/js-cookie/js-cookie/blob/f1cf17d5720c7e5ab71e2a64723a6eeeb3abf7c9/src/api.mjs#L90

This option is not documented in the docs: https://github.com/js-cookie/js-cookie#basic-usage

Happy to send a PR to improve them if you like, after you provide some insights.

Thanks!

@carhartl @FagnerMartinsBrack

**Comment by carhartl** [comment]
You’ve specified that your cookie is supposed to expire one day in the past, thus it immediately expires when written.

**Comment by carhartl** [comment]
I’m sorry, it’s not a bug, it’s expected behavior. It’s the same for `-1000`, or `0`. We have no plans to to sanitize the input here.

**Comment by pensierinmusica** [comment]
> Using -1 in defaults or per-call you would have specified that your cookie is supposed to expire one day in the past, thus it immediately expires when written.

Ok, and why `-1` makes sense as a default value? What is the purpose of writing a cookie that immediately expires?

**Comment by carhartl** [comment]
It’s not a default value. Where you see it is in the api method for removing a cookie. Specifying a date in the past for expiration is the only way to practically delete a cookie.

**Comment by carhartl** [comment]
So what happens is that when you call  `Cookies.remove('foo')` the original cookie with the name "foo" is being overwritten with the one that has the expiration in the past — the outcome is that no cookie with the name "foo" exists afterwards. Technically it‘s the only way to delete a cookie.

**Comment by pensierinmusica** [comment]
@carhartl that makes perfect sense, thanks for the clarification!

What is the default value then? Can we add this info to the docs?

Cheers

**Comment by carhartl** [comment]
The default value is none, which makes a cookie a session cookie. It‘s described in the docs: https://github.com/js-cookie/js-cookie/blob/master/README.md

**Comment by pensierinmusica** [comment]
True, I overlooked that piece of information. I was searching for a "default" word, but "omitted" in this case works too. Thanks!
