### ISSUE TITLE
Align `extend` with `Object.assign`

### ISSUE THREAD

**Issue by nreynis** [js-cookie/js-cookie#578]
Now that `extend` is exported to it's own module, it can be reimported by third party code (assuming you rebundle the code directly from the source).

`extend` is in essence a loose polyfill for `Object.assign`, it should be
- renamed `assign`
- modified to work on the first argument instead of returning a new object (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Merging_objects)

This way you can more easily remove it the day you drop IE support.

**Comment by carhartl** [comment]
Yes... I agree.

**Comment by carhartl** [comment]
0f293a641844b43b6917257ae919b8c3d1a8375a
