### ISSUE TITLE
Can't set the cookie expire date more than 7 days

### ISSUE THREAD

**Issue by aungpyaekyaw** [js-cookie/js-cookie#579]
**Describe the bug**
js-cookie can't se the cookie expire date to more than 7 days using the following format .
 Cookie.set('key','value',{expires:10}) 

**To Reproduce**
1. install js-cookie
2. import Cookies from 'js-cookie';
3. Cookie.set('key','value',{expires:10}) ;
4. In web browser, the cookie will only be lived 7 days if you set greater than 7 day. It's working fine for less than 7day.

**Expected behavior**
cookie should be set for more than 7 day.

-Browser [Brave]

After trying to reproducing the bug in chromium, it's working fine in chromium. So I will open a bug report in Brave repository and still I will let this issues open before this issues is resolved by Brave or js-cookie.

**Comment by carhartl** [comment]
Apparently this is expected behavior in Brave [1], and it doesn't have to do anything with this library (we couldn't do anything about it anyway).

[1] https://github.com/brave/brave-browser/issues/3443
