### ISSUE TITLE
js-cookie not working for me for some reason

### ISSUE THREAD

**Issue by dyetube** [js-cookie/js-cookie#58]
I'm trying to reference (and set) a cookie from an asp.net 4.0 materpage (So I can call a modal popup only once every so often) But js-cookie doesn't seem to be creating the cookie.  Here's my code:

<script src="/Scripts/js.cookie.js"></script> (In the head AFTER jquery loads)

At the bottom just before the Body tag:

$(document).ready(function () {
if ($.Cookies.get('modal_shown') == null) { $.Cookies.set('modal_shown', 'yes', { expires: 60 });
$('#emailModal').foundation('reveal', 'open')}});
$(document).ready(function () { $('#emailModal').foundation('reveal', 'open') });

I also tried JUST setting a cookie like this:
$(document).ready(function () {
    $.Cookies.set('modal_shown2', 'yes', { expires: 60 });
    });

Just to see if it was setting a cookie and it isn't.  Could another script be interfering with it?  I'm dumfounded.
Jeff M.

**Comment by carhartl** [comment]
Instead of `$.Cookies.get(...)` just write `Cookies.get(...)`, i.e. omit the `$.`.

**Comment by carhartl** [comment]
Also see https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0 => "jQuery ($) is removed"
