### ISSUE TITLE
Import broken in latest beta

### ISSUE THREAD

**Issue by redaxmedia** [js-cookie/js-cookie#583]
Import via 3.0.0-beta.2 is broken as of missing `index.js` file.

Current import workaround:

```
import Cookies from 'js-cookie/dist/js.cookie';
```

Solution via `node_modules/js-cookie/index.js`:

```
module.exports = require('./dist/js.cookie');
```
or
```
module.exports = {
    Cookies: require('./dist/js.cookie');
};
```

Desired import:

```
import Cookies from 'js-cookie';
```

**Comment by FagnerMartinsBrack** [comment]
Can you write a test that can reproduce the issue?

**Comment by redaxmedia** [comment]
An import issue is not testable...

**Comment by FagnerMartinsBrack** [comment]
@redaxmedia 

There is a test for it already [here](https://github.com/js-cookie/js-cookie/blob/17b370152c5c0e7d2ac1d04cf594a248fba46bc3/test/module.mjs). What's the difference between the way you're using and they way it's being tested?

Could it be that we need a test for importing cookies from the root of the package so that it can trigger the need for the "main" property on `package.json`?

**Comment by redaxmedia** [comment]
Nope, this test does not take care of the package released on NPM. Just check it out via npm install and try to import it inside a JavaScript file. I cannot provide more help at this point.

**Comment by carhartl** [comment]
Also see: https://github.com/js-cookie/js-cookie/issues/544#issuecomment-564925761

**Comment by redaxmedia** [comment]
@carhartl I opened another issue cause this has nothing todo with the testing setup.

**Comment by carhartl** [comment]
@redaxmedia  Aye aye. It looked like it could be the same issue, but you seem to know better.

**Comment by carhartl** [comment]
I‘m still confused as to how the `index.js` relates to the `browser` field in the package definition. Also, should `index.js` point to the es6 or umd dist variant. Can’t seem to find good answers on the internet.

**Comment by carhartl** [comment]
Slightly different advice here: https://github.com/js-cookie/js-cookie/issues/544#issuecomment-535440792

**Comment by carhartl** [comment]
@redaxmedia I've added an example where I've tested (in Nodejs 13.2.0) that this issue is now fixed, but could you also please give it a try...

**Comment by redaxmedia** [comment]
Finally, I can confirm that `3.0.0-beta.3` works again.
