### ISSUE TITLE
Not possible to set Cookie: HttpOnly: true

### ISSUE THREAD

**Issue by BastianBalthasarBux** [js-cookie/js-cookie#584]
Not possible to set Cookie-attribute: HttpOnly: true

This is also security related.

**Comment by carhartl** [comment]
Please see various earlier tickets.

**Comment by carhartl** [comment]
But to sum it up: http only does what it says: the cookie won’t be available for client side scripting, that’s why it naught appear as if you haven’t written them.

**Comment by carhartl** [comment]
I've added a bit regarding HttpOnly cookies to the FAQ: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#im-using-httponly-true-wheres-my-cookie

Hope that brings a bit more clarity.

**Comment by carhartl** [comment]
PS: Regarding

>that’s why it might appear as if you haven’t written them

I need to correct myself, I tested the behavior in recent Chrome and Firefox, and no cookie is being written at all when using `HttpOnly`. That's in line with the [respective MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) where `HttpOnly` isn't even mentioned.

**Comment by BastianBalthasarBux** [comment]
Thanks for hinting, i did some research myself, and yes, httponly cannot be set by javascript in general.
After thinking a little bit about it, it also does not make sense ... as the content is already exposed by the script trying to set ...
