### ISSUE TITLE
npm minified file

### ISSUE THREAD

**Issue by cdalexndr** [js-cookie/js-cookie#586]
Please provide production ready minified javascript in npm pakage [js-cookie](https://www.npmjs.com/package/js-cookie).
Currently version 2.2.1 contains only  `js.cookie.js`

**Comment by cdalexndr** [comment]
Runned a dry run publish and it seems that the new version can publish the minified files:
```
λ npm publish --dry-run
npm notice
npm notice package: js-cookie@3.0.0-beta.3
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 46B    index.js
npm notice 4.1kB  dist/js.cookie.js
npm notice 1.7kB  dist/js.cookie.min.js
npm notice 1.5kB  package.json
npm notice 14.3kB README.md
npm notice 1.4kB  dist/js.cookie.min.mjs
npm notice 3.5kB  dist/js.cookie.mjs
npm notice === Tarball Details ===
npm notice name:          js-cookie
npm notice version:       3.0.0-beta.3
npm notice package size:  8.8 kB
npm notice unpacked size: 27.7 kB
npm notice shasum:        e1f43ecc020dd82299559ade2a98de1ca0d73763
npm notice integrity:     sha512-qWSGvOo6Uzjzm[...]1YcWRhML0Yz3Q==
npm notice total files:   8
npm notice
+ js-cookie@3.0.0-beta.3
```

It would be best to add **prepublish** in _package.json_ **scripts** to prevent publishing without distribution files:
`"prepublish": "npm run test && npm run dist",`

**Comment by carhartl** [comment]
>It would be best to add prepublish in package.json scripts to prevent publishing without distribution files

That is taken care of:
https://github.com/js-cookie/js-cookie/blob/f33a0c86e1c4480208f121a328c87f8eae5f7388/.release-it.json#L15

**Comment by carhartl** [comment]
Closing since starting with v3 the release contains minified variants. If you have to have it now, you‘ll need to start using the v3 beta for a little more time.
