### ISSUE TITLE
I can't pass in variables as attributes of the cookie, if you could make it so the set function takes in non string variables to.

### ISSUE THREAD

**Issue by SaidKhaboud** [js-cookie/js-cookie#587]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by carhartl** [comment]
Not sure what exactly the problem is. Some examples:

```javascript
var myAttributes = { path: '/' }
Cookies.set('key', 'value', myAttributes)

var myPath = '/foo'
Cookies.set('key', 'value', { path: myPath })

var myValue = 'value'
Cookies.set('key', myValue)

var myKey = 'key'
Cookies.set(myKey, 'value')
```

It helps when you provide useful bug reports.

**Comment by carhartl** [comment]
Is that what you mean? If not could you please provide an example of what you want to accomplish?

**Comment by carhartl** [comment]
I'm guessing a little more. If you want to store an array for instance you can either go for JSON, or write your own converter (examples based on **v3**):

```javascript
// JSON
var value = [0, 1, 2, 3]
Cookies.set('array', JSON.stringify(value))
JSON.parse(Cookies.get('array')) // [0, 1, 2, 3]

// With a converter
var api = Cookies.withConverter({
  read: value => Cookies.converter.read(value).split(',').map(x => x * 1), 
  write: value => Cookies.converter.write(value.join(','))
})
api.set('array', value)
api.get('array') // [0, 1, 2, 3]
```

Just to give you an idea. For arbitrary objects you're likely want to prefer the JSON approach.

If you're using v2, you get json support out of the box, and with that you can store arbitrary values: https://github.com/js-cookie/js-cookie/tree/latest#json

**Comment by carhartl** [comment]
Here's how you could create an api instance (with **v3**) that allows storing arbitrary values:

```javascript
var api = Cookies.withConverter({
  read: value => JSON.parse(Cookies.converter.read(value)),
  write: value => Cookies.converter.write(JSON.stringify(value))
})
api.set('array', [1, 2])
api.get('array') // [1, 2]
api.set('object', { foo: 'bar' })
api.get('object') // {foo: "bar"}
```

HTH

**Comment by andy-cywang** [comment]
Hi, I tried cookie with jQuery but I got the same issue:
My code:
```
var myValue = $('#firstname').val();
Cookies.set('name', myValue)
```
It gives me null when I try to get it:
`Cookies.get('name')`
