### ISSUE TITLE
yarn add js-cookie

### ISSUE THREAD

**Issue by mices** [js-cookie/js-cookie#588]
I included this in my rails 6 project with `yarn add js-cookie`
Then I added 
require("js-cookie")
to application.js but I get the error ReferenceError: Cookies is not defined

**Comment by carhartl** [comment]
Could you please provide actual code?

**Comment by carhartl** [comment]
Isn‘t it in Rails that you‘ll have to use the asset pipeline, and thus in your application.js you would add:

```
//= require js-cookie/js-cookie
```

**Comment by carhartl** [comment]
>Isn‘t it in Rails that you‘ll have to use the asset pipeline

Ah, no, Rails 6 moved to webpack it seems.

**Comment by carhartl** [comment]
With a webpack setup you have to import the js-cookie module before you can use it. I've added the following to `application.js` and it works:

```js
import Cookies from "js-cookie";
Cookies.set("test", "rails");
console.log(Cookies.get("test"));
```
