### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by MetusMeth** [js-cookie/js-cookie#589]
Solved

**Comment by carhartl** [comment]
What‘s saved is always a string. You can implement a custom converter (see docs) if you always want to turn a value into a number upon read.

**Comment by carhartl** [comment]
Wait, I misread the issue..

**Comment by carhartl** [comment]
Tested, and works for me without a problem. 

<img width="455" alt="Screenshot 2020-01-12 at 01 22 12" src="https://user-images.githubusercontent.com/21918/72212322-0636f000-34da-11ea-86e7-264a2ae3f6ca.png">

**Comment by carhartl** [comment]
Could you provide some more information (actual code, version of the library you're using etc.) so we're able to reproduce this problem?

**Comment by MetusMeth** [comment]
Sorry works! I'm not sure what I did wrong however it works now.
