### ISSUE TITLE
Issue with removing the cookie that set with time and path

### ISSUE THREAD

**Issue by deepak458** [js-cookie/js-cookie#591]
Hi, I'm getting issue with cookie, when i set cookies in php using `setcookie("name", 'name');` and run `Cookies.remove("name")` in jQuery, it will remove my cookies value. Work fine ok.

But when i set cookie in PHP using 
`setcookie("name", 'name', time()+86400, '/home', 'domin.com'); //time()+86400 == 1Day` 
and run `Cookies.remove("name")` it will not remove the cookie.

i also try below function but still not work to remove cookie
`Cookies.remove("msg", {path: ''})`

`Cookies.remove("msg", {path: '', expires: '-1'})`

`Cookies.remove("msg", {path: '', expires: '-1',domain:''})`

any of these function not work for me when only when using time, path, and domain, i also try with time and path but still getting same issue.

**Comment by carhartl** [comment]
When removing a cookie you have to use the same values for path and domain the cookie has been set with.

In your case that seems to be “/home” for path and “domin.com” for domain, so:

```js
Cookies.remove('msg', { path: '/home', domain: 'domin.com' })
```

Could you try that?

Caveat: when you’re not currently in that path you won’t be able to delete the cookie either. So deleting this specific cookie while at `/sitemap` will fail.

**Comment by deepak458** [comment]
@carhartl in this i'm using cookies for receive message from another page, so path not fix.

**Comment by deepak458** [comment]
I use below code in my back-end to set cookies using php
`setcookie("msg", 'Document Updated Successfully', time()+3600, '/home', 'domain.com');`

I also try your code `Cookies.remove('msg', { path: '/home', domain: 'domin.com' })` but still cookies not removing

**Comment by carhartl** [comment]
Did you try `Cookies.remove('msg', { path: '/home', domain: 'domin.com' })` literally? What's the real value for domain in your php?

**Comment by carhartl** [comment]
>in this i'm using cookies for receive message from another page, so path not fix

I don't understand what you mean here. Again, take not that if you write a cookie with a path of `/home`, you won't be able to delete it after having browsed to a different page, say `/other-page`.

**Comment by deepak458** [comment]
> Cookies.remove('msg', { path: '/home', domain: 'domin.com' })

This thing work when i'm using path into remove cookies, but in my case i cant fix path for a single page so, is there any solution for it.

**Comment by carhartl** [comment]
I still don't fully understand what the problem is... does it have to do with this library? It seems that removing a cookie seems to work when given the expected path + domain values.

Can you use "/" as value for path? With that it doesn't depend on a single page at all. This will only work if you do not have different msg values per pages.

**Comment by deepak458** [comment]
My question is i'm generating cookie form multiple page like
`Cookies.remove('msg', { path: '/home', domain: 'domin.com' })` 
`Cookies.remove('msg', { path: '/about', domain: 'domin.com' })`
`Cookies.remove('msg', { path: '/login', domain: 'domin.com' })`

but i have created a common file that is main.js and mentioned the some Cookies code over there 
`if(Cookies.get("msg")){`
    `var msg = $.parseJSON(Cookies.get("msg"));`
 `showMessage(msg);`
`Cookies.remove('msg', { path: '/', domain: 'domain.com' });`
 };`

**Comment by deepak458** [comment]
i do not want to mentioned every path into like
`Cookies.remove('msg', { path: '/home', domain: 'domain.com' });`
`Cookies.remove('msg', { path: '/about', domain: 'domain.com' });`
`Cookies.remove('msg', { path: '/login', domain: 'domain.com' });`

**Comment by deepak458** [comment]
Can you suggest me something how i can access real set path in jquery-cookie

**Comment by carhartl** [comment]
I don't think I can help with that.. it's not possible to retrieve a path from a cookie you've already written. You can only know the path at write time. Maybe it's possible for you to maintain a single cookie at the top level path, so that you'd only have to remove it once.

```php
setcookie('name', 'name', time()+86400, '/', 'domain.com');
```
```js
if (Cookies.get('msg')) {
  // ...
  Cookies.remove('msg', { path: '/', domain: 'domain.com' });
}
```
If you can't do that you can at least implement a little loop to avoid the repetition:

```js
["home", "about", "login"].forEach(page => Cookies.remove('msg', { path: '/' + page, domain: 'domain.com' }))
```

If the page is supposed to be dynamic, you can try to read the current page/path from `window.location.pathname`.

**Comment by deepak458** [comment]
Ohh ok Thanks
