### ISSUE TITLE
Phantom key

### ISSUE THREAD

**Issue by qWici** [js-cookie/js-cookie#592]
**Describe the bug**
I am not sure if this is a bug. It may just be a mistake. But you call `write` function with two parameters. This function is return only first converted value. If this is not mistake - can someone explain to me why this is done?

https://github.com/js-cookie/js-cookie/blob/77f377a9ba7aeb1545073402a90e87ec9826ceff/src/api.mjs#L19

P.S. Many thanks for lib :smile_cat:

**Comment by FagnerMartinsBrack** [comment]
I don't think that API is documented anywhere, is it?

Refer to [this](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0) for details of why I'm asking that question.

**Comment by qWici** [comment]
> I don't think that API is documented anywhere, is it?
> 
> Refer to [this](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0) for details of why I'm asking that question.

Yes, you're right. I have used this library many times, without looking in source code. But today I did it - just because if you use something often, then at one point you may want to see how it works. I'm not first day working as webdev, but this line baffled me. So I create this issues to learn something new or point out mistake

**Comment by carhartl** [comment]
We chose to pass both the key and value to the converters so that you can implement a converter that will convert depending on the key. The readme has a section about converters.
