### ISSUE TITLE
Cookies are not updated on Chromium Edge [js-cookie v2.2.1]

### ISSUE THREAD

**Issue by zicheee** [js-cookie/js-cookie#594]
Hi,

I use the latest release v2.2.1 and tried the cookie function in several browsers. While its working on Android using Chrome and on Windows using Firefox there is an issue using Chromium Edge or Edge. Setting an initial value for the cookie is possible: 
`Cookies.set('my-boolean-cookie', true);`
but changing the value, e.g:
`Cookies.set('my-boolean-cookie', false);`
is not possible. There is no error in the console visible. The value is just not updated. I have to remove the cookie and set it again. 
Setting my boolean as string (e.g. 'true', 'false'), the result is still the same and the cookie is not updated.

Best regards
Michael

**Comment by carhartl** [comment]
Did you change the defaults for `path`? Or what's the value for `path` in the console?

**Comment by carhartl** [comment]
I tested this with a Edge Chromium on macOS and cannot reproduce. The value is being updated as expected. Are you using some sort of nightly?

**Comment by carhartl** [comment]
@zicheee Are you able to provide further information helping us to investigate the problem?

**Comment by zicheee** [comment]
Hi @carhartl 
I am very sorry for my late reply. I have installed Windows 10 64bit and was using Chromium Edge (Version 79.0.309.18)

But today I installed an update to 80.0.361.48. Since this update the issue is resolved. So this was sure a bug in the edge version. Sorry for that.
