### ISSUE TITLE
Can't delete cookies from my domain

### ISSUE THREAD

**Issue by nalnir** [js-cookie/js-cookie#597]
I have a function that works great in localhost when I don't have to specify the domain:

```
function deleteProducts() {
            var cs= document.cookie.split(' ')
            for(var i = 0; i < cs.length; i++) {
                if(cs[i].match('-product')) {
                    var prod = cs[i].split('=')[0]
                    // console.log(prod)
                    Cookies.remove(prod, { path: '/', domain: 'xxxxx.firebaseapp.com' })
                }
            }
        };
```

But when I specify the domain in Cookie.remove it doesn't work after deploying to firebase. The cookies set by my domain persist. Not sure where I'm making the mistake.

**Comment by carhartl** [comment]
>When deleting a cookie you must pass the exact same path and domain attributes that were used to set the cookie

In other words, if you don’t have access to a cookie in a particular context, you won’t be able to delete it either. Could you check that? Have those cookies been written with the same attributes you’re passing to`remove()`?

**Comment by nalnir** [comment]
Hi @carhartl, thanks for a very quick answer. I used the vanilla javascript for setting cookie with expiration date set to past without setting domain and it worked. 
So instead of `Cookies.remove(prod, { path: '/', domain: 'xxxxx.firebaseapp.com' })` I used
`document.cookie = prod +'=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';`

**Comment by carhartl** [comment]
Exactly.. looks like you've initially written the cookie without `Domain`, so the following should have worked as well:
```js
Cookies.remove(prod, { path: '/' })
```

These are two different cookies:

```js
Cookies.set(prod, { domain: 'xxxxx.firebaseapp.com' })
Cookies.set(prod)
```
