### ISSUE TITLE
Add note about cookie not working locally into the Wiki

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#600]
Topics to address:

- [x] Cookies don't work in Chrome `file://` (pending test)
- <strike>[ ] As long as you don‘t need to use the domain attribute you can just test on http://localhost and don‘t need to edit /etc/hosts (on Chrome?). (pending test)</strike>

Some issues people created about this to this date (in no specific order): https://github.com/js-cookie/js-cookie/issues/598, https://github.com/js-cookie/js-cookie/issues/247, https://github.com/js-cookie/js-cookie/issues/129, https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762, https://github.com/js-cookie/js-cookie/issues/247#issuecomment-567832007, https://github.com/js-cookie/js-cookie/issues/552, https://github.com/js-cookie/js-cookie/issues/335

**Comment by carhartl** [comment]
Why do we need this?

We‘re running all our tests on localhost in Chrome, that should be proof enough. It‘s all about the Domain attribute. That cookies do no longer work on `file://` also doesn‘t need to be verified, it’s a known fact.

**Comment by carhartl** [comment]
We can easily add the issue with `file://` to the FAQ, which isn’t read by anyone anyway.

**Comment by carhartl** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=56211#c14

**Comment by FagnerMartinsBrack** [comment]
> We can easily add the issue with file:// to the FAQ, which isn’t read by anyone anyway.

Let's do that then. Hopefully there are less occurrences of people opening issues because of this. After we documented the things we have today in the Wiki I've noticed a decrease in number of reports.

**Comment by FagnerMartinsBrack** [comment]
@carhartl Done. See: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions/5b1bffa784fc5530a13eadc6505f8eb2f11176ed

**Comment by carhartl** [comment]
Thanks! I'm going to add a link to the FAQ in the readme, somewhere prominently at the top, like:

> Your cookie isn't working? Have you checked the [FAQ]

Apparently, adding it to the issue template wasn't sufficient.

**Comment by FagnerMartinsBrack** [comment]
@carhartl Do we have evidence it didn't work?  The root cause of https://github.com/js-cookie/js-cookie/issues/598 is the `file://` schema not the use of `HttpOnly` which is well documented in the Wiki :)
