### ISSUE TITLE
Cookie returning undefined value

### ISSUE THREAD

**Issue by AvalonMel** [js-cookie/js-cookie#61]
I'm trying to set up a simple cookie to track one value across a site. I have the plugin included. This is the code I'm using:
```
if(Cookies.get('view') == null) {
		Cookies.set('view', 'mobile');
		console.log(Cookies.get('view'));
	}
```
And in the console all I get is `undefined`
What am I doing wrong here? It seems so straight-forward.

**Comment by jamie-jenks** [comment]
Hey, did you find a work around for this?
