### ISSUE TITLE
Percent-Encoding not being decoded.

### ISSUE THREAD

**Issue by mrpassiontea** [js-cookie/js-cookie#610]
Hi there, I've been using js-cookie on my website for months without issues. Suddenly, the cookies I create on one page are not being decoded on the next pages that read them.

Given the link: 
https://www.joesge.com/pages/repair-service-issues?p=copy-solo-3-wireless-service&cache=false

I set a cookie named "serviceCart".

```
const newCookie = {
   cartItems: serviceCartTemplate
};

Cookies.set("serviceCart", newCookie, {
  sameSite: "lax", secure: true
});
```

Now on this same page, I can write `Cookies.get("serviceCart")` and the command will return `"{"cartItems":[{"id":0,"handle":"copy-solo-3-wireless-service","issues":["454468272131"]}]}"
`. I can also `JSON.parse(Cookies.get("serviceCart"))`. 

Under `Console -> Application -> Cookies -> serviceCart` the value is: `{%22cartItems%22:[{%22id%22:0%2C%22handle%22:%22copy-solo-3-wireless-service%22%2C%22issues%22:[%22454468272131%22]}]}`

Note, up to this point if I'm staying on the same link: https://www.joesge.com/pages/repair-service-issues?p=copy-solo-3-wireless-service&cache=false I can `Cookies.get("serviceCart")` and I can `JSON.parse(Cookies.get("serviceCart"))`. No issues with the percent-encoding.

Now here's the issue, if I visit any page. For instance, the next page after setting the serviceCart cookie on this page is: https://www.joesge.com/pages/repair-service-cart?SOUND=454468272131&Product=Solo+3+Wireless

When I look at `Console -> Application -> Cookies -> serviceCart` the value is: `{%22cartItems%22:[{%22id%22:0%2C%22handle%22:%22copy-solo-3-wireless-service%22%2C%22issues%22:[%22454468272131%22]}]}` they're identical.

The issue is on this new cart page, if I try the command: `Cookies.get("serviceCart")` instead of getting `"{"cartItems":[{"id":0,"handle":"copy-solo-3-wireless-service","issues":["454468272131"]}]}"
` as the value... I get `"{%22cartItems%22:[{%22id%22:0%2C%22handle%22:%22copy-solo-3-wireless-service%22%2C%22issues%22:[%22454468272131%22]}]}"` it's still percent-encoded even though the same command was working on the previous page (where the cookie was created). Can't `JSON.parse` either because it's not in the right format to parse, get's a invalid % token. 

Is there any reason why my code would be working on the previous page, working as in I can `Cookie.get("serviceCart")` and `JSON.parse(Cookies.get("serviceCart"))` without running into any percent-encoding issues. But when I'm on any other page, I get a percent-encoded value as the return from `Cookies.get("serviceCart")`.

Setting the cookie within the repair-service-issues page. 
![image](https://user-images.githubusercontent.com/14931499/76135761-6d51ca80-606d-11ea-9ad5-bed2c840b5e4.png)

Showing that I can get and parse the serviceCart cookie in the repair-service-issues page. The same page where I initially created the cookie.
![image](https://user-images.githubusercontent.com/14931499/76135810-ecdf9980-606d-11ea-954b-efa47eeba51d.png)

Application -> Cookies -> serviceCart value is percent-encoded, but I can still get and parse the percent-encoded value on the repair-service-issues page. 
![image](https://user-images.githubusercontent.com/14931499/76135829-11d40c80-606e-11ea-8c5a-0731a57ca152.png)

Now on the cart page, I try `Cookies.get("serviceCart")` and instead of getting a percent-decoded value, I have a percent-encoded value. Can't JSON.parse this because of the percents.
![image](https://user-images.githubusercontent.com/14931499/76135859-58296b80-606e-11ea-848b-245c359a3a0a.png)

Any reason why it would be like this, previously it's worked for the longest time. Now suddenly, it's not decoding the percent value on other pages other than where the serviceCart was set.

**Comment by carhartl** [comment]
Which version of js-cookie are you using?

**Comment by mrpassiontea** [comment]
> Which version of js-cookie are you using?

Thanks for replying, I'm using this
`<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>`

**Comment by carhartl** [comment]
On the second page you're mentioning, you're not using version 2 but the beta (v3) of the library:

https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js

We recently made changes to the encoding/decoding for the upcoming v3. Please use a consistent version.

**Comment by mrpassiontea** [comment]
Wow, thank you! You're right.
