### ISSUE TITLE
Uncaught TypeError: u[f].split is not a function  at Object.o [as set] (js.cookie.min.js:2)

### ISSUE THREAD

**Issue by Emmanuel-GD** [js-cookie/js-cookie#613]
I am having error when creatng cookie. I have tried both *js.cookie-2.2.1.min.js* and *js.cookie.min.js (v3.0.0-beta.4)*.

**To Reproduce**
1. added reference to 'js.cookie-2.2.1.min.js' or 'js.cookie.min.js (v3.0.0-beta.4)'
2. try creating a cookie like 'Cookies.set('name', 'value', 100000);*
3. It will throw the above error saying 
**js.cookie.min.js:2 Uncaught TypeError: u[f].split is not a function
    at Object.o [as set] (js.cookie.min.js:2)
    at HTMLAnchorElement.<anonymous> (Default.aspx:47)
    at HTMLAnchorElement.dispatch (VM3405 jquery.min.js:2)
    at HTMLAnchorElement.v.handle (VM3405 jquery.min.js:2)**

**Comment by carhartl** [comment]
You're not using the api correctly, not sure what you want to achieve by passing `100000` as third argument, but I'm assuming you want the configure the expiration. This would have to look like this:

```js
Cookies.set('name', 'value', { expires: 100000 }) // 100k days!
```

The readme has information regarding usage.

**Comment by gurr-i** [comment]
then, how to set cookie to expire in seconds or minutes?

**Comment by Abolfazl2647** [comment]
i have the same issue 

```
Cookies.set("token", JSON.stringify(accessToken), {
      expire: accessTokenExpSec / 86400,
    });
```


TypeError: attributes[attributeName].split is not a function
    at Object.set (js.cookie.mjs:75:64)
    at SetTokensInfo (tokenStorage.ts:10:5)
    at Object.onSuccess (oauth.ts:31:20)
    at Mutation.execute (mutation.js:114:37)

**Comment by carhartl** [comment]
@Abolfazl2647 `expires`, not `expire`
