### ISSUE TITLE
Import - withAttributes is not a function

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [js-cookie/js-cookie#616]
![image](https://user-images.githubusercontent.com/29608698/76999295-27cab280-6935-11ea-8ad1-4c61a9b31d37.png)

![image](https://user-images.githubusercontent.com/29608698/76999304-2dc09380-6935-11ea-9b79-e750f08e3f38.png)

No idea why its happening, tried to fix it but got nothing, version ^2.2.1

**Comment by carhartl** [comment]
`withAttributes()` is from v3.

**Comment by carhartl** [comment]
You need to consult the readme for the latest version (as suggested): https://github.com/js-cookie/js-cookie/tree/latest#readme

**Comment by diego-lipinski-de-castro** [comment]
Just checked it out and yeah, with the rc it works, but i see it has no getJSON support, we need to parse it manually or is there something in the package about it?

**Comment by carhartl** [comment]
Parse manually.. https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-beta.0

**Comment by carhartl** [comment]
Or write your own converter!
