### ISSUE TITLE
Brakes the code if the attribute value is a number

### ISSUE THREAD

**Issue by irynagrom** [js-cookie/js-cookie#618]
https://github.com/js-cookie/js-cookie/blob/7d41e167ab6e4c1f65716d7a1ad2533fb952e80b/src/api.mjs#L35

The **attributes** set for us it  { path: '/', domain: '.example.com', maxAge: 63072000, expires: '' }
It brakes the set function since it cannot split the numeric value. 
 **TypeError: attributes[attributeName].split is not a function**

**Comment by carhartl** [comment]
We support arbitrary, custom attributes (i.e. those not documented in the api) only with String types. As a workaround you’ll have to use `maxAge: '63072000'`.

**Comment by carhartl** [comment]
Though I’m wondering why would you want to use an undocumented `maxAge` instead of `expires`?

**Comment by artem-malko** [comment]
For example: https://mrcoles.com/blog/cookies-max-age-vs-expires/#:~:text=Quick%20Answer%3A,this%2C%20it's%20no%20longer%202009)
This is an article, written 2009) You can just make major update with maxAge supporting)

**Comment by carhartl** [comment]
Max-Age is. It supported by browsers we still support (IE 10). That‘s why we won’t implement it, but as mentioned you can use it anyway using a custom attribute.

**Comment by carhartl** [comment]
See #534 as well as #633.

**Comment by bi-kai** [comment]
IE11 was EOS for a long time.
