### ISSUE TITLE
Feature request: pass optional cookieString to get method so it supports non-browser environments

### ISSUE THREAD

**Issue by mbssantos** [js-cookie/js-cookie#621]
**Is your feature request related to a problem? Please describe.**
Hi :wave: I'm building a React SSR app with NodeJS and express. During the server rendering, `document` is undefined so I can't get my cookies and it makes me sad.

**Describe the solution you'd like**
It'd be great if I could tell `js-cookie` to parse cookies from an alternative source. At first glance I'm thinking of having a second optional param that replaces `document.cookie` when calling `get`. 

Something like:

```
function get (key, cookieStr) {
  if (arguments.length && !key)) {
    return;
  }

  if (typeof document === 'undefined' && !cookieStr) {
    return;
  }
  
  var cookies = (cookieStr || document.cookie) ? (cookieStr || document.cookie).split('; ') : [];
```

**Describe alternatives you've considered**
There's a few hardcore options like overwridding `document` on SSR but it's not trivial & could cause all kind of malarkey.

**Additional context**

For my use case I just need to `get` cookies & it doesn't make sense to change them so there's no need to change the `set` method.

I'd probably leave the `cookieString ` validation to the user to keep this light, although I can see the point about wanting some validation in.

Happy to submit a PR and tests if you find this usefull!
For now I'm copy-pasting your get code with these changes to support my use case so no rush.

I can see the argument this is outside the scope of this package but thought I'd ask.

Thanks & good work on this package :)

**Comment by carhartl** [comment]
Same as #513

**Comment by mbssantos** [comment]
Fair enough
