### ISSUE TITLE
how to get Cookie with lax?

### ISSUE THREAD

**Issue by Hess1337** [js-cookie/js-cookie#622]
`let cookie_auth = Cookies.get('hash');
		console.log(cookie_auth);`
undefined
my cookie https://prnt.sc/s40vlw

**Comment by carhartl** [comment]
@Hess1337 In the given screenshot, the checkmark at the bottom to the right containing "HTTP" - does it translate to "HTTP only"?

**Comment by carhartl** [comment]
So, using Google translate... только means only, which means the cookie in question is a _HTTP only_ cookie, thus not accessible to client-side scripting, so it's correctly undefined.

**Comment by carhartl** [comment]
Some more information about HttpOnly cookies can be found here: https://developer.mozilla.org/de/docs/Web/HTTP/Cookies
