### ISSUE TITLE
JSON encoder

### ISSUE THREAD

**Issue by jbpin** [js-cookie/js-cookie#624]
**Is your feature request related to a problem? Please describe.**
https://github.com/js-cookie/js-cookie/blob/355f7efee1265a99ceba62ccd56f28e252dfb5d3/src/api.mjs#L21 Syntax String(value) prevent me from passing any Object to my converter. 
I wish I can create a converter that will handle string conversion/encoding. 

**Describe the solution you'd like**
I suggest changing for
`value = String(converter.write(value, key))`

**Describe alternatives you've considered**
Of course I can use Cookies.set('name', JSON.stringify(value)) but this mean I can't change my converter seamlessly. I've to go all arround my code. 

**Additional context**

**Comment by carhartl** [comment]
Sounds reasonable!

**Comment by carhartl** [comment]
Also seems more of a bug, as converters aren't working as advertised.
