### ISSUE TITLE
expires alone with sameSite: 'strict' seems does not work with Safari

### ISSUE THREAD

**Issue by edwardfhsiao** [js-cookie/js-cookie#627]
**Describe the bug**

Set both ```expires: 10``` and ```sameSite: 'strict' ``` at the same time seems lost  ```strict``` in Safari.
It is not a problem of this library per se since manually setting the cookie in Safari would also destroy ```strict```.

**To Reproduce**

```js
    Cookies.set('foo', 'bar');
    Cookies.set('strictFoo', 'strictBar', { sameSite: 'strict' });
    Cookies.set('strictFooWithExpires', 'strictBarWithExpires', { expires: 10, sameSite: 'strict' });
```
**Expected behavior**

```strictFooWithExpires``` should be ```strict``` in ```sameSite``` field

**Screenshots**

![image](https://user-images.githubusercontent.com/11728228/81468963-2458f680-9215-11ea-969c-2928ee4d688f.png)

**Desktop (please complete the following information):**

- OS: macOs 10.15.3
- Browser Safari
- Version 13.0.5 (15608.5.11)

**Additional context**

Works fine with chrome

**Comment by carhartl** [comment]
> It is not a problem of this library per se since manually setting the cookie in Safari would also destroy strict

So it‘s a bug in Safari?

**Comment by edwardfhsiao** [comment]
@carhartl Yeah, I think so. 

I would not tag a 'Bug' label if there is a 'General info' option for me to create an issue though. However, I think it might be helpful to keep it track here for potential inquiries.

**Comment by carhartl** [comment]
@edwardfhsiao 

I've tried it myself and it works for me... could you try with all cookies cleared before and maybe check whether you have some extensions active that may interfere?

<img width="1245" alt="Screenshot 2020-05-09 at 11 13 23" src="https://user-images.githubusercontent.com/21918/81469632-4edf8b00-91e6-11ea-8f95-549b3e38ae5c.png">

**Comment by edwardfhsiao** [comment]
![image](https://user-images.githubusercontent.com/11728228/81469962-bc0d1380-921a-11ea-9d92-0588bb73fde4.png)
![image](https://user-images.githubusercontent.com/11728228/81469974-c8916c00-921a-11ea-8604-147a99f784d0.png)

Found the problem
```js
   // does work when expire days below 7
   Cookies.set('strictFooWithExpires', 'strictBarWithExpires', { expires: 7, sameSite: 'strict' });
```
```js
   // doesnot work when expire days over 7
   Cookies.set('strictFooWithExpires', 'strictBarWithExpires', { expires: 8, sameSite: 'strict' });
```

**Comment by carhartl** [comment]
Great find, wow... very interesting, seeing it as well.

**Comment by carhartl** [comment]
Capping to 7 days is part of Safari‘s intelligent tracking prevention:

=> https://webkit.org/blog/8613/intelligent-tracking-prevention-2-1/

I guess that it‘s also stripping the SameSite attribute is a bug.

**Comment by carhartl** [comment]
I wasn‘t aware of that until now.. Mentioning this behavior is probably worth adding to the FAQ.

**Comment by edwardfhsiao** [comment]
absolutely, cheers :partying_face:
