### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by inglesuniversal** [js-cookie/js-cookie#628]
1. How to list all enabled cookies and their current set values

2. How to know the amount of bytes available to store cookies, depending on the browser

3. What is the maximum number of days a cookie can stay in memory and is there a way to auto-renew the cookie before it expires.

Thanks and STAY SAFE

**Comment by carhartl** [comment]
1. List cookies:`Cookies.get()` 

2. You could experiment: http://browsercookielimits.squawky.net/

3. Again, I don’t have an answer. In theory you could have a cookie with an expiration date far far in the future (so technically it doesn’t expire), but browsers may cap this as well. Safari for instance allows cookies for a maximum of 7 days as part of its “Intelligent Tracking Prevention” feature. You can’t renew the cookie without the user visiting your site.
