### ISSUE TITLE
Working, but with a couple exceptions

### ISSUE THREAD

**Issue by webdvlpr** [js-cookie/js-cookie#63]
This is working with most of my users, but I have a user it's not working for. He's using the latest version of Chrome, Allows all cookies and does not have an exception set for the site. Any ideas?

**Comment by FagnerMartinsBrack** [comment]
It's very hard to figure out what is going on without more information, we need at least some code to look into.

**Comment by webdvlpr** [comment]
My bad.

 $(document).ready(function() { 
    if( /Android|webOS|iPhone|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
        } else {
            if (Cookies.get('pop2') == undefined) {
                Cookies.set('pop2', '1');
                $('#announcementModal').modal('show');
            }
        }
 });

**Comment by FagnerMartinsBrack** [comment]
Is there any `Malformed URI` error somewhere? We have an issue where an invalid encoded cookie is causing problem, check the code form [this PR](https://github.com/js-cookie/js-cookie/issues/63#issuecomment-120454346) and see if it's working.

You can also print everything that js-cookie process before decoding using a custom converter for debug purposes:

```javascript
var DebuggingCookie = Cookies.withConverter(function( value, name ) {
  window.console && window.console.log && console.log( value + " <=> " + name );
});

DebuggingCookie.get('c');
DebuggingCookie.set('c', 'v');
```

Besides that, the code you presented is supposed to work without any problem.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If the problem still remains we reopen it.
