### ISSUE TITLE
Setting the cookie expiry for more than 7 days does not work in the Brave browser

### ISSUE THREAD

**Issue by krynv** [js-cookie/js-cookie#631]
**Describe the bug**
Setting the cookie expiry for more than 7 days does not work in the Brave browser

**To Reproduce**

1. Create a cookie
`Cookies.set('cookieName', true, { expires: 91 });`
2. Check the browser's cookie in application memory

**Expected behavior**
Expected for expiry date to be set for 91 days from now

**Actual behavior**
Expiry date set to 7 days from now.

**Desktop**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Brave (Chromium based browser)
- Version [e.g. 22] Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by carhartl** [comment]
Similar to Safari‘s Intelligent Tracking Prevention Brave caps expiration at 7 days. 

Also see: https://www.cookiestatus.com/

**Comment by carhartl** [comment]
Safari: https://github.com/js-cookie/js-cookie/issues/627#issuecomment-626144237

**Comment by krynv** [comment]
This is super useful info, thanks!!

**Comment by FagnerMartinsBrack** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions/1b6c1f7d726979efbe47d7fd76579a88835e44b3#why-is-my-cookie-not-being-set

I've added the sub-topic "It's a browser tracking protection mechanism" in case someone looks at the topic "Why is my cookie not being set?"

The topic "Why is my expiration time capped at 7 days, or 24 hours?" assumes the person knows that it is capped at 7 days, but there are a myriad of security reasons why it may not be setting other than capping to a certain timeframe.

@carhartl Let me know what you think.

**Comment by d4kir92** [comment]
this is a big problem for youtube, after restarting browser it removes the cookie and if it gets created manually its deleted after 7 days, so each week we need to create a cookie manually and i need to accept 100 websites cookies again

[#29591](https://github.com/brave/brave-browser/issues/29591)

**Comment by FagnerMartinsBrack** [comment]
@d4kir92 It's something to take on with Brave and browser vendors. Now something we can fix from js-cookie side.

**Comment by d4kir92** [comment]
ok thx for the info!
