### ISSUE TITLE
Max-Age support

### ISSUE THREAD

**Issue by bckatarzyna** [js-cookie/js-cookie#633]
Hello Everyone,

I'm wondering if you are planning to support Max-Age attribute.

Currently (in 2.2.1 but I see the part of code containing [this line](https://github.com/js-cookie/js-cookie/blob/master/src/api.mjs#L35) hasn't changed a lot) when maxAge is passed as an attribute, there is an error caused by its number type (that can't be split).

**Comment by carhartl** [comment]
No it isn’t planned (due to browsers we support not supporting it). If you want to use it via custom attribute make it a string, that will work: `"Max-Age": "12345678"`.

**Comment by bi-kai** [comment]
"Max-Age": "12345678" and "Max-Age": 12345678 are quite different.

**Comment by MarkLyck** [comment]
It's 2023 now. IE10 has met it's EOS a long time ago, can we please add support for "Max-Age"?

and it is now well documented.

**Comment by carhartl** [comment]
Fwiw, with Max-Age setting a cookie becomes so straight-forward, you don’t need a library..

**Comment by KubaZachacz** [comment]
> What advantages does `max-age` provide over `expires`? As is, the library already provides max-age semantics with the `expires` option, does it matter what‘s being used under the hood for expiring the cookie?

Because when you need a cookie for 5 minutes or 1 hour at first you need to make some weird looking calculations to provide a day fraction to `expires` option, and than instead of just set 3600s as max-age value, js-cookie calculates whole future date

**Comment by carhartl** [comment]
> Because when you need a cookie for 5 minutes or 1 hour at first you need to make some weird looking calculations to provide a day fraction to expires option

In case you didn’t know, it‘s possible to pass a `Date` instance, which should make the whole thing pretty expressive.

> instead of just set 3600s as max-age value, js-cookie calculates whole future date

I‘m aware of the implementation. What exactly is your concern here? Performance?

Use `Max-Age`, but really, you do no longer need a library.

**Comment by carhartl** [comment]
Apart from that, an alternative to expressing your entitlement towards free, open-source software would be to create a pull request 🤷‍♂️

**Comment by carhartl** [comment]
What‘s also funny is that, given we would not be changing the user facing public api, out of a sudden the implementation would contain some weird looking code to transform a Date instance into seconds from now..

**Comment by carhartl** [comment]
Just use: 

```javascript
const maxAge = 3600
document.cookie = `foo=bar; max-age=${maxAge}`
```

**Comment by carhartl** [comment]
And for reading cookies a single regex will do — something we couldn’t use either due to some IE peculiarities. That’s why there is a weird looking, awful for-loop for retrieving a cookie value.
