### ISSUE TITLE
sameSite attribute set to none or an invalid value.

### ISSUE THREAD

**Issue by artoodeeto** [js-cookie/js-cookie#636]
**Describe the bug**
Hello. I have an issue where im getting a warning message on my browser (see attached image below). I'm using js-cookies on the frontend and not using expressjs to set my cookies. I'm wondering how can you set `sameSite` attribute in js-cookies? maybe this will fix my warning.

I'm not using the cookie for validation its just a storage for my JWT because I'm using `bearer TOKEN` schema for the validation though and I'm not sure if im just going to ignore this warning message.

**To Reproduce**

here's the code on how I'm setting my cookie:

```
export function setUpSessionOnLoginAndSignup(response: ILoginSignupResponse, dispatch: Function): void {
  const { payload, meta } = response;
  const { expToken, issueDate } = meta;
  const { user, token } = payload;
  dispatch(onSuccessLoginOrSignUp(Number(expToken), Number(issueDate)));
  dispatch(setupUserOnSuccessLoginORSignup(user));
  Cookies.set(process.env.REACT_APP_COOKIE_NAME as string, token, {
    expires: new Date(new Date().getTime() + Number(expToken)),
    secure: true
  });
}
```

**Expected behavior**

**Screenshots**

<img width="1652" alt="Screen Shot 2020-06-08 at 7 57 20 PM" src="https://user-images.githubusercontent.com/19770382/84606394-ac589e80-ae5a-11ea-91fd-942c8153f6b4.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac Catalina v10.15.5
- Browser [e.g. chrome, safari] Firefox developer edition 
- Version [e.g. 22] 78.0b5

**Smartphone (please complete the following information):**

**Additional context**

**Comment by artoodeeto** [comment]
So I added sameSite by in setting my cookies like. 

```
Cookies.set(process.env.REACT_APP_COOKIE_NAME as string, token, {
    expires: new Date(new Date().getTime() + Number(expToken)),
    secure: true,
    sameSite: 'None'
  });
```
I'm still getting a warning. I followed the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/set-cookie/samesite) about sameSite. I set my cookie to secure so when I set sameSite as 'None' I should not get this warning.

**Comment by carhartl** [comment]
Using `{ sameSite: 'none', secure: true }` I do not get such warning. Maybe a cookie lacking this configuration is shadowing the one - did you try after removing all cookies from your site you're testing in?

**Comment by carhartl** [comment]
This doesn't seem to be an issue with the library though, closing.

**Comment by carhartl** [comment]
It could be interesting to see what's listed in Cookies in the dev tools Storage tab...

**Comment by artoodeeto** [comment]
hello. heres the image of the cookies. 

<img width="533" alt="Screen Shot 2020-06-16 at 4 17 50 PM" src="https://user-images.githubusercontent.com/19770382/84837451-05f0d280-afed-11ea-9dfe-330ed890c94b.png">


still have the same issue when same site is set to none.
