### ISSUE TITLE
i want to got "domain" but got "deafult"?

### ISSUE THREAD

**Issue by mouday** [js-cookie/js-cookie#638]
`Cookies.set("name", "deafult")
Cookies.set("name", "domain", {domain: ".baidu.com"})

Cookies.get("name")
"deafult"

Cookies.get("name", {domain: ".baidu.com"})
"deafult"

`
i want to got "domain" but got "deafult"?

**Comment by carhartl** [comment]
You cannot retrieve cookies by some attribute it was written with.

What’s happening here is that you‘re writing a cookie the second time with a domain attribute, but when reading it it‘s not accessible or it‘s being shadowed by the default cookie.
