### ISSUE TITLE
decode Function chinese decode compatible bug

### ISSUE THREAD

**Issue by paulloo** [js-cookie/js-cookie#639]
**Describe the bug**

```
encodeURI('测试') // "%E6%B5%8B%E8%AF%95%E4%BA%86"
```
But in encode Function we use decodeURIComponent to decode, its not perfect .why not add the Compatibility scheme, like this.
```
s.replace(/(%[0-9A-Za-z]%{2})+/g, decodeURIComponent); 
or
s.replace(/(%[0-9A-Z]%{2})+/g, decodeURIComponent) || s.replace(/(%[0-9A-Z]%{2})+/g, decodeURI); 
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carhartl** [comment]
What version are you using?

**Comment by paulloo** [comment]
> What version are you using?

actually  version 2.2.1
the reason is server side set the cookie like this  "%e6%b5%8b%e8%af%95" lowercase letter ；Obviously its Inconformity， weird.
Thanks for reply!! o(∩_∩)o

**Comment by carhartl** [comment]
Ah, now I get it, this has been in fixed in v3: https://github.com/js-cookie/js-cookie/commit/18ed0fd05ae87f11906ae53545681d36731806e6 but unfortunately we had introduced another problem with v3, so I don't really know what to recommend. You can use v3.0.0-beta.3 to make this work...

**Comment by carhartl** [comment]
(Alternatively, for the time being a custom converter will also work with stable v2.2.1.)
