### ISSUE TITLE
How can i set cookies for 1 subdomain?

### ISSUE THREAD

**Issue by zeeshanaligold** [js-cookie/js-cookie#640]
I want to set cookies on example.com and want it available only on foo.example.com & example.com.

I know I can use .example.com but I don't want to be available for all subdomains. 
Can someone help with this use case?

Thanks,

**Comment by carhartl** [comment]
I think you can set a cookie for a subdomain from a parent domain, so `domain: 'foo.example.com'` should work. 

In the future please refrain from asking usage questions, these issues are for tracking actual bugs in the library. Thanks for consideration.

**Comment by zeeshanaligold** [comment]
But if I do `domain: 'foo.example.com'` then will it be available on parent domain also? 
I need it to be on the parent domain also.

**Comment by carhartl** [comment]
Ah.. that‘s not possible.
