### ISSUE TITLE
Safari 7 days expires limit

### ISSUE THREAD

**Issue by guzich** [js-cookie/js-cookie#642]
Safari 13.11.1 
Setting Cookie expires less than 7 days work good, but when expires > 7 cookie set with expires equal 7 days
php function setcookie has no same problem

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carhartl** [comment]
Part of Safari’s Intelligent Tracking Prevention.

https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-is-my-expiration-time-capped-at-7-days-or-24-hours
