### ISSUE TITLE
Cookie not setting on Microsoft Edge 

### ISSUE THREAD

**Issue by mhikhey371** [js-cookie/js-cookie#651]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carhartl** [comment]
Could you please provide more information? For instance, what does the code look like, the OS, what version of Edge? The current amount of information won’t help is in identifying the problem.

**Comment by mhikhey371** [comment]
// //save token
          db.collection('session-cookie').doc(session_id).set({
            transaction_token
          })
          
          //save token
          Cookies.set('cleavepay_check_id', session_id, { path: '*' });
          // sessionStorage.setItem('Cleavepay_id', transaction_token);
          
         //get cookie
          let cookie = Cookies.get('cleavepay_check_id');

          // set state if cookie exist
          if (cookie){
            setUser(cookie)
            setLoading(false)
          }

-----------------------------------------------
On Edge on Windows 10 | 84.0.522.48

**Comment by carhartl** [comment]
The value given for `path` is wrong. If you want to have a cookie available on every path, omit it altogether; if you want particular paths, provide a *valid* path; if you want the current page only, provide `undefined`.

**Comment by mhikhey371** [comment]
> The value given for `path` is wrong. If you want to have a cookie available on every path, omit it altogether; if you want particular paths, provide a _valid_ path; if you want the current page only, provide `undefined`.

Thank you so much, it worked
