### ISSUE TITLE
none/secure value for sameSite attribute?

### ISSUE THREAD

**Issue by columbian-chris** [js-cookie/js-cookie#652]
The readme lists the possible values for the **sameSite** attribute as `lax` or `strict`, but Chrome 84 is throwing me a message that says 

> A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

Without js-cookie saying "none" is an option to set sameSite to, is this what I'm expected to use to apply it with the secure option?

```js
Cookies.set( 'cookie_name', 'value', { sameSite: 'None;', Secure: true })
```

This returns `cookie_name=value; path=/; sameSite=None; Secure`.

**Comment by carhartl** [comment]
Documentation is outdated (back then there was no “None”). Use “None”.

**Comment by columbian-chris** [comment]
Thanks for the response, @carhartl.

Usage of the "none" value also requires there to be a "Secure" attribute.  Is the solution I provided above the expected way I should accomplish this?

**Comment by carhartl** [comment]
Here's what I would expect:

```js
Cookies.set( 'cookie_name', 'value', { sameSite: 'None', secure: true })
```

https://github.com/js-cookie/js-cookie#secure

**Comment by englishextra** [comment]
Just to notice don't try to test `{sameSite`: 'none', secure: true}` while developing on localhost because it is not `https` and your cookie will not get set at all.

**Comment by marcamos** [comment]
This just helped me, immensely. Not sure why it's not part of the package by default.
