### ISSUE TITLE
Expire date in Safari not working

### ISSUE THREAD

**Issue by bidays** [js-cookie/js-cookie#654]
**Describe the bug**
Setting an expire date in Safari doesn't seem to work while it works under Chrome. 

When putting 365 days, the expire date shown in the console in Safari is always +7 days while in Chrome it shows the right date.

E.G: Cookies.set('name', 'value', { expires: 365 })

I am using Safari on macOS Catalina - Safari Version 13.1.1 (15609.2.9.1.2)

I am testing this on a Wordpress website using MAMP in localhost:8888

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-is-my-expiration-time-capped-at-7-days-or-24-hours
