### ISSUE TITLE
Cookies.get isn't working

### ISSUE THREAD

**Issue by justingolden21** [js-cookie/js-cookie#656]
**Describe the bug**

Cookies either aren't being saved or aren't being retrieved by `get`.

**To Reproduce**

`Cookies.set('name','value')`

> `"name=value; path=/"`

`Cookies.get('name')`

> `undefined`

**Expected behavior**

I get 'value' back

**Screenshots**

![image](https://user-images.githubusercontent.com/30274440/90213055-b559e380-dda9-11ea-9a15-651df183a16b.png)

**Desktop (please complete the following information):**

Windows 10 Home 64 bit

Chrome Version 84.0.4147.125 (Official Build) (64-bit)

CDN:

```<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>```

I've checked the [FAQ](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions) and didn't see anything on this.

**Comment by justingolden21** [comment]
It works fine in Firefox:

![image](https://user-images.githubusercontent.com/30274440/90213432-9c9dfd80-ddaa-11ea-9a20-0102dd01e993.png)

**Comment by carhartl** [comment]
Any particular extension in use in Chrome? Are you trying this on `file://`?

**Comment by justingolden21** [comment]
I am trying it on a `file:///`, do cookies not work on local files in Chrome?

Thank you for the quick response :)

**Comment by carhartl** [comment]
No, they don’t, this is also mentioned in the FAQ.

**Comment by justingolden21** [comment]
I must've missed that, thank you.
