### ISSUE TITLE
Cookie.get() mysteriously stopped working - cookies not being read

### ISSUE THREAD

**Issue by eslachance** [js-cookie/js-cookie#657]
**Describe the bug**
This was working earlier and suddenly didn't, and perhaps I did something to change it but... I wouldn't begin to know what. 

**Setup**
This is a react project, created through `razzle`. The only js-cookie related code is in an imported component at the top of every page. here's the code: 

```js
import React from "react";
import { useDispatch } from 'react-redux';
import { unwrapResult } from '@reduxjs/toolkit';
import Cookies from 'js-cookie';
import { checkToken } from '../store/user';

import { useHistory } from "react-router-dom";

const CheckAuth = () => {
  const dispatch = useDispatch();
  const history = useHistory();
  const token = Cookies.get('token');
  console.log(Cookies.get());
  console.log("token", token);
  if(token) {
    dispatch(checkToken(token))
      .then(unwrapResult)
      .then(res => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
        history.push('/');
      })
  }
  return (<></>);
}

export default CheckAuth;
```

The output I get from this:
```
{}__proto__: Object
token undefined
```

**Expected behavior**
Cookie.get("token") should see the token cookie

**Screenshots**
![image](https://user-images.githubusercontent.com/643344/90327191-124aca80-df5f-11ea-9ed9-f217c6144ae1.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home Insider Preview build 20190
- Browser: Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- Version: js-cookie 2.2.1

**Comment by carhartl** [comment]
The screenshot indicates that the cookie `token` is `HttpOnly`, as such it cannot be accessed in client-side scripting.

Please see https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#youre-using-httponly-true as well.

**Comment by eslachance** [comment]
Ah, the confusion came from the FAQ saying "I can't **set** the cookie", not that I couldn't **get** it. Thank you!

**Comment by carhartl** [comment]
Makes sense, the headline is misleading, going to improve it.
