### ISSUE TITLE
Can't set cookie for cross-domain

### ISSUE THREAD

**Issue by tamzidoronno** [js-cookie/js-cookie#658]
I am on the nuxt project, where the host is 'example.wow'. I want to set a cookie for 'example.xyz' with
`Cookies.set('my_cookie',$cookie_variable, { domain: '.' + 'example.xyz' })`

But its not working, the cookie seems to be saved only for the .wow domains, not cross-domains

**Comment by carhartl** [comment]
You cannot set cross-domain cookies.
