### ISSUE TITLE
This line may have a useless error. at "src/api.mjs" 54 line

### ISSUE THREAD

**Issue by mengfei0053** [js-cookie/js-cookie#659]
**Describe the bug**
```js
// src/converter.mjs
export default {
  read: function (value) {
    return value.replace(/%3B/g, ';')
  },
  write: function (value) {
    return String(value).replace(/;/g, '%3B')
  }
}
```
```js 
src/api.mjs 
  function get (key) {
    if (typeof document === 'undefined' || (arguments.length && !key)) {
      return
    }

    // To prevent the for loop in the first place assign an empty array
    // in case there are no cookies at all.
    var cookies = document.cookie ? document.cookie.split('; ') : []
    var jar = {}
    for (var i = 0; i < cookies.length; i++) {
      var parts = cookies[i].split('=')
      var value = parts.slice(1).join('=')
      var foundKey = defaultConverter.read(parts[0]).replace(/%3D/g, '=')
      jar[foundKey] = converter.read(value, foundKey) // Why does this read function have only one argument, and here two are passed in?

      if (key === foundKey) {
        break
      }
    }
    return key ? jar[key] : jar
  }
```

**Expected behavior**
I tried to remove the second parameter, "foundKey", and found that it was normal.

**js-cookie version:**

- Version [e.g. 22]  3.0.0-rc.0

**Comment by carhartl** [comment]
The idea is that _custom_ converters are being called with two arguments, the cookie value and name. We must adhere to this contract even when we’re not making use (and thus omitting the argument) for the built-in converter.

https://github.com/js-cookie/js-cookie/blob/54962f884e9ae33f93e13ac903ffaf1d5a523598/test/tests.js#L352

**Comment by carhartl** [comment]
Looks like the referenced test has been removed by accident while working on v3.

**Comment by carhartl** [comment]
Removed in b22e6cbf6d3279572b212c95f524067f34405259, but this commit will have to be reverted anyway, because of #623

**Comment by mengfei0053** [comment]
Thank you for your answer. Do you want to rewrite the library using Typescript or add JSDoc to your code?

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#can-you-rewrite-the-library-in-typescript
