### ISSUE TITLE
How to listen to cookies created by js-cookies with addEventListener ? 

### ISSUE THREAD

**Issue by ImSolitude** [js-cookie/js-cookie#661]
I'm new to this,

But how can I listen to cookies created with this library, `window.addEventListener("storage", listenerFunc);` is not working. Cookies are not stored in Chrome's Application -> LocalStorage tab.

**Comment by carhartl** [comment]
This library is for working with cookies, LocalStorage is something different and not relevant here.

**Comment by carhartl** [comment]
https://medium.com/swlh/cookies-vs-localstorage-whats-the-difference-d99f0eb09b44
