### ISSUE TITLE
Cookies.get('shopOrigin') undefined

### ISSUE THREAD

**Issue by cedriclajato** [js-cookie/js-cookie#662]
I have cookie set

![cookie-set](https://user-images.githubusercontent.com/57404000/93659195-586ede80-fa75-11ea-9616-bd94525960d9.PNG)

I tried to log it

![log-cookie](https://user-images.githubusercontent.com/57404000/93659203-6a508180-fa75-11ea-97d0-5d2334ae7172.PNG)

But it responded undefined even though it's set correctly

![undefined](https://user-images.githubusercontent.com/57404000/93659207-79373400-fa75-11ea-853e-a32e75a65140.PNG)

**Comment by carhartl** [comment]
Is that possibly a `HttpOnly` cookie?

https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-cant-i-get-a-particular-cookie

**Comment by cedriclajato** [comment]
No, I actually use httpOnly = false.

![httponly-false](https://user-images.githubusercontent.com/57404000/93661819-7fd1a580-fa8d-11ea-9b22-5b3ead6952ec.PNG)

**Comment by carhartl** [comment]
Could you post the result of `document.cookie` here? Also, what does the developer console say about the cookie attributes

**Comment by cedriclajato** [comment]
Oh, looks like on the console it says undefined but when I checked on browser console it's indeed has value.

**Comment by carhartl** [comment]
Not sure which two types of consoles you are now referring to. Could you paste the return value of `document.cookie` here?

**Comment by cedriclajato** [comment]
I followed the shopify tutorial and they recommend your module https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris

I think the console/terminal is undefined because you're using document and since it's node so there's no document at all.

But on browser console cookie shows the value.
