### ISSUE TITLE
Cookies.get() return undefined in react 

### ISSUE THREAD

**Issue by RitikPandey1** [js-cookie/js-cookie#669]
**Describe the bug**
Cookies.get() return undefined in reactjs 

**Screenshots**
![bug](https://user-images.githubusercontent.com/57366926/97784889-c73c6d00-1bc7-11eb-9db0-0b42e0b41902.PNG)

.

**Desktop (please complete the following information):**

- OS: windows 10
- Browser:  chrome 
- Version : 86.0.4240.111

**Comment by carhartl** [comment]
There‘s not enough information given in order to allow us finding the problem. We have tests that prove the functionality in question is working.

Maybe the “jwt” cookie is http only?

**Comment by RitikPandey1** [comment]
jwt cookie are sent with `httpOnly=false,` but still getting undefined in react application
