### ISSUE TITLE
escape is deprecated

### ISSUE THREAD

**Issue by peredozo** [js-cookie/js-cookie#671]
https://github.com/js-cookie/js-cookie/blob/eceefcc0be5bcb07d6ca32b03978e2c6f8cc848e/src/api.mjs#L21

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

You can replace this:
`.replace(/[()]/g, escape)`
like this:
`.replace(/\(/g, '%28').replace(/\)/g, '%29');`

**Comment by carhartl** [comment]
If the ECMAScript host is a web browser `escape` is required to be present and will not go away:

> However, the usage of these features by large numbers of existing web pages means that web browsers must continue to support them.

and

> ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser

https://www.ecma-international.org/ecma-262/6.0/#sec-additional-ecmascript-features-for-web-browsers

**Comment by carhartl** [comment]
However, it might be worth giving it a try to see whether this may reduce the minified, gzipped size of the library.

**Comment by carhartl** [comment]
>However, it might be worth giving it a try to see whether this may reduce the minified, gzipped size of the library.

No, size increased with the given change.
