### ISSUE TITLE
Cookie has been removed but warning message still appears in Firefox

### ISSUE THREAD

**Issue by merccstarr** [js-cookie/js-cookie#672]
**Overview**
Used Cookies.remove() but still receiving the warning message in Firefox:
 _...will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute..._

Using Cookies.remove() should remove a Cookie entirely but if you console.log the following in js.cookie.js within the api function:

`document.cookie = key + '=' + value + stringifiedAttributes`

Then the cookie will still appear but without the secure and SameSite attribute which results in a warning message in Firefox. 

**Steps to reproduce the behavior:**
1. Create a cookie Cookies.set("CookiesEnabled", true, { expires: 365, secure: true, sameSite: "none" });
2. Remove the cookie you have just created with Cookies.remove("CookiesEnabled");
3. Go to Firefox and open up Dev Tools and you will see a warning about the cookie you have made being rejected as the attributes are not set correctly.

JavaScript Cookie v2.2.0
Firefox 82.0.2

**Expected behavior**
No warning messages in the dev tools to appear in Firefox as we have removed the cookie so it shouldn't be flagging it as a warning.

**Screenshots**
This is the full warning message
![image](https://user-images.githubusercontent.com/74257318/98699202-cbf2e500-236e-11eb-9478-f246a93ea3c3.png)

**Comment by carhartl** [comment]
Technically, the only way to remove a cookie is writing one with an outdated expiration date. As such Firefox may warn about the missing attributes, but there‘s nothing we can do about this, and you might want to file a bug for Firefox instead.

**Comment by carhartl** [comment]
PS: I think you can use default attributes in order to workaround this: https://github.com/js-cookie/js-cookie/tree/latest#cookie-attributes

E.g. make the desired `secure` and `sameSite` attributes defaults so that `remove()` is going to pick them up.
