### ISSUE TITLE
Documentation example of how to run JavaScript Animation only once

### ISSUE THREAD

**Issue by Allmedialab** [js-cookie/js-cookie#674]
Hi,

Could someone be so kind to show me how to achieve that a animation only runs once on a webpage?
I mean how do I set a cookie to prevent a script from running more then once for one visitor on a website?

Regards & Thanks,
David

**Comment by Allmedialab** [comment]
Thanks a lot! Guess you know everything!

**Comment by carhartl** [comment]
We’re using issues for tracking actual issues and actual feature requests. We don’t have the capacity for answering general questions regarding usage.
