### ISSUE TITLE
Model not close on click on the save button

### ISSUE THREAD

**Issue by LMG-Jeffy** [js-cookie/js-cookie#675]
I am having some trouble saving a custom cookie setting. The model does not close. The settings are saved correctly because when I refresh the page or use the cross, the correct cookie is created.

Chrome Version 86.0.4240.198 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/17408698/100614823-053bc680-3317-11eb-9935-4d6496d2284a.png)

Is this a bug or a misconfiguration! Thanks in advance.

**Comment by LMG-Jeffy** [comment]
It can also be a UI experience. I expect that if I press save that the modal will close. But maybe that is not the intention and should the cross be clicked again?

**Comment by carhartl** [comment]
@LMG-Jeffy 

Could you explain what this has to do with this library?

**Comment by LMG-Jeffy** [comment]
Monday! My apologies, I'm in the wrong project making an issue,
