### ISSUE TITLE
updating a cookie failing unless deleted first

### ISSUE THREAD

**Issue by lastlink** [js-cookie/js-cookie#676]
**Describe the bug**
If a cookie is already set, when calling the set, it fails, if I delete it before this works fine.  Using it in vuex-persistedstate https://www.npmjs.com/package/vuex-persistedstate#customize-storage

**Comment by carhartl** [comment]
Could you provide a way to reproduce this?

**Comment by lastlink** [comment]
I ended up calling js-cookie directly and stopped using the plugin. but I was using the default setup with js-cookie from the link.
