### ISSUE TITLE
Expires not being set .

### ISSUE THREAD

**Issue by TroyDota** [js-cookie/js-cookie#679]
**Describe the bug**
Expires token not being set and cookie is expiring in at end of Session

**To Reproduce**

```
let options ={ expires: new Date(new Date().getTime() + 60 * 24 * 60 * 60 * 1000) } //60 days
Cookie.set("auth", tokens!.auth, options);
Cookie.set("refresh", tokens!.refresh, options);
```

results in 
```
document.cookie
"refresh=xd; auth=yikes"
```

**Expected behavior**
The Cookies to have an expiry

**Screenshots**
![image](https://user-images.githubusercontent.com/49777269/102495770-32120c80-407f-11eb-840e-53c66d89a21d.png)

**Comment by TroyDota** [comment]
im dumb. sorry

**Comment by smasinde** [comment]
spill the beans, some of us aren't doing so well either

**Comment by TroyDota** [comment]
I was setting it twice.
