### ISSUE TITLE
Cookie not being set in Chrome and Safari but FF fine.

### ISSUE THREAD

**Issue by smasinde** [js-cookie/js-cookie#680]
**Describe the bug**
I'm able to save the cookie in firefox but in chrome and safari, nothing.

**To Reproduce**

`Cookies.set("vue-app", cookie);`

**Expected behavior**
Sets the cookie in Chrome and Safari

- OS: MacOS Big Sur 11.1
- Browser chrome, safari
- Version [87.0.4280.88 (Official Build) (x86_64), 14.0.2 (16610.3.7.1.9)]

**Comment by carhartl** [comment]
This?

https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#you-are-using-the-file-protocol

**Comment by smasinde** [comment]
> This?
> 
> https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#you-are-using-the-file-protocol

No, I'm writing a vuejs application served using vite.. i interact with the app through localhost

**Comment by carhartl** [comment]
In that case the snippet and information you provided clearly isn’t sufficient in order to debug this.

**Comment by carhartl** [comment]
Do you see a cookie in Chrome when using `document.cookie`?

**Comment by smasinde** [comment]
What else do you need? Like I said, it works in Firefox, but strangely does not in Chrome and Safari.

**Comment by smasinde** [comment]
`document.cookie` is empty

**Comment by carhartl** [comment]
> What else do you need?

A test case allowing to reproduce the problem would be most helpful. Our tests show that the code you have given us is working. Thus there must be another factor at play. 

What happens in Chrome if you write a cookie using `document.cookie`, e.g. `document.cookie = "foo"`? Is `document.cookie` still empty afterwards? (If so, you‘d at least know that there‘s something in Chrome, like disabled cookies, that is interacting.)

**Comment by carhartl** [comment]
Ah, if it‘s both Chrome and Safari, could be something webkit related, tracking prevention maybe.

**Comment by smasinde** [comment]
> > What else do you need?
> 
> A test case allowing to reproduce the problem would be most helpful. Our tests show that the code you have given us is working. Thus there must be another factor at play.
> 
> What happens in Chrome if you write a cookie using `document.cookie`, e.g. `document.cookie = "foo"`? Is `document.cookie` still empty afterwards? (If so, you‘d at least know that there‘s something in Chrome, like disabled cookies, that is interacting.)

Let me try and get a minimal setup going and share it.. 

when I execute `document.cookie = "foo"` the cookie is created

**Comment by smasinde** [comment]
Ok so to reproduce:

`yarn create vite-app cookie-repro
cd cookie-repro
yard add js-cookie
`
then in the `src/App.vue` file update:

`<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3.0 + Vite" />
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";
**import * as Cookies from "js-cookie";**

export default {
  name: "App",
  components: {
    HelloWorld,
  }**,
  setup() {
    Cookies.set("repro", "duction", { secure: true, sameSite: "lax" });
  },**
};
</script>
`

Then run `yarn dev`

as you will see the cookie will set in FF but not the others.

**Comment by carhartl** [comment]
I’m seeing `secure: true` there in the cookie attributes. Do you serve the application from https accordingly?

**Comment by smasinde** [comment]
> I’m seeing `secure: true` there in the cookie attributes. Do you serve the application from https accordingly?

No, I was not serving it from localhost.

I removed the attribute and it is now working. 

Thank you so much!

**Comment by InclinedScorpio** [comment]
Hi, I serve mine from https and have secure: true, still it's not working. Have been 3 days fixing it now. Here is the BACKEND URL: https://subleaseit-help.wl.r.appspot.com
FRONTEND URL: https://subleaseit-390202.wl.r.appspot.com

Any help is really appreciated : )

**Comment by carhartl** [comment]
@InclinedScorpio Looks like two different domains..
