### ISSUE TITLE
Cookie setting fails silently when having value contains "/r/n"

### ISSUE THREAD

**Issue by khaledbnmohamed** [js-cookie/js-cookie#681]
**Describe the bug**
When trying to add a value to the browser cookie ex        
` Cookies.set(EMPLOYEE_DATA_COOKIE, { id: 1, value: " I'm a value /r/n that fails" }, { domain: cookiesDomain });`

Cookies don't get set and it doesn't return any errors just fails silently

**To Reproduce**

1.` Cookies.set("test", { id: 1, value: " I'm a value /r/n that fails" });`

**Expected behavior**
Cookies should be set correctly for the "test" key

**Screenshots**

**Comment by carhartl** [comment]
I'm assuming you meant the control characters `\n` \r`? I can set them without problems testing in latest Firefox:
<img width="1186" alt="Screenshot 2021-01-12 at 17 32 15" src="https://user-images.githubusercontent.com/21918/104343574-605afe80-54fc-11eb-8140-a10196db49c8.png">

(`/r/n` works just as well)

Could you provide further information please? Could it be `domain` interfering in your case?

**Comment by khaledbnmohamed** [comment]
While trying to reproduce the issue with the real data I have. I found that the main problem was that my cookie size  4KB that's why it was failing, but I guess it might need a more obvious error for this reason without failing silently? but I'll close it for now. Thanks for your help
