### ISSUE TITLE
Added Support to HttpOnly Attribute

### ISSUE THREAD

**Issue by thadeu** [js-cookie/js-cookie#683]
Whats the chance add support to httpOnly flag?

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#youre-trying-to-use-httponly-true

**Comment by MilamBardo** [comment]
But sometimes we're wanting to set the cookie from server side, to respond to a set cookie request.  That cookie is httponly.

**Comment by carhartl** [comment]
It‘s impossible to access httponly cookies from client-side scripts. What else can I say?
