### ISSUE TITLE
Auto encoded string when using without converter

### ISSUE THREAD

**Issue by domenikTC** [js-cookie/js-cookie#684]
I switched from v3.0.0-rc.0 to v3.0.0-rc.1 an noticed that I can't write an unencoded JSON.stringify value to a cookie without using a converter anymore. Is this a desired behavior?

I think it is related to this commit: https://github.com/js-cookie/js-cookie/commit/b84a35b2d6259c445deac5cc6cc3d2bc21b7be61

**v3.0.0-rc.0**
Cookies.set('name', JSON.stringify([1, 12345])); => [1, 12345]

**v3.0.0-rc.1**
Cookies.set('name', JSON.stringify([1, 12345])); => [1%2C12345]

Cookies.set('name', [1, 12345]); => [1%2C12345]

Cookies.withConverter({
   write: function (value) {
      return JSON.stringify(value)
   }
}).set('name', [1, 12345]); => [1, 12345]

**Comment by carhartl** [comment]
I think this was in fact a regression in rc.0.

**Comment by carhartl** [comment]
We need to encode certain characters in the output/written value, thus don’t expect the written value necessarily to match what you had passed into `set()`. The getter takes care of that when reading the cookie.

**Comment by carhartl** [comment]
PS: If you want the value to be written unaltered then, yes, you will need a converter. But you risk cookies not being written in certain browsers, in particular Safari.

**Comment by domenikTC** [comment]
Thanks for the clarification. I can cope with that.
