### ISSUE TITLE
Vue - cookie getting deleted when refresh page 

### ISSUE THREAD

**Issue by jorgito232** [js-cookie/js-cookie#686]
**Describe the bug**
I´m creating a single token to store a max of 30 characters but after the page is refreshed all my secured token are disappearing. as I red on the wiki, I have everything correct

**To Reproduce**

create the code below

![image](https://user-images.githubusercontent.com/26043766/107160130-56dd7e80-6962-11eb-9431-a0f6be10fc8b.png)

refresh the page after any cookie had been created

**Expected behavior**
keep my secure cookies

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome Versión 88.0.4324.146 and Edge Versión 88.0.705.63
- js-cookie": "^2.2.1"

**Comment by carhartl** [comment]
Do you serve your Vue application from https where this is happening?

**Comment by carhartl** [comment]
@jorgito232 Are you able to provide further information here?

**Comment by carhartl** [comment]
Also, in case you need to support Safari or Brave, please note that an expiration of 180 days won't work due to tracking protection. Will be capped to 7 days at maximum, more information here: https://www.cookiestatus.com

**Comment by carhartl** [comment]
Closing due to lack of feedback.
