### ISSUE TITLE
Cookie wasn't removed when I closes the browser.

### ISSUE THREAD

**Issue by sanvuthy** [js-cookie/js-cookie#69]
I have notice on document on "expired" section said that "Cookie is removed when user closes the browser.", but when I try to use this library it wasn't removed when I closed the browser. 

Please advice me.

**Comment by FagnerMartinsBrack** [comment]
Which browser? Which OS? [Did you closed all instances of the browser](http://stackoverflow.com/questions/30185501/trouble-with-setting-jquery-cookie/30227827)? Do you have a code example that fails?

**Comment by sanvuthy** [comment]
I'm using Chrome Version 44.0.2403.125 (64-bit). OS X Version 10.9.5.

Cookies.set('cookie_name', { items: json_object });
Cookies.getJSON('cookie_name');

**Comment by FagnerMartinsBrack** [comment]
Check [this answer](http://stackoverflow.com/a/10772420) in stackoverflow and make sure "Continue where you left off" setting is disabled in Google Chrome.

Despite that, I have made some tests and identified a condition where the cookie appears not to be deleted. I created a detailed bug report in Chromium bug tracker: [516908](https://code.google.com/p/chromium/issues/detail?id=516098)

**Comment by FagnerMartinsBrack** [comment]
Closing for now due to the lack of feedback from the OP. It appears to be something related to a browser issue.
