### ISSUE TITLE
Cookies.set with the same key failed after expires

### ISSUE THREAD

**Issue by acid122** [js-cookie/js-cookie#691]
I just tried to set cookie with the option expires (for example, 1 min), after the cookie expires and disappears in the "application" tab in the dev panel. I found that it is failed to try to set the cookie with the same key. Does anyone else face the same problem, and ths in advance for any tips:)
Btw, I found that when any cookie expired, it failed to set cookies with any key (including the same key).
Chrome: 90.0.4430.212
Env: Win10 pro
js-cookie: 2.2.1
hostname: localhost

**Comment by carhartl** [comment]
Could you show us the actual code that you‘re using?

**Comment by acid122** [comment]
Sorry for this post, the reason is I set with the same expire time (in type number), and the expire time already passed when I tried to set again.

**Comment by acid122** [comment]
@carhartl ths

**Comment by carhartl** [comment]
Are you using “localhost” as domain name in the cookie attributes? If so, please see https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762
