### ISSUE TITLE
CND UMD js cookie doens't work. Gives "Uncaught ReferenceError: module is not defined" Error

### ISSUE THREAD

**Issue by yizongk** [js-cookie/js-cookie#698]
**Describe the bug**
In your README.md:
```
CDN

Alternatively, include it via jsDelivr CDN:

UMD:

<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
```

I tried to add this link on the html, and run it in the Firefox, Chrome and Edge, and I get this error:
"Uncaught ReferenceError: module is not defined"

Because of this error, I am not able to use the variable Cookie, like so:
```
var csrftoken = Cookies.get('csrftoken');
```
Instead, I will get this error: "ReferenceError: Cookies is not defined"

Note: This CDN was working a day or two ago, or at least a week ago, and only recently broke some of my sites (The error only started happening today July 14th 2021 for me).

I have opened a stackoverflow question about this:
https://stackoverflow.com/questions/68383988/firefox-and-chrome-error-when-linking-js-cookie-uncaught-referenceerror-module?noredirect=1#comment120856728_68383988

**To Reproduce**

1. Open up this link: https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js
2. Copy the content in there
3. Open any browser and its console (By pressing Ctrl+Shift+i)
4. Paste your content into the console and press enter:
5. like so:
![image](https://user-images.githubusercontent.com/22630760/125684071-4fd607e4-e435-46b9-ba2c-0904f2073abb.png)
6. It will output: "Uncaught ReferenceError: module is not defined"

**Expected behavior**
After you run step 4 above, when you run the following, it shouldn't give an error:
```
var csrftoken = Cookies.get('csrftoken');
```

**Screenshots**
This is the line causing the error.
![image](https://user-images.githubusercontent.com/22630760/125683443-c6a002bc-da01-40ba-94f0-b91826bab2b9.png)
Looks like it's in CommonJS style instead of UMD style

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser
     Chrome Version 91.0.4472.114 (Official Build) (64-bit)
     Edge Version 91.0.864.67 (Official build) (64-bit)
     Firefox Version 89.0 (32-bit) 

**Additional context**

**Comment by Elte156** [comment]
This is also affecting our production websites.

We've been using this CDN URL without issue since May 2020.
`<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>`

![image](https://user-images.githubusercontent.com/6825856/125696343-2e4b6713-c449-446e-b098-08bb0a7f8911.png)
![image](https://user-images.githubusercontent.com/6825856/125696300-b6065353-ac4c-4c30-a8c6-bc2fec9fe15c.png)

We possibly need to target a specific version as the url above is returning version `3.0.0-rc.2`: https://cdn.jsdelivr.net/npm/js-cookie@3.0.0-rc.2/dist/js.cookie.js

**Comment by eperezf** [comment]
It is also affecting our production websites. It was working a couple of days ago.

**Comment by Elte156** [comment]
Our solution will be to use:
`<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0-rc.1/dist/js.cookie.min.js"></script>`
until this breaking change is resolved.

**Comment by carhartl** [comment]
A release candidate introduced a breaking change. For the release candidate use this reference:

```
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.umd.min.js"></script>
```

**But I strongly advise to use the latest stable version for production environments.**

https://github.com/js-cookie/js-cookie/tree/latest#direct-download

**Comment by realityking** [comment]
Or, just really on the hint js-cookie gives to jsdelivr and use this URL: `https://cdn.jsdelivr.net/npm/js-cookie@rc`

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-rc.4
