### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by thk-root** [js-cookie/js-cookie#700]
I'm sure you're aware of this specific issue, but I highly encourage you to make it backwards comptabile.

This broke our production code, which heavily relies on frontend cookies and we have no clue how much issues that caused, but we're aware that there should be plenty.

We rolled back to version 2, which now works fine, but I implore you, to not push versions, that are incompatible, on the latest CDN release.

Nevertheless, amazing library.

Thanks!

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-rc.4
