### ISSUE TITLE
DO you guys change the CDN url often?

### ISSUE THREAD

**Issue by RoNyx164** [js-cookie/js-cookie#701]
Hi. today I found out that the url of the CDN had changed and the banner for the cookies on my site was not working. Just wanted to know if you change the CDN url often or was just something rare?

Previous: <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>

Today: <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

or was the trouble in the /dist and /src in the url, I don't know maybe when I copied it the first time...

**Comment by carhartl** [comment]
Wasn't on purpose.

I strongly advise not to use beta or rc versions in production.

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-rc.4
