### ISSUE TITLE
question: Typescript typings for js-cookie V3?

### ISSUE THREAD

**Issue by roddypratt** [js-cookie/js-cookie#717]
I've just tried upgrading to V3 and it looks like the DefinitelyTyped typings are out of step with the new module structure.

`import * as Cookies from "js-cookie"`
`let test = Cookies.get("MyCookie")`

...gives...
_export 'get' (imported as 'Cookies') was not found in 'js-cookie' (possible exports: default)_

Should I flag that in the DefinitelyTyped project rather than here?

**Comment by carhartl** [comment]
Yes!

**Comment by carhartl** [comment]
I‘m working on https://github.com/carhartl/ts-cookie

**Comment by carhartl** [comment]
The typings are definitely (no pun intended!) out of step, but what happens if you write:

```
import Cookies from "js-cookie"
```

**Comment by roddypratt** [comment]
@carhartl This:

Module '"c:/proj/.yarn/cache/@types-js-cookie-npm-2.2.7-025262d629-8a45b2a60f.zip/node_modules/@types/js-cookie/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

index.d.ts(115, 1): This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

I can try enabling `allowSyntheticDefaultImports` but that's not ideal...

**Comment by miguel-krasamo** [comment]
I'm facing the same issue, adding types or even declaring it as a module in types will not be enough to make it work.

**Comment by roddypratt** [comment]
'issue' on DefinitelyType is here https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54767

**Comment by FagnerMartinsBrack** [comment]
Ping @theodorejb, contributor of types for js-cookie since js-cookie/js-cookie#50. He might be able to help on this.

**Comment by carhartl** [comment]
There's https://github.com/carhartl/typescript-cookie now which provides fully compatible type definitions for js-cookie.
