### ISSUE TITLE
Typescript definitions are out of date

### ISSUE THREAD

**Issue by Meemaw** [js-cookie/js-cookie#718]
`@types/js-cookie` should be updated to match the `3.0.0` release of `js-cookie`

**Comment by carhartl** [comment]
We are not the maintainers of these typings. Please see #717 and https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54767

**Comment by carhartl** [comment]
There's https://github.com/carhartl/typescript-cookie now which provides fully compatible type definitions for js-cookie.

**Comment by jakemayfield** [comment]
> There's https://github.com/carhartl/typescript-cookie now which provides fully compatible type definitions for js-cookie.

Unfortunately: "This repository has been archived by the owner on Jul 8, 2023. It is now read-only."
