### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by Maaark** [js-cookie/js-cookie#72]
I'm running 5.1.1 on my Android device and I'm using Chrome, but it doesn't seem to set or receive the cookies. But the image says it's supported?

**Comment by FagnerMartinsBrack** [comment]
Yes, js-cookie runs a lot of tests in Android 5.1 automatically on every commit. The image represents the current state of js-cookie tests in Android 5.1, if this is not working in your case, then it means there is something wrong going on.

Can you please post the simplified code that you are using in Android 5.1 that fails to set the cookie?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP, we need a [simplified code](http://sscce.org/) sample that is failing to be able to take any action on this issue.

**Comment by Purushoth-ltr** [comment]
I'm running 5.0.1 on my android device and implementing this  in phonegap app. Setting a JSON array in the cookie. It's working fine with IOS app (v 9.0.2). But `Cookies.set('Schedules', { date: 'dates', start:'Start_time', end: 'End_time' })`.

When i set the same cookie inside android its not working. Tried with [https://github.com/js-cookie/js-cookie/releases/tag/v2.1.3](url) minified js and also Raw js from [https://raw.githubusercontent.com/js-cookie/js-cookie/master/src/js.cookie.js](url). 

Am i missing anything else?

**Comment by FagnerMartinsBrack** [comment]
@Purushoth-ltr Please provide an [SSCCE](http://sscce.org/), otherwise there's nothing we can do.

**Comment by Purushoth-ltr** [comment]
<div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="js/js.cookie.js"></script>
        <script>
        
            window.onload = function () {
                console.log("window.load");
                
                Cookies.set('foo', [{ date: 'bar' , start: 'bar1', end: 'bar2' },{ date: 'bar3' , start: 'bar4', end: 'bar5' },{ date: 'bar' , start: 'bar7', end: 'bar8' }]);
            }
        
            $(document).ready(function(){
                              
                              var found = false;

                              setInterval(function(){

                                          if (typeof Cookies('foo') === 'undefined'){
                                            alert('No cookie foo');
                                            Cookies.remove('foo');
                                          } else {
                                            for(var i = 0; i < Cookies.getJSON('foo').length; i++) {
                                                if (Cookies.getJSON('foo')[i].date == 'bar') {
                                                    found = true;
                                                    alert('found');
                                                    break;
                                                }
                                          }
                                          alert(Cookies.getJSON('foo').length);
                                          }
                                         
                                          }, 60000);
                              
                                });
                   </script>


this is my code.

**Comment by FagnerMartinsBrack** [comment]
@Purushoth-ltr This does not qualify as an [SSCCE](https://sscce.org) because it is too much code. Can you please provide a simple example without HTML?

**Comment by Purushoth-ltr** [comment]
@FagnerMartinsBrack 
 
`$(document).ready(function(){                              
       Cookies.set('foo', 'bar');
       if (typeof Cookies('foo') === 'undefined'){
                alert('No cookie foo');
      }
       else {
                alert('cookie foo found');
         }
});`

Is this ok? In IOS i get the alert `cookie foo found`. But in android it always goes into if condition.

**Comment by FagnerMartinsBrack** [comment]
Take a look in the following issues https://github.com/js-cookie/js-cookie/issues/226 and https://github.com/js-cookie/js-cookie/issues/227 to see if they might be causing the issue.

If not, please create a new issue printing the `document.cookie` value before you call `Cookies.get()`. The common case seems to be working, since we test in on Android: https://saucelabs.com/u/js-cookie. It might be some external state of the browser cookies that is influencing on the behavior of the library.

**Comment by Purushoth-ltr** [comment]
Thanks @FagnerMartinsBrack. I'll look into it.
