### ISSUE TITLE
Saving session cookies to display pop-ups in Chrome

### ISSUE THREAD

**Issue by milad-abedini** [js-cookie/js-cookie#721]
I wrote a pop-up using js-cookie to be displayed to the user only once in each browser session At the moment, this code works well in Firefox browser and if we refresh the page, the pop-up will not be displayed again, but in other browsers such as Chrome and Edge, when we refresh the page, the pop-up will be displayed again. Where do you think the problem is?

`index.html`

          <!DOCTYPE html>
          <html lang="en" >
          <head>
            <meta charset="UTF-8">
            <title>popup session</title>
            <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'>

          </head>
          <body>
          
          <div class="container mt-5">
            <h1>js-cookie</h1>

            
            <div class="modal fade" id="MyModal" tabindex="-1" role="dialog" aria-labelledby="MyModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="MyModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="embed-responsive embed-responsive-16by9">
                      Test
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
          
            <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
          <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'></script>
          <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'></script>
          <script src='https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js'></script><script  src="./script.js"></script>

          </body>
          </html>

`script.js`
`
$(document).ready(function() {
  if (document.cookie.indexOf("FooBar=true") == -1) {
    document.cookie = "FooBar=true; max-age=86400"; // 86400: seconds in a day
    $('#MyModal').modal('show');
  }
});
`

**Comment by carhartl** [comment]
Can‘t see where you are using js-cookie at all in all the code you gave.
