### ISSUE TITLE
Set method not working on iPhone

### ISSUE THREAD

**Issue by kcubero27** [js-cookie/js-cookie#722]
First of all, thanks for your huge contribution! 🎉 

**Describe the bug**
We are using js-cookie to set a JWT token so that it can be used in the Authorization header. However, when setting the cookie in a mobile phone, the Cookies.set method seems not to work.

When using a laptop, the set method works like a charm and the cookie is set into the document.cookie. However, when doing the same steps using a mobile phone, the cookie is not set into the document.cookie.

Our code looks like this:
```
if (typeof window !== 'undefined') {
      Cookies.set(COOKIE_ACCESS_TOKEN, token, {
        secure: true,
        sameSite: 'strict',
      });
    }
```
COOKIE_ACCESS_TOKEN is 'a_t' and token is a JWT. We are using Next.js as the framework.

**To Reproduce**

1. Use an iPhone
2. Open Chrome or Safari browsers
3. Go to https://xceed.me/authenticate and login
4. An error message will appear saying the header cannot be empty

Consider that it doesn't happen all the time, it's only sometimes.

**Expected behavior**
Every time Cookies.set method is called, the cookie should be set and Cookies.get should return the value saved previously.

**Smartphone (please complete the following information):**

- Device: iPhone Xs
- OS: iOS 14.7.1
- Browser: Chrome and Safari
- Version: Chrome 92.0.4515.90, Safari 14

**Additional context**
I don't believe it's a library issue. In fact, I think it's more a problem from our side on how we are using the library. I was hoping you could help me to fix it 🤞🏻

**Comment by carhartl** [comment]
What‘s the size of your JWT token? I‘ve seen before that the size of a JWT token exceeded the possible size and then the cookie doesn’t get written in the first place..

**Comment by kcubero27** [comment]
Hi @carhartl There is no fixed size. For example, mine is around 873 characters. I didn't realize that could be a problem. I was more focused on the access of the document.cookie, the cookie name, etc. I'll check it out if that's the issue. Thank you a lot!!

**Comment by carhartl** [comment]
It‘s not consistent across browsers.. here for instance is some more information: https://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key

**Comment by kcubero27** [comment]
I'll close this issue due to the fact that seems that is related to the token length.

Thanks @carhartl again!

**Comment by kcubero27** [comment]
In case somebody else sees this, seems that Safari blocks the set of the cookie. We have decided to move to localStorage instead.


https://www.macworld.com/article/232426/apple-safari-removing-do-not-track.html
https://webkit.org/blog/7675/intelligent-tracking-prevention/
