### ISSUE TITLE
how do we get expires value from the cookie?

### ISSUE THREAD

**Issue by encryptblockr** [js-cookie/js-cookie#723]
I am able to set the cookie with the following

```
Cookies.set('name', 'value', { secure: true, expires: 30 });
```

but how do i get the value of the `expires`?

when i do `Cookies.get('name')` i only get the value but no way to get the value for the `expires` filed

**Comment by carhartl** [comment]
It‘s not possible.

**Comment by encryptblockr** [comment]
any reason not to make this a feature to allow one to pull expiry from the cookie set?

**Comment by carhartl** [comment]
Again, it is not possible. Once the cookie has been written, its attributes can‘t be read.

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-wont-you-let-me-get-a-cookie-with-a-particular-attribute-say-path-or-expires

**Comment by encryptblockr** [comment]
ok cool...for anyone reading this

you can just **create another cookie with the expiry date** and then be able to do computation on that
