### ISSUE TITLE
Cookie.set() returns undefined on prod stage

### ISSUE THREAD

**Issue by exaucae** [js-cookie/js-cookie#729]
**Describe the bug**
My custom cookie is not set when running the React app on production ; although it works well on local environment.
This is confusing.  You can see in the caption below that the token to be set in the cookie is well defined.
I have also verified that typeof document is Object (not undefined).

I've tried several ways to set the cookie:
- adding  domain
- setting another cookie with same value ( to see if it was not overridden)
- log all cookies

They are all resumed here:
````js

    const tokenLogger = (tokens: unknown) => {
        console.log('onKeycloakTokens', tokens);
        Cookies.set('AUTH_TOKENS', tokens as any);
        console.log('AUTH TOKENS IS:', Cookies.get('AUTH_TOKENS'));
        Cookies.set('AUTH_TOKENS',tokens as any, { path: '', domain: 'my.domain.com' });
        console.log('AUTH TOKENS DOMAINED IS:', Cookies.get('AUTH_TOKENS'));

       // login a BIS token to see if the previous one was overridden by any means
        Cookies.set('AUTH_TOKENS_BIS', tokens as any);
        console.log('AUTH TOKENS BIS IS:', Cookies.get('AUTH_TOKENS_BIS'));

       // login a TER token with domain to see if the previous one was overridden by any means or domain was the issue
        Cookies.set('AUTH_TOKENS_TER',tokens as any, { path: '', domain: 'my.domain.com' });
        console.log('ALL VISIBLE COOKIES:', Cookies.get());

    }


````

Using:

-  "@types/js-cookie": "^2.2.6",
- "js-cookie": "^2.2.1",

**To Reproduce**
Can't show you a proper environment, since the issue is on prod.

**Expected behavior**
My custom cookie is set.

**Screenshots**

![tokens-err-prod](https://user-images.githubusercontent.com/64139733/132124341-3c99f534-ee2c-4ecb-b61c-63815b801850.PNG)

**Desktop**

- OS: Windows 10 Professionnal 10.0.19043 N/A Build 19043
- Browser: chrome
- Version  92.0.4515.159 (Official Build) (64-bit)

Same behaviour On Opera & EDGE.

**Comment by carhartl** [comment]
In production, can you set a cookie at all using `document.cookie`?

What type is `tokens` at runtime?

**Comment by carhartl** [comment]
Are there maybe configured different defaults in production?

**Comment by exaucae** [comment]
tokens type is `AuthClientTokens` from react-keycloak. I doubt it to relevant our use case.

Defaults are the same in prod & dev.

I'm  running pipelines to show the output setting document.cookie in prod. I will ping you ASAP.

**Comment by exaucae** [comment]
@carhartl ,

I am able to set token with document from the code.

 I now suspect the issue to be a matter of cookie lenght, as stated [in your FAQ   ](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-are-my-cookies-being-deleted). I'll may to confirm/infirm it soon.

**Comment by exaucae** [comment]
I confirm it was a token lenght issue. That one was beyond 4096 bytes in certain cases. This is no more related to js-cookie.

Thanks for your support.
