### ISSUE TITLE
Installation using bower don't get minimized version

### ISSUE THREAD

**Issue by invaderhd** [js-cookie/js-cookie#73]
I think you should add a minimized version of your plugin. 
At this moment if someone install your plugin using bower we only get the file js.cookie.js you should add js.cookie.min.js by default.

**Comment by FagnerMartinsBrack** [comment]
There is [an issue](#57) to implement and automatic release process to publish the minified version in package managers like bower and npm. This is one more reason to do it, so I have added a new bullet point there.

In the mean time you can:

* Download the minified version directly from the [releases page](https://github.com/js-cookie/js-cookie/releases)
* Minify using your custom build procedure, it should be alright
* Add in your build procedure a task to execute `npm install && grunt` inside the project directory, then the minified file will be created at `src/js.cookie-x.x.x.min.js`

**Comment by FagnerMartinsBrack** [comment]
Closed in favor of #57
