### ISSUE TITLE
Most recent version on cdnjs.com seems to be stalled at 2.2.1

### ISSUE THREAD

**Issue by fschiettecatte** [js-cookie/js-cookie#730]
**Describe the bug**
The most recent code version on [cdnjs.com](https://cdnjs.com/libraries/js-cookie) seems to be stalled at 2.2.1, not sure what the actual issue is.

**Comment by carhartl** [comment]
Requires writing an issue here: https://github.com/cdnjs/packages#become-a-contributor

**Comment by fschiettecatte** [comment]
Got it, thank you !!
