### ISSUE TITLE
域名存储失败

### ISSUE THREAD

**Issue by baijuyibuyiju** [js-cookie/js-cookie#732]
![image](https://user-images.githubusercontent.com/71108831/134269110-2aa8cab3-6ae3-4b45-8189-9fda5792b8dd.png )
你好 我在www.xxx.store下存储cookie 想存储到域名store下  getHost运行结果是store但是却没有存储上 这是什么原因呢

**Comment by carhartl** [comment]
“store” is not a valid domain.
