### ISSUE TITLE
Cookies.set not updating cookie values in Safar

### ISSUE THREAD

**Issue by ioannescox** [js-cookie/js-cookie#741]
We're seeing an issue where the Cookies.set method is not updating cookie values in the latest version of Safari (15.0 ).  Values are being correctly updated in Chrome.  

The code we're using is:

$(document).ready(function(){
  Cookies.set('ad-gate', 'false');
  Cookies.set('ad-gate-passed', 'true');
});

Neither of these values are updating as expected.  Thanks for any insight.

**Comment by carhartl** [comment]
Works here with Safari 15.1/Big Sur
<img width="1276" alt="Screenshot 2021-11-18 at 13 21 39" src="https://user-images.githubusercontent.com/21918/142414706-2bf8b80a-4176-4923-9dc2-9bbae0870438.png">

Must be something in your particular environment..

**Comment by carhartl** [comment]
Closing due to lack of feedback. We’ll need at least reproduction..

**Comment by ioannescox** [comment]
Thanks for your response @carhartl, took some time to retest. 

It appears this issue is isolated to Safari on native iOS.  After this script runs:

Cookies.set('ad-gate', 'false');
Cookies.set('ad-gate-passed', 'true');
 
The value of ad-gate is still true, and ad-gate-passed (a new cookie) is not set and does not exist.  

![Screen Shot 2021-11-29 at 3 51 56 PM](https://user-images.githubusercontent.com/52802794/143961407-c7c3e62a-062d-4114-bd33-13bdefe7b5ab.png)
e 

Once the page is reloaded, the values and new cookie appear as expected.  It seems to be that the cookies don't get updated in real time as they do in desktop browsers.  

Is that the expected behavior?

**Comment by carhartl** [comment]
>Once the page is reloaded, the values and new cookie appear as expected. It seems to be that the cookies don't get updated in real time as they do in desktop browsers.

Is that the expected behavior?

**Comment by carhartl** [comment]
>Once the page is reloaded, the values and new cookie appear as expected. It seems to be that the cookies don't get updated in real time as they do in desktop browsers.
>
>Is that the expected behavior?

Nothing I'm aware of. This is Safari Safari, not a WebView?

**Comment by tholden92** [comment]
Having the same issue in chrome on desktop

**Comment by WangLeto** [comment]
Try specifying a domain parameter when using js-cookie with Safari. Safari has stricter cookie policies than some other browsers.
