### ISSUE TITLE
Cookie Value Undefined

### ISSUE THREAD

**Issue by noahdennis-sys** [js-cookie/js-cookie#743]
Hello! I was curious about what I may have done wrong here! I am trying to get a cookie from google 0auth so I can get the users ID. But the cookie keeps coming back as invalid. I can see the cookie is here in the browser, although it's from a accounts.google.com domain, but I have tried with and without the domain part. 

`console.log(Cookies.get('user_id', { domain: 'accounts.google.com'}))` I have tried this

`console.log(Cookies.get('user_id'))` And this

![Screenshot 2021-11-05 at 23 17 24](https://user-images.githubusercontent.com/76561460/140588514-de2e5745-f4e7-4426-a2a2-e363538574e6.png)

**Comment by carhartl** [comment]
Looks like it’s a HttpOnly cookie.. we cannot access such a cookie via JavaScript.
