### ISSUE TITLE
Does the Cookie.set function have an httpOnly flag that can be passed to prevent XSS attacks?

### ISSUE THREAD

**Issue by rbeach4** [js-cookie/js-cookie#745]
I am in the process of implementing js-cookie with vuex-persistedstate to hold onto an access token and refresh token in a cookie. I need to implement the httpOnly flag to prevent from XSS attacks from outside users. Any suggestion on how to set the flag to true here?
<img width="1212" alt="Screen Shot 2021-11-12 at 5 22 54 PM" src="https://user-images.githubusercontent.com/25426480/141544744-a901ef75-d0bb-4a49-af42-f0f0f7ae76b1.png">

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions

**Comment by rbeach4** [comment]
what is the underlying reason for HttpOnly not to work with js-cookie? From my experience, it is best practice to set HttpOnly = true

**Comment by carhartl** [comment]
It‘s all explained in the FAQ, you can read about it there, if you like.
