### ISSUE TITLE
How to access `Cookies` in Chrome dev tools when using webpack?  

### ISSUE THREAD

**Issue by oshihirii** [js-cookie/js-cookie#746]
"js-cookie": "^3.0.1"  
"webpack": "^5.63.0"  
"expose-loader": "^3.1.0"  
chrome Version 95.0.4638.69 (Official Build) (64-bit)  

Hello,

I've looked in the FAQ:

https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions

I am trying to use `Cookie` in Chrome dev tools console, eg:

    Cookies.get()

But get error:

    Uncaught ReferenceError: Cookies is not defined

I seem to recall I came across this years ago and it was resolved by adding something in `webpack.config.json`?    

I currently have this in `module` > `rules`:

```js
module: {
rules: [
{
    test: require.resolve('js-cookie'),
    loader: 'expose-loader',
    options: {
        exposes: ['Cookies'],
    },
},
// ... 
]
}
```  
And this in `plugins`:   
```js
// https://webpack.js.org/plugins/
plugins: [
    // https://webpack.js.org/plugins/provide-plugin/#usage-jquery
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
    }),
],
```
 
I import `js-cookies` into my main browser-side file with:

    import Cookies from 'js-cookie';  

Does anyone know how I can make `Cookies` available in Chrome dev tools?

Thank You.  

**Edit:**  

Some other `webpack.config.js` content that may be relevant:

```js
module.exports = {
    // see:  https://www.npmjs.com/package/uglifyjs-webpack-plugin
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                sourceMap: true,
            }),
        ],
    },
    mode: 'development',
    // see:  https://stackoverflow.com/a/49100966
    devtool: 'cheap-module-source-map',
    entry: './src/js/common.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist/js'),
    }
// .......
```

**Comment by oshihirii** [comment]
I also tried this in `webpack.config.js` (per this [post](https://github.com/js-cookie/js-cookie/issues/201#issuecomment-351042496)) but get same error:

```js
    plugins: [
        // https://webpack.js.org/plugins/provide-plugin/#usage-jquery
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
        }),
        new webpack.ProvidePlugin({ Cookies: 'js-cookie' }),
    ]
```

**Comment by carhartl** [comment]
Please use https://github.com/js-cookie/js-cookie/discussions for questions regarding usage. I don‘t see how this is a bug of this library.

**Comment by carhartl** [comment]
While here, if you only need it for debugging in the console you could try: 

```js
const { default: api } = await import("./dist/js.cookie.mjs");
```

Though this assumes v3 with the ES module variant.
