### ISSUE TITLE
How to set cookie expire in hours or minutes or seconds?

### ISSUE THREAD

**Issue by simonsantan** [js-cookie/js-cookie#749]
Hi there, In the documentations, I find only to add cookie expires in day(s). But I want to add expires for 1 hour or 120 minutes or 3600 second, Then How can I add this expires time? Please give me example for hours, minutes and seconds?

**Comment by carhartl** [comment]
Please take a look at the FAQ or various issues asking for how to do this.

**Comment by HT-35** [comment]
yout can try: 
var inFifteenMinutes = new Date(new Date().getTime() + 15 * 60 * 1000);
Cookies.set('foo', 'bar', {expires: inFifteenMinutes})
