### ISSUE TITLE
jd-cookie not working in android

### ISSUE THREAD

**Issue by sujaykadam** [js-cookie/js-cookie#751]
Trying out authentication functionality in a react app, cant seem to get js-cookie to create a cookie in android on chrome.
using v3.0.1
`Cookies.set("token", response.data.tokendata, { expires: 0.5 });`
Works perfectly on windows browsers.

Thanks for help in advance.

**Comment by carhartl** [comment]
What‘s the size of tokendata?

**Comment by carhartl** [comment]
I've added a Google Pixel to the BrowserStack tested devices here: 7140e7569b362d03190b4932e3280548e68441de, and our test suite runs successfully with this Android device included.

Thus, I am closing this until you're able to provide more information (e.g. which Android version exactly) and a reproduction (in which case we're going to reopen the issue) — but in the past such a problem has usually been related to the particular environment/application, but not the library itself. I already hinted at the cookie value size as a possible culprit, the FAQ might give more hints.
