### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#753]
Thoughts on a possible v4:

- TypeScript support
- Tree-shakable cookie methods
- ES module only

Practically this means merging https://github.com/carhartl/typescript-cookie

**Comment by gilbarbara** [comment]
hey @carhartl 

Why ES Module only?

**Comment by carhartl** [comment]
> hey @carhartl
> 
> Why ES Module only?

Simplicity, reducing maintenance effort..

**Comment by Eveeifyeve** [comment]
I am willing to help out with this I think it would be great because why have a separate package for typescript also ESModules are much better now I thought I will contribute back since I am using this for [TeaClient](https://github.com/teaclientmc)
