### ISSUE TITLE
How can js-cookie help Open Source funding?

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#754]
<sup>This is a continuation of [this thread](https://github.com/js-cookie/js-cookie/pull/744), which was the first attempt to help fund Open Source using crypto. However, it doesn't work for the reasons in the thread itself, so we're back to the drawing board.</sup>

The js-cookie project has millions of downloads on NPM per week, billions on JSDelivr, and thousands of unique visitors every day. How can we direct that traffic from js-cookie to help with Open Source funding awareness?

**Comment by carhartl** [comment]
Can we please use Discussions instead of an issue. I still prefer using issues for work on the library.

**Comment by carhartl** [comment]
(An open issue or PR to means there‘s work to do.)

**Comment by FagnerMartinsBrack** [comment]
Oh ok, to be honest I've never used discussions before so it will be my first time ;)

**Comment by FagnerMartinsBrack** [comment]
Done: https://github.com/js-cookie/js-cookie/discussions/755
