### ISSUE TITLE
Uncaught TypeError: i[l].split is not a function

### ISSUE THREAD

**Issue by krishnaTORQUE** [js-cookie/js-cookie#757]
**Describe the bug**
Gettings Error when build react for production

`Uncaught TypeError: i[l].split is not a function`

**To Reproduce**
Not sure

**Expected behavior**
working in development & suppose to work on production as well

**Screenshots**
![Screenshot_20220121_132636](https://user-images.githubusercontent.com/4960568/150488554-5887f0cc-edf1-4ca1-ad1d-58b7000c7f11.png)

**Desktop (please complete the following information):**

- OS: debian 11
- Browser: Firefox, Chrome & Chrome Based
- Version: Latest

**Smartphone (please complete the following information):**
Did not tried

**Comment by carhartl** [comment]
Unable to reproduce with the given information.
