### ISSUE TITLE
how to set sameSite?

### ISSUE THREAD

**Issue by wlw330296385** [js-cookie/js-cookie#758]
my code :
```
import Cookies from 'js-cookie'
Cookies.withAttributes({ sameSite: 'strict' });
```
then it can not works, the error :
```
Uncaught TypeError: _jsCookie.default.withAttributes is not a function
    at eval (auth.js?5f87:4)
    at Object../src/utils/auth.js (app.js:45448)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (user.js?0f9a:2)
    at Object../src/store/modules/user.js (app.js:45286)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (index.js?4360:6)
    at Object../src/store/index.js (app.js:45250)
```

**Comment by carhartl** [comment]
This is related to how webpack makes the package available as a module.

**Comment by carhartl** [comment]
Would be helpful if you could post your package.json along with the webpack config..

**Comment by carhartl** [comment]
Here’s a working webpack example: https://github.com/js-cookie/js-cookie/tree/main/examples/webpack

**Comment by carhartl** [comment]
Apart from that `withAttributes()` will give you an api instance with the given attributes set as defaults. Usage (as documented in the readme):

```js
const api = Cookies.withAttributes({ sameSite: "strict" })
api.set("foo", "bar") // SameSite applied..
```

Please avoid using issues for asking questions regarding usage. That is what discussions are for: https://github.com/js-cookie/js-cookie/discussions

There’s also an FAQ: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions
