### ISSUE TITLE
Error with big cookies

### ISSUE THREAD

**Issue by rodrigo2000** [js-cookie/js-cookie#76]
Falla cuando la cookie tiene más de 4096 caracteres, y no regresa ningún tipo de error cuando esto sucede.

**Comment by FagnerMartinsBrack** [comment]
>  Practical user agent implementations have limits on the number and
   size of cookies that they can store.  General-use user agents SHOULD
   provide each of the following minimum capabilities:
 > * At least 4096 bytes per cookie (as measured by the sum of the length of the cookie's name, value, and attributes).
> * At least 50 cookies per domain.
> * At least 3000 cookies total.

-- http://tools.ietf.org/html/rfc6265#section-6.1

That is the desired behavior, you should take care for not storing more than 4096 bytes in a single cookie.
Ese es el comportamiento deseado, usted debe tener cuidado de no almacenar más de 4096 bytes en un solo cookie.

**Comment by FagnerMartinsBrack** [comment]
You can detect the cookie length to check if the cookie has a valid size or not:
Puede detectar la longitud de el cookie para comprobar si el cookie tiene un tamaño válido o no:

`` javascript
var cookie = Cookies.get( "mio_cookie" );
var size = cookies.length;
if ( size > 4096 ) {
  throw new Error( "cookie is too big =(" );
}
```

**Comment by FagnerMartinsBrack** [comment]
Closing for now, since this doesn't appear to be a problem with js-cookie itself.

**Comment by tchoulihan** [comment]
I'm having a problem with this. I'm serializing a large javascript object to the cookie, and when it gets big enough, the behavior becomes erratic.

**Comment by FagnerMartinsBrack** [comment]
@tchoulihan as stated above this is something we can't control, there is a limit of 4096 bytes per cookie. You should not use cookies to store large data, instead try to store id references and fetch the complete data later from the database.

**Comment by tchoulihan** [comment]
I see. I ended up using `localStorage` instead of cookies to store data.

Sorry about that.

**Comment by FagnerMartinsBrack** [comment]
It's ok. `localStorage` is probably the best option for your use case :)

**Comment by FagnerMartinsBrack** [comment]
Added to the Wiki: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions/d279bdbee6148b19c0f714d407a4c3e68a226f59
