### ISSUE TITLE
CodeClimate badge not working

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#761]
See https://codeclimate.com/github/js-cookie/js-cookie/builds.

I've got in touch with their support as I'm not able to login using Github account. I'll change the account for our shared email @carhartl as soon as I get access again. Do you remember who created this account, was it you or me?

**Comment by FagnerMartinsBrack** [comment]
I suspect this might be related to Github recent change from `master` default branch name to `main`, but I'm investigating.

**Comment by carhartl** [comment]
Fixed it in the CodeClimate repo settings.
