### ISSUE TITLE
subdomain syntax doesn't work with localhost

### ISSUE THREAD

**Issue by jose-zenledger** [js-cookie/js-cookie#762]
**Describe the bug**
`.localhost` does not allow subdomains

**To Reproduce**
1. set domain to save cookie to `.localhost`
2. go to `example.localhost` and observe you can't save then retrieve the cookie

**Expected behavior**
If the domain `.localhost` is specified I would expect `example.localhost` and `test.example.localhost` to be able to access cookies and they are not.

**Desktop (please complete the following information):**

- OS: MacOS Monterey
- Browser chrome and safari
- Version 3.0.1 & 2.2.0 of js-cookie

**Comment by carhartl** [comment]
The problem is that `.localhost` isn’t recognized as a valid domain name. `.local` is supposed to work.

https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762

**Comment by carhartl** [comment]
(In any case this isn’t a problem the library can do something about!)
