### ISSUE TITLE
I got error when I set an object

### ISSUE THREAD

**Issue by aron-hivebrite** [js-cookie/js-cookie#768]
Hello, I use the version 3.0.1 and I got the following error:

`VM7276:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)`

Looking the `set` function syntax:
`(method) Cookies.CookiesStatic<object>.set(name: string, value: string | object, options?: Cookies.CookieAttributes): string``

I see that we can use an object, so I used the following code:
```
  const myOptions = {
    functional: [
      {
        name: 'option1',
        accepted: true,
      },
    ],
    required: [
      {
        name: 'option2',
        accepted: true,
      },
    ],
    tracking: [],
  };

  Cookies.set('my_key', myOptions, {
    expires: 120,
  });
```

So, I got the following result in the browser:
<img width="357" alt="Capture d’écran 2022-03-18 à 15 31 27" src="https://user-images.githubusercontent.com/67704982/159032702-b89cf888-aa5a-4f63-9d0a-2ada990c8274.png">

And when I read the cookie whit the following code:
```
  const cookieValue = Cookies.get('my_key');
  console.log('CookieValue', cookieValue);
```

I got an error:
<img width="475" alt="Capture d’écran 2022-03-18 à 15 31 48" src="https://user-images.githubusercontent.com/67704982/159033001-015f5a57-db3d-44b4-9898-1f70cc6464ee.png">

Could you confirm this behavior please?

**Comment by carhartl** [comment]
Objects are not supported (they were in v2). Use `JSON.stringify()` to transform the value to a string before setting a cookie.

I believe the TypeScript typings you are referring to are outdated (they have not been updated for v3).

**Comment by aron-hivebrite** [comment]
Yes, please, update the documentation on the syntax of the TypeScript typings to only use "string".
Thank for your fast response 👍

**Comment by carhartl** [comment]
> please, update the documentation on the syntax of the TypeScript typings to only use "string"

We are not maintaining these.

**Comment by carhartl** [comment]
PS: If you are looking for correct, up-to-date typings take a look at https://github.com/carhartl/typescript-cookie

**Comment by carhartl** [comment]
I noticed that types have been updated a few months ago for v3: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/js-cookie

Looks like you have been using an outdated version.

**Comment by aron-hivebrite** [comment]
Yes, I got it:
        `set(name: string, value: string | T, options?: CookieAttributes): string | undefined;`
So, we can see that the. `set` function can be a string or a `T` type, where `T` extends from object.
You, say that js-cookie from version 3 use only string, right?
So, if it is true, I suggest you change the Typed definiton to:
        `set(name: string, value: string, options?: CookieAttributes): string | undefined;`

**Comment by carhartl** [comment]
Ah, exactly, depending on the use of a particular converter (which might accept a `T` generic of some type), `set()` has to accept `T`. 

> So, if it is true, I suggest you change the Typed definiton to

We don’t maintain these.

**Comment by carhartl** [comment]
Looks like a shortcoming of the TypeScript type definitions, and there‘s not a lot we can do about this.

**Comment by carhartl** [comment]
Presumably it's this line that ultimately will allow `object`: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1de258709db1c26485c3b307cd67255d342bf93b/types/js-cookie/index.d.ts#L97

**Comment by carhartl** [comment]
Aforementioned typescript-cookie (which is fully compatible with js-cookie) improves on this:
<img width="552" alt="Screenshot 2022-03-21 at 11 56 46" src="https://user-images.githubusercontent.com/21918/159247875-9a4c3580-09c6-4122-9679-9bc219d2d4d5.png">

**Comment by aron-hivebrite** [comment]
Interesting to know.

So, I could create a file to custom Cookies, like that:

```
import Cookies from 'js-cookie';

export const cookies = Cookies.withConverter({
  write: function (value) {
    return JSON.stringify(value);
  },
});
```

And use my custom file in any place where I need it, like that:
```
import { cookies } from './my-custom-js-cookies';

cookies.set("foo", {item: {option: 'value'}});
cookies.get("foo");
cookies.remove("foo");
```
