### ISSUE TITLE
Can't set multiple cookies

### ISSUE THREAD

**Issue by mycarrysun** [js-cookie/js-cookie#769]
**Describe the bug**
I don't think multiple cookie setting is working (at least in a testing environment)

**To Reproduce**

```js
test('this should work', () => {
  cookies.set('first', 'firstValue');
  expect(document.cookie).toBe('first=firstValue; path=/'); // this works
  cookies.set('second', 'secondValue');
  expect(document.cookie).toBe('first=firstValue; path=/; second=secondValue; path=/'); //this fails
});
```

**Expected behavior**
![Screen Shot 2022-03-23 at 9 57 17 PM](https://user-images.githubusercontent.com/9121901/159826644-1507714e-5e70-422d-8c2a-b169708bb1cc.png)

I'm just running this in jest with @testing-library/jest-dom - not sure if that has anything to do with this issue

Shouldn't this line https://github.com/js-cookie/js-cookie/blob/341df52bff8dd2840434a43e9bf7d4f159a84e6a/src/api.mjs#L46-L47 be appending a value rather than entirely setting `document.cookie`?

**Comment by carhartl** [comment]
First, you cannot read out once set cookie attributes. This line must fail:

```javascript
expect(document.cookie).toBe('first=firstValue; path=/; second=secondValue; path=/'); //this fails
});
```

You can only assert something like this:

```javascript
expect(document.cookie).toBe('first=firstValue; second=secondValue‘);
```

Regarding appending:
>document.cookie is an [accessor property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#description) with native setter and getter functions, and consequently is not a [data property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#description) with a value: what you write is not the same as what you read, everything is always mediated by the JavaScript interpreter.

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
