### ISSUE TITLE
IOS scrolltop problem in Ajaxify website

### ISSUE THREAD

**Issue by Allmedialab** [js-cookie/js-cookie#773]
Thanks for this fabulous plugin!

https://www.yourweblab.nl/aml-01 test site

I have a issue on the latest IOS iPad and iPhones. This test website contains Ajaxify from Arvind Gupta www.4nf.org that has scroll to top implemented. With scroll to top meaning when clicking from page to page the page scrolls up back to top.

The js.cookie.min.js script hides the class on my pages in a Pinegrow Greensock animation like this with the idea to only play the animation on the first web page loaded:

`let myCookie = Cookies.get('preloader-hide');
let title = document.querySelector('.preloader-hide');

if (myCookie) {
    title.classList.add('cookie');
} else {
    Cookies.set('preloader-hide', 'true', {expires: 31});
};`

Works perfect in almost all OS.

But in IOS it results in the fact that the scrolltop doesn't work anymore so when I scroll down a page and click to another page it freezes my website. Removing the js.cookie.min.js fixes the problem. 

No errors in the console!

Any ideas?

Regards & Thanks,

David

**Comment by arvgta** [comment]
Hi there,

I am the author of [Ajaxify ](https://4nf.org/)and would like to confirm that I am at your disposal to help debug this issue, especially if it is primarily due to my plugin or an interaction of it with JS Cookie .

Thanks and regards,
Arvind Gupta

**Comment by carhartl** [comment]
Seems to work on an iPhone 12 Pro, iOS 15.4.1 at least..

**Comment by carhartl** [comment]
I doubt this has to do with cookies, rather than some sort of Safari bug. Fwiw, Safari‘s ITP will cap the cookie expiration to 7 days, so you won‘t get the 31 as intended.

**Comment by carhartl** [comment]
We would need a stripped down test case for reproducing the problem. This most often helps with finding the underlying cause..
