### ISSUE TITLE
Need One More Cookie Attribute 

### ISSUE THREAD

**Issue by UsmanTariq02** [js-cookie/js-cookie#775]
Hi @carhartl can we have one more Cookie Attribute to enable the flag of httpOnly...
Like others we have secure, expire etc...
Why won't we have httpOnly attribute?
Can we discuss more on this as soon as possible?

**Comment by UsmanTariq02** [comment]
Like I am trying to enable the httpOnly flag but am unable to do that as you did not have any attribute in your package.

**Cookies.set('token', token, {expires: in60Minutes , secure: true, httpOnly: false, sameSite: 'strict'});**
Everything except httpOnly is currently working fine....

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#youre-trying-to-use-httponly-true
