### ISSUE TITLE
Installation instructions in README may be misleading

### ISSUE THREAD

**Issue by CaseyG5** [js-cookie/js-cookie#783]
This issue concerns the README.md file that accompanies this project.  (I checked the FAQ but found nothing relevant.)

**Describe the bug**
The installation instructions seem flawed as they only led me down a windy road of errors.  I tried every `import` configuration I could think of as well as `Cookies.noConflict()`.  All I got was **Uncaught ReferenceError: Cookies is not defined** or **Uncaught TypeError: Cookies.set is not a function**.

**To Reproduce**

1. Follow the instructions in the README:
```
<script type="module" src="/path/to/js.cookie.mjs"></script>
<script type="module">
  import Cookies from '/path/to/js.cookie.mjs'

  Cookies.set('foo', 'bar')
</script>
```

2. Link to your app.js or app.mjs script too:
`<script src="app.js"></script>`

4. Try to access Cookies from your app.js:
`Cookies.set('universe', '42');`

5. See the error in your browser's console.

**Expected behavior**
I expected the instructions to lead me in the right direction.  Alas, they did not.  But I hope this saves at least one other person from a lot of frustration due to hours of wasted time.

**Solution**
After trying every `import` variation I could think of, here's the one that worked:
`<script src="/path/to/js.cookie.js"></script>`        // Omit `type="module"`  and note the .JS extension (not .MJS)
With that my script could then access the Cookie object.
I recommend including this in the next version of the README file.

**Desktop (please complete the following information):**
- OS:  macOS 10.13.6
- Browser:  Brave (Chrome engine)
- Version:  1.39.122, Chromium: 102.0.5005.115

**Additional context**
My HTTP server provides the js.cookie.js file.

**Comment by carhartl** [comment]
From the readme:

>Starting with version 3 [releases](https://github.com/js-cookie/js-cookie/releases) are distributed with two variants of this library, an ES module as well as an UMD module.
>
>Note the different extensions: .mjs denotes the ES module, whereas .js is the UMD one.

Thus you as a developer must decide which variant you are going to use, but the mjs variant is very much ok. There are also examples in this repository demonstrating how (and that) it works.

**Comment by CaseyG5** [comment]
Yes, I'm aware there are are both .JS and .MJS files, as mentioned in the issue post I offered.  Did you not read it?  This was not a bug report; the library does appear to be working.  But the basic setup instructions you (or perhaps someone else) included in the README are inaccurate.  The "examples" are not helpful either and don't demonstrate any working code.  Recall that browsers cannot load modules, at least for now.  This is an opportunity for you to improve both the README and the examples in your project to facilitate the use of your library.  Are you open to that?

**Comment by carhartl** [comment]
You may send a PR with the improvements you have in mind.
