### ISSUE TITLE
set cookie failed, but got none error!

### ISSUE THREAD

**Issue by zhiyouth** [js-cookie/js-cookie#784]
**Describe the bug**
hi bro, when I set cookie for other domain, cookie set failed, but I have not catch the error!

**To Reproduce**

1. Go to set cookie for other domain.
2. exec this code, if cookie set failed. I want get some message.
3. got none error.

**Expected behavior**
want an errors!

**Screenshots**
![image](https://user-images.githubusercontent.com/49746677/176342819-91e1cfa7-c610-4498-a1af-63017d999071.png)

![image](https://user-images.githubusercontent.com/49746677/176342332-9fb97c14-fd10-4fd9-a876-9844be4ea5c0.png)
![image](https://user-images.githubusercontent.com/49746677/176342922-36b699d0-e369-4ed5-bd56-783a8acc75ea.png)

**Desktop (please complete the following information):**

- OS: windows
- Browser: chrome
- Version: 105.0.5137.4

**Comment by ErrorBot1122** [comment]
same issue
