### ISSUE TITLE
store an object variable is incorrect

### ISSUE THREAD

**Issue by Xavlight** [js-cookie/js-cookie#789]
Hi,

**Describe the bug**
when I store an object variable, this is incorrect.
I get [object Object] on reading.

**To Reproduce**
Cookies.set("test", { "value1" : 1, "value2" : 2 } );
console.log(Cookies.get("test"));

**Expected behavior**
In version 2.2.1, this worked and it was converted to a string.
"test" : "{\"value1\":1,\"value2\":2}"    --> (like JSON.stringify)

- OS: Windows
- Opera
- 3.0.1

**Additional context**
I had a 'Cookies.withConverter' to solve the problem.
var cookiesjs = Cookies.withConverter({
  write: function (value, name) {
	return (typeof(value) === 'object')?JSON.stringify(value):value;
  }
})
Can't this be integrated in a future version?

Thanks

Xav

**Comment by carhartl** [comment]
See release notes for v3.

**Comment by Xavlight** [comment]
Thank you for your quick response.

But, I can't find the notes.
Where is the part that talks about this subject?

Thanks

**Comment by Xavlight** [comment]
Ok, sorry.
I find it in info releases.

It's a pity, I found it practical.

Thanks
