### ISSUE TITLE
Unable to create cookie at the root of a site

### ISSUE THREAD

**Issue by Trebly** [js-cookie/js-cookie#79]
Hi,

I  try to create cookies which are common for all pages of a site, opened in several tabs.

Even the use of {site :'mysite', path: '/' } the cookie is created in path  "mysite/mypage".

Chrome windows 44.0.2403.157 m.
js.cookies 1.5.1 
I am into a debugging phase of my soft and I have not planned to change js.cookie to version 2.0.3 before the end of current development phase (I made some adaptations to fit with 1.5.1). But if this problem is linked to the version, I will upgrade even not planned.

Trebly

**Comment by FagnerMartinsBrack** [comment]
@Trebly That is an odd behavior, if you create a cookie using the code below it is supposed to be available across the whole site in js-cookie 1.5.1 (because the default path: '/' was added in v2 and onwards):

```javascript
Cookies.set( "name", "value", {
  path: "/"
});
```

Are you sure this is the code you are using? Can you post a simple example that fails so I can check out?

By the way, there is no "site" option in js-cookie 1.5.1, you can see the supported options [here](https://github.com/js-cookie/js-cookie/tree/v1.5.1#cookie-options).

**Comment by Trebly** [comment]
Hi,

I uses 

Cookies.set( "name", "value", { site "mysite",  path: "/" });

I confirm the version is 1.5.1, this Cookies.set creates the cookie with right value but 
if url is  
`http:// <mysite>/<mypage>/<mysecond_level>#<fragment>`
the path is "/<mypage>/<mysecond_level>" not "/"
with google chrome with filter on <mysite> I can find (filter) all related cookies to the site

Mycode is : 
`Cookies.json = true;
 Cookies.raw = true;
var dnow = new Date( ).getTime();
var TOC_navlinks = Array [...................... ];
  var bkm_parmsS = {set_date:dnow, upd_date:dnow, limit_date:dnow+limit_span,str_parms:"{ expires: 365, path: '/',domain: 'bty-blg1.trebly.net'}"}; 
 Cookies.set('bty_blg1-bookmarks', TOC_navlinks, bkm_parmsS.str_parms);
`
When I get the cookie I have just to JSON.parse(get);

Best regards

Trebly

**Comment by FagnerMartinsBrack** [comment]
There is a problem with your code, you are passing `bkm_parmsS.str_parms` as the cookie options, but it contains a String, not an Object Literal as [specified in the docs](https://github.com/js-cookie/js-cookie/tree/v1.5.1#cookie-options):

> Cookie attributes can be set globally ... by passing a **plain object** to the options argument

The final result in your code will be this:

```javascript
Cookies.set(
  'bty_blg1-bookmarks',
  [1, 2],
  // bkm_parmsS.str_parms
  "{ expires: 365, path: '/',domain: 'bty-blg1.trebly.net'}"
);
```

But the correct is:

```javascript
// No quotes in the last argument
Cookies.set( 'bty_blg1-bookmarks', [1, 2], {
  expires: 365,
  path: '/',
  domain: 'bty-blg1.trebly.net'
});
```

Change `str_parms:"{ expires: 365, path: '/',domain: 'bty-blg1.trebly.net'}"` to `str_parms:{ expires: 365, path: '/',domain: 'bty-blg1.trebly.net'}` and it will probably work.

**Comment by Trebly** [comment]
Hi,
Thanks, better late (very, very...) than never.

Trebly

**Comment by KES777** [comment]
Despite on the [documentation](https://github.com/js-cookie/js-cookie#basic-usage):

>Create a cookie, valid across the entire site:
Cookies.set('name', 'value');

The code:

    Cookies.set( 'app_period', from.unix() +'--' +to.unix() )

creates cookie restricted to current `path`:
    
![__](https://user-images.githubusercontent.com/799021/54837115-49676e80-4cce-11e9-9727-58f40f684afa.jpg)


Work around:

    Cookies.set( 'app_period', from.unix() +'--' +to.unix(), { path: '/' } )

**Comment by FagnerMartinsBrack** [comment]
It creates on `{ path: '/' }` by default. See this line in the code: https://github.com/js-cookie/js-cookie/blob/d2724a87a29cbf7ee539452fb42b3e3a1aff95a8/src/js.cookie.js#L52

@KES777 Please incluse js-cookie lib through [the CDN](https://jsdelivr.com/package/npm/js-cookie) and build a [SSCCE](http://sscce.org/) that can reproduce the problem.

**Comment by KES777** [comment]
oh, sorry, I come here from old repo to v1.5.1 =(
and not take attention that now is much new version is available
