### ISSUE TITLE
The cookie always seems to get deleted when closing browser?

### ISSUE THREAD

**Issue by ElixirMike** [js-cookie/js-cookie#790]
Maybe I don't understand functionality, but I'm trying to create a Cookie that will expire in 30 days.
I set it this way in my react code, where token is a string and I set it to a value of true when the complete a process step on the page.

Cookies.set(token,'true', { expires: 30 });

On return to the page, I use this to get Cookie.
const isValidated =Cookies.get(token);

If the browser stays open, this works. However, as soon as I close/re-open the browser, it no longer can detect the cookie.
Shouldn't the cookie remain for 30 days? Or am I missing something?

**Comment by carhartl** [comment]
This is in every single browser, or only a particular one? Are there any browser extensions active? Can‘t really tell with this lack of information..

**Comment by ElixirMike** [comment]
Good point, I just tested in Chrome, and it works correctly. 
I am having the issue in the Microsoft Edge browser. Version 103.0.1264.77 (Official build) (64-bit)

**Comment by carhartl** [comment]
This behavior could be caused by tracking prevention in Edge..

**Comment by ElixirMike** [comment]
It's a vanilla version of Edge. Is there a setting you think that can be disabled? Or are you just saying it won't work with Edge?

**Comment by carhartl** [comment]
I don’t have Edge and don’t know what the default setting is. But it looks like you can turn it off: https://support.microsoft.com/en-us/microsoft-edge/learn-about-tracking-prevention-in-microsoft-edge-5ac125e8-9b90-8d59-fa2c-7f2e9a44d869

Please test again with it turned off. If really the protection is the reason there‘s nothing we can do.

**Comment by ElixirMike** [comment]
I turned it off, but still have same issue.

**Comment by carhartl** [comment]
I found at least one other pointer here: https://textslashplain.com/2022/05/26/losing-your-cookies/

Could you check about://settings/clearBrowsingDataOnClose

**Comment by carhartl** [comment]
It would also be interesting what the console reveals about the cookie (in particular expiration)

**Comment by ElixirMike** [comment]
That was it....was set to delete all cookies on close...which is a bad default setting if you ask me. Most people won't even go near those settings.

Anyways, thanks for the help!

**Comment by ElixirMike** [comment]
Also, just FYI, I turned Tracking Prevention back on and set it to the default value of "Balanced" and it continued to work...so at least that's good news.
