### ISSUE TITLE
 Cookie has domain set to the public suffix

### ISSUE THREAD

**Issue by ravi-chukka** [js-cookie/js-cookie#791]
I am just getting data from cookie using js-cookie in my application. code is as follows,

import Cookies from 'js-cookie';
Cookies.get(INITIAL_FACILITY_ID_COOKIE_NAME)

At the time of unit testing I am getting an error as follows, 

Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}

I am using jest for testing.
Please let me know a possible solution for this

**Comment by carhartl** [comment]
There seems to be a proposal already for how to fix it for your unit tests. If that doesn’t work for you, you should find a solution searching the issues here for “localhost”.

**Comment by carhartl** [comment]
For instance, this might be a pointer: https://github.com/js-cookie/js-cookie/issues/486#issuecomment-453910762

**Comment by nicolasiscoding** [comment]
@ravi-chukka this fixed it for me in jest 

https://github.com/jsdom/jsdom/issues/3419#issuecomment-1224224003

Running into another issue now which I am troubleshooting
