### ISSUE TITLE
Cookies.get() doesnt return me a cookie in nextJS api route

### ISSUE THREAD

**Issue by philmetzger** [js-cookie/js-cookie#792]
I am using NextJS and have this API route.

How come the first console.log shows hte cookie get the second cant find it?

```
export default async function handler(req, res) {
  console.log(req.cookies);
  const token = Cookies.get('token');
  console.log(token);
....
```

"js-cookie": "^3.0.1",
"next": "12.1.6",

**Comment by carhartl** [comment]
The are a ton of possible reasons for this, but with the given information it‘s hard to tell. It might be the case that NextJS by default works with httponly cookies for instance. We will not be able to read such cookies with the library.

**Comment by carhartl** [comment]
I have no experience with NextJS whatsoever, but depending on the library you‘re using to set cookies server-side, httponly may be the default, as described here: https://maxschmitt.me/posts/next-js-cookies/

**Comment by carhartl** [comment]
Oh wait.. it‘s all server-side to begin with, but this library isn’t meant to be used like this.
