### ISSUE TITLE
Setting the expires value as a number does not add the relevant number of days

### ISSUE THREAD

**Issue by SimonShirley** [js-cookie/js-cookie#794]
**Note**: Timings are going to be slightly off as the Date.Now() value is going to change as I type this.

**Date today:** Thu, 06 Oct 2022

----

**Describe the bug**
Setting the expires value as a number does not add the number of days to the cookie expiry date.

----

**To Reproduce**

Can be set in code but also from Chrome DevTools console.

Code entered:
`Cookies.set("cookieKey", "cookieValue", { expires: 7 });`

Console returned:
`'cookieKey=cookieValue; path=/; expires=Thu, 06 Oct 2022 10:15:58 GMT'`

----

Code entered:
`Cookies.set("cookieKey", "cookieValue", { expires: 1 });`

Console returned:
`'cookieKey=cookieValue; path=/; expires=Thu, 06 Oct 2022 10:16:02 GMT'`

----

**Expected behavior**
Setting a positive expires number should set the expiry date into the future, so
`Cookies.set("cookieKey", "cookieValue", { expires: 7 });`

Should return something like the following:
`'cookieKey=cookieValue; path=/; expires=Thu, 13 Oct 2022 10:15:58 GMT'`

----

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 21H2
- Browser: Chrome Desktop 
- Version: 106.0.5249.103 (Official Build) (64-bit)

----

**Additional context**
Appears to work correctly when setting the date using a Date string / object, so:
```
var testDate = Date.now();
Cookies.set("cookieKey", "cookieValue", { expires: new Date(testDate.setDate(testDate.getDate() + 7)) });
```

...will create a cookie on the 13th October 2022.

**Comment by SimonShirley** [comment]
Forgot to add - Using js-cookie v3.0.1

**Comment by carhartl** [comment]
We have a test that proves (should prove) that this is working as expected: https://github.com/js-cookie/js-cookie/blob/f79d254efcc9fcc12624a732db917d3823f1f6d0/test/tests.js#L309

Which browser are you seeing this behavior in? Could you create a failing test or provide a minimal reproduction?

**Comment by SimonShirley** [comment]
As requested, I've tried to setup a minimal project to re-test this on.

Writing a little JsFiddle, it appears to work as it should, which rules out the bug coming from the library code and therefore must be some error in my work project somewhere.

I've run it on Chrome again and in Firefox, but this time on my mac at home. (I was using my work PC earlier).

https://jsfiddle.net/etrkqywg/2/

![image](https://user-images.githubusercontent.com/10355079/194410165-7fcd7341-861d-4887-9379-6b5cff56ca3e.png)

Apologies for creating a bug when there isn't one. I'll try again at work tomorrow but it's looking likely to be something my end.
