### ISSUE TITLE
Expire does not work

### ISSUE THREAD

**Issue by OfficialDevvCat** [js-cookie/js-cookie#797]
Hey there,

I use this code to create a cookie
```
Cookies.set("cookieAccept", "true", { expires: 365, path: '/' });
```
However, if I check the cookie inside chrome it clearly states the expire date as: `When the browsing session ends`.

I have tried multiple methods like
```
let aNewYearTime = new Date(new Date().getTime() + 365 * 24 * 60 * 60 * 1000);
Cookies.set("cookieAccept", "true", { expires: aNewYearTime , path: '/' });
```
but nothing seems to work.

**Comment by carhartl** [comment]
What happens if you try a smaller value, say 3 (days)..

**Comment by carhartl** [comment]
It could also be the effect of this setting, when enabled: https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Callow-or-block-cookies%2Cdelete-cookies-after-you-close-chrome

**Comment by OfficialDevvCat** [comment]
The issue has been resolved as it was the fact that the `.js` was cached on chrome and didn't refresh until I did `CTRL`+`F5`... Stupid me. sometimes we have to step away from the code for a while in order to succeed in the future. Thanks for the help and have a nice week coming ahead! :D
