### ISSUE TITLE
Cookie for subdomain

### ISSUE THREAD

**Issue by jadeye** [js-cookie/js-cookie#80]
Hi
Thanx for sharing...!

I am using JavaScript Cookie v2.0.2.
I wish to set a cookie for a subdomain.
Setting a cookie on a subdomain also sets a cookie for the domain!
So I have the cookie with same name twice: once for `sub.domain.name` & once for `domain.name`.
Now when I wish to change cookie, I have to do it twice: once for `sub.domain.name` & once for `domain.name`, while am only setting the cookie once!
Is this normal behavior? how can this be prevented? : What am I doing wrong?;

My code:
	`Cookies.set('cookieName', '<?php echo $lang; ?>',{path:'" + window.location.hostname + "'});`

Thanx

**Comment by FagnerMartinsBrack** [comment]
The [docs says](https://github.com/js-cookie/js-cookie/tree/v2.0.2#path) that path is:

> A String indicating the **path** where the cookie is visible.

If you want to set the cookie for the domain/subdomain, consider using the [domain](https://github.com/js-cookie/js-cookie/tree/v2.0.2#domain) attribute instead.

**Comment by jadeye** [comment]
Thank you...
I have tried replacing `path:''` with `domain` but in vain.
I have tried combining the two but still without luck :-(

I would appreciate it if you could take a look...
[site](http://oc2000.polumetis.net/)

Now if you change the languages from the top menu,
This script is to change that cookie:

`                                Cookies.remove('googtrans',{path:'',domain: 'oc2000.polumetis.net'});
                                Cookies.remove('googtrans',{path:'',domain: '.oc2000.polumetis.net'});
                                Cookies.remove('googtrans',{path:'',domain: '.polumetis.net'});
                                console.log('After remove - ' + Cookies.get('googtrans'));
                                Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: '.oc2000.polumetis.net'});
                                Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: 'oc2000.polumetis.net'});
                                Cookies.set('googtrans', '/en/<?php echo $lang; ?>',{path:'',domain: '.polumetis.net'});
`
