### ISSUE TITLE
 How to set HttpOnly in vue

### ISSUE THREAD

**Issue by Triumph297** [js-cookie/js-cookie#802]
Our project wants to set HttpOnly, but we don't know how to set it。
![image](https://user-images.githubusercontent.com/79828369/199448727-072ec7bb-0ed1-4fa9-b941-40d56813862a.png)

**Comment by mmq-ljj** [comment]
me too

**Comment by carhartl** [comment]
https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#youre-trying-to-use-httponly-true

**Comment by furqon** [comment]
> Our project wants to set HttpOnly, but we don't know how to set it。 ![image](https://user-images.githubusercontent.com/79828369/199448727-072ec7bb-0ed1-4fa9-b941-40d56813862a.png)

sorry im continuing this closed thread.
do you manage to get httponly cookies?

**Comment by magoerlich** [comment]
> > Our project wants to set HttpOnly, but we don't know how to set it。 ![image](https://user-images.githubusercontent.com/79828369/199448727-072ec7bb-0ed1-4fa9-b941-40d56813862a.png)
> 
> sorry im continuing this closed thread. do you manage to get httponly cookies?

No and nobody will get it working: Because it's impossible **by Design.**
@carhartl already posted the only valid answer to this.
