### ISSUE TITLE
After deleting cookie somehow it's coming again 

### ISSUE THREAD

**Issue by purushothaman-source** [js-cookie/js-cookie#804]
```js
Cookies.remove("session", {
          sameSite: "strict"
        });
```
I used this above statement to remoe the cookie ..but somehow it came back again

**Comment by carhartl** [comment]
When and how exactly do you see the cookie and you expect it to no longer exist?

**Comment by carhartl** [comment]
How did you set the cookie?

**Comment by carhartl** [comment]
Cannot reproduce, lacking additional information.

**Comment by Mifayo** [comment]
> How did you set the cookie?

also has the same issue 
but i set cookie in test.domain.com i use it in app.domain.com and i removed it from app.domain.com but it still there

**Comment by carhartl** [comment]
@Mifayo Unless you have set the cookie with the domain `.domain.com` you cannot delete it across subdomains.

**Comment by Mifayo** [comment]
> @Mifayo Unless you have set the cookie with the domain `.domain.com` you cannot delete it across subdomains.

I used this 
`document.cookie = "key=;domain=.domain.com;max-age=0";`
instead of 
Cookie.remove

**Comment by purushothaman-source** [comment]
It was solved ..My bad .. From backend they seetinf cookie through response -header ..
