### ISSUE TITLE
why node >=14 but npm >=9.5

### ISSUE THREAD

**Issue by ZhangHang12135** [js-cookie/js-cookie#818]

**Comment by carhartl** [comment]
For asking questions there‘s discussions, if there‘s a bug please report accordingly..

**Comment by carhartl** [comment]
(I want to make sure that a recent npm is being used, so that package provenance is supported.)

**Comment by carhartl** [comment]
Breaking like this wasn't intentional, my intention was to communicate that we'd need a recent npm supporting `--provenance`. But it's really only needed in the release workflow. I'm removing this.

**Comment by carhartl** [comment]
39a0f40ef22eeb64906836b5cf00ea615ebe8739

I'm releasing a new version.
