### ISSUE TITLE
3.0.5 Release notes missing

### ISSUE THREAD

**Issue by simPod** [js-cookie/js-cookie#819]
Hello, can we create 3.0.5 release? https://github.com/js-cookie/js-cookie/releases

thanks!

**Comment by MacrayBlackhand** [comment]
Not sure if this is related, but jsDelivr is confused. The search results still show 3.0.1, but when I click in to get the link, it is showing 3.0.5.  Here, it is still showing 3.0.4 as the current.

**Comment by jimaek** [comment]
The site has a delay because it relies on Algolia's search index. But the CDN browser should always be up-to-date https://cdn.jsdelivr.net/npm/js-cookie/
