### ISSUE TITLE
How to set cookie with HttpOnly

### ISSUE THREAD

**Issue by pawankv** [js-cookie/js-cookie#821]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by carhartl** [comment]
You‘ll find the answer in the faq.

**Comment by Demaxl** [comment]
> You‘ll find the answer in the faq.

Where is the faq?

**Comment by columbian-chris** [comment]
Answer in FAQ: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#youre-trying-to-use-httponly-true
