### ISSUE TITLE
Add a 'dist' folder to the repo?

### ISSUE THREAD

**Issue by subfighter3** [js-cookie/js-cookie#824]
I usually include the script in each project to avoid external downloads, but everytime the script got an update I have to manually download the latest version from some CDN. Why don't you add a 'dist' folder in this repo?

**Comment by carhartl** [comment]
Use `npm pack`, which will also provide you with additional supply-chain security with package provenance.

(Long time ago this has been discussed before, related to minified versions. Long story short, this repo contains the source code, but nothing else. For releases aka dists there‘s releases, that is the published package on npmjs.com, single source of truth.)
