### ISSUE TITLE
 Error: ReferenceError: QUnit is not defined when running yarn test

### ISSUE THREAD

**Issue by Canoir** [js-cookie/js-cookie#826]
**Describe the bug**
 Error: ReferenceError: QUnit is not defined when running yarn test

**To Reproduce**

1. Fork Project
2. RUN npm install -d
3. RUN npx grunt

**Expected behavior**
to run tests

**Screenshots**
![image](https://github.com/js-cookie/js-cookie/assets/24988065/906cf211-620d-4dad-9b72-9d4f6e75c7c2)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser -
- Version -

**Comment by carhartl** [comment]
Don't you see the test output nonetheless? I saw this myself but never figured out where this is coming from -- while tests still run fine.

**Comment by Canoir** [comment]
yes exactly. tests are working fine but with many errors.

**Comment by carhartl** [comment]
Don’t have time to investigate..

**Comment by carhartl** [comment]
For tests.js this test is producing the error: https://github.com/js-cookie/js-cookie/blob/3834c918a0993fed52dba95d2cb448305e965951/test/tests.js#L89-L103

**Comment by carhartl** [comment]
The other ones are coming from `test/encoding.js`, which are also using an iframe, so something about the iframe..

**Comment by carhartl** [comment]
I traced the error back to this line: https://github.com/qunitjs/qunit/blob/ceea0ec2d04c274218bb3a0a91ffaf49c85bf3c1/src/test.js#L211

More likely a bug in qunit.js itself, where the original (window) context is being lost in the callback returned by `assert.async()`.

**Comment by carhartl** [comment]
Ah, found this: https://github.com/gruntjs/grunt-contrib-qunit/issues/202
