### ISSUE TITLE
cookies.get return expired cookie

### ISSUE THREAD

**Issue by Trigun87** [js-cookie/js-cookie#827]
on chrome in the network console i see the expired cookies like you can see from the screenshot
![image](https://github.com/js-cookie/js-cookie/assets/33032691/e07b7172-f4cf-41a1-a705-6773ed59406b)

when i call cookies.get i get the value of the cookie instead of undefined and i don't have a way for check if the cookie is expired or not

**Comment by carhartl** [comment]
We wouldn’t have either.. this would be a bug on Chrome‘s side.

**Comment by carhartl** [comment]
Though the time shown in your task bar is local time, while the one in the console for expires is UTC, so those cookies might not actually be expired at all…
