### ISSUE TITLE
.remove() API not work when it's runing in a iframe enviroment

### ISSUE THREAD

**Issue by zhouzongren** [js-cookie/js-cookie#846]
**Describe the bug**
As the title discriped

**To Reproduce**

1. run a local server A 
2. run a local server B and B has a iframe page which embed page A
3. operate server A's cookies by js-cookies api like fake code blow
`Cookies.set('key', 'value', {
    secure: true,
    sameSite: 'None',
  })`
5. remove the cookie and you'll see that 'key' not deleleted
`Cookies.remove('key')
Cookies.get('key') //  still console 'value'
`

**Expected behavior**
.remove works great in a nomal websit page expect iframe page

**Screenshots**
it's quit difficut to show screnn shot.

**Desktop (please complete the following information):**

- OS: mac os
- Browser chrome 
- Version 119.0.6045.199

**Comment by khanakia** [comment]
Any update i having the same issue

**Comment by carhartl** [comment]
Where (iframe/window) are you setting and removing the cookie?

**Comment by khanakia** [comment]
I had a website that loaded inside the iframe and then the user tried to log in to the website inside an iframe. 

However setting cookie using raw code works `window.document.cookie = 'cross-site-cookie231=noneCookie; SameSite=None; Secure';`

**Comment by carhartl** [comment]
@khanakia You‘re saying that writing a cookie within an iframe does not work? The issue being reported mentions that only removing doesn’t work. For me it’s impossible to investigate without the actual code.

**Comment by khanakia** [comment]
Yes, the issue is the same for removing or setting the cookie inside the iframe.

I can understand the actual code is big and hard to share. I will see if somehow I can create some test code for you to check

**Comment by khanakia** [comment]
Here are the 2 ways to test.

## First
- Open https://in.jeoga.com/cookie-frame.html
- Try to set cookie - Works
- Try to remove cookie - Do not works

## Second In IFrame
- open https://khanakia.com/cookie.html
- We just embed the https://in.jeoga.com/cookie-frame.html in an iframe
- Now try to set cookie within in the iframe - Do not works.

**Comment by carhartl** [comment]
Yes please, appreciated. Also, in my experience, often times reducing the code for a minimal reproduction helps with finding the cause (which might not have to do with library). And otherwise it‘s mostly guesswork for me anyway.

**Comment by carhartl** [comment]
@khanakia I noticed you're using version 2.0.4 in the frame, could you try and upgrade to 3.0.3 (latest)?

**Comment by carhartl** [comment]
Another thing I noticed.. in Firefox, writing the cookie in the iframe works, thus not writing it at all in Chrome must have to do with its stronger cookie policies. I think Chrome blocks cookies altogether now if they don't have a `SameSite` attribute.

**Comment by carhartl** [comment]
Also, in your example: the remove button is lacking the handler! 

```html
<button>Remove Cookie</button>
```

So clearly, in this case the cookie isn't going to be deleted :)

**Comment by carhartl** [comment]
With these things fixed, on servers on localhost, I see both writing and removing cookies working fine in Chrome and Firefox.

**Comment by khanakia** [comment]
I am sorry I just realized that too. 

Also, I tested it in Firefox it works fine. Yes, so it has something to do with Chrome then.

Thanks :)

**Comment by khanakia** [comment]
I just created a new button Set Raw cookie here https://khanakia.com/cookie.html
and when I use this code `document.cookie = 'cross-site-cookie231=noneCookie; SameSite=None; Secure';` in Iframe it works
Note: I also updated the js cookie code to set `SameSite=None`

Why is it so then?

**Comment by carhartl** [comment]
>But still it's not working in IFRAME in chrome

Some hints here: https://stackoverflow.com/questions/45094712/iframe-not-reading-cookies-in-chrome

**Comment by carhartl** [comment]
@khanakia I believe you need `Cookies.set('test', "1234",  { sameSite: 'None', secure });`

**Comment by khanakia** [comment]
Ok Just updated the code `Cookies.set('test', "1234",  { sameSite: 'None', Secure: true });` and it worked.

Now only Removing the cookie is not working

**Comment by carhartl** [comment]
>Now only Removing the cookie is not working

Yes, consistently in both Firefox and Chrome. Still a mystery to me.

**Comment by khanakia** [comment]
Ok figured. I just updated the code to this `Cookies.remove('test', { sameSite: 'None', secure: true });` now removing also works

**Comment by carhartl** [comment]
Aaaah, I had been thinking about it, but wasn't sure. Apparently what's in the readme also applies to `SameSite` and `Secure`.. adding this to the readme and closing this. Thank you very much @khanakia for your help! 🙏 

<img width="854" alt="Screenshot 2023-12-25 at 09 53 36" src="https://github.com/js-cookie/js-cookie/assets/21918/8a620ffe-7128-4c29-9b9b-779c0f2aafa5">

**Comment by carhartl** [comment]
Must use 

```js
Cookies.remove('key', 'value', { secure: true, sameSite: 'None' })
```
