### ISSUE TITLE
Cookie does NOT get destroyed when set with either no expire value or an expire value of 0

### ISSUE THREAD

**Issue by fabricepallaud** [js-cookie/js-cookie#848]
Whether I set my cookie by writing `Cookies.set('cookie_case_studies_visible', true)` or `Cookies.set('cookie_case_studies_visible', true, { expires: 0 })`, in either case it is not destroyed when closing my browser.

This issue occurs both with Chrome and Firefox. Haven't tested with other browsers yet.

Am I missing something?

Vue 3 app, `package.json`: `"js-cookie": "^3.0.5"`.

**Comment by carhartl** [comment]
Have you checked https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#why-does-the-browser-not-remove-the-cookies-after-i-close-it ?

**Comment by carhartl** [comment]
@fabricepallaud So is this the case for you? Can we close this?

**Comment by fabricepallaud** [comment]
Yes you can, thank you. I've just set an expire time of a few hours which will do for my case.
