### ISSUE TITLE
Cookie is set but attirbutes are not?!

### ISSUE THREAD

**Issue by TsgabiXD** [js-cookie/js-cookie#851]
This will set the Cookie 'token', but not it's attributes and i don't know why (in Firefox):
`Cookies.set('token', token, { expires: 1, secure: true, domain: domain, sameSite: 'strict', path: '/' });`

In Edge the Cookie is set, but I cannot remove it.
But in Edge I can set Cookies the way above. In that case I can set the attributes *secure* and *strict*.

This is not working at all:
`Cookies.withAttributes({ secure: true, domain: domain, sameSite: 'strict', path: '/', expires: 1 });`

**Comment by carhartl** [comment]
What is the actual value for the `domain` attribute?

**Comment by TsgabiXD** [comment]
Since it defaults to 'localhost', I wrote 'localhost' in there (for development reasons).
I noticed just now when I remove the domain attribute. Like this:
`Cookies.set('token', token, { expires: 1, secure: true, sameSite: 'strict', path: '/' });`
The attributes *secure* and *strict* are getting set.

But when i try to use the Cookies.withAttributes() function it doesn't work out. Like this:
`Cookies.withAttributes({ secure: true, expires: 1, sameSite: 'strict', path: '/' });`

Btw. Edge and Firefox are working equal, that's my bad of misinterpreting the Edge-Developper-Tool. (sorry for that)

**Comment by carhartl** [comment]
You cannot use “localhost”, it is not a valid domain name, and some browsers reject the cookie.

**Comment by carhartl** [comment]
https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

**Comment by TsgabiXD** [comment]
Oh, thank you. I didn't know that.
