### ISSUE TITLE
Help To use cookies across domains

### ISSUE THREAD

**Issue by Viclaww** [js-cookie/js-cookie#854]
I am sharing cookies across my subdomains. It works locally but not after production.

 `  //This is the first domain jellosite.com
    Cookies.set("jellosite-authToken", payload.access, {
          expires: 100,
        });
        Cookies.set("jellosite-user", JSON.stringify(payload.user || null), {
          expires: 100,
        });` 

`
// this is the sub domain dashboard.jellosite.com
const userData =
  Cookies.get("jellosite-user", {
    domain: "jellosite.com",
  }) || null;
const initialState = {
  access: Cookies.get("jellosite-authToken", {
    domain: "jellosite.com",
  }),
  user: JSON.parse(userData),
  currentSlug:
    Cookies.get("jellosite-current-slug", {
      domain: "jellosite.com",
    }) || null,
};
`

**Comment by carhartl** [comment]
I think you need to specify the domain consistently whenever you are setting the cookie.

**Comment by carhartl** [comment]
Also, you cannot specify the domain when getting a cookie, either a cookie is readable or not in a particular context (for instance the current domain).

**Comment by carhartl** [comment]
```js
Cookies.set("jellosite-authToken", payload.access, { expires: 100, domain: ".jellosite.com" });
Cookies.get("jellosite-authToken");
```

**Comment by Viclaww** [comment]
Thanks @carhartl , I really appreciate this. It works fine
