### ISSUE TITLE
Document how to use partitioned cookies

### ISSUE THREAD

**Issue by cdauth** [js-cookie/js-cookie#855]
I was looking through the documentation about whether setting [partitioned cookies](https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies) is supported and couldn't find anything.

From a brief look at the source code, it seems like setting partitioned cookies is already possible by simply passing `partitioned: true` to the cookie attributes. It would be nice to document this in the README.

**Comment by carhartl** [comment]
The referenced documentation states it is an experimental feature, therefore not going to add it to the documentation.

**Comment by carhartl** [comment]
PS: It’s not just adding documentation- once it’s officially part of the public api we’ll also need tests, just something to keep in mind.

**Comment by dcts** [comment]
@cdauth can you share an example on how you used partitioned cookies just for future devs looking for it? Now that chrome is pushing messages in console to update cookies lot of people will want a quick solution. 

(although not officially supported, its a great quick fix IMO)

**Comment by cdauth** [comment]
I simply did this:
```javascript
Cookies.set(name, value, { expires: 3650, partitioned: true });
```

In particular, I did it like this to only make the cookie partitioned when we are not allowed to set a third-party cookie:
```javascript
Cookies.set(name, value, { expires: 3650, partitioned: !(await document.hasStorageAccess()) });
```
