### ISSUE TITLE
Remove selected cookie value from array

### ISSUE THREAD

**Issue by psdes** [js-cookie/js-cookie#857]
Hi there,

I have stored cookies in one option like that:

name: apa_amenieties
value: klimatyzacja%2Csauna%2Cvip%2Cekspres-cisnieniowy%2Cbasen%2Ckominek%2Cogrzewanie-podlogowe separated by "%2C"

When I use Cookies.remove('apa_amenities',  { path: '' }); is removing all but I want to remove just one for example sauna.
Using Cookies.remove('apa_amenities', 'sauna', { path: '' }); not working, 

There is other way for removing just selected from that value?

**Comment by carhartl** [comment]
It’s not possible to remove cookies by attributes.

**Comment by carhartl** [comment]
You’ll have to adapt the cookie value and write the cookie again. Might be possible to implement a custom converter.

**Comment by psdes** [comment]
This array is used in ajax filters to save selected filters, each one is checkbox value selected (checked) and is showing in that array or not and there is working fine adding or removing each value so there is no way to do that just by remove just one or add just by this cookie script?

**Comment by psdes** [comment]
Function I use there for that is
`    var apa_amenities = [];
    $.each($("input[name='apa_amenities']:checked"), function () {
        var amenietieVal = $(this).val();
        Cookies.remove(apa_amenities, {path: ''});
        apa_amenities.push(amenietieVal);
        $('#active_apa_amenities_' + amenietieVal + '').remove();
        Cookies.set('apa_amenities', apa_amenities, { expires: 7, path: '' });

    });
`
