### ISSUE TITLE
Clarify the behavior for the domain attribute

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#87]
Perhaps we should mention in the "domain" attribute section of the README more details on how the sub-domain syntax works according to [the spec](http://tools.ietf.org/html/rfc6265#section-5.2.3). See #81.

**Comment by vemv-kantox** [comment]
Could be a good idea. Few programmers are going to read an RFC. js-cookie is in a position of trust to present us a distilled version of cookie behavior!

**Comment by FagnerMartinsBrack** [comment]
I believe changing the docs by including "subdomain" instead of "domain" fixes most confusion about the domain attribute:

> A String indicating a valid subdomain where the cookie is visible.

A domain doesn't make sense (the domain cannot be changed), so it makes sense documenting that it accepts only a subdomain of the current domain. I believe this is an interpretation confusion, where the docs assumes that a subdomain is also a domain.

It can be more specific like:

> A String indicating a valid subdomain where the cookie is visible. For security reasons, only subdomains of the current page are allowed.

**Comment by FagnerMartinsBrack** [comment]
#91
