### ISSUE TITLE
Failing in Android 5.1?

### ISSUE THREAD

**Issue by tconroy** [js-cookie/js-cookie#93]
According to the build status this is currently failing in Android 5.1. Any insight? I don't have a 5.1 device to test with.

**Comment by FagnerMartinsBrack** [comment]
That seems to be an issue in Sauce Labs, no commit was made in the source that might have caused any breakage. In the tests page it shows "Test exceeded maximum duration after 180 seconds", but Travis build [says all tests have runs successfully](https://travis-ci.org/js-cookie/js-cookie#L591).

**Comment by FagnerMartinsBrack** [comment]
I restarted the last build manually via Travis web UI and now it is all green, thank you! :+1:
