### ISSUE TITLE
Cookies.get('cookieName') occasionally returning undefined.

### ISSUE THREAD

**Issue by tconroy** [js-cookie/js-cookie#94]
Hey there,

So I'm not entirely sure what the issue here is, and it may not be with js-cookie, but I wanted to bring it up just in case.

We have a page which uses Varnish to set a cookie on page load. The contents of the cookie is a JSON object, however the object params are wrapped in single quotes ( ' ) instead of double-quotes ( " ) due to a dumb reason I won't go into here.

Anyway, using js-cookie, I attempt to read in the cookie data like so:

```javascript
var utilCookie = Cookies.get('utilCookie');
if (typeof utilCookie === 'undefined') {
  // performs a failsafe by falling back to a default value 
} else {
  // uses the value of the cookie elsewhere in the app
}
```

So the problem here is occasionally, that `undefined` block is being tripped. We know the cookie is being set by the server so the issue isn't on our end. We've noticed that it happens most frequently with mobile users using in-app browsers (such as hitting the page from a Facebook share link, inside the Facebook App). 

How extensively has js-cookie been tested with these in-app browsers? What is the read time for js-cookie? I imagine it should be near instantaneous, but I'm curious if it's not and we're getting undefined because the value hasn't been fully loaded into memory.

Dunno, grasping at straws here, but any input / food for thought is appreciated!

**Comment by FagnerMartinsBrack** [comment]
Sup.

> however the object params are wrapped in single quotes ( ' ) instead of double-quotes ( " ) due to a dumb reason I won't go into here.

Well that's non standard. If you use `Cookies.getJSON` you might get the correct version or you might not. I believe most browsers accept single quoted keys, but the [JSON spec says](http://json.org/) that double quotes are mandatory so you can't expect this to work everywhere =/. We don't know of any browser compatibility regarding this and we have no test either, we just use `JSON.parse` as long as the cookie value starts with either `[` or `{` when using `Cookies.getJSON`.

> What is the read time for js-cookie? ... but I'm curious if it's not and we're getting undefined because the value hasn't been fully loaded into memory

Yeah it's instantaneous. JavaScript is single threaded, so this operation should block the screen, unless somebody override `Cookies` or something.

The best way to narrow this is to replace the code with the native cookies implementation, like `document.cookie = "utilCookie=value"` and read using `document.cookie` instead of the `Cookies` API, then see what happens (if the error persists).

One of the reasons I can think of:

* There are too many cookies in the page, so they might have been reaching the limit and being disposed by the browser.
* You could maybe have `Cookies.json === true` that might be triggering the JSON reading for all operations (see https://github.com/js-cookie/js-cookie/issues/89#issuecomment-140365293)

**Comment by tconroy** [comment]
Hey there.

Right, so about the single quotes, I've been reading in the cookie data this way; use a regex replace to swap out single quotes for doubles, then parse the JSON:

```javascript
var utilCookie = Cookies.get('utilCookie');
JSON.parse( utilCookie.replace(new RegExp(/'/g), '"')
```

I'm wondering if the processing time of the read/parse is causing a race condition in which the value is "undefined" (since it's still being formatted)? 

For what it's worth I tried throwing the whole mess into a jQuery deferred promise scenario like shown:

```javascript
  var deferred = $.Deferred(),
  utilCookie = Cookies.get('utilCookie');

  if (typeof utilCookie === 'undefined') {
    deferred.resolve(/* an object representation of some data we resolve to on failure */);
  } else {
     console.error('utilCookie is present, parse the JSON it:');
     deferred.resolve(JSON.parse( utilCookie.replace(new RegExp(/'/g), '"') ));
  }

 return deferred.promise();
```


.. but it didn't seem to solve our problem of the value being undefined by the time we access it. the `undefined` condition occasionally is tripped, particularly in mobile, and particularly in mobile in-app browsers.

Not necessarily anything wrong with js-cookie but wanted to prod some of the great minds here and see if you had any ideas. :+1:

**Comment by FagnerMartinsBrack** [comment]
> I'm wondering if the processing time of the read/parse is causing a race condition in which the value is "undefined" (since it's still being formatted)?

It is impossible that the following code has any race condition by itself:

```javascript
var utilCookie = Cookies.get('utilCookie');
JSON.parse( utilCookie.replace(new RegExp(/'/g), '"')
```

The implementation inside the context of a complex page though, might have. `Cookies.get` calls internally `document.cookie` to read the data. One thing I could think of is if another code were changing `document.cookie` outside in an undefined order. JavaScript is "async" until the callback is executed (the page hangs), but the order in which the callbacks are executed can cause Race Conditions by changing/removing the cookie before or after the `Cookies.get` call (which is technically the same as `document.cookie`).

So my bet would be in another code changing `document.cookie` while using either a:

* AJAX Request
* `setTimeout`
* or `setInterval`

... that executes conditionally before or after the `Cookies.get( "utilCookie" )` call.

**Comment by tconroy** [comment]
Hey @FagnerMartinsBrack,

Thanks for your input. Thinking about this the lat few days I believe you're right. The app is fairly complex and there is the possibility that other cookie operations are occurring concurrently so I'm going to attempt to investigate that. Thank you for your input, please feel free to close/delete this thread. :)

**Comment by FagnerMartinsBrack** [comment]
:+1:

**Comment by sidaurukfreddy** [comment]
hey anyone know how to detect if success delete cookie itself, i always got undefine  this is my code 

`console.log(Cookies.remove('token'), 'this is value')`
