### ISSUE TITLE
Problem with expires parameter

### ISSUE THREAD

**Issue by fender-hm** [js-cookie/js-cookie#96]
Hello, thank you for your work.
In manual sad that "If omitted, the cookie becomes a session cookie." But I have a problem because if I close browser and then open cookie is still there. Browser Chrome on Debian. Is it a problem of a plugin or just normal behavior of a browser?
Thank you for help.

**Comment by FagnerMartinsBrack** [comment]
Do you have the "Continue where you left off" setting enabled in Chrome? If you do, it might restore the cookie when you reopen the browser.

**Comment by fender-hm** [comment]
yep... this is it, thank you!

**Comment by FagnerMartinsBrack** [comment]
X-Ref: https://github.com/js-cookie/js-cookie/issues/69#issuecomment-126856706,
