### ISSUE TITLE
get doesn't work when browsing locally

### ISSUE THREAD

**Issue by ajck** [js-cookie/js-cookie#97]
If I'm just viewing my site off the local filesystem (i.e. path is file://[path to file]/mypage.html ). as I do continuously during development, then Cookies.get('[my cookie key]') doesn't work, even though setting them works fine (as confirmed by checking site cookies in Chrome). If I upload the same site to the server, it works fine.

Is this a bug, or is there a way around it? I set an expiry time so they aren't just session cookies, and did the noConflict thing just in case, but it made no difference.

Thanks.

**Comment by FagnerMartinsBrack** [comment]
It's a security restriction from Chrome, [see here](http://stackoverflow.com/a/347997/1400037)

**Comment by FagnerMartinsBrack** [comment]
It is recommended to setup a server using [node-static](https://github.com/cloudhead/node-static) if you want to be sure there will be no trouble in handling cookie locally.
