### ISSUE TITLE
Duplicated cookie entries

### ISSUE THREAD

**Issue by garmgrey** [js-cookie/js-cookie#98]
Hello. 
I have some issue with dublicating cookie entries.
Some time, when i call 
```javascript
Cookies.set('my-cookie-name', 'value', {'path': '/'});
```

I am sure that I call this method only one place in my code, but in result I have:

```
---------------------------------------------------------------
    Name               Value     Domain              Path
---------------------------------------------------------------
    my-cookie-name     1         mydomain.com        /foo/bar/
    my-cookie-name     value     mydomain.com        /
---------------------------------------------------------------
```

This does not happen every time.

**Comment by FagnerMartinsBrack** [comment]
You are creating two cookies with the same name but different `Path`, that's not recommended because it causes this kind of confusion. A cookie is defined by its `domain`, `path` and `secure` attributes, you need to take care to avoid duplicated operations.

See the links at https://github.com/js-cookie/js-cookie/issues/37#issuecomment-113964814 for additional information.

> I am sure that I call this method only one place in my code

Even though you call it once, the user could already have a cookie locally. Changing the code does not delete a cookie that was persisted earlier.

Another theory is that you might be passing an Object Literal reference in the `attributes` argument, then another code change the Object and the cookie is created with another `Path`.

Anyway, it's pretty hard to figure out the problem without a reduced test case.

**Comment by gcollombet** [comment]
I have the same problem. I call 
  Cookies.set('my-cookie-name', 'value');
from a single location but it create me two cookie with same name one with / and one with my page requested uri.

**Comment by garmgrey** [comment]
@gcollombet That is why I use the attribute {path: '/'}. But this does not solve the problem.

@FagnerMartinsBrack Cookie with name ```'my-cookie-name'``` sets in only one place of code.
This issue i catch on my dev machine, so it can't be a old (or wrong) cookie.
But i use it for toggle some state. i mean like this:
```javascript
var state = 'on';
$elem.on('click', function(e){
    state = state === 'on' ? 'off' : 'on';
    Cookies.set('my-cookie-name', state, {path: '/'});
});
```

May be it's wrong usage? And i need to remove old cookie before set new value?

**Comment by FagnerMartinsBrack** [comment]
@garmgrey 
If you remove the cookie before setting the value it works?
What is the output of `Cookies.set()` operation in all calls? Can you put a `console.log` there?

**Comment by garmgrey** [comment]
@FagnerMartinsBrack This problem occurs rarely, so it is difficult to catch. At this moment i remove cookie before set new value and do not catch the problem again. But i think it is wrong usage of ```js-cookie``` lib.

Do you mean this?
```javascript
console.log(Cookies.set('my-cookie-name', state, {path: '/'}));
```

**Comment by gcollombet** [comment]
Ok sorry,  in my case it was a the server part that add the wrong cookie
(I'll do a setcookie in php... ).

**Comment by FagnerMartinsBrack** [comment]
> Do you mean this?

Yes, just so I would know the output that js-cookie does internally using `document.cookie`.

Don't rely on this though, the returning value is not documented and should be used only for debugging purposes.

> But i think it is wrong usage of js-cookie lib.

If you have any questions regarding js-cookie usage you can use the [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie) tag on stackoverflow. The benefit of asking there is that it has better PageRank for Google and therefore has a greater chance to help somebody else in the future ;)

If you ask on StackOverflow please link here to increase awareness.

**Comment by garmgrey** [comment]
@FagnerMartinsBrack @gcollombet 
Thank you. I will write here when I find an answer...

**Comment by garmgrey** [comment]
@FagnerMartinsBrack [Question on StackOverflow](http://stackoverflow.com/questions/33011827/excess-record-in-cookies)

**Comment by FagnerMartinsBrack** [comment]
I will close this for now since it doesn't seems to be any `js-cookie` internal problem.
